### ISSUE TITLE
Python: empty f-string is not matched by "..." pattern

### ISSUE THREAD

**Issue by GrosQuildu** [semgrep/semgrep#10047]
**Describe the bug**
For Python, the `"..."` pattern does not match empty f-strings (`f""`). This seems to be an inconsistency.

**To Reproduce**
https://semgrep.dev/playground/s/yyRjO

```yaml
rules:
  - id: python-fstring
    languages:
      - python
    severity: ERROR
    patterns:
      - pattern: $X = "..."
```

```python
a = "asd"
b = ""
c = f"asd"
d = f""
e = f"{2+2}"
```

The a, b, and c lines are matched, d and e lines are not matched.

**Expected behavior**
I would expect the `"..."` pattern to match empty f-strings, because the pattern matches not-empty, constant f-strings already.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X P2: regular bug that should get fixed

**Use case**
The bug makes us to write additional pattern-not cases, so it is a minor inconvenience. See https://github.com/trailofbits/semgrep-rules/pull/39#discussion_r1549533409
