### ISSUE TITLE
JavaScript: Tracking destructured object's property inside function

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#1005]
What would be the way to track destructured object's property inside function?

example:
```javascript
function test({foo}, bar) {
    console.log(foo)
}
```

trying to track `foo` from the example I came up with several patterns but none of them works:

link: https://semgrep.live/3qBG

```yaml
  pattern: |
    function $F ($FOO,...) {
      ...
      console.log($FOO);
      ...
    }
```

```yaml
  pattern: |
    function $F ({$FOO},...) {
      ...
      console.log($FOO);
      ...
    }
```

```yaml
  pattern: |
    function $F ($INPUT,...) {
      ...
      console.log($INPUT.foo);
      ...
    }
```

```yaml
  patterns:
    - pattern-inside: function $F ($FOO,...) {...}
    - pattern: console.log($FOO);
```

```yaml
  patterns:
    - pattern-inside: function $F ({$FOO},...) {...}
    - pattern: console.log($FOO);
```
