### ISSUE TITLE
Semgrep doesn't match else statements in Java

### ISSUE THREAD

**Issue by r0075h3ll** [semgrep/semgrep#10094]
Code Snippet
---

```java
if (num > 0) {
    System.out.println("Number is positive.");
} else if (num < 0) {
    System.out.println("Number is negative.");
} else {
    System.out.println("Number is zero.");
}
```

When trying to match else statements in scenarios like above, Semgrep throws parsing errors. I haved used Semgrep Playground for this.

Rule
---

```yaml
rules:
  - id: phone
    languages: [java]
    message: "Use of System.out.println detected"
    severity: ERROR
    pattern: |
      else {
        System.out.println(...);
      }
```

Error
---

<img width="558" alt="image" src="https://github.com/semgrep/semgrep/assets/38760238/c4e4c657-a3f7-4779-ac0e-7e5c6bb0e515">

**Comment by ievans** [comment]
this is expected behavior as `else` is not a valid AST element without a preceding `if` clause. sorry the messaging is confusing! Just put an if clause before it, e.g. `if (...) { ... } else { ... }`

**Comment by r0075h3ll** [comment]
You're correct, the pattern did match the code when I used `if`, but it also. imo, limits the scope of findings as the hardcoded credentials, or even vulns for that matter, in the `else` statement will get ignored if a rule tries to not look inside an `if` block.

**Comment by r0075h3ll** [comment]
You're correct, the rule just worked fine when tried `if` block to write the pattern. Although, here's a case where Semgrep gets confused as to where to look for a pattern when it exists within a block that is to be ignored.

```yaml
rules:
  - id: untitled_rule
    patterns:
      - pattern: test;
      - pattern-not: |
          if ($X) {
            ...
          }
    
    message: Semgrep found a match
    languages:
      - java
    severity: WARNING
```

Output
---

![image](https://github.com/semgrep/semgrep/assets/38760238/4bdde511-8d1d-4180-ab49-a67e072e36a3)
