### ISSUE TITLE
False Positives in Taint Mode when multiple related sanitizer rules defined with focus-metavariable

### ISSUE THREAD

**Issue by andrew-konstantinov** [semgrep/semgrep#10167]
**Describe the bug**
I have a code base where a certain sanitizer is used both as `sink(id)` as well as `sanitize(id.toString())` (this is Kotlin). I've defined two sanitizer rules, each of them correctly matching one of these patterns, however when used together it looks like a more generic one takes priority (`sink(id)`) and the other one is completely ignored:

```yaml
    # These two sanitizer rules together should produce zero findings
    # (identifying sanitizers in all four test cases), but they produce
    # (false positive) findings at test1 and test2
    pattern-sanitizers:
      # Alone, produces findings at test1 and test2
      - patterns:
        - pattern: sanitize($X)
        - focus-metavariable: $X
        by-side-effect: true

      # Alone, produces findings at test3 and test4
      - patterns:
        - pattern: sanitize($X.toString())
        - focus-metavariable: $X
        by-side-effect: true
```

**To Reproduce**
A concise example that demonstrates the problem (Kotlin): https://semgrep.dev/playground/s/5rzll

**Expected behavior**
All sanitizer rules should be matched separately. It should be never possible to create more matches by adding a new sanitizer rule to existing ones, but that's exactly what we observe right now: commenting out the second rule will avoid matching test1 and test2, but enabling it produce these false positive matches.

**Screenshots**
With only one sanitizer pattern enabled (`sanitize($X.toString())`), `test1` and `test2` examples are correctly identified as sanitized and not matched:
<img width="1185" alt="image" src="https://github.com/semgrep/semgrep/assets/122047699/652d7876-acd9-4046-b85b-7b5826734d40">

By adding an additional sanitizer pattern, parsing of the previous rule appears to be affected, as `test` and `test2` not are considered matches:
<img width="1185" alt="image" src="https://github.com/semgrep/semgrep/assets/122047699/bdf6a19c-3539-4e45-816f-f6adb2edb68a">

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
The issue surfaced when using Semgrep Pro for integration within the CI/CD, but it is reproducible on semgrep.dev as well.

**Use case**
Significantly reduce false positives, increasing confidence in the Semgrep results and enabling it's adoption in our CI/CD.
