### ISSUE TITLE
metavariable-pattern always fails with aliengrep

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#10222]
**Describe the bug**

Matching against the contents of a metavariable extracted with aliengrep fails with the following error message:
```
[WARN] Internal matching error when running test-aliengrep-mv on target:
 An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
```

**To Reproduce**

Use the following `generic.yaml` rules:
```yaml
rules:
  # works: one finding
  - id: test-spacegrep-mv
    severity: ERROR
    languages:
      - generic
    options:
      generic_engine: spacegrep
    message: |
      found '$X'
    patterns:
      - pattern: |
          key = $X
      - focus-metavariable: $X
      - metavariable-pattern:
          metavariable: $X
          pattern: value
  # fails with error message in --strict --verbose mode:
  # "metavariable-pattern failed because $X does not bind to a
  # sub-program. please check your rule"
  - id: test-aliengrep-mv
    severity: ERROR
    languages:
      - generic
    options:
      generic_engine: aliengrep
    message: |
      found '$X'
    patterns:
      - pattern: |
          key = $X
      - focus-metavariable: $X
      - metavariable-pattern:
          metavariable: $X
          pattern: value
```

They're the same rule except for the `generic_engine` option.

Target file `target`:
```
key = value
```

Command:
```
$ semgrep -c ./generic.yaml target --strict --verbose
...
[WARN] Internal matching error when running test-aliengrep-mv on target:
 An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
...
┌────────────────┐
│ 1 Code Finding │
└────────────────┘
                         
    target
   ❯❯❱ test-spacegrep-mv
          found 'value'
                       
            1┆ key = value

```

**Expected behavior**

There should be two findings, one for each rule, rather than just one.

**Screenshots**

The original Playground example as provided by @inkz is https://semgrep.dev/playground/s/3qNKr

![image](https://github.com/semgrep/semgrep/assets/343265/f6209547-bf67-456a-baad-9ce8fdf768ef)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

any

**Use case**

Matching words containing `-`.
