### ISSUE TITLE
`match` matching ignores the branches enum variant names

### ISSUE THREAD

**Issue by Ten0** [semgrep/semgrep#10251]
**Describe the bug**
In semgrep's Rust matching, `match` matching ignores the branches enum variant names

**To Reproduce**
https://semgrep.dev/playground/s/ZqJ1W
```yml
rules:
  - id: my_pattern_id
    languages:
      - rust
    severity: ERROR
    message: Semgrep found a match
    pattern: match ... { Ok(_) => ..., Err(_) => ... }
```

 ```rust
match f() {
    Abc(_) => {}
    Def(_) => {}
}
```

**Expected behavior**
Does not match

**Actual behavior**
![image](https://github.com/semgrep/semgrep/assets/9094255/cd6e1be7-dc77-4364-aed8-41391178f760)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**

CI makes good practices check based on semgrep. We want to forbid underscore-matching both the Ok and Err variant of a result, but this creates a lot of false positives.
