### ISSUE TITLE
Pattern parser throws an error when parsing patterns with explicit private attributes

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#10258]
**Describe the bug**
Parser engine throws up when parsing patterns with explicit private attributes, e.g.

```yaml
rules:
  - id: parser-doesnt-like-private-attributes
    pattern: |
        #$ATTR(...) {
          ...
        }
    message: Semgrep found a match $ATTR
    languages: [ts,js]
    severity: WARNING
```
The *engine* parsing *targets* can handle private attributes just fine - this shows up if you have e.g. a rule that finds function definitions, then you use the metavariable values to construct a new Semgrep rule.

**To Reproduce**
https://semgrep.dev/playground/s/kx2Zz

as long as you don't use a private attribute explicitly in a pattern, the engine is happy:
https://semgrep.dev/playground/s/NbYA1

further complicating the issue, *calling* a private attribute with `this` seems to parse just fine:
https://semgrep.dev/playground/s/eqlwE

**Expected behavior**
this should parse. 

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev,  semgrep 1.72.0

**Use case**
recursively templated scans using results from Semgrep itself
