### ISSUE TITLE
Whether the current feature supports taint analysis to detect memory leakage

### ISSUE THREAD

**Issue by WhereIsOops** [semgrep/semgrep#10265]
I would like to check the following code snippet when the quit function is executed, but file_list[i]->compress_buf is not free.
```
#include <stdio.h>
#include <stdlib.h>
#include <zlib.h>
#include <string.h>
typedef struct{
    char name[0x30];
    char *content;
    char *compress_buf;
    unsigned int size;
    unsigned int compress_size;
    int is_compressed;
}file_struct;
char quit_name[0x20] = {0};
file_struct *file_list[0x20] = {0};

int init(){
    setvbuf(stdout,0,2,0);
    setvbuf(stdin,0,2,0);
    setvbuf(stderr,0,2,0);
    alarm(0x20);
}
int menu(){
    printf("root@compress-machine >");
}


int createFile(){
    char name[0x30] = {0};
    printf("FileName: ");
    safeRead(name,0x20);
    for(int i = 0;i < 0x20;i++){
        if(file_list[i]){
            if(!strcmp(name,file_list[i]->name)){
                puts("File Is Exits");
                break;
            }
        }
    }
    int idx = searchEmptySpace();
    if(idx < 0){
        puts("Full");
        return -1;
    }
    
    file_struct *f = calloc(1,sizeof(file_struct));
    if(!f){
        perror("calloc");
        return -1;
    }
    strncpy(f->name,name,0x20);
    printf("FileSize: ");
    unsigned int size = readInt();
    if(size <= 0 || size > 4096){
        free(f);
        f = NULL;
        puts("Invalid Size");
        return -1;
    }
    f->content = calloc(1,size);
    if(!f->content){
        free(f);
        f = NULL;
        perror("calloc");
        return -1;
    }
    f->compress_buf = calloc(1,compressBound(size));
    if(!f->compress_buf){
        free(f->content);
        f->content = NULL;
        free(f);
        f = NULL;
        perror("calloc");
        return -1;
    }
    f->size = size;
    f->compress_size = compressBound(size);
    printf("FileContent: ");
    safeRead(f->content,size);
    f->is_compressed = 0;
    file_list[idx] = f;
    return 0;
}


int quit(){
    for(int i = 0;i < 0x20;i++){
        if(file_list[i]){
            free(file_list[i]->content);
            file_list[i]->content = NULL;
            free(file_list[i]);
            file_list[i] = NULL;
        }
    }
    puts("Your Name?");
    scanf("%s",quit_name); 
    printf("Really Exit? yes(1)/no(0)");
    int choice = readInt();
    if(choice == 1){
        exit(0);
    }
    else{
        return 0;
    }
}

int main(){
    char buffer[1024] = {0};
    init();
    while(1){
        memset(buffer,'\x00',1024);
        menu();
        safeRead(buffer,0x10);
        if(!strcmp("create",buffer)){
            createFile();
        }
        else if(!strcmp("quit",buffer)){
            quit();
        }
        else{
            puts("Invalid command");
            continue;
        }

    }
}
```
I wrote a scan rule for this using the taint pattern
```
rules:
  - id: memory-leak
    message: Semgrep found a match
    languages:
      - c
      - cpp
    severity: WARNING
    mode: taint
    options:
      interfile: true
    pattern-sources:
      - patterns:
          - pattern: $PTR = $ALLOC(...);
          - metavariable-pattern:
              metavariable: $ALLOC
              pattern-either:
                - pattern: calloc
                - pattern: malloc
          - focus-metavariable: $PTR
        by-side-effect: true
    pattern-sinks:
      - pattern-either:
        - pattern: exit(...)
        at-exit: true
      #   - pattern-not-inside: |
      #       free($PTR->$MEM)
      # - pattern-not-inside: |
      #     free($PTR)
    pattern-propagators:
      - pattern: $E[$INDEX] = $S
        from: $S
        to: $E

```
I want to detect unreleased memory on exit, but the result is not as expected. Whether a feature supports the detection
