### ISSUE TITLE
"taint_assume_safe_functions: true" dosen't work while setting "control: true" in pattern-sources filed

### ISSUE THREAD

**Issue by WhereIsOops** [semgrep/semgrep#10272]
I slightly modified the example in the "Assume function calls are safe" section of the guide by adding control:true to the pattern-sources. Surprisingly, the Assume function calls are safe function failed.
[Assume function calls are safe](https://semgrep.dev/docs/writing-rules/data-flow/taint-mode#assume-function-calls-are-safe)
```
rules:
  - id: taint-rule
    languages:
      - js
    message: Tainted sink!
    mode: taint
    options:
      taint_assume_safe_functions: true
    pattern-sources:
      - pattern: tainted
        control: true

    pattern-sinks:
      - pattern: sink(...)
    severity: WARNING

```
I suggest to adjust the priority of these two switches.
