### ISSUE TITLE
Golang Taint Analysis doesn't work - Function parameter as source

### ISSUE THREAD

**Issue by giftbowen** [semgrep/semgrep#10359]
**Describe the bug**
Function Parameter as source doesn't work for golang.
The match pattern requires the parameter to be explicitly typed, but the same feature in Java doesn't require this parameter type.

- Code
```
package test1

func func1(a, b string) string {
	return a + b
}

func func2(a string) string {
	return a
}

func check1(a string, b string) error {
	c := func1(a, b)
	sink(c)
	return nil
}

func check2(a string) error {
	c := func2(a)
	sink(c)
	return nil
}
```

- Rule
```
rules:
  - id: dont-work-func-parameter-as-source
    languages:
      - go
    message: Test
    mode: taint
    pattern-sources:
      - patterns: 
        - pattern-inside: |
            func check1($X,...) error {
              ...
            }
        - pattern: $X
    pattern-sinks:
      - pattern: sink(...)
    severity: WARNING
```

- What works
```
# if the rule pattern-inside checks parameter type, it works.
# but I also tried this for Java, and Java doesn't require the type for the parameter
        - pattern-inside: |
            func check1($X string,...) error {
              ...
            }
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Doesn't work for both UI or local build with pro engine

**Use case**
What will fixing this bug enable for you?
Analyze security issues in golang
