### ISSUE TITLE
Golang Taint Analysis doesn't work for struct functions

### ISSUE THREAD

**Issue by giftbowen** [semgrep/semgrep#10358]
I have got a sample code one written without struct another with struct, the taint analysis for no-struct works but doesn't work for with-struct.

**What is _NOT_ working**
In this taint analysis, sink() is called twice, the one that is in the same function (with source) can be found, but the one in another function cannot be found.

- Code
```
package test1

type handler struct {
}

func (h *handler) sink(x string) (string, error) {
	return "", nil
}

func (h *handler) getInput(a, b string) string {
	return a + b
}

func (h *handler) foo(x string) {
	h.sink(x)
}

func (h *handler) Test(a, b, c string) error {
	userInput := h.getInput(a, b)
	h.foo(userInput)
	h.sink(userInput)
	return nil
}
```

- Rule
```
rules:
  - id: dont-work-inter-procedure
    languages:
      - go
    message: Test
    mode: taint
    pattern-sources:
      - patterns:
        - pattern-inside: |
            func (h *handler) Test(...) error {
              ...
            }
        - pattern: $X
    pattern-sinks:
      - pattern: $Y.sink(...)
    severity: WARNING
```

**What is working**
- Code
```
package test1

func sink(x string) (string, error) {
	return "", nil
}

func getinput(a, b string) string {
	return a + b
}

func foo(x string) {
    sink(x)
}

func Test(a, b, c string) error {
	user_input := getinput(a, b)
	foo(user_input)
	sink(user_input)
    return nil
}
```

- Rule
```
rules:
  - id: dont-work-inter-procedure
    languages:
      - go
    message: Test
    mode: taint
    pattern-sources:
      - patterns:
        - pattern-inside: |
            func Test(...) error {
              ...
            }
        - pattern: $X
    pattern-sinks:
      - pattern: sink(...)
    severity: WARNING
```

The codes are almost the same with the only difference of in struct or not

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Doesn't work for both UI or local build with pro engine

**Use case**
What will fixing this bug enable for you?
Analyze security issues in golang
