### ISSUE TITLE
Golang Taint Analysis with Interfile - Trace doesn't show full history of taint analysis - Intermediate trace history is lost

### ISSUE THREAD

**Issue by giftbowen** [semgrep/semgrep#10361]
**Describe the bug**
Run the below code and rule in local semgrep scan with --pro option, it can find the source, sink and one intermediate trace, but not all the intermediate traces, like in below code scanning. func foo1 is not returned from the scan output

- Code
```
package handler

func sink(x string) (string, error) {
	return "", nil
}

func getInput(a, b string) string {
	return a + b
}

func foo(x string) {
	foo1(x)
}

func foo1(x string) {
	foo2(x)
}

func foo2(x string) {
	sink(x)
}

func Test(a, b, c string) error {
	userInput := h.getInput(a, b)
    foo(userInput)
	sink(userInput) 
	return nil
}

```

- Rule
```
rules:
  - id: golang-inter-procedure
    languages:
      - go
    message: Test
    mode: taint
    pattern-sources:
      - patterns:
          - pattern-inside: |
              func Test(...) error {
                ...
              }
          - pattern: $X
    pattern-sinks:
      - pattern: sink(...)
    severity: WARNING
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
local build with semgrep pro
