### ISSUE TITLE
Taint rules will not match in C# checked blocks

### ISSUE THREAD

**Issue by robvinson** [semgrep/semgrep#10423]
**Describe the bug**
Taint rules will not match in csharp `checked` blocks.

**To Reproduce**

test code:
```csharp
checked {
    //!! Doesn't match but should
    source(sink(x));
}

try {
    //match
    source(sink(x));
}

// match
source(sink(x));
```

test rule:
```
rules:
  - id: test
    languages:
      - csharp
    severity: ERROR
    message: Test
    pattern-sources:
      - pattern: source(...)
    pattern-sinks:
      - pattern: sink(...)
    mode: taint
```

**Expected behavior**
Taint mode should support matching in C# `checked` blocks.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Installed from pip (v 1.81.0) and semgrep.dev playground.

**Use case**
Security audits of decompiled C# code or C# code which otherwise uses checked blocks.
