### ISSUE TITLE
v1.75 introduces FPs in taint rules

### ISSUE THREAD

**Issue by craigmarksmith** [semgrep/semgrep#10447]
**Describe the bug**
Consider the rule:

```yaml
rules:
- id: "test"
  languages:
  - "csharp"
  mode: taint
  pattern-sources:
  - patterns:
    - pattern-inside: |
        $RET $METHOD(...,$VAR,...){...}
    - focus-metavariable: $VAR
  pattern-sinks:
  - pattern: "(System.DirectoryServices.DirectoryEntry $SOURCE).Path = ..."
  - pattern: "(System.DirectoryServices.DirectorySearcher $SEARCHER).Filter = ..."
  message: Testing $VAR
  severity: "WARNING"
```
and the test

```csharp
// License: LGPL-3.0 License (c) security-code-scan

using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using System.DirectoryServices.Protocols;
using System.Net;

// ref: csharp_injection_rule-LdapInjection
namespace consoleApp.cSharp.Injection
{
    internal class LdapInjection : IScenarioRunner
    {
        string ldapserver = "127.0.0.1:3889";
        string ldapbasedn = "dc=example,dc=org";
        string ldapuser = "cn=admin,dc=example,dc=org";
        string ldappassword = "adminpassword";

        public void UseDirectorySearcherPathTest(string pathPara)
        {
            string ldapfilter = "(objectClass=*)";

            try
            {
                using (DirectoryEntry entry = new DirectoryEntry("LDAP://" + ldapserver + "/" + ldapbasedn, ldapuser, ldappassword, AuthenticationTypes.None))
                {

                    // ruleid: test
                    entry.Path = "LDAP://" + ldapserver + "/" + pathPara;

                    DirectorySearcher ds = new DirectorySearcher(entry);
                    ds.SearchScope = System.DirectoryServices.SearchScope.Subtree;

                    // ok: test
                    ds.Filter = string.Format(ldapfilter);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

    }
}
```

In [v1.74.0](https://github.com/semgrep/semgrep/releases/tag/v1.74.0) this test passes, only finding a vulnerability at `entry.Path = "LDAP://" + ldapserver + "/" + pathPara;`.

In [v1.75.0](https://github.com/semgrep/semgrep/releases/tag/v1.75.0) and later, this test fails with a vulnerability found at `ds.Filter = string.Format(ldapfilter);`. `ds.Filter = string.Format(ldapfilter);` should not be marked as a finding since `ldapfilter` is defined within the function and is not tainted. 

**To Reproduce**

This test can be seen to fail at https://semgrep.dev/playground/s/d89YZ.

To test semgrep v1.74 and v1.75 separately

```sh
git clone git@gitlab.com:craigmsmith/csharp-semgrep-1.75-fp-test.git
cd csharp-semgrep-1.75-fp-test
docker run -it --rm -v ${PWD}:/app -w /app returntocorp/semgrep:1.74.0-nonroot semgrep --metrics=off --test ./
# these tests will pass
docker run -it --rm -v ${PWD}:/app -w /app returntocorp/semgrep:1.75.0-nonroot semgrep --metrics=off --test ./
#these tests will fail 
```

**Expected behavior**
I would expect this test to continue to pass. 

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by craigmarksmith** [comment]
@IagoAbal @aryx is this issue something either of you might be able to help me with? I've tested each commit in [v1.74.0...v1.75.0](https://github.com/semgrep/semgrep/compare/v1.74.0...v1.75.0) and I can see the change that introduced this behaviour was added in [this commit](https://github.com/semgrep/semgrep/commit/db4f238e2a7a2548b5a624f31f6e4bf938862c50).

FWIW, I was able to narrow the issue down to this commit by
1. cloning https://github.com/semgrep/semgrep.git
2. commenting out [`ENTRYPOINT ["make"]`](https://github.com/semgrep/semgrep/blob/a8efd0cec01af4238656575d5edb2127b1076ac3/Dockerfile#L377) and [`RUN --mount=type=secret,id=SEMGREP_APP_TOKEN SEMGREP_APP_TOKEN=$(cat /run/secrets/SEMGREP_APP_TOKEN) semgrep install-semgrep-pro --debug`](https://github.com/semgrep/semgrep/blob/a8efd0cec01af4238656575d5edb2127b1076ac3/Dockerfile#L300)
3. updating the submodules with `git submodule update --init --recursive`
4. building the docker image with `docker run -it --rm -v \${PWD}:/app semgrep-$SHA sh`

Once the image had built I ran the image mounting a directory which included the check and test shown in the description then ran `semgrep --metrics=off --test ./` in that directory. 

I did that until I found the first commit that caused test to fail.

**Comment by IagoAbal** [comment]
@craigmarksmith Semgrep says that `entry.Path` is tainted, because it's defined as `"LDAP://" + ldapserver + "/" + pathPara` and `pathPara` is a source. Then `ds` is tainted, because is defined as `new DirectorySearcher(entry)`. Then your rule declares the whole `ds.Filter = string.Format(ldapfilter);` as a sink, and that sink is tainted because it contains `ds` in it. I think the reasoning is correct. 🤔 Could you explain why do you think it's incorrect?

**Comment by IagoAbal** [comment]
One thing that did change in Semgrep is that, previously, when an object had a field tainted (like `entry`), and the entire object was passed to a function that was "opaque" to Semgrep (like the `DirectorySearcher` constructor), Semgrep was not considering that object as tainted. We could perhaps add a rule option to restore that behavior when needed.

*However*, maybe the best solution is to write the rule differently, in a more precise way. For example, if you wrote your sink like this you get the findings that you expected:

```yaml
  pattern-sinks:
  - patterns:
    - pattern-either:
      - pattern: "(System.DirectoryServices.DirectoryEntry $SOURCE).Path = $RHS"
      - pattern: "(System.DirectoryServices.DirectorySearcher $SEARCHER).Filter = $RHS"
    - focus-metavariable: $RHS
```
