### ISSUE TITLE
My rule can not work for java comment.

### ISSUE THREAD

**Issue by sustbeckham** [semgrep/semgrep#10457]
my source code : 
```
public interface HealthCheckApi {

    Result healthCheck(boolean checkDependency);

    Result healthCheckV2(boolean checkDependency);

    /**
     *  comment
     *
     * @param checkDependency
     * @return
     */
    Result healthCheckV3(boolean checkDependency);
}
```

and my rule config: 
```
id: api-interface-methods-must-have-docs
message: [$FUNC]!
severity: ERROR
metadata:
  type: BUG
  severity: BLOCKER
  effortMinutes: 10
languages:
  - java
patterns: 
  - pattern: |
      interface $NAME {
        
          /**
           * $FUNC_DOC
           */
          $RETURN_TYPE $FUNC(...);
      }
  - metavariable-pattern:
      metavariable: $NAME
      pattern-regex: '\S+Api'
  - focus-metavariable: $FUNC 
```

But when I run the config, and all method in interface matched. is this a bug ? or semgrep can not support java comment ?
