### ISSUE TITLE
Statement indentation prevents matching

### ISSUE THREAD

**Issue by icholy** [semgrep/semgrep#10481]
**Describe the bug**

In some cases, indenting a statement causes matching to fail.

**To Reproduce**

https://semgrep.dev/playground/s/lBoo9

Rule:

``` yml
rules:
  - id: test
    patterns:
      - pattern: 'foo($E, $C)'
      - focus-metavariable: $E
      - pattern-regex: .*
    message: 'Test'
    languages:
      - typescript
    severity: WARNING
```

Code:

``` typescript
// match
foo('event:foo', () => {

});

	// no match
	foo('event:foo', () => {

	});
```

**Expected behavior**

Both statements match

**Screenshots**

![image](https://github.com/user-attachments/assets/956e45b8-e89b-44b7-a40a-379c64808d6c)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**

I have a large number of deprecated event handlers in the codebase I'm trying to flag.

**Comment by iuliadmtru** [comment]
If you just remove the `pattern-regex` it matches: https://semgrep.dev/playground/s/GdDD2. I'm not sure what the exact explanation for this is though. It's because of how the regex `.*` handles whitespace/newlines. If you change the regex to include newlines as well it matches the indented case: https://semgrep.dev/playground/s/0oYY5. And if you keep the regex `.*` but write the second `foo` in one line, there's a match as well: https://semgrep.dev/playground/s/KxqqX. 🤷🏻‍♀️

**Comment by icholy** [comment]
It works if I use `metavariable-regex` instead of `focus-metavariable` followed by `pattern-regex`:

``` yml
rules:
  - id: test
    languages:
      - typescript
    severity: ERROR
    message: Test
    patterns:
      - pattern: foo($E, $C)
      - metavariable-regex:
          metavariable: $E
          regex: .*
      - focus-metavariable: $E
```

I just noticed something weird though. The patterns in my original rule are being re-ordered. The original rule has the `pattern-regex` last because I want it to match against `$E`:

``` yml
rules:
  - id: test
    patterns:
      - pattern: 'foo($E, $C)'
      - focus-metavariable: $E
      - pattern-regex: .*
    message: 'Test'
    languages:
      - typescript
    severity: WARNING
```

But if you switch to structured mode and then back, the `pattern-regex` and `focus-metavariable` patterns are switched.

https://github.com/user-attachments/assets/bc513eb7-746c-4d6c-83e2-b73040c71a0f
