### ISSUE TITLE
`pattern-not` not working with `metavariable-pattern`

### ISSUE THREAD

**Issue by Kiblyn11** [semgrep/semgrep#10492]
**Describe the bug**
`metavariable-pattern` break all matches when used with `pattern-not`

**To Reproduce**

Code

```
[HttpPost]
public async void Test([FromRoute] Guid testId)
{
    var user = get_user();
    var a = Test(1);

    return true;
}
```

Rule working (match because Testt is not Test)

```
rules:
    - id: test
      patterns:
          - pattern-inside: |
                [$HTTPMETHOD(...)]
                public $RET $FOO(...) {
                    ...
                }
          - pattern-not: |
                [$HTTPMETHOD(...)]
                public $RET $FOO(...) {
                    ...
                    var a = Testt(...);
                    ...
                }
          - metavariable-regex:
                metavariable: "$HTTPMETHOD"
                regex: "Http(Get|Post|Delete|Patch|Put)"
      message: "Test"
      severity: WARNING
      languages:
          - csharp
      path: .*\.cs
```

Rule Bug (Should also match as the metavariable gives Testt)

```
rules:
    - id: test
      patterns:
          - pattern-inside: |
                [$HTTPMETHOD(...)]
                public $RET $FOO(...) {
                    ...
                }
          - pattern-not: |
                [$HTTPMETHOD(...)]
                public $RET $FOO(...) {
                    ...
                    var a = $FUNC(...);
                    ...
                }
          - metavariable-regex:
                metavariable: "$HTTPMETHOD"
                regex: "Http(Get|Post|Delete|Patch|Put)"
          - metavariable-regex:
                metavariable: "$FUNC"
                regex: "Testt"
      message: "Test"
      severity: WARNING
      languages:
          - csharp
      path: .*\.cs

```

**Expected behavior**

Be consistent when used in pattern like this it works as expected I can match or not with metavariable

```
          - pattern: |
                [$HTTPMETHOD(...)]
                public $RET $FOO(...) {
                    ...
                    var a = $FUNC(...);
                    ...
                }
          - metavariable-regex:
                metavariable: "$HTTPMETHOD"
                regex: "Http(Get|Post|Delete|Patch|Put)"
          - metavariable-regex:
                metavariable: "$FUNC"
                regex: "Test"
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep OSS

**Comment by Kiblyn11** [comment]
In fact I think it's the usage of 2 `metavariable-regex` on the same pattern that cause the issue.
I couldn't find any explicit limit on the usage of many `metavariable-regex`.

**Comment by kopecs** [comment]
This seems like the expected behaviour to me (but is a bit confusing). Essentially you have a rule which is `(A AND NOT B) WHERE (CONDITION 1 AND CONDITION 2)`, but what you really want is `(A AND NOT (B WHERE CONDITION 1)) WHERE CONDITION 2`. This is because you want to remove potential matches which match `B` (i.e., the pattern with `var a = $FUNC(...);`), but putting the `metavariable-regex` at the top level with everything else adds it as a positive constraint on the final match (this is the reason the two examples you give are different---the former correctly "scopes" the constraint by embedding it in the pattern directly).

So to put that back into the YAML, what you would want would be something along the lines of
```yaml
rules:
  - id: test
    languages:
      - csharp
    severity: ERROR
    message: Test
    patterns:
      - pattern: |
          [$HTTPMETHOD(...)]
          public $RET $FOO(...) {
              ...
          }
      - pattern-not:
          patterns:
          - pattern: |
              [$HTTPMETHOD(...)]
              public $RET $FOO(...) {
                  ...
                  var a = $FUNC(...);
                  ...
              }
          - metavariable-regex:
              metavariable: $FUNC
              regex: Testt
      - metavariable-regex:
          metavariable: $HTTPMETHOD
          regex: "Http(Get|Post|Delete|Patch|Put)"
    path: .*\.cs

```
where the metavariable-regex on `$FUNC` is only applied within the `pattern-not`. Note also that `metavariable-regex` is unanchored, so if you want anchored matches you'll need to add anchors.
