### ISSUE TITLE
It seems to have no effect on the Rust language

### ISSUE THREAD

**Issue by zhedazijingang** [semgrep/semgrep#10510]
**Describe the bug**

There are no valid prompts

**To Reproduce**

```rust
/// This function adds two numbers together
fn add_two_numbers(a: i32, b: i32) -> i32 {
    a + b
}

/// This function multiplies two numbers
fn multiply_numbers(a: i32, b: i32) -> i32 {
    a * b
}

/// This method does something else
fn divide_numbers(a: i32, b: i32) -> i32 {
    a / b
}
```

For the above code, I want to check for a mismatch between comments and method names. The configuration is as follows:

```yaml
rules:
  - id: rust-method-doc-mismatch
    languages: [rust]
    message: "The documentation comment does not match the method name."
    severity: WARNING
    patterns:
      - pattern: |
          /// $DOC_COMMENT
          fn $METHOD_NAME(...)
    metavariable-regex:
      metavariable: $DOC_COMMENT
      regex: ".*(?i)($METHOD_NAME).*"
    metadata:
      category: consistency
      technology: rust
```

**Expected behavior**

execute ` semgrep --config rust-method-doc-mismatch.yaml just-test.rs`

I  hope it can provide effective prompts.

But in fact, there is no hint

**Screenshots**

![image](https://github.com/user-attachments/assets/5d1a5da2-5a39-455e-9098-bcc363625224)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
