### ISSUE TITLE
[Python] ExceptionGroup statements cause syntax errors ("except*")

### ISSUE THREAD

**Issue by NyanKiyoshi** [semgrep/semgrep#10511]
**Describe the bug**
The following valid Python statement leads to syntax errors in YAML rules and `.py` rules test files:

```
try:
    ...
except* Exception: # <-- the star ('*')
    ...
```

Python grammar is as follows:[^1]

```
try_stmt  ::=  try1_stmt | try2_stmt | try3_stmt
try1_stmt ::=  "try" ":" suite
               ("except" [expression ["as" identifier]] ":" suite)+
               ["else" ":" suite]
               ["finally" ":" suite]
try2_stmt ::=  "try" ":" suite
               ("except" "*" expression ["as" identifier] ":" suite)+  # <--- The bug
               ["else" ":" suite]
               ["finally" ":" suite]
try3_stmt ::=  "try" ":" suite
               "finally" ":" suite
```

**To Reproduce**

1. Create a rule with the following (playground: https://semgrep.dev/playground/s/r61oW):
    ```yaml
    rules:
      - id: try-except-star
        pattern: |
          try:
            ...
          except* ... as $X:
            ...
        message: Semgrep found a match
        languages: [python]
        severity: WARNING
    ```
2. It fails with:
    ```
    Rule parse error in rule try-except-star:
     Invalid pattern for Python: Stdlib.Parsing.Parse_error
    ----- pattern -----
    try:
      ...
    except* ... as $X:
      ...
    
    ----- end pattern -----
    Engine(RuleParseError)
    ```

Alternatively, it can be done in a rule test file:

1. Create a Python rule's test file (playground: https://semgrep.dev/playground/s/yy4G7):
    ```
    try:
        ...
    except* Exception: # <-- the star ('*')
        ...
    ```
2. Fails with:
    ```
    Syntax error at line target.py:3:
     `*` was unexpectedEngine(PartialParsing)
    ```

**Expected behavior**
I expected Semgrep to parse the file and rule properly.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Reproduced against:
- Semgrep Cloud (semgrep.dev)
- PyPI package version: `1.86.0`

**Use case**
It would allow to write a test case to ensure the Semgrep rules match `except*` when a developers uses such statements.

[^1]: https://docs.python.org/3.12/reference/compound_stmts.html#the-try-statement
