### ISSUE TITLE
Fail to parse GitHub Actions contexts

### ISSUE THREAD

**Issue by szepeviktor** [semgrep/semgrep#10577]
**Describe the bug**

```
When parsing a snippet as Bash for metavariable-pattern
 in rule 'yaml.github-actions.security.curl-eval.curl-eval',
 `{ runner.tool_cache` was unexpected
```

`${{ runner.tool_cache }}` is not Bash code, it is replaced with a value before passing it on to Bash.

**To Reproduce**
```yaml
        -
            name: "Setup problem matcher for PHPUnit"
            run: |
                echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
```

**Expected behavior**
Understand contexts.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
`image: "semgrep/semgrep"`

**Use case**
What will fixing this bug enable for you?

Run Semgrep in GHA workflows.
