### ISSUE TITLE
Rule matches expression even though it matches X in && (!X)

### ISSUE THREAD

**Issue by bellon-tiobe** [semgrep/semgrep#10635]
**Describe the bug**
Expressions which should be excluded are not. A rule like this:
```yaml
    pattern-either:
      - patterns:
          - pattern: global $GLOBAL = ...
          - pattern-not: global $GLOBAL::$TYPE = ...
      - patterns:
          - pattern: const $GLOBAL = ...
          - pattern-not: const $GLOBAL::$TYPE = ...
          - pattern-not-inside: ...
          - pattern-not-inside: ...
          - pattern-not-inside: ...
```
should exclude global variables with type specified, because they would match either of the `pattern-not` branches, which are under _"match all"_ combinators, so that should yield false.

**To Reproduce**
1. Go here: https://semgrep.dev/playground/r/AbU9BLk/juan_bellon_tiobe_com.asml-xxxx-global-must-have-type
2. Run and see lines 10, 22 & 48.

**Expected behavior**
Any expression matching `variable::type` should be excluded.

**Screenshots**
![const_implicit_global](https://github.com/user-attachments/assets/f3b6efda-997e-4a6b-bc4c-da46d7faa553)
![explicit_global](https://github.com/user-attachments/assets/4a43e17d-c51b-4a59-a305-dd084018f048)

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
The result is the same scanning locally, offline.

**Use case**
Implement a coding standard rule which applies to global variables.

**Comment by kopecs** [comment]
This seems expected to me, if a bit confusing. Namely, a `pattern-not` in a pattern like
```yaml
patterns:
 - pattern: const $FOO = ...
 - pattern-not: const $FOO::$BAR = ...
```
will not remove matches for the former, since the metavariables differ. That is, if you consider a match like
```
const FIRST::SECOND = whatever;
```
the first pattern (`const $FOO = ...`) would match with `$FOO` being `FIRST::SECOND`, and then the second would match the same range with `$FOO` as `FIRST`; since these aren't the same, it won't remove the match. Another explanatory example might be a pattern like
```yaml
patterns:
  - pattern: $X + 1
  - pattern-not: $Y + $X
 ```
still matching `3 + 1` since the `$X`s would differ when comparing the two ranges and deciding if to remove the finding.

I think something like https://semgrep.dev/playground/s/v8EvA should work in this case. Would that resolve this for you?
