### ISSUE TITLE
`export default function` from JS matches non-exported function

### ISSUE THREAD

**Issue by kamranayub** [semgrep/semgrep#10633]
**Describe the bug**

It seems semgrep's handling of `export default ...` in JS doesn't match my expectations.

Given the following code:

**test.js**

```js
function Breadcrumb({ id }) {
 ...
}
```

I have a rule that should match only when the function is default-exported:

```yml
rules:
  - id: check-slots-client-breadcrumb-export
    patterns:      
      - pattern: |
          export default function Breadcrumb({ id }) {
            ...
          }
      
    message: "Ensure the Breadcrumb component is exported"
    severity: ERROR
    languages: [javascript]
```

The function is matched even when I don't expect it to be (it's not exported _at all_).

See playground: https://semgrep.dev/playground/s/9AY8Y

Furthermore, it matches when it _is not_ default-exported:

```js
export function Breadcrumb({ id }) {
 ...
}
```

I don't _think_ I'm writing the rule wrong.

**To Reproduce**

 https://semgrep.dev/playground/s/9AY8Y

**Expected behavior**

It should **only** match when the function is default-exported.

**Screenshots**

![image](https://github.com/user-attachments/assets/2fe5c132-0254-48fc-b59d-9c623b9c4be1)

![image](https://github.com/user-attachments/assets/8914746f-9a56-40a4-9c0d-84af7abcc0ea)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

Playground

**Use case**

This was unexpected with verifying code within a lab environment where the user needs to follow the instructions to export a default component. It would pass when they didn't do it. I can test it other ways but this was unexpected.

**Workaround**

In my case, I can define a `pattern-either` and then in my lab environment I can verify semgrep returns `2 findings` to ensure the user wrote the right code.

```yml
rules:
  - id: check-slots-client-breadcrumb-export
    patterns:  
      - pattern-either:
        - pattern-regex: export default function Breadcrumb
        - pattern: |
            export default function Breadcrumb({ id }) {
              ...
            }
      
    message: "Ensure the Breadcrumb component is exported"
    severity: ERROR
    languages: [javascript]
```
