### ISSUE TITLE
Parse error with c++ structured binding

### ISSUE THREAD

**Issue by alexis-glass-scandit** [semgrep/semgrep#10666]
**Describe the bug**

With a structured binding and a static variable, and a rule which matches on `stat(...)`, the parse of a cpp files fails partway through.

**To Reproduce**

With the following minimal reproduction example, `semgrep` reports a parse error partway through (see below for the error)

`semgrep_rules.yml`
```
rules:
  - id: dont-use-stat
    pattern-either:
      - pattern: stat(...)
    message: "Usage of stat"
    severity: ERROR
    languages: [c++, c]
```

`semgrep_test.cpp`
```
#include <iostream>
#include <unordered_map>

int main() {
  static int32_t bar = 0;  // <-- without this line there is no parse error

  std::unordered_map<std::string, std::string> foo;
  foo["first"] = "second";
  foo["third"] = "fourth";

  for(auto &[key, value] : foo) {
    std::cout << key << ": " << value << std::endl;
  }
}
```
invocation:
```
semgrep --debug --error --config semgrep-rules.yml semgrep_test.cpp
```

error:
```
[00.09][ERROR]: exception on /path/to/semgrep_test.cpp (Parsing_error.Other_error (single name expected for simple var, /path/to/semgrep_test.cpp:11:12 "["))
```

**Expected behavior**

There should be no parse error.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Using semgrep installed by pip.

**Use case**
Matching `stat(...)`.
