### ISSUE TITLE
Pattern-sanitizers work wrong in if statements

### ISSUE THREAD

**Issue by yoshino-s** [semgrep/semgrep#10665]
**Describe the bug**
Pattern-sanitizers work wrong in if statements.

**To Reproduce**
https://semgrep.dev/playground/s/BY9OA

**Expected behavior**
Both code in line 17 and 35 are ok.

**Screenshots**
![image](https://github.com/user-attachments/assets/146c1b1d-5bb9-44a7-a85b-7abbeab32623)

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
I don't know if this is a bug. If not, how can I implement this feature?

**Comment by nmote** [comment]
Interesting. That does look like a bug. Thanks for the report!

**Comment by IagoAbal** [comment]
@yoshino-s in this case we can (and should) do something about it, because it's a very common pattern (and this is an issue we had suffered ourselves too), but note that in general Semgrep is not path-sensitive. The `||` is lazy and `newPath` will only be sanitized in the execution paths where `FILTER_PATTERN.matcher(newPath).matches()` is being evaluated. We can cover the most common / simple cases but there will always be cases left to handle.

**Comment by IagoAbal** [comment]
A workaround in your case could be:

```yaml
    pattern-sanitizers:
      - exact: true
        patterns:
          - pattern: $S
          - pattern: |
              if(<... $F.matcher($S).matches() ...> ) {
                ...
              }
              ...
```

But it has some drawbacks, one of them that it is slower.
