### ISSUE TITLE
Autofix Java classes drops annotations

### ISSUE THREAD

**Issue by Pamplemousse** [semgrep/semgrep#10686]
**Describe the bug**

Autofix on class declaration containing Java annotations drops said annotations.

**To Reproduce**

```yaml
rules:
  - id: fooify
    languages:
      - java
    severity: ERROR
    message: automatically add annotation @Foo
    patterns:
      - pattern: class $CLAZZ
    fix: |
        @Foo
        class $CLAZZ
```

```java
class Bar { }

@Something
class Baz { }
```

```shell
semgrep --config example.yaml --autofix example.java
```

Gives the following diff, where we see that the pre-existing `@Something` annotation on class `Baz` has been dropped.

```
diff --git a/example.java b/example.java
index c643e02..6242eb4 100644
--- a/example.java
+++ b/example.java
@@ -1,6 +1,7 @@
+@Foo
 class Bar {
 }
 
-@Something
+@Foo
 class Baz {
 }
```

**Expected behavior**

I expected the annotations that weren't caught by the original pattern not to be replaced.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

Running official binary `pip install`ed, version `1.97.0`.

**Use case**

It would me to autofix problematic code without breaking it.
