### ISSUE TITLE
Incorrect Substitution of Metavariable for YAML Anchors

### ISSUE THREAD

**Issue by devAL3X** [semgrep/semgrep#10693]
**Describe the bug**
When using a YAML file containing YAML [anchors](https://yaml.org/spec/1.2.2/#692-node-anchors) and aliases (e.g., `&anchor` and `*alias`), capturing parts with aliases using a metavariable does not correctly substitute the metavariable in the output message. Instead, the resulting message partially substitutes the alias and improperly handles the captured value.

**To Reproduce**

1. Use a YAML file with anchors and aliases.
2. Create a Semgrep rule that captures content using a metavariable targeting the alias.
3. Observe that the metavariable does not correctly replace the alias in the rule message.

rule:
```yaml
rules:
  - id: docker-compose-test
    languages:
      - yaml
    severity: ERROR
    message: matched "$IMAGE"
    patterns:
      - pattern: 'image: "$IMAGE"'

```

test yaml:
```yaml
version: "3"

test-anchor: &anchor semgrep/semgrep:1.79-nonroot

services:
  image: *anchor
```

same example in playground: https://semgrep.dev/playground/s/wdkA0

The metavariable `$IMAGE` is captured correctly, as shown in the JSON output from Semgrep:  
```json
{
  "metavars": {
    "$IMAGE": {
      "start": {
        "line": 3,
        "col": 14,
        "offset": 27
      },
      "end": {
        "line": 3,
        "col": 42,
        "offset": 55
      },
      "abstract_content": "semgrep/semgrep:1.97-nonroot"
    }
  }
}
```

However, in the final message output, the resolved value is not displayed correctly. Instead, the message includes the alias and a partial value: 
```
matched "&anchor semgrep/semgrep:1.97"
```

**Expected behavior**
message:
```
matched "semgrep/semgrep:1.97-nonroot"
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
- **OS**: macOS 14.5
- **Semgrep Version**: `1.97.0`

Also the issue is reproducible in the Semgrep playground.

**Use case**
Fixing this bug would enable reliable use of Semgrep in YAML files that utilize anchors and aliases, ensuring accurate metavariable substitution and consistent behavior. This is critical for analyzing YAML configurations like `docker-compose.yml`, where anchors are commonly used.
