### ISSUE TITLE
Literals being ignored in taint analysis

### ISSUE THREAD

**Issue by kam193** [semgrep/semgrep#10776]
**Describe the bug**
I try to make a taint rule respecting a literal value that can be the same in two places. However, it looks like it is capable of detecting variables only. I can imagine that this is the design, but I didn't find any explicit statement in the docs that it cannot work.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev/playground (click "share" and make public to get a shortlink): https://semgrep.dev/playground/s/Db1qy

Basically, the minimal rule looks like (in playground is a little bigger to show things I've tried):

```yaml
    mode: taint
    pattern-sources:
      - patterns:
          - pattern: |
                  $F = open($FILE_PATH, ...)
                  ...
                  $F.write(...)
          - focus-metavariable: $FILE_PATH
        by-side-effect: true

    pattern-sinks:
      - patterns:
          - pattern-either:
              - pattern: |
                  subprocess.Popen([$PYTHON, $FILE_PATH, ...], ...)
          - focus-metavariable: $FILE_PATH
 ```

And the tests and results are:

![obraz](https://github.com/user-attachments/assets/dadf4a41-5af5-42f2-add3-f48e7015b0b9)

**Expected behavior**
Both variable and literal cases are detected - this is still the same value.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

I've tested it using locally installed semgrep OSS as well as in the playground - both pro and turbo mode.

**Use case**
What will fixing this bug enable for you?

Catching cases when a static literal is used for unsafe action.
