### ISSUE TITLE
Java - ellipsis operator parse failure

### ISSUE THREAD

**Issue by jagprog5** [semgrep/semgrep#10773]
Semgrep's Java support for the `...` operator seems poor.

For example, this rule and others like it give a syntax error:

```yaml
rules:
  - id: redacted
    languages:
      - java
      - kt
    severity: INFO
    message: redacted
    pattern: |
      $VAR = $SOMETHING
      ...
      $VAR2 = $SOMETHING2
```

` Invalid pattern for Java: Stdlib.Parsing.Parse_error`

If I change the language to others, e.g. python, then it works as expected.

In semgrep Java, how would I match something occurring after a different thing?

For example:

```java
import java.security.*;
import java.security.spec.*;
import javax.crypto.spec.*;

public class Cls extends HttpServlet
{
    protected void something() throws IOException {
        Type p = new Type("ABC");

        p.initialize(456); // capture this
    }
}

```

- [x] P0: blocking your adoption of Semgrep or workflow

**Environment**

Semgrep version: `v1.101.0` via playground.
