### ISSUE TITLE
fix-regex doesn't appear to work on generic

### ISSUE THREAD

**Issue by davidfraser** [semgrep/semgrep#10805]
I've been trying to use fix-regex for rules applying across an entire codebase, using the `generic` language type. However, the rule seems to be ignored. Here's a basic use case:
```yaml
rules:
- id: test-regex-pytxt
  patterns:
  - pattern: 'print(my, name)'
  fix-regex:
    regex: '(.*)\)'
    replacement: '\1, flush=True)'
  message: Honour where honour's due
  languages: [generic]
  severity: WARNING

- id: test-regex-py
  patterns:
  - pattern-either:
    - pattern: 'print(my, name)'
  fix-regex:
    regex: '(.*)\)'
    replacement: '\1, flush=True)'
  message: Honour where honour's due
  languages: [python]
  severity: WARNING
```

With a Python file:
```python
print(my, name)
```
and a text file:
```
print(my, name)
```

semgrep with the above config and `-a` fixes the Python file to `print(my, name, flush=True)`. The text file detects the `[generic]` rule match, but leaves the file unchanged, and doesn't apply the fix.
