### ISSUE TITLE
metavariable-regex is allowed on top-level but ignored

### ISSUE THREAD

**Issue by ygrek** [semgrep/semgrep#10815]
**Describe the bug**
Thanks to the structured editor in the playground I figured what's wrong, so it is not a bug as i thought initially but a confusion with schema. Still error about wrong schema would be useful..

**To Reproduce**
https://semgrep.dev/playground/s/YGwNd
```
rules:
  - id: test
    languages:
      - ocaml
    severity: ERROR
    message: test
    pattern: ($LOG $...ARGS; Lwt.return_unit)
    metavariable-regex:
      metavariable: $LOG
      regex: log_
```
doesn't give any errors but metavariable-regex is ignored when matching.
The correct way is to wrap with `patterns` as follows:
```
    patterns:
      - pattern: ($LOG $...ARGS; Lwt.return_unit)
      - metavariable-regex:
          metavariable: $LOG
          regex: log_
```

**Expected behavior**
Expecting error message that rule is wrong (or "has unrecognized/skipped keys : metavariable-regex")

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
```
$ pipx install semgrep
$ semgrep --version
1.106.0
```
