### ISSUE TITLE
Is `pattern-inside` same as `pattern` when it comes to AND operation?

### ISSUE THREAD

**Issue by fubuki8087** [semgrep/semgrep#10817]
Look at these two rule examples:

```yaml
- patterns:
  - pattern-inside: |
      def foo(...):
        ...
  - pattern: print(...)
```

```yaml
- patterns:
  - pattern: |
      def foo(...):
        ...
  - pattern: print(...)
```

The code that needs to be matched is as follows:

```python
def foo():
    print("Inside foo")
```

It seems that both rules can match the code. The first rule means it first matches the function body `foo`, and within that body, it then matches the call to `print`. The second rule means it matches the code under both conditions: (1) in the function body `foo`, and (2) at the callsite of `print`.

It feels like there is no difference between `pattern-inside` and `pattern` in this case. I’m not sure what the purpose of `pattern-inside` is.
