### ISSUE TITLE
Python keyword-only-arguments causes "metavariable-pattern failed because $ARG does not bind to a sub-program"

### ISSUE THREAD

**Issue by meshy** [semgrep/semgrep#10828]
**Describe the bug**
My rule (which uses `metavariable-pattern`) is skipped on any file containing a function requiring [keyword-only arguments](https://peps.python.org/pep-3102/).

When it fails, it prints the error:

```
Internal matching error when running my-rule on target.py:
 An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/semgrep/semgrep

metavariable-pattern failed because $ARG does not bind to a sub-program, please check your ruleEngine(MatchingError)
```

**To Reproduce**

https://semgrep.dev/playground/s/Kx6v7?editorMode=advanced

```python
def a(*, b):
    pass
```
```yaml
rules:
  - id: my-rule
    languages:
      - python
    patterns:
      - pattern: |
          def $FUNC($ARG, ...):
              ...
      - metavariable-pattern:
          metavariable: $ARG
          pattern: arg_name
    message: test
    severity: ERROR
```

**Expected behavior**
Parsing this file should not crash.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Installed from PyPI.

**Use case**
I will be able to match arguments with particular names.
