### ISSUE TITLE
Type and Value Extraction doesn't work in Java with Meta Variables

### ISSUE THREAD

**Issue by zer00oo0-hu** [semgrep/semgrep#10842]
**Describe the bug**
I was trying to extract all ``@RequestHeader`` name its type and associated variable name, but it seems it works only when provide ``@RequestHeader($HEADER)`` the moment you provide ``@RequestHeader($HEADER) $TYPE $VAR`` It shows zero results.

**To Reproduce**
https://semgrep.dev/playground/s/QrY6J
```yaml
rules:
  - id: request-header-with-param
    languages: [java]
    severity: INFO
    message: "Found request header: $HEADER with parameter $VAR"
    # Force a newline between the annotation and the parameter type/name.
    pattern: |
      @RequestHeader($HEADER) $TYPE $VAR
    metadata:
      category: security
      technology: spring
```

```java

  @PostMapping("/signal/{rnd-item}")
  public ResponseEntity<?> signal(
      @RequestHeader("X-USER-ID") String uid,
      @RequestHeader("x-app-version") String appVersion,
      @RequestHeader("x-device") String device,
      @PathVariable("rnd-item") String randomItem) {
    log.info("Signal received for user: {} with item: {}", uid, randomItem);
    return ResponseEntity.ok(
        betaDetailService.storeUserDetail(
            uid, randomItem, appVersion, device));
  }
```

**Expected behavior**
It should detect all request header names, types and associated variable names

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by kopecs** [comment]
You need a slightly different pattern here, I believe. Does
```yaml
rules:
  - id: request-header-with-param
    languages: [java]
    severity: INFO
    message: "Found request header: $HEADER with parameter $VAR"
    # Force a newline between the annotation and the parameter type/name.
    pattern: |
      $FUNC(..., @RequestHeader($HEADER) $TYPE $VAR, ...) { ... }
    metadata:
      category: security
      technology: spring
```
Work as you expect?

Generally patterns have to syntactically be expressions, statements or declarations (so a single parameter cannot itself comprise a pattern---this is mostly due to ambiguity).
