### ISSUE TITLE
Csharp region avoid findings detection

### ISSUE THREAD

**Issue by sebasrevuelta** [semgrep/semgrep#10851]
**Describe the bug**
This [csharp file](https://github.com/jerryhoff/WebGoat.NET/blob/master/WebGoat/Code/SQLiteMembershipProvider.cs) has some "region lines" from 20-51.
The following sample rule:
```
rules:
- id: "csharp_injection_rule-SQLInjection"
  languages:
  - "csharp"
  patterns:
    - pattern: "(SqliteCommand $CMD).CommandText = <...$ARG...>;"
    - pattern-not: "(SqliteCommand $CMD).CommandText = \"...\";"
  message: |
    SQL Injection is a critical vulnerability that can lead to data or system compromise.
  severity: "WARNING"
  metadata:
    shortDescription: "Improper Neutralization of Special Elements used in an SQL
      Command ('SQL Injection')"
    category: "security"
    owasp:
    - "A1:2017-Injection"
    - "A03:2021-Injection"
    cwe: "CWE-89"
    security-severity: "Medium"
```
it reports 33 findings removing or comment the region lines 20-51, but 0 findings with these lines.

**To Reproduce**
Scan the file with the sample rule.
```
semgrep scan --config=rules/sqli.yaml 
````
**Expected behavior**
Detected all the expected cases.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by yosefAlsuhaibani** [comment]
Taking a closer look at this: It seems like four variables within the lines 21-50 are what causing the disappearing findings, i.e if you uncomment:
```csharp
        public sealed class SQLiteMembershipProvider : MembershipProvider
        {
                #region Private Fields
                private const string _httpTransactionId = "SQLiteTran";
                private const int NEW_PASSWORD_LENGTH = 8; //34
                /*
                private const string APP_TB_NAME = "[aspnet_Applications]";
                private const string USER_TB_NAME = "[aspnet_Users]";
                private const string USERS_IN_ROLES_TB_NAME = "[aspnet_UsersInRoles]";
                private const string PROFILE_TB_NAME = "[aspnet_Profile]";
                */
                private const int MAX_APPLICATION_NAME_LENGTH = 256;
                private const int MAX_USERNAME_LENGTH = 256;
                private const int MAX_PASSWORD_LENGTH = 128;
                private const int MAX_PASSWORD_ANSWER_LENGTH = 128;
                private const int MAX_EMAIL_LENGTH = 256;
                private const int MAX_PASSWORD_QUESTION_LENGTH = 256;
                private static string _connectionString;
                private static string _applicationName;
                private static string _applicationId;
                private static bool _enablePasswordReset;
                private static bool _enablePasswordRetrieval;
                private static bool _requiresQuestionAndAnswer;
                private static bool _requiresUniqueEmail;
                private static int _maxInvalidPasswordAttempts;
                private static int _passwordAttemptWindow;
                private static MembershipPasswordFormat _passwordFormat;
                private static int _minRequiredNonAlphanumericCharacters;
                private static int _minRequiredPasswordLength;
                private static string _passwordStrengthRegularExpression;
                private static readonly DateTime _minDate = DateTime.ParseExact ("01/01/1753", "d", CultureInfo.InvariantCulture);

                #endregion
```
You'd get all 34 findings (I got 34: I saw you mentioned 33 in your issue, is this expected/was that a typo?). I think this is a naming bug (i.e those variables persist)

**Comment by yosefAlsuhaibani** [comment]
Here's a minified example:
```csharp
namespace a
{
		public override bool func ()
		{
                        //uncomment this line to get the finding
			public string USER_TB_NAME = "aa";
			cmd.CommandText = "UPDATE " + USER_TB_NAME;
	        }
}
```
With the same rule except without typed metavariables:
```yaml
rules:
- id: "csharp_injection_rule-SQLInjection"
  languages:
  - "csharp"
  patterns:
    - pattern: "($CMD).CommandText = <...$ARG...>;"
    - pattern-not: "($CMD).CommandText = \"...\";"
  message: |
    SQL Injection is a critical vulnerability that can lead to data or system compromise.
  severity: "WARNING"
```
What I think is happening is that when `USER_TB_NAME` is commented, the engine isn't able to constant fold/evaluate the string concatenation, and so it leaves `"UPDATE" + USER_TB_NAME"` as is (hence we match the `pattern:` and we don't match the `pattern-not`). When we uncomment the string, constant folding happens and we match the `pattern-not`.
