### ISSUE TITLE
[JS] erroneous very high memory with dict pattern

### ISSUE THREAD

**Issue by jagprog5** [semgrep/semgrep#10986]
The file to scan is found [here](https://github.com/Keyfactor/ejbca-ce/blob/1997844652b2eace1d4e5b2a6d9d8274f1ed5f0f/doc/dist/js/lunr-index.js). It is a 5mb file which contains a large nested json structure in javascript.

```js
var lunrIndex = {"version":"0.5.0","fields":[{"name":"title","boost":10}, ...
```

The rule is as follows:

```yml
rules:
  - id: redacted
    languages:
      - javascript
      - typescript
    severity: INFO
    message: msg
    pattern-either:
      - pattern: "$IMPORT.decrypt({$PROP_KEY: $PROP_VALUE}, ...)"
      - pattern: "$IMPORT.encrypt({$PROP_KEY: $PROP_VALUE}, ...)"
```

The intent of the rule is to match findings like:

```js
function decryptMessage(privateKey, ciphertext) {
    return window.crypto.subtle.decrypt(
      { 
        name: "RSA-OAEP" },
      privateKey,
      ciphertext,
    );
  }
```

Some downstream filtering then uses the metavariables, to extract content.

On latest semgrep, that rule scanning that file causes memory usage to jump to ~_2.5GB_. It should instead use next to nothing, since the function names to scan are never used in the test file - the arg is gated by context which never happens.

I think this is a bug in semgrep's js engine. But alternative rules would be helpful as well. Thanks!
