### ISSUE TITLE
[Python] A false positive in Semgrep taint mode

### ISSUE THREAD

**Issue by MarkCarter88** [semgrep/semgrep#10984]
**Describe the bug**
Hi, I am running Semgrep in taint analysis mode using CLI and getting false positives. 
For a (simplified) program below I expected to see no issues. Semgrep, however, reports a finding at line 6, where the variable `tainted` is overwritten, even though `tainted` is not an argument to the sink function. 

```
import random
from typing import Any
class MainActivity:
  def MainFunction(self): 
    tainted = MainActivity.source() # created tainted data 
    tainted = MainActivity.sink(81) # overwrite tainted data
 
  @staticmethod
  def source():
    return "Hello" 

  @staticmethod
  def sink(param: int):
    print(param)
    return "" 
```

I am using the following rule to detect the taint (all sources are functions named source, all sinks are names sink and may have an index):
```
rules:
  - id: py-taint
    languages:
      - python
    message: Detected sink
    mode: taint
    pattern-sources:
      - pattern: $X.source(...)
      - pattern: $X.i_source(...)
      - pattern: $X.b_source(...)
      - pattern: $X.s_source(...)
    pattern-sinks:
      - pattern-regex: '.*sink(\d*).*#?'
    severity: WARNING
 ```

**To Reproduce**
Run `semgrep scan --config=rule-above.yaml` on the program above.

**Screenshot**
Semgrep reports that tainted data is passed to the sink in line 6.
<img width="715" alt="Image" src="https://github.com/user-attachments/assets/cb051d99-2b3f-44e5-bb3e-28d3f235d18c" />
 
**Expected behavior**
Zero findings because the tainted data is not passed to the sink function.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Running a local build (installed with pip), version 1.120.1.

**Comment by dijkstracula** [comment]
Hi Mark,

Thanks for filing this issue - I agree that the behaviour here is funny.  I've raised the issue internally and we'll take a look.

Thanks!
Nathan

**Comment by kopecs** [comment]
Hey @MarkCarter88, any reason you can't have a "proper" pattern as the sink? E.g., `$OBJ.sink(...)`? This is a pretty odd pattern to have as a sink and I doubt we are likely to dedicate time to working on this interaction of regex matches with lvalues which previously were tainted.

**Comment by MarkCarter88** [comment]
@kopecs sorry, the notification got lost in the mail. I have many sinks that are named, e.g., `a.sink(arg)`, `obj.b_sink10(arg)`, `self.s_sink4(arg)`, so regex seemed like the most general solution. Is there a better way to configure such sinks without explicitly listing them all?

**Comment by kopecs** [comment]
The issue is more that your regex is overbroad and doesn't rely on any semantic property. You could do something like
```yaml
patterns:
- pattern: $FUNC(..., $ARG, ...)
- focus-metavariable: $ARG
- metavariable-regex:
    - metavariable: $FUNC
    - regex: as above 
```
and I think that would resolve your issue

**Comment by MarkCarter88** [comment]
Thanks! I changed my rules to:
```
rules:
  - id: py-taint
    languages:
      - python
    message: Detected sink
    mode: taint
    pattern-sources:
      - patterns:
        - pattern: $F()
        - metavariable-regex:
            metavariable: $F
            regex: '.*source(\d*)'
    pattern-sinks:
      - patterns:
        - pattern: $F(...,$ARG,...)
        - focus-metavariable: $ARG
        - metavariable-regex:
            metavariable: $F
            regex: '.*sink(\d*)'
    severity: WARNING
``` 
and tried on a few examples, seems like the issue is resolved.
