### ISSUE TITLE
CircleCI - Exited with code exit status 2 using semgrep docker image

### ISSUE THREAD

**Issue by louisbizouerne-lifen** [semgrep/semgrep#10981]
**Describe the bug**
When running Semgrep in CircleCi with the default config from the doc (https://semgrep.dev/docs/semgrep-ci/sample-ci-configs#circleci), it says `Exited with code exit status 2` without explaining any error. Using the same command through the python image, it works well (within the same repo)

**To Reproduce**

Not working pattern:
See `.circleci/config.yml` bellow
```
version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: new
          context:
            - semgrep
jobs:
  semgrep-full-scan:
    docker:
      - image: semgrep/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep CE full scan"
          command: semgrep scan --config auto --debug
```
Output from CircleCI:
```

┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Not sending pseudonymous metrics since metrics are configured to AUTO and registry usage is False

Exited with code exit status 2
```

Working pattern
See `.circleci/config.yml` bellow
```
version: 2.1

jobs:
  semgrep:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: Install semgrep
          command: python3 -m pip install semgrep
      - run:
          name: Run semgrep scan
          command: semgrep scan --config auto --debug

workflows:
  version: 2
  SAST:
    jobs:
      - semgrep
```
**Expected behavior**
Running `semgrep scan --config auto --debug` from the Semgrep image should work or should provide more details about the error.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
CircleCI

**Use case**
Deploying Semgrep CE as a SAST in our CI
