### ISSUE TITLE
Subject: Why is this .find() rule still flagged even with companyId in the object?

### ISSUE THREAD

**Issue by mituso89** [semgrep/semgrep#10993]
Hi, I'm writing a rule to ensure .find() is always called with a filter that includes companyId. Here's my Semgrep rule:
```

rules:
  - id: mongoose-find-without-companyid
    languages:
      - typescript
      - javascript
    severity: WARNING
    message: Avoid using .find() without a companyId filter.
    patterns:
      - pattern: |
          $MODEL.find($OPT)
      - metavariable-pattern:
          metavariable: $OPT
          patterns:
            - pattern-not: |
                { companyId: $_ }
            - pattern-not: |
                { ..., companyId: $_, ... }
    metadata:
      category: security
```

However, it's still flagging the following code:
```
const userRoleFilter = {
  companyId: 1
};

await AccessUserRoleModel.find(userRoleFilter);

```

this includes companyId, so I don’t understand why they’re still being flagged. Is there something wrong with the pattern-not logic? Or do I need to use pattern-either or pattern-inside?

Thanks in advance!
