### ISSUE TITLE
Metavariables inside square bracket inside parentheses

### ISSUE THREAD

**Issue by sam-rad** [semgrep/semgrep#11009]
I guess this is more of a question rather than bug report. I have a function call with an array argument and wanna replace it with regular arguments like this:

```ts
// Before
func(['a', 'b'])

// After
func('a', 'b')
```

Now if I use this config:
```yml
rules:
  - id: blah
    languages:
      - ts
    pattern: func([ ... ])
    fix: func($...ARGS)
```

It finds the matches but obviously the fix doesn't work since we have no `$ARGS` defined in the pattern. 

Now if I replace that with:

```yml
rules:
  - id: blah
    languages:
      - ts
    pattern: func([ $...ARGS ])
    fix: func($...ARGS)
```

Then it matches nothing. What am I doing wrong?
