### ISSUE TITLE
Asterisk in python code causes unexpected matches of a pattern.

### ISSUE THREAD

**Issue by melonora** [semgrep/semgrep#11023]
**Describe the bug**
In Python unpacking a list with `*` influences the matching of rules with semgrep. More specifically I defined the following rule:

```
rules:
  - id: avoid-any-fstring-in-trans
    languages:
      - python
    message: Avoid any f-strings inside trans._(); use .format() after translation.
    severity: ERROR
    patterns:
      - pattern: trans._($STR)
      - metavariable-pattern:
          metavariable: $STR
          pattern: f"..."
```

and it fails due to this part in the python code:
```
        for camera in self.canvas.camera, *self.canvas.grid_cameras:
            camera._3D_camera.depth_value = 128 * diameter
```

**To Reproduce**
I created an example in the playground which includes the complete script on which the matching failed. Now the first example includes the code snippet above, but as you can see it includes also `trans._("...")` in the findings resulting in a total of 15 findings instead of 1:
https://semgrep.dev/playground/s/zyWL1

The second example does not have the above code snippet. I slightly rewrote it and now we have 0 findings:
https://semgrep.dev/playground/s/pZqLN

I also manually checked whether adding a code snippet like `trans._(f'{b}_test_case')` causes a match which it does in the second example.

**Expected behavior**
I would expect 0 matches as the fstrings do not match the pattern.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Use on CI

**Use case**
In napari we use semgrep to check particular syntax in our CI workflows.
