### ISSUE TITLE
Rust: Patterns looking for specific trait implementations do not match

### ISSUE THREAD

**Issue by derconno** [semgrep/semgrep#11064]
**Describe the bug**
It should be possible to match for specific traits being implemented. 

**To Reproduce**
https://semgrep.dev/playground/s/nWlbd

Rule:
```yaml
rules:
  - id: trait-implementation
    languages:
      - rust
    severity: WARNING
    patterns:
      - pattern: impl $IMPL for $_
      - metavariable-regex:
          metavariable: $IMPL
          regex: (BarTrait)
    message: BarTrait is implemented
```

Code:
```Rust
struct FooStruct;

// ok: trait-implementation
impl FooStruct {
        fn foo() {
        }
}

// ruleid: trait-implementation
impl BarTrait for FooStruct {
        fn bar() {
        }
}
```

**Expected behavior**
Not only should rules match that generally look for implementations of a struct, but also ones that are restricted to specific traits. 

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
