### ISSUE TITLE
pattern-regex on a single metavariable

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1217]
I've seen several cases where it would be helpful to make pattern-regex operator not on a full range, but on a single metavariable.

E.g.: 
```
- pattern: 'foo($X)
- pattern-regex:
   - regex: '[0-9]'
   - metavariable: '$X'
 ```
