### ISSUE TITLE
Pattern regex is slow to run

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1387]
The following rules for hardcoded passwords are slow to run, possibly because of the complexity of the regex. Does the regex run on the whole file or only what matches other patterns?

Pending performance improvements with these rules I've temporarily removed them from blocking my team's CI builds.

```yaml
rules:
- id: hardcoded_password_1
  patterns:
    - pattern-inside: $X = "..."
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*="
  message: "Hardcoded password 1"
  languages: [javascript]
  severity: WARNING
- id: hardcoded_password_2
  patterns:
    - pattern-inside: var $X = "...";
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*="
  message: "Hardcoded password 2"
  severity: WARNING
  languages: [javascript]
- id: hardcoded_password_3
  patterns:
    - pattern-inside: $X == "...";
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*=="
  message: "Hardcoded password 3"
  severity: WARNING
  languages: [javascript]
- id: hardcoded_password_4
  patterns:
    - pattern-inside: if ($X == "...") {...};
    - pattern-regex: "\\(\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*=="
  message: "Hardcoded password 4"
  severity: WARNING
  languages: [javascript]
- id: hardcoded_password_5
  patterns:
    - pattern-inside: |
        function $F(..., $X="...", ...) {
          ...
        }
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*="
  message: "Hardcoded password 5"
  severity: WARNING
  languages: [javascript]
- id: hardcoded_password_6
  patterns:
    - pattern-inside: $X[$Y] = "...";
    - pattern-regex: "\\[('|\")?\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)('|\")?\\]"  
  message: "Hardcoded password 6"
  severity: WARNING
  languages: [javascript]
- id: hardcoded_password_7
  patterns:
    - pattern-inside: |
        $Y = {$X: "..."};
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?):"  
  message: "Hardcoded password 7"
  severity: WARNING
  languages: [javascript]
```

**Comment by mschwager** [comment]
Hey there,

I see a few ways we could speed this up. First, this looks like a great opportunity to use the new [`metavariable-regex`](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#metavariable-regex) operator. This would allow us to update the following rule:

```
  patterns:
    - pattern-inside: $X = "..."
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*="
```

```
  patterns:
    - pattern: $X = "..."
    - metavariable-regex:
        metavariable: $X
        regex: "(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)"
```

This reduces the size and complexity of the regex, and only runs it over the contents of the metavariable as opposed to the entire source code file.

The second optimization is a bit trickier. We currently pass each individual rule to `semgrep-core`. So if we combine the rules using something like `pattern-either` we can minimize the calls to `semgrep-core`. If we consider the following:

```
rules:
- id: hardcoded_password_1
  patterns:
    - pattern-inside: $X = "..."
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*="
  message: "Hardcoded password 1"
  languages: [javascript]
  severity: WARNING
- id: hardcoded_password_2
  patterns:
    - pattern-inside: var $X = "...";
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*="
  message: "Hardcoded password 2"
  severity: WARNING
  languages: [javascript]
- id: hardcoded_password_3
  patterns:
    - pattern-inside: $X == "...";
    - pattern-regex: "\\w*(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)\\s*=="
  message: "Hardcoded password 3"
  severity: WARNING
  languages: [javascript]
```

We could instead turn this into one rule like so:

```
  patterns:
    - pattern-either:
        - pattern: $X = "..."
        - pattern: var $X = "...";
        - pattern: $X == "...";
    - metavariable-regex:
        metavariable: $X
        regex: "(?i)(pas+wo?r?d|pass(phrase)?|pwd|token|secrete?)"
```

I haven't tested the performance differences between multiple rules vs. using `pattern-either` but I suspect the latter will be quicker. Hope this helps! Let me know if this improves things :+1:
