### ISSUE TITLE
RFC: Simplify pattern matching API

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#1489]
## Why

- Our current API has many different possible keys, and their interactions are hard to fully define
- Our current API doesn't meet well-known mental models
- Some functionality of our current API is broken (e.g. `pattern-inside` with `pattern-either`)

## Needs

- Minimize the number of API components of the matching API
- Ideally fit the API within a well-known mental model
- Create an easily maintainable and well-documented API

## Proposal

- [Boolean set logic](https://en.wikipedia.org/wiki/Boolean_algebra) is well understood and well researched; let's use it
- Make five API components available:
  - `pattern`: Specifies a single Semgrep pattern; value is always code text; result is the product of a range (a.k.a. a fully connected set of code byte offsets) and a set of metavariable matches
  - `regex`: Specifies a single regular expression; value is always text; result is the product of a range and an empty set of metavariable matches
  - `metavariable`: Specifies constraints on metavariable bindings; value is an object of constraint parameters; result is the product of the universal set and a set of metavariable constraints; must be used in a conjunction
  - `and`: Performs a set intersection of two or more matches; the intersection is non-empty iff all identically named metavariables match
  - `or`: Performs a set union of two or more matches; the returned set is a fully disjoint set of range-metavariable products; the union of two products with identical ranges but different metavariables is a set of two range-metavariable products
  - `not`: Takes the set complement of its single argument's match; value is always `and`, `or`, or `pattern`
- For ease of transition, all components must be nested under a top-level `match` key in the rule YAML
- When compiling the rule, DeMorgan's and Distributive Laws are applied to simplify the match; the resulting match will be a simple union of intersections, each of which must include one non-complement pattern (see below)

### Examples

- A single match:
```yaml
match:
  pattern: foo(...)
```

- Match all except an edge case:
```yaml
match:
  and:
    - pattern: foo(...)
    - not:
        pattern: foo(..., safe=True)
```

- Multiple possible taint avenues:
```yaml
match:
  and:
    - or:
      - pattern: |
           def $FUNC(...):
             ...
             $R = requests.$METHOD(...)
             ...
      - pattern: |
           def $FUNC(...):
             ...
             $R = requests.$METHOD.get(...)
             ...
    - pattern: |
           $DATA = $R.get("...", ...)
           ...
    - or:
      - pattern: some_sink($DATA)
      - pattern: some_other_sink($DATA)
```

- Complement ranges are disallowed:
```yaml
# INVALID
match:
  or:
    - pattern: a
    - not:
         pattern: b

# EQUIVALENT, AND ALSO INVALID
match:
  not:
    - and:
      - not:
          pattern: a
      - pattern: b

# VALID
match:
  not:
    - or:
      - pattern: a
      - not:
          pattern: b
```

## Issues

- How to achieve the current `pattern-inside` functionality is not obvious, and omitting a trailing statement ellipses will cause no matches
- Debugging nested `not`s could be tricky -- to downscope we could ban them at anything other than the leaf position
- Documenting a set-oriented specification in approachable terms might be difficult without the use of mathematical jargon
- There's room to play with the naming; e.g. `all-of` for `and`, `any-of` for `or`
