### ISSUE TITLE
'y' and 'n' patterns cause internal semgrep-core error

### ISSUE THREAD

**Issue by defreez** [semgrep/semgrep#1597]
**Describe the bug**
A pattern of exactly `y` or `n`, causes an internal error on semgrep.dev. Other single character literals work just fine. This only occurs if `|` is not used in the pattern.

The error message on semgrep.dev is

```
{"code":2,"message":"an internal error occured while invoking semgrep-core:\n\tinvalid yaml: wrong rule fields\nAn error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep","type":"SemgrepError"}
```

**To Reproduce**
Use this pattern 
```
rules:
- id: bad-letter
  pattern: y
  message: |
    message
  fix: |
    
  severity: WARNING
```

or
```
rules:
- id: bad-letter
  pattern: n
  message: |
    message
  fix: |
    
  severity: WARNING
```

semgrep.dev adds the `|` automatically when navigating away from the Advanced tab, so I cannot provide a semgrep.dev link. 

**Expected behavior**
I expect this to behave the same way as other literal characters. The following pattern works fine.

```
rules:
- id: bad-letter
  pattern: b
  message: |
    message
  fix: |
    
  severity: WARNING
```
