### ISSUE TITLE
Go rule matches when it shouldn't

### ISSUE THREAD

**Issue by dgryski** [semgrep/semgrep#1602]
With semgrep version 0.21.0

```
~/go/src/github.com/flynn/flynn/test/runner $ semgrep --exclude=vendor -l go -e '$R.Header.Set($HDR, $VAL); ... ; $R.Header.Set($HDR, $VAL2); ' .
runner.go
840:		req.Header.Set("Content-Type", "application/json")
841:		req.Header.Set("Authorization", "token "+r.githubToken)
```

The `$HDR` values should be the same (according to the rule) but clearly they are not.

This also happens with the following yaml file:
```
rules:
  - id: use-header-set
    patterns:
            - pattern: |
                    $R.Header.Set($HDR, ...)
                    ...
                    $R.Header.Set($HDR, ...)
    message: "duplicate header set"
    languages: [go]
    severity: ERROR
```

This yaml file does not match on the following code however:
```
package main

func main() {

	r.Header.Set("Foo", "Bar")

	fmt.Println("hello, world")

	r.Header.Set("Fob", "Baz")
}
```

But it *does* match on the following (missing `package main` line, making it an invalid Go file? Is there something in the runner.go file that's causing it to fail to parse but not reporting it, and then that messes up the matching code later?)

```
func main() {

	r.Header.Set("Foo", "Bar")

	fmt.Println("hello, world")

	r.Header.Set("Fob", "Baz")
}
```
