### ISSUE TITLE
Support for "pattern-not-regex"

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1607]
**Is your feature request related to a problem? Please describe.**
Someone asked about this and I myself had a need for this scenario. See https://github.com/returntocorp/semgrep-rules/blob/63e92b8d2e8b956b0c50e541170f819be5140d54/python/flask/security/xss/audit/template-href-var.html for an example and comments about how this would be useful.

**Describe the solution you'd like**
`pattern-not-regex`, similar to `pattern-regex` + `pattern-not`

**Describe alternatives you've considered**
I tried using negative lookaheads and negative lookbehinds which are native in regular expressions, but either 1) these don't work in Python `re` or 2) they're too complicated for my pea-brain to make work. In theory... just doing `pattern-not` but for regex sounds easier  😅 

**Additional context**
Another person asking:
![image](https://user-images.githubusercontent.com/2374948/91618273-caed1280-e93e-11ea-8496-b5dcf56befd4.png)

**Comment by dgryski** [comment]
I was looking for this today.  I ended up finding a better way to structure this rule, but one of my attempts looked like this:

```
rules:
  - id: hmac-needs-new
    patterns:
        - pattern: hmac.New($FUNC,...)
        - pattern-not: hmac.New(md4.New, ...)
        - pattern-not: hmac.New(md5.New, ...)
        - pattern-not: hmac.New(sha1.New, ...)
        - pattern-not: hmac.New(sha256.New, ...)
        - pattern-not: hmac.New(sha512.New, ...)
    message: "maybe calling hmac.New with non-standard hash"
    languages: [go]
    severity: ERROR
```

And I would have been happy to have instead
```
- pattern: hmac.New($H, ...)
- metavariable-regex:
   metavariable: '$H'
   regex-not: '(md5|md5|sha1|sha256|sha512).New'
```

The example at https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#metavariable-regex shows blocklisting insecure functions.  I wanted to have a rule allowing-listing good functions.

**Comment by mschwager** [comment]
We can get most of the way there with a [negative lookahead assertion](https://docs.python.org/3/library/re.html#regular-expression-syntax):

```
$ cat test.yaml 
rules:
- id: test-not-regex
  message: Test not regex
  severity: WARNING
  languages: [go]
  patterns:
    - pattern: hmac.New($H, ...)
    - metavariable-regex:
        metavariable: '$H'
        regex: '(?!sha1|sha256|sha512)'
```

```
$ cat test.go 
package main

import (
	"crypto/hmac"
	"crypto/md5"
	"crypto/sha1"
	"crypto/sha256"
	"crypto/sha512"
)

func main() {
	mac1 := hmac.New(md5.New, []byte("foo"))
	mac2 := hmac.New(sha1.New, []byte("foo"))
	mac3 := hmac.New(sha256.New, []byte("foo"))
	mac4 := hmac.New(sha512.New, []byte("foo"))
}
```

```
$ python -m semgrep --config test.yaml test.go 
running 1 rules...
test.go
severity:warning rule:test-not-regex: Test not regex
12:	mac1 := hmac.New(md5.New, []byte("foo"))
```

Unfortunately we're missing the `.New` detection at the end of the `regex`, but I suspect this rule is precise enough to get it right most of the time. Note the `metavariable-regex` implementation uses [`re.match` instead of `re.search`](https://docs.python.org/3/library/re.html#search-vs-match). This means the negative lookahead assertion correctly fails to match at the beginning of the string and stops searching:

```
In [51]: re.match('(?!sha1|sha256|sha512).New', 'md5.New')

In [52]: re.search('(?!sha1|sha256|sha512).New', 'md5.New')
Out[52]: <_sre.SRE_Match object; span=(3, 7), match='.New'>

In [53]: re.match('(?!sha1|sha256|sha512)', 'md5.New')
Out[53]: <_sre.SRE_Match object; span=(0, 0), match=''>

In [54]: re.search('(?!sha1|sha256|sha512)', 'md5.New')
Out[54]: <_sre.SRE_Match object; span=(0, 0), match=''>
```

We could consider negative lookbehind assertions, but they require fixed length strings. So we can't do something like `(?<!sha1|sha256|sha512).New`. We could also consider `pattern-regex` since it uses `re.search` under the hood. This is a logical start:

```
rules:
- id: test-not-regex
  message: Test not regex
  severity: WARNING
  languages: [go]
  patterns:
    - pattern-inside: hmac.New(...)
    - pattern-regex: '(?!sha1|sha256|sha512).New'
```

The problem is that this will also match the `hmac.New` portion of the string:

```
$ python -m semgrep --config test.yaml test.go 
running 1 rules...
test.go
severity:warning rule:test-not-regex: Test not regex
12:.New
12:.New
13:.New
13:.New
14:.New
14:.New
15:.New
15:.New
```

There may be some way to improve upon this, but I think your best bet will be the limited negative lookahead assertion with `metavariable-regex`.
