### ISSUE TITLE
Expand support for compile-time constants

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1645]
Currently, we support constant propagation under limitations (globals in Python see #349; variables under the `const` keyword for other languages).

However, many of the checks we write involve a need to ensure that an expression evaluates to a compile-time constant. This is key to supporting the sort of secure-by-default work that, for instance, Google leverages heavily with things like detecting SQLi. 

Desired behavior: expand constant propagation such that we don't need to rely on the `const` keyword. Pattern `$X.innerHTML = "..."` should match: 

```
var term = random() > 0.5 ? 'baz' : 'baz2';
thing.innerHTML = term + ' &mdash; else';
```

Stretch/Non-goals:
* Although we usually see a need for compile-time-constant _strings_, it might be helpful to be able to specify const for any type in the program, e.g. `($X: const<int>)`, even if the languages doesn't have a concept of const
* A basic implementation can be intraproceedural, with a stretch implementation being interproceedural but intrafile. (Related: equality binding constant propagation: https://github.com/returntocorp/semgrep/issues/374)

**Comment by clintgibler** [comment]
+1 this would be really helpful. Agreed that intraprocedural within 1 file would get most of the value (for now), at least based on how we write rules currently and community rule writing asks.

Per @ievans's first point, doing this for more than just strings would be nice (ints, floats, ...).

**In practice**, what users generally want to know is:

> Is this <variable|function argument|etc> **not** a compile-time-constant; that is, could it be a dynamic value (and thus potentially user controlled)?

So when @ievans says `$X.innerHTML = "..."`, this is actually the *safe* case, so your rule would probably combine that with a `pattern-not` like:

```yaml
- patterns:
     - pattern-not: $X.innerHTML = "...";    # filter out false positives
     - pattern: $X.innerHTML = ...;          # what remains is interesting
```

To save users some work combining clauses, would it be useful to provide a primitive like [metavariable-regex](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#metavariable-regex) but for checking that a metavariable is **not** a constant? Example:

```yaml
- patterns:
     - pattern: $X.innerHTML = $Y;
     - metavariable-not-constant: "$Y"
```

Not sure how best to express this, but I've often wanted to be able to say, "... and X is not a compile time constant."
