### ISSUE TITLE
semgrep.dev lesson 6b solution not working

### ISSUE THREAD

**Issue by ropnop** [semgrep/semgrep#1786]
Following along with the lessons and the "hint" on https://semgrep.dev/learn/15 does not seem to work:

```
rules:
- id: subprocess-call
  patterns:
  - pattern: subprocess.call(...)
  - pattern-not: subprocess.call("...", ...)
```

This finds no matches. What is the correct "solution" to match the last 2 `subprocess.call` lines, but not the first one with a hardcoded string?
