### ISSUE TITLE
OWASP ASVS as a metadata ?

### ISSUE THREAD

**Issue by SPoint42** [semgrep/semgrep#1851]
We have CWE and OWASP as a metadata. 
I see some effort to add ASVS rules. https://github.com/semgrep/rules-owasp-asvs

I made some work on mapping semgrep in OWASP Requirements.

Could it be possible to add it in some rules in the semgrep-rules repo ? 

I can contribute on some to launch the effort

**Comment by clintgibler** [comment]
Hey @SPoint42 👋  Thanks for reaching out, much appreciated! Yes, we have been chatting with several of the people involved with OWASP ASVS and are keen to help support people in using Semgrep to determine how their repos measure up to ASVS best practices.

We've done some internal mapping of Semgrep <=> CWE <=> ASVS control, as both Semgrep rules and ASVS controls have a CWE listed.

Just to clarify, were you thinking about contributing some new rules to `semgrep-rules`, or what were you thinking about? Happy to share some ideas if that'd be helpful, but would be curious to hear what you have in mind :)

Would much appreciate your help!

**Comment by SPoint42** [comment]
I mean something like that on each rules: 

```yaml
rules:
 ............
    metadata:
      owasp: 'A1: Injection'
      asvs: 'ASVS-4.0.2:5.3.3'
      cwe: >-
        CWE-95: Improper Neutralization of Directives in Dynamically Evaluated
        Code ('Eval Injection')
```
