### ISSUE TITLE
String Regular Expressions Not Matching in Go Imports

### ISSUE THREAD

**Issue by bflad** [semgrep/semgrep#1927]
**Describe the bug**

(Continuation of https://github.com/returntocorp/semgrep/issues/1897#issuecomment-716980074)

When attempting to use the `"=~/REGEX/"` syntax within the `import` statements of a Go source file, no matches are returned as expected.

**To Reproduce**

https://semgrep.dev/s/gpKx/

Source:

```go
package main

import (
  "fmt"

  "github.com/aws/aws-sdk-go/service/accessanalyzer"
  "github.com/aws/aws-sdk-go/service/acm"
)

func main() {}
```

Attempted patterns:

```
import ("=~/github.com/aws/aws-sdk-go/service/.*/") # no matches
```

```
import ("=~/"github.com/aws/aws-sdk-go/service/.*"/") # syntax error
```

```
import ("=~/\"github.com/aws/aws-sdk-go/service/.*\"/") # no matches
```

```
import ("=~/.*/") # no matches
```

```
import "=~/.*/" # no matches
```

**Expected behavior**

Match on line 3.

**What is the priority of the bug to you?**

P2 -- there is an available workaround using `metavariable-regex`:

```yaml
    patterns:
      - pattern: |
          import ("$X")
      - metavariable-regex:
          metavariable: '$X'
          regex: '^"github.com/aws/aws-sdk-go/service/[^/]+"$'
```
