### ISSUE TITLE
Feature - Add the ability to specify a maximum or expected number of violation before triggering an `ERROR`

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#1982]
**Describe the solution you'd like**

For example, if the rule is violated 10 times it's a `WARNING`, but the 11 time it's `ERROR` . The idea is to progressively reduce the usage of a rule, ratcheting down the number progressively, and preventing new infractions. 

For example, we want to deprecate the use of a library in our code without having to do a full rewrite.

On top of that, it would be nice if the target (expected) value would also trigger an `ERROR` if the violation count is lower than the target value to ensure as we remove the offending code we update the target value accordingly.

I am imagining those two options to be 

For a random rule I copied of the docs (I do not endorse using md5 or sha1):

```
rules:
  - id: insecure-crypto-usage
    pattern-either:
      - pattern: hashlib.md5(...)
      - pattern: hashlib.sha1(...)
    message: "insecure cryptography hashing function"
    languages: [python]
    expected-maximum: 1
    severity: ERROR
```

```
rules:
  - id: insecure-crypto-usage
    pattern-either:
      - pattern: hashlib.md5(...)
      - pattern: hashlib.sha1(...)
    message: "insecure cryptography hashing function"
    languages: [python]
    expected-violations=2
    severity: ERROR
```

**Describe alternatives you've considered**

I ended up writing my own terrible linter, I could invoke `semgrep` from it, but at this point a plain regex is good enough right now. 
https://gist.github.com/j-martin/1d32157d9f27afb48840397c3745de54

**Additional context**
Discussion: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1604689682050900

I have been told it should be easy for me to implement. At this point, I am curious about what should be keywords names or what would be the preferred syntax to define those.
