### ISSUE TITLE
spacegrep does not match equivalent metavariables

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#2154]
**Describe the bug**
spacegrep / generic pattern matching does not match equivalent metavariables.

For example, this rule:

```yaml
rules:
- id: invalid-copy-from-reference
  patterns:
  - pattern-inside: |
      FROM ... as $REF
      ...
      ...
  - pattern: COPY --from=$REF
  languages: [generic]
  ...
```

does not match:

```dockerfile
FROM debian:jesse as build
RUN stuff
FROM debian:jesse
# ruleid: invalid-copy-from-reference
COPY --from=build some stuff ./
```

**To Reproduce**
https://semgrep.dev/s/Rr0E/?version=develop

**Expected behavior**
Expect to match because `as build` and `--from=build` are the same.
