### ISSUE TITLE
pattern-regex and pattern not working together

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2295]
**Describe the bug**
Trying to use both `pattern-regex` and `pattern` in a single rule and they do not seem to be compatible. I am hoping this is just user error, but I have tried a number of combinations and the matches are not what I would expect.

**To Reproduce**
https://semgrep.dev/s/Rok8/

My goal is to be able to distinguish these two lines:
```
return list.concat(paramValues.map(value => { return ({type: key, text: value}); } ));
return list.concat(paramValues.map(value => ({type: key, text: value})));
```
Semantically they are equivalent so a pattern of `$VAR => { return $EXPR; }` matches both. But I want to recognize just the first form -- with the explicit `return` -- so I can then use autofix to convert it to the second form.

Complete rule:
```
- id: concise-expression
  patterns:
    - pattern-either: 
      - pattern: $VAR => { return $EXPR; }
    - pattern-regex: 'return'
    - metavariable-regex:
        metavariable: '$EXPR'
        regex: '\{[^}]*\}'
  message: use simple expression instead of block
  fix: $VAR => ($EXPR)
```

Note that the `metavariable-regex` clause can be ignored for the purposes of this issue.

**Expected behavior**
Semgrep will match on this line...
```
return list.concat(paramValues.map(value => { return ({type: key, text: value}); } ));
```
but NOT match on this line:
```
return list.concat(paramValues.map(value => ({type: key, text: value})));
```
Also, I then want `autofix` to be able to change the first line to the second line.

**Screenshots**
NA

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
P2 regular

**Environment**
semgrep 0.35.0
