### ISSUE TITLE
Live editor missing documentation for keys required for local run

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2302]
From: https://notes.eatonphil.com/static-analysis-with-semgrep.html

> Copy this into config.yml. Let's modify the pattern to warn on all print calls, not just print calls with a single string argument:

```
rules:
- id: fail-on-print
  pattern: |
    print(...)
  message: |
    Semgrep found a match
  severity: WARNING
```
> The editor doesn't mention it (nor do any docs I can find) but we also need to include two keys in the individual rule object: mode and languages.

> Semgrep fails really weirdly if you set mode to anything other than search, but it won't warn you that what you set is garbage. The languages setting is similarly fickle and doesn't give you much feedback if you set it incorrectly.

Priority: P2

Suggestion: We should add documentation of the converted syntax that the live editor is magically inserting, or reconsider that "magic" -- possibly by always showing the `language:` key in the YAML to the user and just editing the yaml if the user switches the language dropdown.
