### ISSUE TITLE
Go Pattern Matching With ([]interface{}) Type Assertion

### ISSUE THREAD

**Issue by bflad** [semgrep/semgrep#2376]
**Describe the bug**

[Interface types in Go](https://golang.org/ref/spec#Interface_types) can be type asserted to any valid type at compile time (though they may panic at runtime). An example use case for this is an abstract data mapping function that returns an interface type whose result is later parsed into primitive Go types. It is unclear in this case whether there is a possible pattern to match this code scenario or if there is a potential gap in Go syntax handling.

**To Reproduce**

Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/s/qx68/

Code:

```go
package main

func main() {
    var v interface{}
    _ = v.([]interface{})
}
```

Configuration:

```yaml
rules:
- id: go-interface-type-assertion
  pattern: |
    $VALUE.([]interface{})
  message: |
    Match Go interface type assertion
  severity: WARNING
```

Result:

```
Pattern could not be parsed as a Golang semgrep pattern
```

Also errors if changing the pattern to `v.([]interface{})`.

**Expected behavior**

Match on `_ = v.([]interface{})` line.

**What is the priority of the bug to you?**

P2

**Environment**

Discovered locally on 0.36.0, verified on semgrep.dev.
