### ISSUE TITLE
pattern-not-regex does not properly filter out matches

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#2465]
**Describe the bug**
`pattern-not-regex` does not correctly filter out matches that I expect it would.

**To Reproduce**
https://semgrep.dev/s/clintgibler:pattern-not-regex-bug.

**Expected behavior**
I would expect this rule to match the first line, but **not** the latter two. However, all three lines are matched.

```yaml
    patterns:
      - pattern-regex: "Foo"
      - pattern-not-regex: "Foo-"
      - pattern-not-regex: "-Foo"
```

```
Foo==1.1.1

Foo-Bar==3.0.8
Bar-Foo==3.0.8
```

**What is the priority of the bug to you?**
P1
