### ISSUE TITLE
metavariable-regex not working with pattern-inside?

### ISSUE THREAD

**Issue by xmo-odoo** [semgrep/semgrep#2548]
When using `pattern-inside` and `metavariable-regex` which tries to filter one of the `pattern-inside`'s metavariables, the match seems to never happen https://semgrep.dev/s/8ykq

```yaml
  patterns:
    - pattern-either: 
      - pattern: |
          return None
      - pattern: |
          return
    - pattern-inside: |
        class $C:
            def $METHOD(...):
              ...
    - metavariable-regex:
        metavariable: "$METHOD"
        regex: "^[^_].*"
```
The intent is to match all methods which are "public" (not starting with `_`) and use a bare `return` or a `return None`. Commenting the `metavariable-regex`, all methods with the return are matched (including those we want to exclude).

Duplicating the `pattern-inside` so the metavariables are extracted from a `pattern`, things work as expected: https://semgrep.dev/s/gLGx
```yaml
  patterns:
    - pattern-inside: |
        class $C:
            ...
    - pattern-either:
      - pattern: |
              def $METHOD(...):
                ...
                return
      - pattern: |
              def $METHOD(...):
                ...
                return None
    - metavariable-regex:
        metavariable: "$METHOD"
        regex: "^[^_].*"
```

The problem with the workaround is that I also want to match functions which don't return (and thus have an implicit `return None`), but I don't see how I could match a `pattern-not: return $X` inside a method with the proper name.
