### ISSUE TITLE
Document sarif report in the github action

### ISSUE THREAD

**Issue by javixeneize** [semgrep/semgrep#2617]
Hi

Is Sarif supported in the github action? I can see the CLI supports that but i dont know if the action does. If so, it might be added to the documentation for clarity :)

https://github.com/marketplace/actions/semgrep-action

Thanks

**Comment by brendongo** [comment]
Hi @javixeneize we do have a Sarif report function on semgrep-action. You're right it does look like we don't have it well documented. Modifying the issue to reflect need to add it to documentation.

For now you can turn it on by setting generateSarif in the config file to 1 if using githubactions. See last line of following config:
```
name: Semgrep
on:
  pull_request: {}

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          # Generate a SARIF file for GitHub's code scanning feature. See the next step.
          generateSarif: "1"
```

or if setting the env variable INPUT_GENERATESARIF to 1

Note that this feature is experimental so is not as hardened as other features
