### ISSUE TITLE
Multi steps rules, or rules analyzing multiples files at the same time

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2653]
It would be great if a semgrep rule could reference multiple files at the same time.
For example, we could like to first detect classes which are using a dangerous function,
and then write another rule to search for uses of those classes in other files.

reference discussion:  https://r2c-community.slack.com/archives/C018NJRRCJ0/p1614333745011800

We either need:
 - a way to express mutliple files in a rule
 - a way to express multiple steps/stages, where each step could use information gathered by the previous step

 I think option 2 would be easier.

**Comment by aryx** [comment]
cc @clintgibler @minusworld @inkz @mschwager

**Comment by aryx** [comment]
```
rules:
 - step1:
    -  pattern-inside: class $FOO { ... }
    - pattern: eval(...)
  - step2: using step1.$FOO
    - pattern: new $FOO(...)
    - message: dangerous use of $FOO; this class internally use eval()
```
