### ISSUE TITLE
Expression equivalence under variable definition substitution

### ISSUE THREAD

**Issue by dkasak** [semgrep/semgrep#2783]
Say I want to check whether a project is checking for string equality under lowercase. The following rule seems like it should do the job:

```
pattern-either:
  - pattern: $X.lower() == $Y.lower()
  - pattern: $X.lower() != $Y.lower()
  - pattern: $X.upper() == $Y.upper()
  - pattern: $X.upper() != $Y.upper()
```

However, this will only match those exact expressions. Even a simple semantically equivalent case such as the following would remain undetected:

```python
a = "FOO"
a = a.lower()

if a != "BAR".lower():
    pass
```

Ideally, semgrep should be able to match the above snippet with the previously stated rules by concluding that `a` is equivalent to the expression `a.lower()` since there were no re-assignments or mutations of `a` in between the assignment and the comparison.

Real world cases are likely to get more complicated, with at least some statements in between, which might complicate matters due to mutability concerns in some languages. It still seems like it could work in a significant number of cases, though (for instance, with `lower()` in Python as above, since Python strings are immutable).

Is implementing something like this possible with the current state of semgrep's engine? Or am I perhaps missing an easy workaround? 

## Alternatives

Of course, it would be possible to "unroll" this manually, by wrapping everything in a large `pattern-either` clause and then listing variants of the above patterns with and without an appropriate `pattern-inside` that would detect this simple case, but this gets very cumbersome quickly.
