### ISSUE TITLE
Semgrep won't scan files that don't end with the right extension

### ISSUE THREAD

**Issue by kiwiz** [semgrep/semgrep#2837]
**Describe the bug**
Semgrep won't scan a `yaml` file if the file doesn't end in a `.yml` or `.yaml` file when targetting a directory. I tried specifying an `paths.include` entry, but that doesn't work.

**To Reproduce**
Create a rule that targets `yaml` and scan a directory with yaml files:
```yaml
rules:
- id: some-id
  languages:
  - yaml
  message: Message
  metadata:
    ticket: SREX-5
  patterns:
    - pattern-inside: "$X"
  severity: ERROR
  paths:
    include:
      - "OWNERS"
```

```bash
$ semgrep -f rules.yaml some_dir
```

**Expected behavior**
Semgrep should scan the yaml files and report any findings

**Screenshots**
N/A

**What is the priority of the bug to you?**
P2

**Environment**
`semgrep v0.44`
