### ISSUE TITLE
Report parsing error location for errors in yaml files in the playground

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2925]
When there is a mistake in a yaml file in the playground, it's very hard to know what is wrong.

**Comment by aryx** [comment]
for example what is wrong with this rule:
```
rules:
  - id: my_pattern_id
    languages:
      - yaml
    message: |
      Semgrep found a match
    patterns:
      - pattern-either:
          - pattern-inside: |
              permissions:
                ...
      - pattern: - "Jobs/Read"
    severity: WARNING
```
if you put that in the playground it just says invalid yaml pattern, but no error location (the error is the '-' in the pattern: line)
