### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by YakDriver** [semgrep/semgrep#2985]
**Is your feature request related to a problem? Please describe.**
I want to use semgrep to find and fix problems in Markdown documentation.

We use semgrep extensively in the [Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws) to enforce code conventions and style in Go code. It would be awesome to use the same tool, which is already part of our CI, to help bring consistency to our documentation. In my attempts to use semgrep on our Markdown, I get a lot of `Semgrep exited with an unspecified error` messages.

https://semgrep.dev/s/70JQ

**Describe the solution you'd like**

```yaml
rules:
- id: docs-prefer-required-or-optional-label
  languages: [markdown]
  patterns:
    - pattern-either: 
      - pattern: |
          \* `...` - ...
    - pattern-inside: |
        \#\# Argument Reference
        ...
        \#\# Attributes Reference
    - pattern-not: |
        \* `...` - (Optional...)
    - pattern-not: |
        \* `...` - (Required...)
  message: Use (Optional) or (Required) with all arguments
  severity: WARNING
```

**Describe alternatives you've considered**
grep
Custom Go static analysis

**Additional context**

We'd love to enforce rules on these types of files, for example:
* https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/cloudfront_origin_request_policy.html.markdown
* https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/eks_cluster.html.markdown
* https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/lb_ssl_negotiation_policy.html.markdown

These files go on to become, for example:
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_request_policy
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_ssl_negotiation_policy
