### ISSUE TITLE
semgrep autofix breaks format strings

### ISSUE THREAD

**Issue by pokle** [semgrep/semgrep#2995]
**Describe the bug**
autofix opens up format string quotes, but doesn't put them back together

**To Reproduce**
( I'm not linking to  https://semgrep.dev because that exposes another bug in the playground! If you want to see for yourself, try https://semgrep.dev/s/v0vY/ - and switch to the advanced tab. You'll find that it has broken the indentation of `fix`, making it inoperable )

pr.yml:
```
rules:
- id: print-is-bad
  pattern: print($E)
  message: Please use our logging framework instead
  fix: log($E)
  languages:
  - python3
  severity: ERROR
```

pr.py:
```
print(f"abc")
```

run: 
```
 $ semgrep -f pr.yml pr.py
running 1 rules...
pr.py
severity:error rule:print-is-bad: Please use our logging framework instead
1:print(f"abc")
autofix: log(abc)
ran 1 rules on 1 files: 1 findings
```

Notice that the autofix line is missing the quotes around the string.

**Expected behavior**

The autofix line should look like:

```
autofix: log(f"abc")
```

**Screenshots**

**What is the priority of the bug to you?**
P1 (important to fix or quite annoying)

**Environment**
Running off a pip installed semgrep from today
```
$ semgrep --version
0.48.0
```
