### ISSUE TITLE
semgrep does not detect/refuse rules with multiple metavars in metavariable-regexp

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3084]
See https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/blob/main/rules/eslint.yml#L751

Running semgrep-core -config with just this rule leads to an exn:
```
[pad@yrax semgrep (develop)]$ yy -dump_rule tests/OTHER/rules/gitlab_slow1.yaml 
+ /home/pad/semgrep/_build/default/src/cli/Main.exe -dump_rule tests/OTHER/rules/gitlab_slow1.yaml
[0.112  Info       Main.Dune__exe__Main ] loaded log_config.json
[0.113  Info       Main.Dune__exe__Main ] Executed as: /home/pad/semgrep/_build/default/src/cli/Main.exe -dump_rule tests/OTHER/rules/gitlab_slow1.yaml
[0.113  Info       Main.Dune__exe__Main ] Version: semgrep-core version: v0.50.1-11-g378d4525, pfff: 0.42
[[("metavariable", (Tag2 ("$V"))); ("regex", (Tag2 ("[0-9]+")))]; ("metavariable", Tag2 ("$ARG")); ("regex", Tag2 ("[^0-9]+"))]
Uncaught exception:
  
  Parse_mini_rule.InvalidYamlException("wrong parse_extra fields")

```

**Comment by aryx** [comment]
@mschwager was metavariable-regexp designed to allow multiple metavariables?

**Comment by aryx** [comment]
I don't think we have a single semgrep-rules/ using multiple metavariables there.

**Comment by mschwager** [comment]
Nope! This was a bug on their end. You can't have multiple metavariables in a single `metavariable-regex`, but you can have multiple `metavariable-regex`s.

**Comment by aryx** [comment]
but we don't detect the error when parsing the rule?

**Comment by aryx** [comment]
Ok so semgrep-core is right ... the issue should be "Semgrep does not detect metavariable-regexp using multiple metavariables?"

**Comment by mschwager** [comment]
Yeah, this will take some deeper investigation. Ideally we would throw some kind of validation error, but it's not so easy to detect. IIRC repeating the same keys is valid YAML - the former are simply overwritten by the latter. It may be difficult to detect this because our YAML library returns the YAML object with the former, repeated keys already overwritten, so we don't have a great opportunity to detect that behavior.

**Comment by minusworld** [comment]
I think the issue is that `jsonschema` incorrectly thinks the `metavariable-regex` keys are correct because they all have valid names according to our rule schema. This is either a bug in `jsonschema` or there's a feature we're missing.

I tested this by writing a bunch of unit tests and found that this rule reports an invalid schema error:

```
        rules:
        - id: boto3-internal-network
          patterns:
          - pattern-inside: $MODULE.client(host=$HOST, port=$PORT)
          - metavariable-comparison:
              metavariable: $PORT
              comparison: $PORT > 9999
              metavariable: $MODULE
              regex: '(server|servers)'
          message: "Boto3 connection to internal network"
          languages: [python]
          severity: ERROR
```

but this rule does **not**:

```
        rules:
        - id: boto3-internal-network
          patterns:
          - pattern-inside: $MODULE.client(host=$HOST)
          - metavariable-regex:
              metavariable: $HOST
              regex: '192.168\.\d{1,3}\.\d{1,3}'
              metavariable: $MODULE
              regex: (boto|boto3)
          message: "Boto3 connection to internal network"
          languages: [python]
          severity: ERROR
```
