### ISSUE TITLE
JavaScript unhandled `require` pattern

### ISSUE THREAD

**Issue by Ayrx** [semgrep/semgrep#3115]
The following `require` structure seems to be unhandled by semgrep currently:

```yaml
rules:
- id: child-process
  message: |
    Test
  severity: WARNING
  languages:
  - javascript
  - typescript
  pattern-either:
    - patterns:
      - pattern: child_process.exec($CMD, ...)
      - pattern-not: child_process.exec("...", ...)
```

```js
const exec = require('child_process').exec;
exec(cmd);
```
https://semgrep.dev/s/X8eB/

**What is the priority of the bug to you?**

P2: regular bug that should get fixed

**Comment by Ayrx** [comment]
This pattern also fails:

```js
var x = require('child_process');
x.exec(cmd);
```

While the following pattern matches:
```js
var child_process = require('child_process');
child_process.exec(cmd);
```

**Comment by clintgibler** [comment]
I'm getting a "Pattern could not be parsed as a Typescript semgrep pattern" error from:

```typescript
import fs = require('fs')
```

This may be a separate parsing bug, but putting it here because it's related.

**Comment by aryx** [comment]
cc @emjin

**Comment by skylarmb** [comment]
+1 on this. It seems that without advanced regex patterns, semgrep cannot detect many semantically equivalent import patterns in Javascript and Typescript, even if they are a bit unconventional.

```yml
rules:
  - id: banned-import
    pattern-either:
      - pattern: import 'module-name'
    message: Banned import detected
    languages:
      - typescript
      - javascript
    severity: ERROR
```

```typescript
// ruleid: banned-import PASS
import 'module-name'; 
// ruleid: banned-import PASS
import m from 'module-name';
// ruleid: banned-import PASS
import { m } from 'module-name';
// ruleid: banned-import PASS
const m = require('module-name'); 
// ruleid: banned-import PASS
const { m } = require('module-name'); 
// ruleid: banned-import FAIL
const m = require('module-name' as any); 
// ruleid: banned-import FAIL
let m = (require as any)('module-name')
// ruleid: banned-import FAIL
const m = require('module-name/lib');
// ruleid: banned-import FAIL
const m = require(['module-name'][0])
// ruleid: banned-import FAIL
const _require = require // this is basically what webpack does with __webpack_require__
const m = _require('module-name')
```
