### ISSUE TITLE
Buildkite documentation

### ISSUE THREAD

**Issue by daghan** [semgrep/semgrep#3126]
in https://semgrep.dev/docs/sample-ci-configs/#buildkite, it seems plugin shouldn't be indented, and there shouldn't be a quote in $SEMGREP_DEPLOYMENT_ID".

so instead of this:
```
- label: ":semgrep: Semgrep"
  command: semgrep-agent --publish-deployment $SEMGREP_DEPLOYMENT_ID" --publish-token $SEMGREP_APP_TOKEN
    plugins:
      - docker#v3.7.0:
```
it should be this:
```
- label: ":semgrep: Semgrep"
  command: semgrep-agent --publish-deployment $SEMGREP_DEPLOYMENT_ID --publish-token $SEMGREP_APP_TOKEN
  plugins:
      - docker#v3.7.0:
```
