### ISSUE TITLE
Ensure invalid configurations are reported

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3142]
**Describe the bug**
Semgrep does not report invalid `metavariable-regex` clauses as an invalid config. For example:

```
metavariable-regex:
  metavariable: $X
  regex: ...
  metavariable: $Y
  regex: ...
```

is not reported as invalid when run with `--validate`.

### We need to make sure all invalid config files are reported as invalid.

**To Reproduce**
Put this text in a file, `invalid.yaml`:

```
rules:
  - id: boto3-internal-network
    patterns:
      - pattern-inside: $MODULE.client(host=$HOST)
      - metavariable-regex:
         metavariable: $HOST
         regex: '192.168\.\d{1,3}\.\d{1,3}'
         metavariable: $MODULE
         regex: (boto|boto3)
    message: "Boto3 connection to internal network"
    languages: [python]
    severity: ERROR
```

Then try:

```
➜  rules git:(main) ✗ semgrep -f invalid.yaml --validate
Configuration is valid - found 1 valid configuration(s), 0 configuration error(s), and 1 rule(s).
```

**Expected behavior**
This should be reported as invalid.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
