### ISSUE TITLE
[Metachecker] detect wrong use of pattern-not

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3202]
Context https://r2c-community.slack.com/archives/C018NJRRCJ0/p1622060003061000

```
rules:
  - id: golang
    languages:
      - go
    message: Only functions without return statement
    patterns:
      - pattern-inside: |
          func $METHOD(...) {
            ...
          }
      - pattern-not: return ...
    severity: WARNING
```
"I wanted to match only functions that do not contain a return statement. Is this the way to go?
I expected it to not match this (but it did):"

Actual solution: https://semgrep.dev/s/B4w7
