### ISSUE TITLE
[Java] import $PATH; does not capture the whole path including the trailing .*

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#3243]
**Describe the bug**

I am trying to prevent our engineers to use wildcard import. With grep I can do `.*\.\*` to escape the `.*`, but semgrep does not seem to be handling those. I might be doing something wrong (e.g. YAML escaping on top of regex escaping), but permutations like `.*\\.\\*` or `.*\\\.\\\*` did not help. I could not find anything in the docs regarding this behavior.

```yml
rules:
  - id: java-prevent-wildcard-imports
    languages:
      - java
    message: Match found
    patterns:
      - pattern: import $PATH;
      - metavariable-regex:
          metavariable: $PATH
          regex: .*\.\*
    severity: ERROR
```

`ripgrep` for example works as expected:

```
$ rg 'import .*\.\*;'
<redacted>.java
13:import javax.ws.rs.*;

<redacted>.java
27:import java.util.*;
```

**To Reproduce**
https://semgrep.dev/s/j-martin:java-prevent-wildcard-imports

**Expected behavior**
Escaped regex characters are handled properly.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed
