### ISSUE TITLE
Undetected typos / errors in metavariable names

### ISSUE THREAD

**Issue by xmo-odoo** [semgrep/semgrep#3305]
When using metavariable-regex with an incorrect metavariable, no error is triggered:

```yml
    patterns:
      - pattern: |
          var $UTIL = require("something_or_other");
          ...
          $UTIL.$FUNC(...)
      - metavariable-regex:
          metavariable: $METHOD
          regex: (a|b|c)
```
Note the `metavariable` doesn't match anything defined in the `pattern`. I did not.

Now I do not know how "missing" metavariables are modelled internally by semgrep, or how `metavariable-regex` is modelled, so it's possible that there's a way to check that the metavariable is *not* matched and thus the feature makes sense, but it seems a bit odd.
