### ISSUE TITLE
nosemgrep ignored for bandit.B110 if python exception is specified

### ISSUE THREAD

**Issue by jdunnpenguin** [semgrep/semgrep#3355]
I have only tested this within a Gitlab  CI/CD pipeline so please disregard if this is already resolved upstream. In Python the following does not properly ignore a Bandit B110 finding:
```
    try:
         os.unlink('{}.squashfs'.format(pos))
    except FileNotFoundError: # nosemgrep: bandit.B110 # best effort unlink, may already be deleted
         pass
```
However, without the exception specified it works as expected so this does work:
```
    try:
         os.unlink('{}.squashfs'.format(pos))
    except: # nosemgrep: bandit.B110 # best effort unlink, may already be deleted
         pass
```

**Comment by minusworld** [comment]
Hey @jdunnpenguin, thanks for filing this issue!

I suspect there are a few things contributing to this.

`nosemgrep` comments currently have to be at the top line of a finding. Since the [rule definition for B110](https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/blob/main/rules/bandit.yml#L128) looks like this,

```
- id: bandit.B110
  patterns:
    - pattern: |
        try:
          ...
        except $X:
          pass
  message: | 
    Try, Except, Pass
  metadata:
    cwe: 'CWE-703: Improper Check or Handling of Exceptional Conditions'
  severity: INFO
  languages: [python]
```

that means the `nosemgrep` comment needs to be on the same line as the `try:`.

Further, looking at the rule definition, I think the reason it _looks like_ unnamed excepts are ignored is because they are not matched in the first place. The rule as written won't catch unnamed excepts and needs an extra clause like:

```
- pattern: |
  try:
    ...
  except:
    pass
```

If you make an MR to Gitlab they should be able to fix that! Alternatively, @aryx, do you think we should make the original rule as written also catch the unnamed except case?
