### ISSUE TITLE
[Terraform] semgrep generic mode unable to parse brackets properly

### ISSUE THREAD

**Issue by MilindPurswani** [semgrep/semgrep#3380]
**Describe the bug**
While playing with semgrep, I learned that it doesn't parse brackets properly.  I am currently trying to develop a terraform rule to detect s3 buckets with no logging enabled and here is my rule file:

```yaml
rules:
- id: s3-no-log
  patterns:
    - pattern: |
        logging{...}
    - pattern-not-inside: |
        resource "aws_s3_bucket" "..." {...}
  message: S3 bucket with no logging detected.
  severity: ERROR

```

For some reason, it is not detecting this behaviour: 

```terraform
resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
  # ruleid: s3-public-rw-bucket
  acl    = "public-read-write"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}
```

**Expected behavior**
I am assuming it has to do something with how semgrep handles curly brackets but I may be wrong here. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11857683/122276442-c9331200-ceb2-11eb-89b4-318555f46d6b.png)

**What is the priority of the bug to you?**

- P0
I am currently planning to adopt semgrep as unified pattern matcher for all my tools. If this works out, I won't have to rely on different tools and would be able to use this for all IaC scanning.
