### ISSUE TITLE
[Autofix] sometimes drops closing bracket in python slices

### ISSUE THREAD

**Issue by JDegesysHelm** [semgrep/semgrep#3387]
**Describe the bug**
The closing bracket is sometimes dropped in the autofix.

**To Reproduce**
https://semgrep.dev/s/juliusdegesys:closingbracketbugrepro
```yaml
rules:
- id: test
  message: Bug Repro
  severity: INFO
  pattern: f($X)
  fix: f($X, 1)
```
Input file:
```python
# These are ok:
f(x[0])
f([0, 1])
f(x(0, 1))
# Closing square bracket of $X gets dropped in autofix below:
f(x[0, 1])
f(x[0, 1, 2])
f(x[0, 1:2])
f(x['a', 'b'])
```
Output:
```
severity:info rule:test: Bug Repro
autofix: f(x[0], 1)
2:f(x[0])
--------------------------------------------------------------------------------
autofix: f([0, 1], 1)
3:f([0, 1])
--------------------------------------------------------------------------------
autofix: f(x(0, 1), 1)
4:f(x(0, 1))
--------------------------------------------------------------------------------
autofix: f(x[0, 1, 1)
6:f(x[0, 1])
--------------------------------------------------------------------------------
autofix: f(x[0, 1, 2, 1)
7:f(x[0, 1, 2])
--------------------------------------------------------------------------------
autofix: f(x[0, 1:2, 1)
8:f(x[0, 1:2])
--------------------------------------------------------------------------------
autofix: f(x['a', 'b', 1)
9:f(x['a', 'b'])
ran 1 rules on 1 files: 7 findings
```

**Expected behavior**
Closing bracket not to be dropped in autofix.
```
severity:info rule:test: Bug Repro
autofix: f(x[0], 1)
2:f(x[0])
--------------------------------------------------------------------------------
autofix: f([0, 1], 1)
3:f([0, 1])
--------------------------------------------------------------------------------
autofix: f(x(0, 1), 1)
4:f(x(0, 1))
--------------------------------------------------------------------------------
autofix: f(x[0, 1], 1)
6:f(x[0, 1])
--------------------------------------------------------------------------------
autofix: f(x[0, 1, 2], 1)
7:f(x[0, 1, 2])
--------------------------------------------------------------------------------
autofix: f(x[0, 1:2], 1)
8:f(x[0, 1:2])
--------------------------------------------------------------------------------
autofix: f(x['a', 'b'], 1)
9:f(x['a', 'b'])
ran 1 rules on 1 files: 7 findings
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
```
pip install semgrep
$ semgrep --version
0.56.0
```

**Comment by spookylukey** [comment]
It also sometimes duplicates a closing square bracket. That might be a different bug, but it seems similar enough that it is worth documenting here.

Rules:
```yaml
rules:
  - id: use-list-not-List
    languages:
      - python
    message: Use list instead of typing.List
    pattern: typing.List[$T]
    fix: list[$T]
    severity: WARNING

  - id: use-dict-not-Dict
    languages:
      - python
    message: Use dict instead of typing.Dict
    pattern: typing.Dict[$T, $U]
    fix: dict[$T, $U]
    severity: WARNING
```

Code:
```python
from typing import Dict, List

# This is fixed correctly:
List[int]

# Additional closing bracket added:
Dict[str, int]
```

In the second case, it seems that the match is finding `Dict[str, int` rather than `Dict[str, int]`.

See:
https://semgrep.dev/s/spookylukey:closing-bracket-autofix-bug-list
https://semgrep.dev/s/spookylukey:closing-bracket-autofix-bug-dict
