### ISSUE TITLE
Ruby String Interpolation Pattern Parsing Error

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3390]
**Describe the bug**
Semgrep exits with `Rule id: my_pattern_id contains a pattern that could not be parsed as a pattern for language Ruby: Rails.logger.info("Creating update with params` error when parsing the following pattern:

```
 rules:
 - id: my_pattern_id
   pattern: Rails.logger.info("Creating update with params #{params}")
   message: Semgrep found a match
   severity: WARNING
   languages: [ruby]
```

With test-file 
```
Rails.logger.info("Creating update with params #{params}")
``` 

**To Reproduce**
Copy and paste the above lines of code into separate files. 

Run the following command in the command-line:
`semgrep -f ruby_test.yaml ruby_test.rb`

**Expected behavior**
A match to occur on the first line of the file.

**Extra**
This actually works in semgrep-core, so I suspect there may be something happening with the python wrapper.
The reason I didn't use semgrep.dev is because it keeps cutting off the rest of the pattern.
