### ISSUE TITLE
[Python] constant propagation inside/outside context created by `with` statement

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#3402]
https://semgrep.dev/s/RP8O/

```python
def test1():
    hardcoded = "yo man!"
    with something() as foobar:
        print(hardcoded)
```

```yaml
  patterns:
    - pattern: |
        print(...)
    - pattern-not: |
        print("...")
```

constant propagation does not work for variables outside `with` context
