### ISSUE TITLE
[JavaScript] matching a field with a function in a JS object

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#3456]
matching a field in a JS object does not work if value is a function
works: https://semgrep.dev/s/lxWB/
```
{foo: ...}
```
```javascript
{
  foo: 1,
  bar: 2
}
```

does not work: https://semgrep.dev/s/YX4D/
```
{foo: ...}
```

```javascript
{
  foo: function(one) { console.log(one) },
  bar: 2
}
```

It works if you give a name to the function https://semgrep.dev/s/qqZR

Also, it is not possible to match a pattern inside a function in a specific field

example: https://semgrep.dev/s/65kW/

```
  patterns:
    - pattern: |
        return $X
    - pattern-inside: |
        {renderer: ...}
```

```javascript
{
  notRenderer: function f1(value, meta, record) { return value; },
  renderer: function f2(value, meta, record) { return value; }
  }
```

will match both lines

**Comment by IagoAbal** [comment]
Apparently, when inside a record, `function(one) { console.log(one) }` is parsed as a function definition (or "method") whereas `function f(one) { console.log(one) }` is parsed as a lambda-expression. It may be a problem with the front-end, what do you think @mjambon ?

**Comment by IagoAbal** [comment]
Note that `{renderer: ...}` is equivalent to `{..., renderer: ..., ...}` and this matches the entire record (in fact we should prefer the explicit way). You could use `metavariable-pattern` instead https://semgrep.dev/s/053w, i.e.:
```
    patterns:
      - pattern-inside: |
          {..., renderer: $F, ...}
      - pattern: $F
      - metavariable-pattern:
          metavariable: $F
          pattern: return ...
```

Maybe we should have a way to select a single field in a record but that may require some new syntax, cc @aryx.
