### ISSUE TITLE
Regression due to `pattern: $X` optimization

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3476]
**Describe the bug**

We can't (in general) optimize a `pattern: $X` that follows a sequence of `pattern-inside`s by simply extracting the value of `$X` in the `pattern-inside` matches. As long as there is a `...`, `pattern: $X` could be match inside that region of code, and the result would not be equivalent.

**To Reproduce**

The link to the Playground would be https://semgrep.dev/s/65Bq but the example gets rewritten and no longer works...

Config file:
```yaml
rules:
- id: test
  patterns:
    - pattern-inside: |
        f($X, ...)
        ...
    - pattern: |
        $X
  message: Semgrep found a match
  languages: [python]
  severity: WARNING
```

Target file:
```python
#ruleid:test
f(a, b, c)
g(c)
h(b)
#ruleid:test
i(a) # NOT MATCHING
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by emjin** [comment]
Unrelated to this particular issue (presumably): I can't get your semgrep link to work for me. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/5942585/124615012-d6547880-de42-11eb-83ef-0f75f56c2c68.png)

**Comment by IagoAbal** [comment]
> Unrelated to this particular issue (presumably): I can't get your semgrep link to work for me. Am I doing something wrong?

As far as I can tell that is a bug in the Playground (or some weird bug in Semgrep). If you create a new Python example, go to advance mode, and copy-paste the config and target that I provided, it works. Now you try to share it, and use the link, and it does not work anymore... (But sharing the link has the side-effect of rewriting the pattern so that's why I'm not sure if this is a Playground or a Semgrep bug.)

**Comment by IagoAbal** [comment]
Actually, if I pass to Semgrep CLI the rewritten pattern formula:
```yaml
  patterns:
    - pattern-either: 
      - pattern: |
          $X
    - pattern-inside: |
        f($X, ...)
        ...
```
Then it works and I get the results that I expected (the optimization doesn't kick in I guess due to the `pattern-either`). It must be a bug in the Playground, so I opened a separate issue returntocorp/semgrep-app#2907.
