### ISSUE TITLE
pattern-not-regex doesn't work when under metavariable-pattern

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#3503]
**Describe the bug**

In the following (simplified) structure

```yml
      - metavariable-pattern:
          metavariable: $VALUE
          patterns:
            - pattern-not-regex: ^[0-9]+$
```

It seems like the `pattern-not-regex` is ignored. `pattern-regex` works as expected however.

**To Reproduce**

https://semgrep.dev/s/WOLj

**Expected behavior**

`pattern-not-regex` should work

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
