### ISSUE TITLE
autofix mishandles embedded quotes in string replacements for Python

### ISSUE THREAD

**Issue by spookylukey** [semgrep/semgrep#3648]
Given a rule like this:
```yaml
rules:
- pattern: foo("$S")
  fix: bar("$S")
  languages: [python]
```

autofix will replace:
```python
foo('hello "friend"')
```

with
```python
bar("hello "friend"")
```

which is a syntax error.

**Expected behavior**
Should get a properly quoted string, either:
```python
bar('hello "friend"')
```

or
```python
bar("hello \"friend\"")
```

**What is the priority of the bug to you?**

- P1: important to fix or quite annoying

**Environment**
Latest Semgrep (0.59 at time of writing)

Example in playground: https://semgrep.dev/s/spookylukey:string-quoting-bug
