### ISSUE TITLE
YAML using pattern-either to match different variables and use of metavariable-pattern is not working

### ISSUE THREAD

**Issue by harold-stripe** [semgrep/semgrep#3683]
**Describe the bug**
https://semgrep.dev/s/RPEq/. Our YAML format supports 2 possibilities for setting some configuration . A value or a list. (in the next example self is OK, URLs are not)
```
default:
  providers:
    provider1:
      # this directive has a list of sources
      frame-src:
      # ok: csp-directive-sources
      - self
      # ruleid: csp-directive-sources
      - https://www.provider1.com/
      # ruleid: csp-directive-sources
      - https://api.provider1.com/
    provider2:
      # this directive is a single direct value
      # ruleid: csp-directive-sources
      frame-src: https://www.provider2.com/
    provider3:
      # this directive is a single direct value
      # ok: csp-directive-sources
      frame-src: self
```
So matching each elements of the lists is easy, I’m using
```
$DIRECTIVE: [...,$DIRECTIVE_SOURCE,...]
```
My rule will now match every single $DIRECTIVE_SOURCE
https://semgrep.dev/s/AwO2/

but if I’m trying to either match directive sources in a list or if it’s a direct value.
Trying to do
```
      - pattern-either:
          - pattern-inside: |
              $DIRECTIVE: [...,$DIRECTIVE_SOURCE,...]
          - pattern-inside: |
              $DIRECTIVE: $DIRECTIVE_SOURCE #I'm trying to match a directive value when it's not a list
```
doesn’t work (it just matches the second part of the either)

**To Reproduce**
https://semgrep.dev/s/DwEP/

**Expected behavior**
I expect to be able to have the metavariable `$DIRECTIVE_SOURCE` match any element in a list of the hash or the value if the hash doesn't contain an array.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev
