### ISSUE TITLE
Have `metavariable-comparison` work on variables, not just literals

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#3727]
**Is your feature request related to a problem? Please describe.**

Currently, metavariable-comparison only works on literals (`5`, `"cat"`).

Sometimes, however, it'd be useful to operate on variables, using whatever constant propagation is able to tell us about them.

Something like:

```yaml
rules:
- id: c-comparing-metavars
  patterns:
    - pattern: |
        int $X = $XVAL;
        int $Y = $YVAL;
    - metavariable-comparison:
      metavariable: $XVAL
      comparison: $XVAL < $YVAL  
  message: Trying to compare metavars
  languages: [c]
  severity: WARNING
```

```c
int main() {
    int x = 3;
    int y = 5;
    if (x < y) {
        print("less");
    }
}
```

**Describe the solution you'd like**

Ideally metavariable-comparison just "does the right thing," regardless of if the matched metavariable is a literal or variable.

This would allow broader, automatic matching of rules like this, which would currently not work if a non literal was used: [use_of_weak_rsa_key.yaml](https://github.com/returntocorp/semgrep-rules/blob/2b32e459b0e9baf8f41ab881d0bdf6cf9a72799f/go/lang/security/audit/crypto/use_of_weak_rsa_key.yaml
).

**Describe alternatives you've considered**
I suppose `pattern-where-python` could be used here, but that's been deprecated.

**Additional context**

There's been one or two customer asks for functionality like this, like being able to compare array bounds in C, or using `metavariable-` patterns to reason about the string values that constant propagation can tell us.

More discussion and context: https://returntocorp.slack.com/archives/CHG013EPJ/p1629233756164100?thread_ts=1629203004.157800&cid=CHG013EPJ
