### ISSUE TITLE
Inherit from other rules

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3728]
In many frameworks, the possible sources of taint are the same. It would make writing rules easier and leave less possibility for error if we could have some inheritable templates. For example, we could have:

```
rules:
- id: brakeman-template
  mode: taint
  pattern-sources:
    - pattern: param
    - pattern: cookies
    - pattern: request.env
```

```
rules:
- id: session-taint
   extends: brakeman-template (maybe this would be a url???)
   mode: taint
   pattern-sources:
      - pattern: <hypothetical additional pattern>
   pattern-sinks:
      - pattern: session(...)
```

And then we could have a semgrep check that anyone who uses `param` in their rule is poked about this template!
