### ISSUE TITLE
[CONVENIENCE] pattern syntax for non-literals

### ISSUE THREAD

**Issue by xmo-odoo** [semgrep/semgrep#3758]
A common theme of sensitive APIs is that an in-source literal is *usually* safe (mostly), but a computed value (especially with user-provided data) is not.

This means in my experience a common pattern is:

    - patterns:
        - pattern: $SOME.$THING(...)
        - pattern-not: $SOME.$THING('...')

Would be nice if there was a way to directly specify that the first `...` is non-literal.

**Comment by xmo-odoo** [comment]
![supervisor](https://user-images.githubusercontent.com/7571158/144803075-81353154-dd5b-4871-b078-03e899ce6f24.gif)

**Comment by xmo-odoo** [comment]
![dog](https://user-images.githubusercontent.com/7571158/150346083-77cfa6b8-0ecb-498b-ba28-1c5199cd8e14.png)

**Comment by xmo-odoo** [comment]
![animal 1](https://user-images.githubusercontent.com/7571158/152739422-7a1f7ca3-8d9b-44e9-a76b-88717b9dbb4b.png)

**Comment by xmo-odoo** [comment]
Addendum: this can be worked around using [`metavariable-pattern]`(https://semgrep.dev/docs/writing-rules/rule-syntax/#metavariable-pattern), but it's only worth it for very large source patterns as this is not exactly terse:
```yaml
patterns:
    - pattern: $SOME.$THING($V)
    - metavariable-pattern:
        metavariable: $V
        patterns:
            pattern-not: '"..."'
```
it also has the recurring trap that yaml will interpret `"..."` as a universal pattern `...`, so the string needs to be double quoted in order for the pattern to be the string literal pattern.
