### ISSUE TITLE
Relative `paths` are not handled properly

### ISSUE THREAD

**Issue by kiwiz** [semgrep/semgrep#3782]
**Describe the bug**
Prior to `0.58`, an `paths.include` path with a `./` would properly pick up the file. 

**To Reproduce**
```
rules:
- id: test-rule
  languages:
  - generic
  message: hi
  paths:
    include:
    - ./readme.md
  patterns:
  - pattern: ''
  severity: INFO
```

1. Create a file called `readme.md` and put some content in it
2. Run the rule against semgrep `0.57` and `0.58`.

**Expected behavior**
Semgrep should scan the target file.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Official binary
