### ISSUE TITLE
Understand re-exports

### ISSUE THREAD

**Issue by xmo-odoo** [semgrep/semgrep#3783]
I'm not quite sure how "deep" semgrep goes in its analysis, but one thing it doesn't seem to understand is the "re-exports" variant of aliasing, at least for Python:
```python
# foo.py
from bar import fn
fn()
# bar.py
from baz import fn
# baz.py
def fn(): ...
```
```yaml
# conf.sem
rules:
  - id: indirect
    languages: [python]
    severity: ERROR
    message: ''
    pattern: baz.fn()
```
