### ISSUE TITLE
Cannot write `pattern: y` (upgrade to YAML 1.2)

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3806]
**Describe the bug**
You cannot write `pattern: y` in Semgrep, because apparently the `y` gets parsed as `true`!

**To Reproduce**
https://semgrep.dev/s/Q4AJ

**Comment by nbrahms** [comment]
is this part of the YAML standard?

**Comment by nbrahms** [comment]
Per the YAML standard, only literal `true` and `false` are boolean scalars: https://yaml.org/spec/1.2/#id2803629

**Comment by emjin** [comment]
So I thought it was, because the YAML library in opam does this, but looking at the standard I agree with Nathan.

**Comment by emjin** [comment]
ooh perhaps this is outdated https://github.com/avsm/ocaml-yaml (they cite YAML 1.1). I can definitely update then

**Comment by nbrahms** [comment]
Note that even:
```yaml
rules:
- id: test
  pattern: !!str y
  message: Match Found!
  languages: [python]
  severity: WARNING
```
gets parsed incorrectly
