### ISSUE TITLE
Mixing taint and search mode returns vague error message

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#3895]
**Describe the bug**
When a rule specifies `mode: taint` *and* a search pattern like `pattern: `, the error message returned is vague and pretty unactionable. 

This will likely confuse users, and will take them a fair amount of work to figure out how to fix it, if they can at all.

I'm not sure where is best to fix this, maybe in the Python part not Semgrep core?

**To Reproduce**
Copy the following into a file like `taint_test.yml`:

```yml
rules:
  - id: php-search-and-taint-mode
    languages:
      - php
    message: |
      Need to sanitize output
    mode: taint
    pattern: echo $FOO;
    pattern-sanitizers:
      - pattern: htmlspecialchars(...)
    pattern-sinks:
      - pattern: echo ...;
    pattern-sources:
      - pattern: DB::$ANYFUNC(...)
    severity: WARNING
```

Copy the following into a source code file, like `taint_test.php`:

~~~php
<?php
$foo = DB::getAccount($foo_id);
echo $foo;

$bar = DB::getAccount($bar_id);
$baz = htmlspecialchars($bar);
echo $baz;
?>
~~~

Run Semgrep:

~~~bash
$ semgrep --config taint_test.yml taint_test.php
~~~

**Expected behavior**
I would expect a more specific and actionable error message, like:

> It appears you're using the `pattern` clause while in `taint` mode, which is not allowed. Only 'pattern-sanitizers', 'pattern-sinks', and 'pattern-sources' can be used while in `taint` mode. See https://semgrep.dev/docs/writing-rules/data-flow/#taint-tracking for more details.

**Screenshots**
![Screen Shot 2021-09-16 at 6 48 53 AM](https://user-images.githubusercontent.com/767449/133624102-8c3fe1eb-e319-49bd-8dea-de02ed9c9af8.png)

> ^ but which is it, what do I actually do to fix this? - Confused user

**What is the priority of the bug to you?**

- [ ] P1: important to fix or quite annoying

We're starting to use taint mode more and more internally, and we're gradually encouraging external users to leverage it as well. Thus, we should try to smooth down the various sharp edges for them where possible. 

**Environment**
macOS official build, 0.65.0
