### ISSUE TITLE
Issue with pattern-not-regex and parentheses

### ISSUE THREAD

**Issue by mlefebvre** [semgrep/semgrep#3918]
**Describe the bug**
Hello,

I have an issue that prevents pattern-not-regex from working properly since v0.57.
If a pattern is surrounded by parentheses, it doesn't seem to match correctly.

Am I doing something wrong?

**To Reproduce**
Create the following configuration file:
```
rules:
- id: some-id
  languages:
  - regex
  message: Some rule
  paths:
    include:
    - '*.yaml'
    - '*.yml'
  patterns:
  - pattern-regex: "(?im)^[ \\t]*-?[ \\t]*?[a-z0-9_-]*(secret|password|token|auth)[ \\t]*=[ \\t]*[^\\s]+[ \t]*$"
  - pattern-not-regex: "(=[\\t ]*\"\")"
  severity: ERROR
```
(I know that I don't really need parentheses in this case, I just wanted to repro the issue)

Create a file containing the following content:
```
potato:
  - SOME_API_TOKEN=""
```

Scan the file with semgrep

**Expected behavior**
The line shouldn't match since it contains =""

**Screenshots**
With v0.56
![image](https://user-images.githubusercontent.com/2453368/134248758-f3bb9be4-2340-4598-bf38-9c5066eabdad.png)

With v0.65
![image](https://user-images.githubusercontent.com/2453368/134248859-dc39090d-7663-4d6e-a183-750d59904f2e.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed
