### ISSUE TITLE
Tidle (backtick) string in Go not matched

### ISSUE THREAD

**Issue by khanhldt** [semgrep/semgrep#3930]
**Describe the bug**
I was investigating replacing GoSec rules with Semgrep, rule G201, and found that it looks like Semgrep is unable to parse backtick Go string, which is unfortunately a quite common way to declare SQL strings in this case.

**To Reproduce**
Rule (for demo purpose only, not the final rule to replace G201):
```yaml
rules:
- id: "gosec.G201"
  patterns:
  - pattern-inside: |
      $Q := fmt.Sprintf("$QUERY", ...)
      ...
  - metavariable-regex:
      metavariable: "$QUERY"
      regex: "select"
  - pattern-either:
    - pattern: "$DB.Query($Q,...)"
  message: SQL query construction using format string
  severity: "WARNING"
  languages: ["go"]
```

Test file that works:
```
package main

import (
    "database/sql"
    "fmt"
)

func test(conn *sql.DB, someVar string) {
    query := fmt.Sprintf("select region from %s", someVar)
    conn.Query(query)
}
```

Test file that doesn't work:
```
package main

import (
    "database/sql"
    "fmt"
)

func test(conn *sql.DB, someVar string) {
    query := fmt.Sprintf(`select region from %s`, someVar)
    conn.Query(query)
}
```

**Expected behavior**
Expected both test files to have worked with that rule.

**What is the priority of the bug to you?**

- [ x ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Tested using https://semgrep.dev/editor
