### ISSUE TITLE
Equivalence between go string literals and raw string literals

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3938]
In go, backtick strings are "raw strings" (unescaped) (see https://golang.org/ref/spec#String_literals). In particular, they are always constant literals, and users may want to match them using "...".

Example:

Rule:

```
rules:
- id: "gosec.G201"
  patterns:
  - pattern-inside: |
      $Q := fmt.Sprintf("$QUERY", ...)
      ...
  - metavariable-regex:
      metavariable: "$QUERY"
      regex: "select"
  - pattern-either:
    - pattern: "$DB.Query($Q,...)"
  message: SQL query construction using format string
  severity: "WARNING"
  languages: ["go"]
```

With string literal:

```
package main

import (
    "database/sql"
    "fmt"
)

func test(conn *sql.DB, someVar string) {
    query := fmt.Sprintf("select region from %s", someVar)
    conn.Query(query)
}
```

With raw string literal:

```
package main

import (
    "database/sql"
    "fmt"
)

func test(conn *sql.DB, someVar string) {
    query := fmt.Sprintf(`select region from %s`, someVar)
    conn.Query(query)
}
```

With the equivalence, both of these would match that rule
