### ISSUE TITLE
Rule specification: Distinguish target filter from target analyzer

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3961]
Currently there's only a `languages` field which is used both for selecting which files should be scanned and for selecting the analyzer. However, we have analyzers (regex, generic) which are not tied to a particular language. Right now filtering targets for these must be done via rule-specific include/exclude rules which don't work as well as the built-in language selectors.

Proposal: keep the `languages` field as the target selector, add a new optional field called `analyzer`:
* The `languages` field would be a list (union) of programming languages or file formats known by semgrep. This could include values like `["go"]` or `["javascript", "typescript"]` as is it today. It would no longer accept the values `["regex"]` or `["generic"]`.
* The special language `any` could be used to select any file.
* The new `analyzer` field would default to the semgrep pattern parser and matcher, which perhaps should be called `semgrep`. Other values would include `generic` and `regex`.
* `pattern-regex` is now deprecated as the root pattern. It becomes `analyzer: regex` and a regular `pattern` field holding the regex.

Example 1: regex
--

Note that this uses `pattern` rather than `pattern-regex`.
```
rules:
  - id: legacy-eval-search
    languages:
      - javascript
      - typescript
    analyzer: regex
    message: Insecure code execution
    pattern: eval\(
    severity: ERROR
```

Example 2: generic (spacegrep)
--

```
rules:
  - id: legacy-eval-search
    languages:
      - javascript
      - typescript
    analyzer: generic
    message: Insecure code execution
    pattern: eval(...)
    severity: ERROR
```

Example 3: semgrep
--

Implicit `analyzer` field:
```
rules:
  - id: legacy-eval-search
    languages:
      - javascript
      - typescript
    message: Insecure code execution
    pattern: eval(...)
    severity: ERROR
```

Explicit `analyzer` field:
```
rules:
  - id: legacy-eval-search
    languages:
      - javascript
      - typescript
    analyzer: semgrep
    message: Insecure code execution
    pattern: eval(...)
    severity: ERROR
```

Example 4: semgrep matching + regex
--

Here, `pattern-regex` is a post-processing filter that operates on the output of `pattern-inside`. This is not new. The root analyzer is the default (`semgrep`) and indicates how to process the `pattern-inside` field.
```
rules:
  - id: boto-client-ip
    languages:
      - python
    message: boto client using IP address
    patterns:
      - pattern-inside: boto3.client(host="...")
      - pattern-regex: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
    severity: ERROR
```

Example 5: generic scanning on all the files
--

`any` selects all the source files. Large files and files that don't look human-readable are still automatically excluded.

```
rules:
  - id: legacy-eval-search
    languages:
      - any
    analyzer: generic
    message: Insecure code execution
    pattern: eval(...)
    severity: ERROR
```

Example 6: known languages unsupported by semgrep parsers
--

Assume dockerfiles can be detected by semgrep but we can only analyze them with the regex or generic analyzers.
```
rules:
  - id: dockerfile-sudo
    languages:
      - dockerfile
    analyzer: generic
    message: don't require sudo in dockerfiles
    pattern: RUN sudo ...
    severity: ERROR
```
