### ISSUE TITLE
Semgrep v0.67.0 changes pattern matching behaviour in ruby

### ISSUE THREAD

**Issue by NEllusion** [semgrep/semgrep#3981]
**Describe the bug**
In semgrep `v0.66.0` the the pattern `Oj.load(..., mode: :object, ...)` in a ruby rule config would match both calls to `Oj.load` which used the hash rocket syntax, `:mode => :object` and the normal hash syntax `mode: :object`. However, in `v0.67.0` this changed and now for ruby methods which contain named parameters, you need to specify both ways to pass in the arguments as patterns.

**To Reproduce**

Install semgrep 0.66.0 or earlier. 

Run semgrep test with the following config/test file: 

```yml
# ruby-oj-load-deserialization.yml

rules:
- id: ruby-oj-load-deserialization
  languages: [ruby]
  pattern: 'Oj.load(..., mode: :object, ...)'
  message: |
    Oj.load is unsafe by default
  severity: WARNING
```

```rb
# ruby-oj-load-deserialization.rb

# ruleid: ruby-oj-load-deserialization
Oj.load(user_input, :mode => :object)
```

However, after upgrading to version 0.67.0 this test fails.

**Expected behavior**
The test should continue to pass unless a breaking change is mentioned in the changelog

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
    * If this bug is not with `semgrep test` itself, this could potentially be breaking rules.
- [ ] P2: regular bug that should get fixed

**Environment**
Running locally with semgrep installed via PIP
