### ISSUE TITLE
Matching a pattern inside the same pattern makes the outside pattern match

### ISSUE THREAD

**Issue by timhemel** [semgrep/semgrep#3991]
**Describe the bug**
Whenever I match a structure inside another structure, and the pattern syntax for those is the same, the outside pattern is returned as a match.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
```
rules:
  - id: nested class
    languages:
      - csharp
    message: nested class $B in $A
    patterns:
      - pattern: |
          class $B { ... }
      - pattern-inside: |
          class $A { ... }
    severity: INFO
```

```
class A {
    class B { }
}
```

returns 3 matches:

```
Line 1: nested class A in A
Line 2: nested class B in A
Line 2: nested class B in B
```

**Expected behavior**
I would have expected only one match: 

```
Line 2: nested class B in A
```

Workarounds via metavariable-comparison to check if `$A != $B` will not work, because I would like to detect structures with the same name that are actually nested.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
