### ISSUE TITLE
Autofix is broken because of import statements.

### ISSUE THREAD

**Issue by s3rius** [semgrep/semgrep#4185]
**Describe the bug**
I faced this issue when I was writing my own set of rules in .semgrep.yml.
I've tried to reproduce this bug on semgrep.dev playground and it's reproducible.

**To Reproduce**
Create custom rule with fix.
For example:
```yaml
rules:
  - id: exception-useless-parentheses
    pattern: raise $X()
    fix: raise $X
    message: Found useless parentheses
    languages: [python]
    severity: ERROR
```

This rule must validate that exception with no parameters have no parentheses.
And it works well for this sample:
```python
def test_test():
  raise RandomError()  # Works ok.
```

But if we add import statement for the exception, it breaks.

```python
from randomlib.errors import RandomError


def test_test():
  raise RandomError()
```

Semgrep suggests the following:
```
raise randomlib.errors import RandomError
```

**Expected behavior**

I expect that if I use $X variable it uses only $X variable and no import statement is the suggestion.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
It can be reproduced on https://semgrep.dev/editor and in standalone cli tool. The version of semgrep is 0.70.0.

**Comment by Kolaer** [comment]
```
rules:
- id: exception-useless-parentheses
  patterns:
    - pattern: raise $X()
    - pattern-not-inside: |
        import $X
        ...
  message: Found useless parentheses
  languages: [python]
  severity: ERROR
  fix: raise $X
```
Seems to work fine: https://semgrep.dev/s/Q9Gk
