### ISSUE TITLE
Semgrep will timeout multiple times on parsing a file

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#4238]
Scenario: two rules, run on the same file. Parsing the file times out. Semgrep will try to parse the file both times.

Example:

(First rule is not parsed because it can be filtered out; it is only there because the later yaml rules reference it)

```yaml
rules:
- id: ocaml.lang.best-practice.string.ocamllint-str-string-after
  pattern: String.sub $S $N (String.length $S - $N)
  message: Use instead `Str.string_after`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-string-after
    shortlink: https://sg.run/OPKk
    dev.semgrep.actions: &id001
    - block
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-string-after
    semgrep.ruleset: ocaml
- id: ocaml.lang.correctness.physical_vs_structural.physical-equal
  pattern: $X == $Y
  message: You probably want the structural inequality operator =
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: correctness
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.correctness.physical_vs_structural.physical-equal
    shortlink: https://sg.run/Zv14
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.correctness.physical_vs_structural.physical-equal
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.bool.ocamllint-bool-false
  pattern-either:
  - pattern: $X = false
  - pattern: $X == false
  - pattern: $X <> true
  message: Comparison to boolean. Just use `not $X`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.bool.ocamllint-bool-false
    shortlink: https://sg.run/9oEy
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.bool.ocamllint-bool-false
    semgrep.ruleset: ocaml
```

Command:
```
➜  semgrep-app git:(develop) semgrep --config ../testing/ocamllint-bool-false.yaml frontend/yarn.lock --time
Running 3 rules...
100%|███████████████████████████████████████████████████████████████████████████████|3/3
Warning: 2 timeout error(s) in frontend/yarn.lock when running the following rules:
[testing.ocaml.lang.best-practice.bool.ocamllint-bool-false,
testing.ocaml.lang.correctness.physical_vs_structural.physical-equal]

Semgrep-core timing summary:
Total CPU time: 60.0177  File parse time: -2.0000  Rule parse time: 0.0072  Match time: -2.0000
Slowest 5/1 files
frontend/yarn.lock                                                     (606KB): 60.0106
Slowest 5 rules to run (excluding parse time)
testing.ocaml.lang.best-practice.bool.ocamllint-bool-false:             run time 31.0048  match time -1.0000
testing.ocaml.lang.correctness.physical_vs_structural.physical-equal:   run time 31.0041  match time -1.0000
testing.ocaml.lang.best-practice.string.ocamllint-str-string-after:     run time 0.0089  match time 0.0000
ran 3 rules on 1 files: 0 findings
found problems analyzing 2 files; run with --verbose for details or run with --strict to
exit non-zero if any file cannot be analyzed cleanly
```
