### ISSUE TITLE
Tree-sitter times out parsing yarn.lock file

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#4239]
Run: 

Create config:
```
rules:
- id: ocaml.lang.best-practice.string.ocamllint-str-string-after
  pattern: String.sub $S $N (String.length $S - $N)
  message: Use instead `Str.string_after`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-string-after
    shortlink: https://sg.run/OPKk
    dev.semgrep.actions: &id001
    - block
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-string-after
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.ref.ocamllint-ref-decr
  pattern: $X := $X - 1
  message: You should use `decr
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.ref.ocamllint-ref-decr
    shortlink: https://sg.run/weYd
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.ref.ocamllint-ref-decr
    semgrep.ruleset: ocaml
- id: ocaml.lang.performance.list.ocamllint-length-list-zero
  pattern: List.length $X = 0
  message: You probably want $X = [], which is faster.
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: performance
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.performance.list.ocamllint-length-list-zero
    shortlink: https://sg.run/8yrQ
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.performance.list.ocamllint-length-list-zero
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.ifs.ocamllint-useless-else
  pattern: if $E then $E1 else ()
  message: Useless else. Just remove the else branch;
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.ifs.ocamllint-useless-else
    shortlink: https://sg.run/rd7J
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.ifs.ocamllint-useless-else
    semgrep.ruleset: ocaml
- id: ocaml.lang.correctness.physical_vs_structural.physical-equal
  pattern: $X == $Y
  message: You probably want the structural inequality operator =
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: correctness
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.correctness.physical_vs_structural.physical-equal
    shortlink: https://sg.run/Zv14
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.correctness.physical_vs_structural.physical-equal
    semgrep.ruleset: ocaml
- id: ocaml.lang.correctness.useless_if.ocamllint-useless-if
  pattern: if $X then $E else $E
  message: Useless if. Both branches are equal.
  languages:
  - ocaml
  severity: ERROR
  metadata:
    category: correctness
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.correctness.useless_if.ocamllint-useless-if
    shortlink: https://sg.run/7o3Q
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.correctness.useless_if.ocamllint-useless-if
    semgrep.ruleset: ocaml
- id: ocaml.lang.correctness.useless_eq.useless-equal
  pattern: $X = $X
  message: This is always true. If testing for floating point NaN, use `Float.is_nan`
    instead.
  languages:
  - ocaml
  severity: ERROR
  metadata:
    category: correctness
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.correctness.useless_eq.useless-equal
    shortlink: https://sg.run/EkPB
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.correctness.useless_eq.useless-equal
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.bool.ocamllint-bool-false
  pattern-either:
  - pattern: $X = false
  - pattern: $X == false
  - pattern: $X <> true
  message: Comparison to boolean. Just use `not $X`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.bool.ocamllint-bool-false
    shortlink: https://sg.run/9oEy
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.bool.ocamllint-bool-false
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.hashtbl.hashtbl-find-outside-try
  patterns:
  - pattern: |
      Hashtbl.find ...
  - pattern-not-inside: |
      try ... with ... -> ...
  message: You should not use Hashtbl.find outside of a try, or you should use Hashtbl.find_opt
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.hashtbl.hashtbl-find-outside-try
    shortlink: https://sg.run/yd7A
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.hashtbl.hashtbl-find-outside-try
    semgrep.ruleset: ocaml
- id: ocaml.lang.correctness.physical_vs_structural.physical-not-equal
  pattern: $X != $Y
  message: You probably want the structural inequality operator <>
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: correctness
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.correctness.physical_vs_structural.physical-not-equal
    shortlink: https://sg.run/nd3r
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.correctness.physical_vs_structural.physical-not-equal
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.ifs.ocamllint-backwards-if
  pattern: if $E then () else $E2
  message: Backwards if. Rewrite the code as 'if not $E then $E2'.
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.ifs.ocamllint-backwards-if
    shortlink: https://sg.run/b7Ov
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.ifs.ocamllint-backwards-if
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.bool.ocamllint-bool-true
  pattern-either:
  - pattern: $X = true
  - pattern: $X == true
  - pattern: $X != false
  message: Comparison to boolean. Just use `$X`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.bool.ocamllint-bool-true
    shortlink: https://sg.run/1ZE1
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.bool.ocamllint-bool-true
    semgrep.ruleset: ocaml
- id: ocaml.lang.performance.list.ocamllint-length-more-than-zero
  pattern: List.length $X > 0
  message: You probably want $X <> [], which is faster.
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: performance
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.performance.list.ocamllint-length-more-than-zero
    shortlink: https://sg.run/gLZ5
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.performance.list.ocamllint-length-more-than-zero
    semgrep.ruleset: ocaml
- id: ocaml.lang.correctness.useless_let.useless-let
  pattern: let $X = $E in $X
  message: Useless let
  languages:
  - ocaml
  severity: ERROR
  metadata:
    category: correctness
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.correctness.useless_let.useless-let
    shortlink: https://sg.run/LwDY
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.correctness.useless_let.useless-let
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.string.ocamllint-str-last-chars
  pattern: String.sub $S (String.length $S - $N) $N
  message: Use instead `Str.last_chars`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-last-chars
    shortlink: https://sg.run/eLvL
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-last-chars
    semgrep.ruleset: ocaml
- id: ocaml.lang.compatibility.deprecated.deprecated-pervasives
  pattern: Pervasives.$X
  message: Pervasives is deprecated and will not be available after 4.10. Use Stdlib.
  languages:
  - ocaml
  severity: ERROR
  metadata:
    category: compatibility
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.compatibility.deprecated.deprecated-pervasives
    shortlink: https://sg.run/dKe0
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.compatibility.deprecated.deprecated-pervasives
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.string.ocamllint-useless-sprintf
  pattern-either:
  - pattern: Printf.sprintf "..."
  - pattern: Printf.sprintf "%s" $S
  message: Useless sprintf
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-useless-sprintf
    shortlink: https://sg.run/vzl0
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-useless-sprintf
    semgrep.ruleset: ocaml
- id: ocaml.lang.best-practice.string.ocamllint-str-first-chars
  pattern: String.sub $S 0 $N
  message: Use instead `Str.first_chars`
  languages:
  - ocaml
  severity: WARNING
  metadata:
    category: best-practice
    technology:
    - ocaml
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-first-chars
    shortlink: https://sg.run/x16y
    dev.semgrep.actions: *id001
    semgrep.policy:
      id: 18613
      name: Rule Board - Block column
      slug: rule-board-block
    semgrep.url: https://semgrep.dev/r/ocaml.lang.best-practice.string.ocamllint-str-first-chars
    semgrep.ruleset: ocaml
```

➜  semgrep-app git:(develop) semgrep --config [config] frontend/yarn.lock --time --debug
