### ISSUE TITLE
[Join mode] Optional conditions

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4255]
**Is your feature request related to a problem? Please describe.**
Join mode needs some kind of "must-match" counter or optional designation.  Not all of the properties are guaranteed to match, particularly if you're manually enumerating stuff: Model.Foo vs Model.Foo.Bar?

**Describe the solution you'd like**
A condition similar to the following:

```yaml
    on:
    - operator: 'user-input.$P1 > unescaped-extensions.$PROPERTY'
    - operator: 'user-input.$P1 > unescaped-extensions.$PROPERTY'
      optional: true
```

Also see these links: 
- https://semgrep.dev/s/kboberg@chegg.com:razor_raw_html
- https://semgrep.dev/s/kboberg@chegg.com:unsafe_asp_controller_string
