### ISSUE TITLE
golang: taint tracking

### ISSUE THREAD

**Issue by Sebastian1011** [semgrep/semgrep#4280]
**Is your feature request related to a problem? Please describe.**
I'm trying to track where the data flows from a thrift handler param , but got an Error:
 Pattern parse error: In rule tacing: Invalid pattern for Golang

my rules yaml looks like follows:

```
rules:
  - id: tacing
    languages:
      - golang
    message: find data flow
    mode: taint
    pattern-sources:
      - patterns:
        - pattern-inside: sourcefunction ($REQ, ...) {...}
        - pattern: $REQ
    pattern-sinks:
      - pattern: sinkfunction(...)
    severity: ERROR
```

**Describe the solution you'd like**
Is there any sugestion, how to write taint tracking rules in this case.
