### ISSUE TITLE
Taint mode in PHP doesn't work on object that method is called on 

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#4320]
https://semgrep.dev/s/sjord:domdocument_load

```
  pattern-sources:
  - patterns:
    - pattern: new DOMDocument(...)
  pattern-sinks:
  - patterns:
    - pattern-inside: $DOMDOCUMENT->load($FILENAME, ...)
    - pattern: $DOMDOCUMENT
```

```
<?php
$doc = new DOMDocument();
$doc->load('file.xml');  // I expect this to match, it doesn't
$doc->load($doc);  // I expect this to match, it does
$something->load($doc);  // This doesn't match, as expected.
```

I try to match calls to `DOMDocument::load`, with taint mode to track whether `$DOMDOCUMENT` is the result of a call to `new DOMDocument()`, in `$DOMDOCUMENT->load($FILENAME, ...)`. However, this doesn't seem to work properly. `$doc->load('file.xml')` doesn't match, even though `$doc` should be tainted here.
