### ISSUE TITLE
Support ellipsis metavariables for parameters

### ISSUE THREAD

**Issue by sfc-gh-nsfard** [semgrep/semgrep#4420]
**Is your feature request related to a problem? Please describe.**

I'd like to extract a java method signature (including arguments) into a metavariable.

**Describe the solution you'd like**

The ellipsis metavariable can be used in a `message` and print out all arguments.

**Describe alternatives you've considered**

**Additional context**

for example, given the following java snippet:

```java
public class ClassA {
  public void func(MyObj obj) {
    obj.writeObj("object");
  }
}
```

and the following rule:
```yaml
rules:
- id: blah
  patterns:
    - pattern: (MyObj $OBJ).writeObj(...);
    - pattern-inside: |
        $RT $METHOD($...ARGS) {
          ...
        }
  message: $METHOD($...ARGS)
  languages: [java]
  severity: INFO
```

I'd like to see the message: `func(MyObj obj)`
