### ISSUE TITLE
[Python] Cannot parse tuple expansion

### ISSUE THREAD

**Issue by vmarkovtsev** [semgrep/semgrep#4461]
**Describe the bug**
semgrep considers Python3 files with `return a, *b` invalid.

**To Reproduce**
```
def foo():
    a = 1,
    return 2, *a

print()
```
raises
```
Semgrep Core WARN - Syntax error in file bug.py:3
	`*` was unexpected
```
Note: there must be some rule match. For example, this is my config:
```
rules:
- id: python-no-print
  pattern: print(...)
  message: Replace print with logging
  languages: [python3]
  severity: ERROR
```

**Expected behavior**
This is a valid Python 3 syntax. Works on 3.8+, I didn't check older versions.

Also,
```
def foo():
    a = 1,
    return (2, *a)
```
successfully parses.

**What is the priority of the bug to you?**

P1 - there are many files in my project with that syntax but I have a workaround.

**Environment**
semgrep 0.77.0
