### ISSUE TITLE
[JS] Taint does not propagate through `.push(...)` for arrays

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4509]
**Describe the bug**
It appears that taint mode stops propagating data at `.push(...)` in array objects.

**To Reproduce**
This link has 3 examples. The third does not work, but should.
https://semgrep.dev/s/bXKp

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by IagoAbal** [comment]
At present taint-mode only propagates taint through explicit assignments. In your example taint needs to be propagated through a side-effectful method call. We could perhaps asume that a (pressumably void-returning) method call like `data.push(input)` does taint `data` if `input` is tainted. We make similar assumptions in constant propagation already.

The current workaround would be:
```yaml
pattern-sources:
  - patterns:
    - pattern-inside: |
        $ARRAY.push(<... req.query ...>)
        ...
    - pattern: $ARRAY
```
