### ISSUE TITLE
homebrew deploy action broken due to updated python version

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#4555]
**Describe the bug**
Update on Homebrew-core job is failing during release https://github.com/returntocorp/semgrep/runs/4889454978?check_suite_focus=true

This is because https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml#L320 has hardcoded the version of python that is running and github action is no longer running 3.9.9 but is running 3.9.10

We should dynamically figure out what version of python is installed / what path of pipgrip should be overwritten instead of hard coding it here.

**To Reproduce**
Create new job in https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/tests.yml

Copy 
```
  test-homebrew-core-pr:
    name: Update on Homebrew-Core
    runs-on: macos-10.15
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          # Needs to be < 3.10 see https://github.com/returntocorp/semgrep/issues/4213
          python-version: 3.9
      - name: Brew update
        run: brew update
      - name: Install brew pipgrip
        run: brew install pipgrip
      - name: Install pip pipgrip
        run: pip install pipgrip
      - name: Point homebrew pipgrip to pip pipgrip
        # Homebrew brew calls brew pipgrip internally but brew pipgrip is pinned to python3.10
        # this tricks it into using our 3.9 pipgrip
        run: rm /usr/local/opt/pipgrip/bin/pipgrip && ln /Users/runner/hostedtoolcache/Python/3.9.9/x64/bin/pipgrip /usr/local/opt/pipgrip/bin/pipgrip
```
And make a new PR. This job should fail for the above detailed reasons
