### ISSUE TITLE
Support `fix` action to delete lines

### ISSUE THREAD

**Issue by lgfa29** [semgrep/semgrep#4572]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to prevent a specific pattern from being used in a code base. In these situations I can write a rule to match and detect the pattern, but currently there's not way to provide a `fix` for it, which would be to delete the matching lines.

Example playground: https://semgrep.dev/s/kzdK

**Describe the solution you'd like**
This may be a little tricky to define in YAML, but maybe it would be possible to differentiate a missing key from an empty string?

```yaml
# Missing `fix` key, no fix.
- id: ...
  pattern: ...

# Empty `fix` key, delete match.
- id: ...
  pattern: ...
  fix: ""
```

But maybe that's too subtle and error-prone, in which a special key could be used (`fix_by_delete: true`?).

**Describe alternatives you've considered**
An empty `key` value as described above is currently ignored. In some cases it could be possible to use a comment (e.g.: `fix: "//"`), but that's not very elegant 😅 

**Additional context**
N/A
