### ISSUE TITLE
PHP: Support for matching types in function parameters

### ISSUE THREAD

**Issue by idawson-gl** [semgrep/semgrep#4589]
Right now it's not possible to match types defined in function parameters. This makes it impossible to match functions or methods that are defined with type information.

Example here: https://semgrep.dev/s/idawson-gl:findmethod

It would be excellent if we were able to match on types, or use ellipsis to ignore them.

The only way to currently match a function like the one above is to have a rule that matches the variable name, which.. is not ideal.

```
rules:
- id: Test
  patterns:
    - pattern: public function someMethod($X) { ... }
    - metavariable-regex:
        metavariable: $X
        regex: (.*var.*)  
  message: someMethod with var
  languages: [php]
  severity: INFO
```

Interestingly, this is also an issue for classes that extend other classes (again seems to be a type propagation issue). The difference is I can actually get it to match (again using metavariable-regex):
```
rules:
- id: Test
  patterns:
    - pattern: |
        class $CLASS extends $X { ... }
    - metavariable-regex:
        metavariable: $X
        regex: (\\SomePkg\\SomeBase)    
  message: someMethod with var
  languages: [php]
  severity: INFO
```
