### ISSUE TITLE
Python f-strings appear to be string literal concatenation

### ISSUE THREAD

**Issue by huonw** [semgrep/semgrep#4608]
**Describe the bug**

A pattern like `"..." "..."` is handy for catching string literal concatenation in Python (https://docs.python.org/3/reference/lexical_analysis.html#string-literal-concatenation), ala https://pylint.pycqa.org/en/latest/messages/warning/implicit-str-concat.html. However, this pattern also flags some single strings: `f"anything"`, even without any substitutions. Fortunately, this can be disabled with an extra `pattern-not: f"..."`, but maybe that causes some false negatives.

**To Reproduce**
https://semgrep.dev/s/AyZ8

```yaml
rules:
- id: untitled_rule
  patterns:
    - pattern: |
        "..." "..."
    - pattern-not: f"..."
  message: Semgrep found a match
  languages: [python]
  severity: WARNING
```

```python
print("A" "B" "C")
print(
  "A"
  "B"
  "C"
)
print("A", f"B", f"C")
```

With the `pattern-not`, only the first two prints are flagged, with it removed/commented out, the two f-strings in the last print is flagged too.

**Expected behavior**

A pattern like `"..." "..."` shouldn't match f strings.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Simplify our rule outlawing string literal concatenation.
