### ISSUE TITLE
Strict flag confusing behavior with nosem

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#4625]
**Describe the bug**
It looks like `--strict` causes semgrep to report an error on on a `nosem` inline ignore if it contains rule_ids that do not match
a rule_id of a finding that fired on that line.

This is inconsistent because it does not report that nosem if no finding fires on that line.

**To Reproduce**
On foo.py
```
# nosem: eqeq
x = 1
```
Run  `semgrep --config config.yml --strict foo.py`

config.yml
```
rules:
- id: eqeq
  languages:
  - python
  message: "eqeq"
  pattern: $X = 1
  severity: INFO
```

then change the rules to be 
```
- id: fingerprints.fingerprints.cai-python-technology-python
  languages:
  - generic
  message: Detected a .py file. This likely indicates py is in use.
  metadata:
    license: Semgrep Registry License
    source: https://semgrep.dev/r/fingerprints.fingerprints.cai-python-technology-python
    shortlink: https://sg.run/QbgD
  paths:
    include:
    - '*.py'
  pattern-regex: ^.
  severity: INVENTORY
```
semgrep will now report an error

**Expected behavior**
1. We should error on nosems with no findings independent of whether or not something managed to fire on it (i.e. running without the eqeq rule should report an error but it doesnt)
2. `--strict` should not report an error in the second rule file because there is a matching rule to the nosem it just isnt the first file

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
