### ISSUE TITLE
Error message when using "generic" in a rule configuration with multiple languages is unclear

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#4698]
**Describe the bug**
When running a rule with a `languages` list with `generic` and at least one other language causes a parser error with:

`invalid language unsupported language: generic`

**To Reproduce**
Here is a working `generic` rule:
https://semgrep.dev/s/returntocorp:generic-single-language-parser-example

Replacing the rule with:

```
rules:
- id: generic-multi-language-parser-example
  pattern: $A = "..."
  message: This is a message.
  languages:
    - generic
    - html
  severity: WARNING
```
will cause a parser error in playground:

```
{"code":2,"level":"error","message":"[ERROR] Semgrep Core — Rule parse error\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nIn rule generic-multi-language-parser-example: invalid language unsupported language: generic\n","rule_id":"generic-multi-language-parser-example","type":"Rule parse error"}
```
**Expected behavior**
Error message should indicate that `generic` mode does not support other values in the `languages` key in the rule definition.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
This is a QoL "why is my rule broken" change - users familiar with the inner workings of the parser may find this error intuitively obvious as `generic` is a "catch-all" parser but the application should be specific when telling the user *why* their rule broke.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-889/error-message-when-using-generic-in-a-rule-configuration-with-multiple.

**Comment by Pamplemousse** [comment]
This is still an issue, and IMHO more `P1`:

Because of this and https://github.com/semgrep/semgrep/issues/7276 , rules need to be duplicated to apply to Java files as well as JSP ones. Which increases maintenance burden.

I wish I could maintain a single rule that said:
```yaml
languages: [generic, java]
# ...
paths:
  include:
    - '*.java'
    - '*.jsp'
```
