### ISSUE TITLE
Semgrep fails when defining a pattern with a modifier in PHP

### ISSUE THREAD

**Issue by Hamz-a** [semgrep/semgrep#4710]
**Context**
It would be nice to be able to match specific PHP class fields, for example:
```php
class Post extends Model
{
    use HasFactory;

    protected $guarded = array();  // try to match this
    protected  $guarded = [];  // and this
    protected $aaa = 'aaa'; // but not this
    protected $fillable = ['title']; // and not this
}
```
The most simple pattern would look like this: ` - pattern: $guarded = []`. But this will match all kinds of stuff, for example a simple code snippet `$guarded = [];` anywhere might be matched...

We can add some constraints using `pattern-inside`. Ideally, it would be nice to also specify that it needs to be `protected`.

**Bug**
When the simple pattern above is prepended with `protected`, the Semgrep engine fails with the following error message:
```json
{
    "code": 2,
    "level": "error",
    "message": "[ERROR] Semgrep Core — Pattern parse error\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nIn rule laravel-mass-assignment-empty-guarded: Invalid pattern for PHP\n",
    "rule_id": "laravel-mass-assignment-empty-guarded",
    "spans":
    [
        {
            "config_end":
            {
                "col": 37,
                "line": 4,
                "offset": 99
            },
            "config_path":
            [
                "rules",
                "0",
                "patterns",
                "0",
                "pattern"
            ],
            "config_start":
            {
                "col": 14,
                "line": 4,
                "offset": 76
            }
        }
    ],
    "type": "Pattern parse error"
}
```

**To Reproduce**
Here's a link to the complete snippet without `protected` modifier: https://semgrep.dev/s/Y0BX
Here's a link to the complete snippet with `protected` modifier and fails: https://semgrep.dev/s/6b86

Test sample
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public $guarded = []; // ideally won't match since it's public
    protected $guarded = array();  // match this
    protected  $guarded = [];  // match this
    public $aaa = 'aaa';
    protected $fillable = ['title'];

    private function test() {
        $guarded = []; // if the protected pattern was properly working, this wouldn't match
    }
}

$guarded = 'aaa'; // should not match because outside of class

class Post extends Foo
{
    use HasFactory;

    public $guarded = []; // should not match because wrong class
    protected $guarded = array(); // should not match because wrong class
    public $aaa = 'aaa';
    protected $fillable = ['title'];
}
```

Pattern:
```yaml
rules:
- id: laravel-mass-assignment-empty-guarded
  patterns:
    - pattern: $guarded = []
    - pattern-inside: class $CLASS extends Model { ... }
  message: |
      Laravel disallows mass-assignments by default. Developers can use the $fillable property to explicitly allow certain fields to be mass-assigned. In contrast, the $guarded property can be used to explicitly disallow certain fields to be mass-assigned. However, by setting the value of the $guarded property to an empty array, the default protection mechanism provided by Laravel to thwart mass-assignment vulnerabilities is entirely disabled.
  languages: [php]
  severity: WARNING
```

**Expected behavior**
It should be possible to provide an explicit field modifier in Semgrep rules.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Match specific fields in PHP classes with a specific modifier.
