### ISSUE TITLE
Can't discover files that had problems being analyzed

### ISSUE THREAD

**Issue by johnseekins** [semgrep/semgrep#4720]
**Describe the bug**
A run of `semgrep` completes with a message like the following:

```
found problems analyzing 19 files; run with --verbose for details or run with --strict to exit non-zero if any file
cannot be analyzed cleanly
```

So I run semgrep with `--verbose` to discover these files, only to find out they are messages like:

```
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line /tmp/tmp-73-61d865.mvar-pattern:4: `${{` was unexpected

WARN Semgrep Core — Syntax error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line /tmp/tmp-73-955362.mvar-pattern:1: `${{` was unexpected

WARN Semgrep Core — Syntax error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line /tmp/tmp-73-c5249b.mvar-pattern:4: `{ secrets.DATABASE_PASSWORD_DEV` was unexpected
WARN Semgrep Core — Syntax error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line /tmp/tmp-73-0c6e70.mvar-pattern:4: `${{` was unexpected
```

**To Reproduce**
Not entirely sure. This just...happens when I run the program.

**Expected behavior**
It would be incredible to see the actual file names that are causing syntax problems. And it would be even more incredible to indicate the associated rule.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
running off docker, using manually downloaded rules from the semgrep-rules repo.

Actual command:
```
docker run -t --rm -v $(pwd):/src --workdir /src returntocorp/semgrep:latest --metrics off --no-autofix --config /src/.semgrep/rules/
```

**Use case**
What will fixing this bug enable for you?
No more error messages in a manual run of the program.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-901/cant-discover-files-that-had-problems-being-analyzed.

**Comment by ievans** [comment]
Hi, agreed this is frustrating output, and thanks for the detailed bug report. What are the contents of `.semgrep/rules/`? Can you share a reproducing rule + target file combination? We may be able to solve without it but curious if for instance `--config=auto` or `p/python` works.

**Comment by johnseekins** [comment]
This looks like the broken rule:

```
rules:
- id: curl-eval
  languages:
  - yaml
  message: Data is being eval'd from a `curl` command. An attacker with control of
    the server in the `curl` command could inject malicious code into the `eval`,
    resulting in a system comrpomise. Avoid eval'ing untrusted data if you can. If
    you must do this, consider checking the SHA sum of the content returned by the
    server to verify its integrity.
  metadata:
    category: security
    cwe: 'CWE-78: Improper Neutralization of Special Elements used in an OS Command
      (''OS Command Injection'')'
    owasp: 'A1: Injection'
    references:
    - https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
    technology:
    - github-actions
    - bash
    - curl
  patterns:
  - pattern-inside: 'steps: [...]'
  - pattern-inside: "- run: ...\n  ...\n"
  - pattern: 'run: $SHELL'
  - metavariable-pattern:
      language: bash
      metavariable: $SHELL
      patterns:
      - pattern: '$DATA=<... curl ... >

          ...

          eval <... $DATA ...>

          '
  severity: ERROR
```

**Comment by emjin** [comment]
Hi, can you add `-d` to the semgrep command you ran? It will dump the command sent to the engine tool and also save the rules and targets files. Please send the command and also the two files (they'll be indicated in the command as the rules and targets files)

**Comment by johnseekins** [comment]
```
docker run -t --rm -v $(pwd):/src --workdir /src returntocorp/semgrep:latest --metrics off --no-autofix --config /src/.semgrep/rules/ -d
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Running 1 rules...
/usr/local/bin/semgrep-core -json -rules /home/semgrep/.semgrep/semgrep_rules.yaml -j 8 -targets /home/semgrep/.semgrep/semgrep_targets.txt -timeout 30 -timeout_threshold 0 -max_memory 0 -json_time -fast
```

```
/src $ cat /home/semgrep/.semgrep/semgrep_rules.yaml 
rules:
- id: semgrep.rules.curl-eval
  languages:
  - yaml
  message: Data is being eval'd from a `curl` command. An attacker with control of
    the server in the `curl` command could inject malicious code into the `eval`,
    resulting in a system comrpomise. Avoid eval'ing untrusted data if you can. If
    you must do this, consider checking the SHA sum of the content returned by the
    server to verify its integrity.
  metadata:
    category: security
    cwe: "CWE-78: Improper Neutralization of Special Elements used in an OS Command\
      \ ('OS Command Injection')"
    owasp: 'A1: Injection'
    references:
    - https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
    technology:
    - github-actions
    - bash
    - curl
  patterns:
  - pattern-inside: 'steps: [...]'
  - pattern-inside: "- run: ...\n  ...\n"
  - pattern: 'run: $SHELL'
  - metavariable-pattern:
      language: bash
      metavariable: $SHELL
      patterns:
      - pattern: "$DATA=<... curl ... >\n...\neval <... $DATA ...>\n"
  severity: ERROR
```
I'm going to obfuscate some file names in the targets output...

```
/src $ cat /home/semgrep/.semgrep/semgrep_targets.txt 
[{"path": ".../app.dev.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/actions/.../app.example.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/actions/.../action.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/actions/.../action.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../all.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../config_variables.example.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../config.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/actions/.../cron.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": "dispatch.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/workflows/ci.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../app.example.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": "yamllint.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/workflows/cleanup.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/workflows/scans.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../docker-compose.yml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../docker-compose.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".../app.prod.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]},
{"path": ".github/actions/.../queue.yaml", "language": "yaml", "rule_ids": ["semgrep.rules.curl-eval"]}]
```

**Comment by saez0pub** [comment]
Hello,

I am facing the same problem.
Any variable interpolation in a run block is problematic.
Here is a minimal reproduction:

Test this code against https://semgrep.dev/playground/r/yaml.github-actions.security.curl-eval.curl-eval
```
name: test

jobs:
  test:
    steps:
      - run: echo "${{ foo }}"
```

This code should pass but produces a syntax error.
