### ISSUE TITLE
Autofixing a Python decorator deletes all other decorators on the function

### ISSUE THREAD

**Issue by timmc-edx** [semgrep/semgrep#4721]
### Describe the bug
Because decorators are matched in the context of a function, but without the context of the other decorators, there is no way to preserve the other decorators when autofixing just one of them.

### To Reproduce
Demo: https://semgrep.dev/s/8zLq

Rule that adds `autospec=True` if it's missing from a `@patch` decorator:

```yaml
rules:
- id: autospec-everything
  patterns:
    - pattern: |
        @patch($...PA)
        def $FUNC($...FA):
          $FBODY
    - pattern-not: |
        @patch(..., autospec=True, ...)
        def $FUNC(...):
          ...
  message: Add autospec=True to patch decorators
  languages: [python]
  severity: INFO
  fix: |
      @patch($...PA, autospec=True)
      def $FUNC($...FA):
        $FBODY
```

Code to run against: https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/lms/djangoapps/badges/tests/test_models.py#L217

### Expected behavior
Changes should be made to the decorator and/or the function, and any other decorators should be left untouched.

Alternatively, it should not match in the first place.

### What is the priority of the bug to you?

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

### Environment
`pip install semgrep==0.82.0` on Ubuntu Linux 20.04.

### Use case
By default, mocks from`unittest.mock` will allow any attribute access or method call, which can result in hidden test errors. Using `autospec=True` seems to be a good idea by default, so I'd like to add it everywhere to an existing large codebase.

The only reason I didn't mark this P0 is that it turns out autospec has some other side effects, so I don't actually want to do this change right now. :-)
