### ISSUE TITLE
Parse error using Dockerfile language

### ISSUE THREAD

**Issue by raghavjain3** [semgrep/semgrep#4744]
**Describe the bug**
Unable to parse Dockerfile - Generic mode "works" (scans but result is not accurate) but Dockerfile mode does not

**To Reproduce**
Details in Linear

**Expected behavior**
Rule scans properly when Dockerfile is selected as the language

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Dockerfile scanning

https://semgrep.dev/r?q=generic.dockerfile.correctness.multiple-cmd-instructions.multiple-cmd-instructions

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-921/parse-error-using-dockerfile-language.

**Comment by mjambon** [comment]
This works:
```yaml
rules:
  - id: multiple-cmd-instructions
    severity: ERROR
    languages:
      - generic
    patterns:
      - pattern-not-inside: |
          CMD ...
          ...
          FROM $IMG
          ...
          CMD ...
      - pattern: |
          CMD ...
          ...
          ...
          CMD ...
    message: Multiple CMD instructions were found. Only the last one will take effect.
    metadata:
      source-rule-url: https://github.com/hadolint/hadolint/wiki/DL4003
      references:
        - https://github.com/hadolint/hadolint/wiki/DL4003
        - https://kapeli.com/cheat_sheets/Dockerfile.docset/Contents/Resources/Documents/index#//dash_ref_Instructions/Entry/CMD/0
      category: correctness
      technology:
        - dockerfile
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    paths:
      include:
        - "*dockerfile*"
        - "*Dockerfile*"
 ```
It's `FROM ...` that doesn't make sense. Instead, use `FROM $IMG`.
