### ISSUE TITLE
Core error reported for pattern parse failure

### ISSUE THREAD

**Issue by nealwu** [semgrep/semgrep#4745]
**Describe the bug**
I received the following error message when setting up a new semgrep rule:
```
The following config files produced errors:
	semgrep_rules/pre_commit/not-equal-any.yaml: [ERROR] Semgrep Core — Pattern parse error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

In rule not-equal-any: Invalid pattern for Python
```

**To Reproduce**
I created `not-equal-any.yaml`:
```
rules:
- id: not-equal-any
  pattern: |
    != any_
  message: Using "!= any_(...)" does not do what you want it to do. Use "!= all_(...)" instead.
  languages:
  - python
  severity: ERROR
```

Along with the test `not-equal-any.py`:
```
# ruleid: not-equal-any
Trip.query.filter(Trip.id != any_([1, 2, 3]))

# ok: not-equal-any
Trip.query.filter(Trip.id != all_([1, 2, 3]))

# ok: not-equal-any
Trip.query.filter(Trip.id == any_([1, 2, 3]))
```

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
An official binary (installed via brew)

**Use case**
What will fixing this bug enable for you?
An important rule to catch SQLAlchemy bugs.
