### ISSUE TITLE
Metavariables not working when used within a Deep Expression in Typescript

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#4788]
**Describe the bug**
Metavariables aren't working properly when used in Deep Expressions in Typescript

**To Reproduce**
The rule doesn't save in the editor for some reason, even though it runs both there and in the CLI, so I'll just paste the code below. Changing the `$ASDF` to `id` in the `find()` call makes Semgrep find the line, and the `$ASDF = <... $REQ.params.id ...>` deep expression is verifiably not an issue, as the line is still found if you make the above change but leave the `pattern-inside` intact.

Code for the rule: (extra metadata removed for brevity)
```yaml
rules:
  - id: mongo-query-inject
    languages:
      - ts
    patterns:
      - pattern-inside: |
          $ASDF = <... $REQ.params.id ...>
          ...
      - pattern: |
          $DB.orders.find(..., { $where: <... $ASDF ...> }, ...)
```

Test code:
```typescript
import utils = require('../lib/utils')
import { Request, Response } from 'express'

const db = require('../data/mongodb')

module.exports = function trackOrder () {
  return (req: Request, res: Response) => {
    const id = utils.disableOnContainerEnv() ? String(req.params.id).replace(/[^\w-]+/g, '') : req.params.id

    // ruleid: mongo-query-inject
    db.orders.find({ $where: `this.orderId === '${id}'` }).then(order => {
      const result = utils.queryResultToJson(order)
      if (result.data[0] === undefined) {
        result.data[0] = { orderId: id }
      }
      res.json(result)
    }, () => {
      res.status(400).json({ error: 'Wrong Param' })
    })
  }
}
```

**Expected behavior**
Metavariables should be recognized within a deep expression.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Same result on Semgrep App as in the CLI, although I'm currently unable to save the rule on Semgrep App.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-953/metavariables-not-working-when-used-within-a-deep-expression-in.

**Comment by aryx** [comment]
weird, because this works:
```
rules:
  - id: mongo-query-inject
    languages:
      - ts
    patterns:
      - pattern-inside: |
          $ASDF = <... $REQ.params.id ...>
          ...
          $DB.orders.find(..., { $where: <... $ASDF ...> }, ...)
    severity: ERROR
    message: found a match with $ASDF
 ```
so this is a bug when we combine pattern-inside and pattern here
