### ISSUE TITLE
String created with Sprintf not detected by metavariable-regex

### ISSUE THREAD

**Issue by mtausig** [semgrep/semgrep#4826]
I am trying to write a rule which matches the values of the parameter to a function in go:

```
rules:
- id: arg-starts-with-bar
  patterns:
    - pattern: Foo("$ARG")
    - metavariable-regex:
        metavariable: $ARG
        regex: ^bar
  languages: [go]
```

The rule should match every occurence where the parameter to the `Foo`  function starts with `bar`.
This works fine as long as the parameter is written literally, but unfortunately not if it has been created using `Sprintf`:

```
package foo

func f1() {
    arg := "bar"+"baz"
    Foo(arg)
}

func f2() {
    arg := Sprintf("bar%s", "baz")
    Foo(arg)
}

func f3(id int) {
    arg := Sprintf("bar%v", id)
    Foo(arg)
}
```

The rule matches only the first function call but not the other ones.
I would expect a match for all of theme, since they are all a string starting with `bar` (the first two are even functionally identical).

Playground link: https://semgrep.dev/s/e5vl

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1000/string-created-with-sprintf-not-detected-by-metavariable-regex.

**Comment by aryx** [comment]
But why would you use sprintf with 2 literals? Why not just use directoy "barbaz" ?

**Comment by mtausig** [comment]
> But why would you use sprintf with 2 literals? Why not just use directoy "barbaz" ?

I only used two literals to make the example simpler. In reality, "baz" will of course usually be some variable itself, maybe even a non-string.
But that should not really make a difference from Semgrep's perspective.

I updated my testcase accordingly.

**Comment by aryx** [comment]
We could handle partially-symbolic string, like here we know it starts with baz (if you hardcode the knowledge of sprintf in the engine), and so the metavariable-regexp after could match, but I'm not sure it's worth the complexity.
Also we would need to handle all sprintf like functions in every languages ...

**Comment by mtausig** [comment]
I think that `Sprintf` is a fairly common method for concatenating strings with other datatypes (especially numerics), making this case more common than in other languages like Python or C#

**Comment by IagoAbal** [comment]
You can achieve almost what you want with the experimental _symbolic propagation_ feature: https://semgrep.dev/s/Gbd2
```yaml
    patterns:
      - pattern-either:
        - pattern: Foo("$ARG")
        - pattern: Foo(Sprintf("$ARG", ...))
      - metavariable-regex:
          metavariable: $ARG
          regex: ^bar
    options:
      symbolic_propagation: true
```
If we resolved `Sprintf` to `fmt.Sprintf` we could make Semgrep recognize uses of `Sprintf` that evaluate to constant strings. But I don't think we should make `"$ARG"` match a string that is not constant, just because we know a constant _prefix_. We would need some new kind of string pattern for that specific purpose. But in my opinion _symbolic propagation_ does a nice job here. Do we really need something else?
