### ISSUE TITLE
JS/TS: Metavariable binds too much when used with `$X. ... .$F` style pattern

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#4891]
**Describe the bug**
I'm not sure what the exact issue is, but currently the rule only matches one of the test cases. Deleting the innermost `patterns` that has the `pattern-inside` and the `metavariable-regex` results in all of the test cases matching, which is the behavior I'm expecting.

**To Reproduce**
https://semgrep.dev/s/lejliu:ts-metavariable-regex-bug
Delete 
```
          - patterns:
              - pattern-inside: |
                  $DB = require('$IMPORT')
                  ...
              - metavariable-regex:
                  metavariable: $IMPORT
                  regex: .*mongodb$
```
and rerun the rule.

**Expected behavior**
I expected all the test cases to match.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed
