### ISSUE TITLE
named placeholder in generic language doesn't match "/"

### ISSUE THREAD

**Issue by bstpierre** [semgrep/semgrep#4895]
Using a named placeholder in a pattern-inside with "generic" language matches a string without "/", but doesn't match when "/" is present.

**To Reproduce**

```
rules:
- id: form-action
  patterns:
  - pattern-inside: |
      {{ define "$TEMPLATE" }}
      ...
      {{ end }}
  - pattern: <form action="...">...</form>
  message: Semgrep found a match
  languages: [generic]
  severity: WARNING
```

**Expected behavior**

I think it should match on both `<form>`s in the following code, but it only matches on the second one. Note that the second define-block doesn't contain a "/".

```
{{ define "abc/xyz" }}
<!-- ruleid: form-action -->
<form action="mno"></form>
{{ end }}

{{ define "xyz" }}
<!-- ruleid: form-action -->
<form action="mno"></form>
{{ end }}
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Tested on https://semgrep.dev/playground

I found the original variant of this locally with semgrep cli 0.85.0, installed via pip w/ python 3.9.2 on debian bullseye.

**Use case**
I'm hoping to use this for matching against multiple patterns in Go html templates.
