### ISSUE TITLE
go multiple return value matching

### ISSUE THREAD

**Issue by bstpierre** [semgrep/semgrep#4896]
**Describe the bug**
Patterns for Go multiple return values match more strictly than the argument list, which is confusing.

**To Reproduce**
Try to match any Go function that has `error` in the return type list. All six of these functions should match:

```
func a(b int) error { return nil }
func b() (int, error) { return 0, nil }
func c() (error, int) { return nil, 0 }
func d() (float64, error) { return 0.0, nil }
func e() (float64, error, string) { return 0.0, nil, "" }
func f() (float64, error, string, int) { return 0.0, nil, "", 0 }
```

It seems like this should match: `pattern: func $F(...) (..., error, ...) {...}` but it doesn't. (It apparently only matches a function with exactly three return values, where the center value is type `error` -- function `e` above.)

I thought at first that this more complex rule would be a workaround, but it's not because it doesn't match function `f` above:

```
rules:
- id: error-multiple-return
  pattern-either:
    - pattern: func $F(...) error {...}
    - pattern: func $F(...) (..., error) {...}
    - pattern: func $F(...) (error, ...) {...}
    - pattern: func $F(...) (..., error, ...) {...}
  message: Semgrep found a match
  languages: [go]
  severity: WARNING
```

Adding another pattern with another `, ...` on the end matches `f` but I was hoping for the flexibility described below.

**Expected behavior**
I'm basing my expected behavior on how argument matching works, given this rule:

```
rules:
- id: error-args
  pattern: func $F(..., $X error, ...) {...}
  message: Semgrep found a match
  languages: [go]
  severity: WARNING
```

and this test:

```
// ok: error-args
func test1(x int) { }
// ruleid: error-args
func test2(err error) { }
// ruleid: error-args
func test3(err error, a int) { }
// ruleid: error-args
func test4(a int, err error, b int) { }
// ok: error-args
func test5() { }
```

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Tested on semgrep.dev

I found the original variant of this locally with semgrep cli 0.85.0, installed via pip w/ python 3.9.2 on debian bullseye.

**Use case**
Enforcing a rule that certain functions should not return error.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1042/go-multiple-return-value-matching.

**Comment by bstpierre** [comment]
This attempt at a workaround:

```
rules:
- id: error-multiple-return
  patterns:
  - pattern: func $F(...) $RET {...}
  - metavariable-pattern:
      metavariable: $RET
      pattern-regex: error
  message: Semgrep found a match
  languages: [go]
  severity: WARNING
```

doesn't work because semgrep throws an error:

```
{"code":2,"level":"warn","message":"[WARN] Semgrep Core — Internal matching error\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nWhen running error-multiple-return on __semgrep-internal__benchmark-target__.go: metavariable-pattern failed because $RET does not bind to a sub-program, please check your rule\n","path":"__semgrep-internal__benchmark-target__.go","rule_id":"error-multiple-return","type":"Internal matching error"}
{"code":2,"level":"warn","message":"[WARN] Semgrep Core — Internal matching error\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nWhen running error-multiple-return on target.go: metavariable-pattern failed because $RET does not bind to a sub-program, please check your rule\n","path":"target.go","rule_id":"error-multiple-return","type":"Internal matching error"}
```
