### ISSUE TITLE
Tests with generic language and double brackets cause failure error outputs

### ISSUE THREAD

**Issue by mattbrandman** [semgrep/semgrep#4906]
**Describe the bug**
When a user has a generic rule and the test case has double brackets in it, failure of the test case will return an incorrect error

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
https://semgrep.dev/s/mattbrandman:test

setup the rule and test file in appropriate directories according to test documentation then run the tests the error will be
`Failing due to rule id mismatch. There is a test denoted with 'ruleid: <rule name>' where the rule name does not exist or is not expected in the test file.`

This works in playground but errors in the testing setup

**Expected behavior**
Output showing the incorrect test 

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Local Build

**Use case**
What will fixing this bug enable for you?
We will be able to more thoroughly test our semgrep rules and not worry that they aren't working

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1047/tests-with-generic-language-and-double-brackets-cause-failure-error.

**Comment by mjambon** [comment]
Sorry, I'm looking into this only now. The Semgrep Playground no longer supports multi-rule files. I'll see if I can recover it. Meanwhile, it's tagged as "need-more-info" because I don't see what the issue is. Right now, I can only access the first rule which is:
```yaml
rules:
  - id: rule1
    message: Nunjucks template uses safe filter within script tag
    languages:
      - generic
    metadata:
      securityRequirement: SREX-316
      vulnerabilityType: Injection
      severity: Medium
    severity: ERROR
    pattern: |
      <script>... {{... | safe}}
```
Target code:
```
ruleid: test123
<script> window.__MEMBERS__ = {{ members | dump | safe }}; </script>
# ruleid: ahh
{{ test | sxfe }}
```
https://semgrep.dev/s/OoQL

![image](https://user-images.githubusercontent.com/343265/236971669-34a51461-f738-4ce7-821f-4b23e1910228.png)

**Comment by mjambon** [comment]
My colleagues provided the original rule which is:
```yaml
---
rules:
- id: rule1
  message: Nunjucks template uses safe filter within script tag
  languages:
  - generic
  metadata:
    securityRequirement: SREX-316
    vulnerabilityType: Injection
    severity: Medium
  severity: ERROR
  pattern: "<script>... {{... | safe}}\n"
- id: rule2
  message: Nunjucks template uses safe filter
  languages:
  - generic
  metadata:
    securityRequirement: SREX-316
    vulnerabilityType: Injection
    severity: Medium
  severity: INFO
  patterns:
  - pattern: "{{... | safe}}\n"
  - pattern-not-inside: "<script>... {{... | safe}}\n"
```

* Here's the link for rule2: https://semgrep.dev/s/vb6Y
* The link for rule1 was: https://semgrep.dev/s/OoQL

The screenshot for rule 2 shows 0 match:

![image](https://user-images.githubusercontent.com/343265/236972918-795c0ad5-18e2-4e17-a40f-9cb8254f067b.png)

The results in the playground for rule1 and for rule2 as expected.
