### ISSUE TITLE
[Fix] Metavariable ellipsis not correctly copied with autofix

### ISSUE THREAD

**Issue by 0xDC0DE** [semgrep/semgrep#4963]
**Describe the bug**
A rather simple, straightforward rule results in weird behaviour after applying the autofix:

```
rules:
- id: fix-named-ellipses-commas
  pattern: make_transaction($...BEFORE, secure=False, $...AFTER)
  message: Make sure secure is set to True
  languages: [python]
  severity: WARNING
  fix: make_transaction($...BEFORE, secure=True, $...AFTER)
```

```
make_transaction(transaction = "transaction", secure=False, commit=False)
```
Is corrected to
```
make_transaction(, secure=True, transaction = "transaction", secure=False, commit=False)
```

**To Reproduce**
https://semgrep.dev/s/pieterdc1:autofix-incorrect

**Expected behavior**
This feels like a straightforward autofix.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
