### ISSUE TITLE
[Fix] Metavariable ellipses sometimes match nothing. In a fix it can be necessary to know this.

### ISSUE THREAD

**Issue by 0xDC0DE** [semgrep/semgrep#4964]
**Is your feature request related to a problem? Please describe.**
Sometimes metavariable ellipses (`$...ARGS`) match an empty string. When writing a fix, this is necessary to know. For example, when matching (optional) arguments in a function call, when an empty string is matched, a comma less is needed.

Example rule where this is the case:
https://semgrep.dev/s/pieterdc1:autofix-metavariable-ellipses

The rule 
```
rules:
- id: fix-named-ellipses-commas
  pattern: make_transaction($...BEFORE, secure=False, $...AFTER)
  message: Make sure secure is set to True
  languages: [python]
  severity: WARNING
  fix: make_transaction($...BEFORE, secure=True, $...AFTER)
```

Matches both test cases here:
```
# ruleid: transaction
make_transaction(transaction = "transaction", secure=False)

# ruleid: transaction
make_transaction(transaction = "transaction", secure=False, commit=False)
```

However, to write a correct fix, it is necessary to know whether `$...AFTER` matches an empty string or not. If it matches an empty string, the fix should not have a comma after the `secure=True` argument.

**Describe the solution you'd like**
??? I am not sure, the best solution would be to automagically remove the comma if the metavariable matches an empty string. A fix should always result in syntactically correct code.

**Describe alternatives you've considered**
Writing two rules, one where there are no arguments following the argument we want to match, and one where there are arguments following the argument we want to match.

**Use case**
Better fixes for our users.
