### ISSUE TITLE
Support Meta information in rules

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#498]
**Is your feature request related to a problem? Please describe.**

Currently any additional fields to the rule gammer is not allowed. It would be nice to support that. This is helpful for SAST tools to take advantage of extra meta.
For example
```
rules:
    - id: hardcoded-jwt-key
      pattern: |-
        var $X = []byte("...")
        ...
        $TOKEN := jwt.NewWithClaims(...)
        ...
        $Y := $TOKEN.SignedString($X)
      message: "JWT token is hardcoded"
      languages: [go]
      severity: WARNING
      meta-description: "Tokens should not be hardcoded in source."
      meta-owasp: "A3: Sensitive Data Exposure"
      meta-cwe: "CWE-798: Use of Hard-coded Credentials"
      meta-xxxx: xxxxx
```
or something like
```
rules:
  - id hardcoded-jwt-key
    meta:
        cve: "CWE-798: Use of Hard-coded Credentials"
        owasp:  "A3: Sensitive Data Exposure"
```
