### ISSUE TITLE
PHP - Function arguments with default values not correctly tracked

### ISSUE THREAD

**Issue by federicodotta** [semgrep/semgrep#5021]
**Describe the bug**
When a default value is assigned to a function argument (es. "function test29($test = 'public')"), the parameter is not tracked correctly in the code.

As an example, using the following rule:

```yaml
rules:
- id: test
  languages:
    - php
  severity: ERROR
  message: test
  patterns:
    - pattern-inside: |
        function $FUNC(...,$PAR,...) {
          ...
        }     
    - pattern: $AAAA . <... $PAR ...> . $BBBB;
```
this code does not match:
```php
    public static function testWorking($aaa, $shortName = "public"): array
    {
        $sql = "TEST" . $shortName . "TEST2";
    }
```
while this one match correctly:
```php
    public static function testWorking($aaa, $shortName): array
    {
        $sql = "TEST" . $shortName . "TEST2";
    }
```

**To Reproduce**
The following example shows the issue: https://semgrep.dev/s/ALop

**Expected behavior**
The tracking should work as expected also if the argument has a default value.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
