### ISSUE TITLE
increase the scope of constant propagation to the whole file (with symbolic_propagation: true)

### ISSUE THREAD

**Issue by ttttmr** [semgrep/semgrep#5046]
[Original title: javascript function variable propagation and line matching]

https://semgrep.dev/s/7Qxk

```yaml
rules:
- id: bad-call
  patterns:
    - pattern-either:
      - pattern: bad(...)
  message: Found call to 'bad'
  languages: [js]
  severity: WARNING
```

```js
function bad(s)
   return s

let b1=bad

b1("1")
bad("3")
```

I'm a beginner with semgrep and I think this should match to the b1 function call

so i modify the rules

https://semgrep.dev/s/L2oG

```yaml
rules:
- id: bad-call
  patterns:
    - pattern-either:
      - pattern: bad(...)
      - pattern: |
          $X=bad
          ...
          $X(...)
  message: Found call to 'bad'
  languages: [js]
  severity: WARNING
```

Successfully matched, but it shows matching to line 4 and 7, I want to match to line 6 and 7

Or is there any rule writing to achieve this match, please tell me, thank you

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1187/javascript-function-variable-propagation-and-line-matching.

**Comment by ttttmr** [comment]
I tried a new rule and it got stuck

```yaml
rules:
- id: bad-call
  patterns:
    - pattern-either:
      - pattern: bad(...)
      - pattern:
        - pattern-inside: |
            $X=bad
            ...
        - pattern: $X(...)
  message: Found call to 'bad'
  languages: [js]
  severity: WARNING
```
