### ISSUE TITLE
javascript function variable propagation and line matching

### ISSUE THREAD

**Issue by ttttmr** [semgrep/semgrep#5047]
https://semgrep.dev/s/7Qxk

```yaml
rules:
- id: bad-call
  patterns:
    - pattern-either:
      - pattern: bad(...)
  message: Found call to 'bad'
  languages: [js]
  severity: WARNING
```

```js
function bad(s)
   return s

let b1=bad

b1("1")
bad("3")
```

I'm a beginner with semgrep and I think this should match to the b1 function call

so i modify the rules

https://semgrep.dev/s/L2oG

```yaml
rules:
- id: bad-call
  patterns:
    - pattern-either:
      - pattern: bad(...)
      - pattern: |
          $X=bad
          ...
          $X(...)
  message: Found call to 'bad'
  languages: [js]
  severity: WARNING
```

Successfully matched, but it shows matching to line 4 and 7, I want to match to line 6 and 7

Or is there any rule writing to achieve this match, please tell me, thank you
