### ISSUE TITLE
Combining taint mode and join mode

### ISSUE THREAD

**Issue by ttttmr** [semgrep/semgrep#5062]
**Is your feature request related to a problem? Please describe.**
The taint mode is very convenient, I define some sources and sinks, and can find some bugs
For example, there are a lot of user input sources, sink is the eval function
Then I find a new sink, such as innerhtml, I want to reuse the source written above, in taint mode I can only copy it manually
Or use join mode to reuse rules, but not taint mode

**Describe the solution you'd like**
Convenience of taking rules in taint mode

**Describe alternatives you've considered**
use taint mode, copy it manually

**Use case**
```yaml
rules:
- id: xss
  mode: join-taint
  join:
    refs:
      - rule: location.yaml
        as: user-input1
      - rule: dom-input.yaml
        as: user-input2
      - rule: write-html.yaml
        as: sink1
      - rule: jq-write-html.yaml
        as: sink2
  taint-sources:
    - user-input1.$V1
    - user-input2.$V2
  taint-sink:
    - sink1.$P1
    - sink2.$P2
  message: XSS! $taint-sources is rendered
    unsafely in $taint-sink.
  severity: ERROR
```

**Additional context**
