### ISSUE TITLE
`metavariable-pattern`+`language: L` should work on arbitrary code

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#5063]
This requires that `$MVAR` binds to a string, otherwise it simply evaluates to false:
```yaml
    - metavariable-pattern:
        metavariable: $MVAR
        language: LANG
        pattern: PAT
```

So this does not work: https://semgrep.dev/s/JwJZ

We could actually obtain the exact code matched by `$MVAR` (using location info) and re-interpret it as LANG.

Unfortunately I don't have a good use case for this yet, it's just easy to implement and seems rather reasonable behavior.
