### ISSUE TITLE
Better handle `metavariable-pattern` when nested language is the same as current language

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#5064]
Consider:
```yaml
  - id: test
    message: Test
    languages:
      - python
    patterns:
    - pattern: foo($X)
    - metavariable-pattern:
        metavariable: $X
        pattern: bar + ...
    severity: WARNING
```

If we simply add `language: python` to `metavariable-pattern` this no longer works: https://semgrep.dev/s/5Z3l

The reason is that when using a nested language, `$X` is required to bind to a string (see #5063).
 
But this can be confusing for some users, see https://r2c-community.slack.com/archives/C018NJRRCJ0/p1650095652642469.

We could either have a meta checking rule that flags these cases, or perhaps even better (?) would be that Semgrep simply ignores the nested `language: LANG` when LANG is the same as the current language.
