### ISSUE TITLE
OCaml Matches are leaving a hanging closing-parenthesis, breaking autofix

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [semgrep/semgrep#5078]
**Describe the bug**
When matching a simple construct like `function_name $X`, if there's a parenthetical subexpression in the match, semgrep leaves the *closing* paren of that match excluded.

```yaml
rules:
   - id: replace-function
     languages: [ocaml]
     pattern: somefunc $X
     fix: Lwt.return_error (somefunc ($X))
```

```ocaml
somefunc (`Blah 123)
```

Produces this (syntactically invalid 😓):

```ocaml
Lwt.return_error (somefunc (`Blah 123)))
```

**To Reproduce**
https://semgrep.dev/s/YNko

**Screenshots**
<img width="396" alt="Screen Shot 2022-04-22 at 4 24 03 PM" src="https://user-images.githubusercontent.com/200/164796779-2fa4281f-ff5c-447b-b076-bdae54571f06.png">

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
`pip3 install semgrep`
