### ISSUE TITLE
Open statement existing at all in a rule causes a parse-error

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [semgrep/semgrep#5079]
**Describe the bug**
I'm unable to match on `open` statements at all. (Unrelated to #5076.)

```yaml
rules:
- id: replace-function
  pattern: open Lwt
  languages: [ocaml]
```

```ocaml
open Lwt

some_func
```

**To Reproduce**
https://semgrep.dev/s/Obl2

**Expected behavior**
The first line of the example, `open Lwt`, would be matched.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
We're attempting to mitigate the fallout from #5076; in particular, a desire to minimally scope any autofix replacements — that is, for example, we don't want `Apicore.Container.Result.ContextfulError` dumped into the hundreds of modules that already contain `open Apicore.Container.Result`:

```yaml
rules:
- id: replace-function-under-open
  patterns:
    - pattern: error $X
    - pattern-inside: |
        open Apicore.Container.Result
        ...
  fix: ContextfulError $X
  languages: [ocaml]
- id: replace-function-without-open
  patterns:
    - pattern: error $X
  fix: Apicore.Container.Result.ContextfulError $X
  languages: [ocaml]
```
