### ISSUE TITLE
semgrep-core does not report parse errors for subsequent languages

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#5109]
**Describe the bug**
Semgrep-core is only reporting parse errors on the first language specified in a rule file.
After https://github.com/returntocorp/semgrep/pull/5108, semgrep will also exhibit this behavior

**To Reproduce**
```
rules:
- id: hardcoded-secrets-lang
  patterns:
    - pattern-either:
      - pattern: |
          accessToken: "$A"
      - pattern: config.secret_key = $A
      - pattern: |
          AWS_SECRET_ACCESS_KEY: "$A"
  message: Don't hardcoded secrets in code. Use Vault instead.
  languages: [ruby, ts, js]
  severity: WARNING
```
reports the ruby parse error but moving ruby anywhere else has semgrep-core complete without complaint

**Expected behavior**
semgrep-core should report the ruby parse error or at least let user know they should not be mixing ts and ruby rules?

Otherwise we will silently not have coverage on subsequent languages

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
