### ISSUE TITLE
generic mode doesn't correctly identify hardcoded secrets in YAML

### ISSUE THREAD

**Issue by anshumanbh** [semgrep/semgrep#5110]
**Describe the bug**
Try this rule:

```
rules:
- id: hardcoded-secrets-lang
  patterns:
    - pattern-either:
      - pattern: |
          accessToken: "$A"
      - pattern: CONTENTFUL_DELIVERY_API_ACCESS_TOKEN=$A
      - pattern: config.secret_key = $A
      - pattern: |
          AWS_SECRET_ACCESS_KEY: "$A"
      - pattern: |
          AWS_SECRET_ACCESS_KEY=$A
    - metavariable-analysis:
        analyzer: entropy
        metavariable: $A
  message: Don't hardcoded secrets in code. Use Vault instead.
  languages:
   - generic
  severity: WARNING
```

against this file:

```
apiVersion: v1
kind: Secret
metadata:
  name: secrets-f
  namespace: f
  labels:
    app: secrets-f
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "AKIATESTTESTTEST"
  AWS_ROLE: "test-role"
  AWS_SECRET_ACCESS_KEY: "GpBuHhDM.i6qJgx*9rXQ7*K@"
```

Notice that it doesn't tag the hardcoded secret key.
Now, change the language above from `generic` to `yaml` and notice that it tags it fine.
This is an example of how generic doesn't work and I have to specify the language of the file..

**To Reproduce**
See above

**Expected behavior**
Running the above rule with the language set to `generic` should have flagged the secret key being hardcoded in the yaml file. 

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep CLI 0.90.0

**Use case**
This will allow us to write rules to find custom hardcoded secrets in our codebase
