### ISSUE TITLE
Typescript issue when matching an imported constant

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#5120]
**Describe the bug**

Given this code

```typescript
import { CONST } from '../../../path/to/const';

console.log(CONST)
```

and this rule (EDIT: the `patterns` -> `pattern` structure is useless here and a single `pattern` would work, I got there from editing another rule I was working on...)

```yaml
rules:
- id: two_matches_should_be_one
  patterns:
    - pattern: "console.log($X)"
  message: "$X matched"
  languages:
    - ts
  severity: WARNING
```

I would expect a single match. However it matches twice with the following messages

- `CONST matched`
- `CONST } from '../../../path/to/const' matched`

**To Reproduce**
https://semgrep.dev/s/jj4Z

**Expected behavior**

The match that has part of the const's import shouldn't be there

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Reduce noise in results
