### ISSUE TITLE
Be more tolerant when parsing YAML

### ISSUE THREAD

**Issue by anshumanbh** [semgrep/semgrep#5132]
**Describe the bug**
Try running the rule below:

```
id: hardcoded-secrets-yaml
patterns:
  - pattern-either:
      - pattern: |
          AWS_SECRET_ACCESS_KEY: "$A"
      - pattern: |
          KICKBOX_API_KEY: $A
  - metavariable-analysis:
      analyzer: entropy
      metavariable: $A
message: Don't hardcoded secrets in code. Use Vault instead.
languages:
  - yaml
severity: WARNING
```

against the following YAML:

```
PGUSER: <%= ENV['PGUSER'] %>
PGPASSWORD: <%= ENV['PGPASSWORD'] %>
KICKBOX_API_KEY: 'test_1698418435234634563456ewrtert463456b9'
AWS_SECRET_ACCESS_KEY: 'y+eOOZbV63fasddfg3e44SRLF1'


  <% if !'assets:precompile'.in? Rake.application.top_level_tasks %>
  # Launch Darkly
LAUNCH_DARKLY_SECRET_KEY: 'sdk-asdf2-2345sdfg34'

  <% if ENV['IS_DOCKER'] == 'true' %>
REDIS_URL: redis://redis:6379
CYPRESS_INSTALL_BINARY: 0
DISABLE_SPRING: 1
PIPELINE_ENABLED: 1
PGHOST: db
  <% else %>
REDIS_URL: 'redis://localhost:6379'
  <% end %>
  <% end %>

```

Notice the error:

```
[WARN] Other syntax error at line target.yaml:4:
 (approximate error location; error nearby after) error calling parser: did not find expected key character 0 position 0 returned: 0Engine(InternalError)
```

Now, run the same rule against the following YAML (see commented out section):

```
PGUSER: <%= ENV['PGUSER'] %>
PGPASSWORD: <%= ENV['PGPASSWORD'] %>
KICKBOX_API_KEY: 'test_1698418435234634563456ewrtert463456b9'
AWS_SECRET_ACCESS_KEY: 'y+eOOZbV63fasddfg3e44SRLF1'


#   <% if !'assets:precompile'.in? Rake.application.top_level_tasks %>
#   # Launch Darkly
# LAUNCH_DARKLY_SECRET_KEY: 'sdk-asdf2-2345sdfg34'

#   <% if ENV['IS_DOCKER'] == 'true' %>
# REDIS_URL: redis://redis:6379
# CYPRESS_INSTALL_BINARY: 0
# DISABLE_SPRING: 1
# PIPELINE_ENABLED: 1
# PGHOST: db
#   <% else %>
# REDIS_URL: 'redis://localhost:6379'
#   <% end %>
#   <% end %>
```

Notice that it correctly flags the hardcoded secrets. 

I believe its a valid YAML so the Semgrep parser should continue to find patterns despite of failures. 

**To Reproduce**
See above

**Expected behavior**
In both cases listed above, the Semgrep parser should have flagged the secrets in the YAML.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
This will allow me to write more rules for YAML files.
