### ISSUE TITLE
Generic xml pattern-match error with numbers

### ISSUE THREAD

**Issue by fabian-zeindl-oebb** [semgrep/semgrep#5200]
This rule should match but doesn't:

Rule: 
```
rules:
  - id: outdated-java-version
    message: ""
    languages: ["generic"]
    severity: ERROR
    patterns:
      - pattern-inside: <maven.compiler.source>...</maven.compiler.source>
      - pattern-not: "11"
    paths:
      include:
        - "*.xml"
```

Test:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <properties>
        <!-- ruleid: outdated-java-version -->
        <maven.compiler.source>1.8</maven.compiler.source>

        <!-- ok: outdated-java-version -->
        <maven.compiler.source>11</maven.compiler.source>
    </properties>
</project>
```
