### ISSUE TITLE
semgrep.dev bug report patterns-either.patterns.metavariable-pattern crash

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#5202]
https://semgrep.dev/s/6Be6

Get a rule yaml schema validation error on trying to have 2 `metavariable-patterns`  under a `pattern-either`. Trying to cheat it by putting a `patterns` in between causes a crash.

## Original Code -- not a valid rule apparently
```yaml
      - pattern-either:
            - metavariable-pattern:
                metavariable: $PATH1
                patterns:
                  - pattern-not: |
                      "..."
            - metavariable-pattern:
                metavariable: $PATH2
                patterns:
                  - pattern-not: |
                      "..."
```

## Attempted Code -- Causes Crash
```yaml
      - pattern-either:
          - patterns:
              - metavariable-pattern:
                  metavariable: $PATH1
                  patterns:
                    - pattern-not: |
                        "..."
          - patterns:
              - metavariable-pattern:
                  metavariable: $PATH2
                  patterns:
                    - pattern-not: |
                        "..."
```

## Crash
```json
{"code":2,"level":"error","message":"[ERROR] Fatal error at line __semgrep-internal__benchmark-target__.java:1:\n (Failure \"empty And; no positive terms in And\")\n====[ BEGIN error trace ]====\nRaised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 904, characters 22-68\nCalled from Common.fast_map in file \"src/pfff/commons/Common.ml\", line 430, characters 16-19\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 860, characters 6-57\nCalled from Common.fast_map in file \"src/pfff/commons/Common.ml\", line 434, characters 16-19\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 884, characters 18-67\nCalled from Match_search_rules.matches_of_formula in file \"src/engine/Match_search_rules.ml\", line 1038, characters 21-61\nCalled from Match_search_rules.check_rule in file \"src/engine/Match_search_rules.ml\", line 1053, characters 4-62\nCalled from Common.set_timeout in file \"src/pfff/commons/Common.ml\", line 1429, characters 12-16\nRe-raised at Common.set_timeout in file \"src/pfff/commons/Common.ml\", line 1446, characters 6-13\nCalled from Match_rules.timeout_function in file \"src/engine/Match_rules.ml\", line 48, characters 4-73\nCalled from Match_rules.check.(fun) in file \"src/engine/Match_rules.ml\", line 108, characters 19-792\nCalled from Common.partition_either.part_either in file \"src/pfff/commons/Common.ml\", line 964, characters 15-18\nCalled from Match_rules.check in file \"src/engine/Match_rules.ml\", line 88, characters 4-1023\nCalled from Run_semgrep.semgrep_with_rules.(fun) in file \"src/runner/Run_semgrep.ml\", line 499, characters 13-265\nCalled from Run_semgrep.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file \"src/runner/Run_semgrep.ml\", line 310, characters 21-29\nCalled from Stdlib__fun.protect in file \"fun.ml\", line 33, characters 8-15\nRe-raised at Stdlib__fun.protect in file \"fun.ml\", line 38, characters 6-52\nCalled from Memory_limit.run_with_memory_limit in file \"src/system/Memory_limit.ml\", line 83, characters 6-62\nCalled from Run_semgrep.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file \"src/runner/Run_semgrep.ml\", line 301, characters 17-1023\n=====[ END error trace ]=====\n","path":"__semgrep-internal__benchmark-target__.java","type":"Fatal error"}
{"code":2,"level":"error","message":"[ERROR] Fatal error at line target.java:1:\n (Failure \"empty And; no positive terms in And\")\n====[ BEGIN error trace ]====\nRaised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 904, characters 22-68\nCalled from Common.fast_map in file \"src/pfff/commons/Common.ml\", line 430, characters 16-19\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 860, characters 6-57\nCalled from Common.fast_map in file \"src/pfff/commons/Common.ml\", line 434, characters 16-19\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 884, characters 18-67\nCalled from Match_search_rules.matches_of_formula in file \"src/engine/Match_search_rules.ml\", line 1038, characters 21-61\nCalled from Match_search_rules.check_rule in file \"src/engine/Match_search_rules.ml\", line 1053, characters 4-62\nCalled from Common.set_timeout in file \"src/pfff/commons/Common.ml\", line 1429, characters 12-16\nRe-raised at Common.set_timeout in file \"src/pfff/commons/Common.ml\", line 1446, characters 6-13\nCalled from Match_rules.timeout_function in file \"src/engine/Match_rules.ml\", line 48, characters 4-73\nCalled from Match_rules.check.(fun) in file \"src/engine/Match_rules.ml\", line 108, characters 19-792\nCalled from Common.partition_either.part_either in file \"src/pfff/commons/Common.ml\", line 964, characters 15-18\nCalled from Match_rules.check in file \"src/engine/Match_rules.ml\", line 88, characters 4-1023\nCalled from Run_semgrep.semgrep_with_rules.(fun) in file \"src/runner/Run_semgrep.ml\", line 499, characters 13-265\nCalled from Run_semgrep.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file \"src/runner/Run_semgrep.ml\", line 310, characters 21-29\nCalled from Stdlib__fun.protect in file \"fun.ml\", line 33, characters 8-15\nRe-raised at Stdlib__fun.protect in file \"fun.ml\", line 38, characters 6-52\nCalled from Memory_limit.run_with_memory_limit in file \"src/system/Memory_limit.ml\", line 83, characters 6-62\nCalled from Run_semgrep.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file \"src/runner/Run_semgrep.ml\", line 301, characters 17-1023\n=====[ END error trace ]=====\n","path":"target.java","type":"Fatal error"}
```
