### ISSUE TITLE
regex interpretation crashes when searching for curly brackets in yaml (maybe other places too)

### ISSUE THREAD

**Issue by sfc-gh-jmakinen** [semgrep/semgrep#5216]
**Describe the bug**
I wasn't able to use regex to search for yaml values matching a pattern including curly brackets, even when escaped. I get a stack trace saying perl has hit a memory limit.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
https://semgrep.dev/s/AzOL
```yaml
rules:
  - id: looking for templated commands
    patterns:
      - pattern: |-
          command: "=~/.*\x7b.*/"
         
    message: oof that feels like a bug
    languages:
      - yaml
    severity: ERROR
```

**Expected behavior**
finding all yaml `command` fields with a `{` in their value

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
official binary and semgrep.dev

**Use case**
What will fixing this bug enable for you?
I am fine, because I don't get this bug when I search for closing curly brackets, so my use-case is met. Just feels like a bug is all
