### ISSUE TITLE
Scala: metavariable-regex does not work for import statements

### ISSUE THREAD

**Issue by dpnishant** [semgrep/semgrep#5219]
**Describe the bug**
Given a sample Scala as shown below:
```scala
import javax.servlet.{Filter, FilterChain, ServletRequest, ServletResponse}

class SsoFilter(
                 @Value("${sitesso.cookie.secure}") siteSsoCookieSecure: Boolean
               ) extends Filter {
                   override def doFilter(request: ServletRequest, response: ServletResponse, chain: FilterChain): Unit = {
                       val context = new ServletRequestContext(request.asInstanceOf[HttpServletRequest], response.asInstanceOf[HttpServletResponse])
                   }
               }
```
the following rule throws `[ERROR] Pattern parse error in rule scala-bug:
 Invalid pattern for ScalaEngine(InternalError)`
```yaml
id: scala-bug
severity: ERROR
message: "HTTP Request Filter: $BASE_CLASS->$FILTER_METHOD"
languages: [scala]
patterns:
- metavariable-regex:
      metavariable: $PACKAGE
      regex: (?:org\.springframework\.web\.filter\.(?:\*|OncePerRequestFilter)|javax\.ws\.rs\.container\.(?:\*|ContainerRequestFilter)|javax\.servlet\.(?:\*|Filter)|org\.springframework\.web\.servlet\.(?:\*|HandlerInterceptor))
- pattern: import $PACKAGE
```
However the following rule does work 
```yaml
id: scala-bug
severity: ERROR
message: "HTTP Request Filter: $BASE_CLASS->$FILTER_METHOD"
languages: [scala]
patterns:
- metavariable-regex:
    metavariable: $FILTER_METHOD
    regex: ^(?:filter|doFilter)$
- metavariable-regex:
    metavariable: $BASE_CLASS
    regex: ^(?:ContainerRequestFilter|Filter)$
- pattern-either:
    - pattern: |
        class $CLASS_NAME(...) extends $BASE_CLASS {
        ...
        def $FILTER_METHOD(...): Unit = {
        ...
        }
        }
```
**To Reproduce**
Use this playground URL: https://semgrep.dev/playground/s/dpnishant:scala-bug reproduce the bug. Compare the result with this playground URL: https://semgrep.dev/playground/s/dpnishant:scala-http-filter

Interestingly the same pattern works in `Java` language example: https://semgrep.dev/playground/s/dpnishant:audit-java-http-filter

**Expected behavior**
metavariable-regex should ideally match patterns in the import statements too as it does elsewhere.

**Screenshots**
Not available. Please use the Playground URLs for validation.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Using semgrep 0.92.0 on macOS (via Homebrew)

**Use case**
Better semantic coverage for Scala language
