### ISSUE TITLE
pattern-not not returning expected results

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#5317]
**Describe the bug**

I'll start by saying that this is probably just me not understanding how `pattern-not` works / what its purpose is, but I thought that this would match only `bar2`  but it matches `foo(bar1)` as well:

Code:

```js
`abc${foo(bar1)}def${bar2}`
```

Rule

```yaml
rules:
- id: string-interpolation
  patterns:
    - pattern: |
        `...${$VAR}...`
    - pattern-not: |
        `...${foo($VAR)}...`
  message: $VAR matched
  languages: [js]
  severity: WARNING
```

In the event that this isn't how `pattern-not` is supposed to be used, I'm interested in knowing how I could achieve the same result. I thought of a metavariable regex but what I'd need is `metavariable-not-regex`

**To Reproduce**
https://semgrep.dev/s/5A3k

**Expected behavior**

I would have thought that things that match the `pattern-not` pattern would be filtered out

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
What will fixing this bug enable for you? Increased usefulness of semgrep

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1383/pattern-not-not-returning-expected-results. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by dee-see** [comment]
Oh I thought adding this would do it

```yaml
    - metavariable-pattern:
      metavariable: $VAR
      patterns:
        - pattern-not: "foo(...)"
```

but I'm getting this error

```json
{"message":"{'anyOf': [{'required': ['patterns']}, {'required': ['pattern-either']}, {'required': ['pattern-regex']}]} is not allowed for None\nin pattern ","spans":[{"config_start":{"line":1,"col":1},"config_end":{"line":17,"col":1},"config_path":[]}],"code":0,"level":"","type":"schema"}
```

and I have no idea what to make of that

EDIT: uuuuugggh it's just the indentation I needed 2 extra spaces. I hate YAML 🤦 Alright that mystery is resolved
