### ISSUE TITLE
inconsistent regex

### ISSUE THREAD

**Issue by infi-pc** [semgrep/semgrep#5380]
**Describe the bug**
regex behaves in different ways depending on where it is

**To Reproduce**
minimal test:
https://semgrep.dev/playground/s/infi-pc:minimal-test

more practical test:
https://semgrep.dev/playground/s/infi-pc:use-absolute-paths-for-routing-copy

**Expected behavior**
it should work the same way everywhere

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
I am getting confusing false positives because it behaves in an unexpected way.

![CleanShot 2022-06-01 at 15 54 01](https://user-images.githubusercontent.com/2264725/171421584-cc0922e5-4470-4c5f-8dc1-c5eb9f77ee6f.png)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1407/inconsistent-regex. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by emjin** [comment]
Looking at your minimal example, I believe what you mean is: https://semgrep.dev/playground/s/returntocorp:minimal-test-copy

The most relevant pattern for convenience:
```
patterns:
  - pattern-inside: myCall($X)
  - metavariable-pattern:
      metavariable: $X
      patterns:
        - pattern-regex: .*
        - pattern-not-regex: \$.*
```

What your pattern (copied below) actually does is:

```
patterns:
  - pattern-inside: myCall($X)
  - metavariable-regex:
      metavariable: $X
      regex: (.*)
  - pattern-not-regex: (\$.*)
```

1. match all the `myCall($X)` calls, including
- `myCall(xxx)`
- `myCall($xxx)`
- `(myCall(xxx))`
- `(myCall($xxx))`

2. filter out nothing, because the regex is `(.*)`

3. go through all the matches and filters them based on not-`(\$.*)`. This leaves only
- `myCall(xxx)`
- `myCall($xxx)`
- `(myCall(xxx))`

Frankly, I'm confused by this. I discovered it by wrapping the non-matching `myCall($xxx)` examples in parentheses, which made them match. It might be some subtleties with how our matching engine filters. I don't think this pattern is correct, but I don't know why it behaves like this.

The important part is: `pattern-not-regex` applies to regex to the entire match, not just what's inside. This can make it much harder to reason about. You probably want to filter on the metavariable, not the match, which you would do using `metavariable-pattern` as I described (or constructing a positive regex that expresses exactly what you want).

Hope this is helpful! Also, sorry if this was just an explanation of things you already knew and you were just noting the behavior that I was also confused by. For now, I'm going to close this since there's a workaround
