### ISSUE TITLE
Invalid SARIF: additionalProperty "fixes" exists in instance when not allowed

### ISSUE THREAD

**Issue by sim642** [semgrep/semgrep#5421]
**Describe the bug**
SARIF output produces invalid SARIF and thus fails to be uploaded to GitHub Security:
```
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
```

**To Reproduce**
I have the following GitHub actions workflow that fails with the above error at the upload step:
```yaml
jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run semgrep
        run: semgrep scan --sarif --output=semgrep.sarif

      - name: Upload SARIF file to GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
```

**Expected behavior**
SARIF file should be valid and successfully uploadable to GitHub Security, as it previously was.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker image in GitHub Actions.
