### ISSUE TITLE
Semgrep-core sending import resolution as metavariable value in python

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#5569]
**Describe the bug**
Semgrep reports two findings on the same match because the metavariables are different but the second metavariable value looks like in import resolution or similar

**To Reproduce**
Rule:
```
rules:
  - id: some-rule
    pattern: |
      $MODEL.query.$METHOD(...)
    message: >
      Any message that contains $MODEL
    severity: WARNING
    languages:
      - python
```
Target:
```
from foo.bar import Baz

class C:
    def f(self) -> None:
        Baz.query.filter()
```

https://semgrep.dev/s/02wq (Note two matches instead of 1)

![image](https://user-images.githubusercontent.com/343265/174389820-a5138be1-9a17-4ad6-8f38-8afcc235d9d5.png)

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep 0.98.0

**Use case**
Reduce duplicate rules
