### ISSUE TITLE
Semgrep CI not picking up the rules defined in the monitor board of semgrep App

### ISSUE THREAD

**Issue by offsecdawn** [semgrep/semgrep#5578]
**Describe the bug**
Semgrep ci is not picking up the rules defined in the "monitor board" of the semgrep app. Rather, it is connecting semgrep registry and execute the rules automatically. 
**To Reproduce**
1. Configure Semgrep App with GitHub repository
2. Copy below semgrep.yml code in GitHub action workflow
```
on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']

permissions:
    contents: read
    
name: Semgrep
jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
   ```
3. Go to semgrep app->ruleboard->add few rules explicitly from the registry
4. Go to github repo and trigger the githib action by editing and pushing any file

**Expected behavior**
Semgrep CI should pick the rules defined in the monitor board of semgrep app

**Screenshots**
1.Custom rules defined in the monitor board
![image](https://user-images.githubusercontent.com/51472598/174644241-cbe18a86-3ecc-485a-91f2-96b9cc19917a.png)

2.Below screenshot shows that rules are picked up directly from registry rather than from monitor board
![image](https://user-images.githubusercontent.com/51472598/174644155-30e60f99-55fd-4c4b-ad41-4f197edb0b64.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow

**Environment**
Semgrep dev environment 

**Use case**
- I can customise what rules should be executed as part of the CI cycle
