### ISSUE TITLE
[Solidity] Semgrep doesn't filter the regex properly on metavariables for modifiers

### ISSUE THREAD

**Issue by arbazkiraak** [semgrep/semgrep#5585]
**Describe the bug**

I ran into the following problem, I’m trying to match the pattern on `metavariable` with `metavariable-regex` , The problem is, it matches the pattern where it shouldn’t.

**To Reproduce**

[Steps to reproduce the behavior, ideally a link to https://semgrep.dev:](https://semgrep.dev/s/arbazkiraak:problem)

**Expected behavior**

```
function pause2() public override whenNotPaused {
  on = 1; // should only match
} 
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1540/semgrep-doesnt-filter-the-regex-properly-on-metavariables. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by arbazkiraak** [comment]
This looks like a bug, I had also raised the issue on r2c slack : 

https://r2c-community.slack.com/archives/CK86BJ5DW/p1655810859477049

**Comment by arbazkiraak** [comment]
@mjambon ,

As the modifiers are the core functionality for the solidity language. Is it possible for you to have a priority tag for this issue :)

**Comment by plotchy** [comment]
I ran into this same issue. It appears that if any modifiers in the function declaration pass the `pattern-not-regex`, you get a false match.

This doesn't fix the issue, but you can use a workaround:
```
id: pause-externally-available-1
patterns:
  - pattern-either:
      - pattern-inside: function $F(...) external {...} #no need for $MODS anymore
      - pattern-inside: function $F(...) public {...}   #no need for $MODS anymore
  - pattern: on = $X;
  - pattern-not-inside: function $F(...) onlyOwner {...} #unwrap metavar regex into pattern-not-inside 
  - pattern-not-inside: function $F(...) auth {...}      #unwrap metavar regex into pattern-not-inside 
  - metavariable-regex:
      metavariable: $F
      regex: (pause|unpause)
message: $F() is callable by anyone, without modifiers check
languages:
  - solidity
severity: WARNING
```

**Comment by Raz0r** [comment]
Also metavariables do not work to match inherited contracts in contract declarations:

```yaml
  patterns:
  - pattern: |
      contract $C is $I {
      ...
      }
  - metavariable-regex:
      metavariable: $I
      regex: IERC20
````

/cc @aryx
