### ISSUE TITLE
[solidity] semgrep doesn't match the pattern-either case, if metavariable pattern is defined

### ISSUE THREAD

**Issue by arbazkiraak** [semgrep/semgrep#5591]
**Describe the bug**

When writing a case using `pattern-either` which contains multiple `pattern-inside` and if `metavariable-pattern` is defined to match either case, then it will only match the case where metavariable exists for `pattern-inside`

**To Reproduce**

https://semgrep.dev/s/arbazkiraak:problem2

**Output**

```
{"code":2,"level":"warn","message":"[WARN] Internal matching error when running pause-externally-available-1 on target.sol:\n An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nmetavariable-pattern failed because $MOD is not in scope, please check your rule","path":"target.sol","rule_id":"pause-externally-available-1","type":"Internal matching error"}
```

**Expected behavior**

It should have matched both the cases, with modifier and without modifier functions.

**Comment by arbazkiraak** [comment]
This might be a expected behaviour or bug, Is there any workaround to match both the cases provided in the playground example above?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1547/[solidity]-semgrep-doesnt-match-the-pattern-either-case-if. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
I'm not sure if this is a bug or an unfixable limitation of how unbound metavariables are handled. Thanks for reporting it.

Meanwhile, for this particular example, the following workaround should work: https://semgrep.dev/s/returntocorp:pause-externally-available-workaround
```
patterns:
  - pattern: $A = $B;
  - pattern-inside: function $F(...) external {...}
  - pattern-not-inside: function $F(...) external nonAdmin {...}
```

**Comment by arbazkiraak** [comment]
Hey @mjambon,

Thanks for the prompt response on the issue,

Q1. I'm aware that this workaround will work, Is there any way to achieve the same using an `regex` instead of `pattern` to detect any function **modifier** that starts with `non` word?

https://semgrep.dev/s/arbazkiraak:problem2-2

Q2. The only way i can think of is using `metavariable-regex`,  but using `metavariable-regex` doesn't match the function which doesn't have contain a metavariable value. I really wish if there was a way to tell `metavariable-regex` to perform for `pattern-either` condition so that it could have match both the patterns.

Q3. I would like to know if there could some workaround to achieve the problem using a `regex` [or] this would be an unfixable limitation?

**Comment by mjambon** [comment]
Sorry for the delay! Here's what I got:
```yaml
id: pause-externally-available-mjambon
pattern-either:
  - patterns:
      - pattern-inside: function $F(...) external $MOD {...}
      - pattern: $A = $B
      - metavariable-regex:
          metavariable: $MOD
          regex: (only|something)
  - patterns:
      - pattern-inside: function $F(...) external {...}
      - pattern-not-inside: function $F(...) external $MOD {...}
      - pattern: $A = $B;
message: $F() is callable by anyone, without modifiers check
languages:
  - solidity
severity: WARNING
```
https://semgrep.dev/playground/s/returntocorp:pause-externally-available-mjambon

As you can see, `pattern-either` is used to completely separate the two cases. This involves some duplication which may or may not be tolerable depending on the use case.
