### ISSUE TITLE
with statement patterns match all with statements

### ISSUE THREAD

**Issue by spookylukey** [semgrep/semgrep#5634]
**Describe the bug**

For Python code, rules that match `with foo` will match any `with` statement, instead of specifically the expression in the `foo`.

For example, this rule:
```yaml
id: with-contextlib-supppress
severity: ERROR
languages:
  - python
patterns:
  - pattern: |
      with contextlib.suppress(Exception):
        ...
message: Test
```

Run on this code:
```python
import contextlib
import warnings

with warnings.catch_warnings():
    pass


with contextlib.suppress(Exception):
    pass

```
I expect only the last with statement to match, but both of them match:
```
Scanning 1 file.

Findings:

  semgrep_with_bug.py 
     specific-with
        Test

          6┆ pass
          ⋮┆----------------------------------------
         10┆ pass
```

Example in Playground: 
https://semgrep.dev/playground/s/spookylukey:with-contextlib-supppress

It appears that Semgrep only handles with statements that have an `as` clause. See also https://github.com/returntocorp/semgrep/issues/5635 which is related.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Latest Semgrep, version 0.98.0, including Playground.

**Use case**

Fixing this will fix being able to work with code containing `with` statements.
