### ISSUE TITLE
Expressions are not found within with statement "contents" if there is no `as` clause

### ISSUE THREAD

**Issue by spookylukey** [semgrep/semgrep#5635]
**Describe the bug**

Given the following rule:
```yaml
id: expression-in-with-statement-contents
severity: ERROR
languages:
  - python
patterns:
  - pattern: contextlib.suppress
message: Test
```

I expect all uses of the `contextlib.suppress` to be found. But in the following code, the first usage is found, but the second, in a `with` statement first line is not found:
```python

import contextlib

f = contextlib.suppress(Exception)

with contextlib.suppress(Exception):
    pass
```

See playground link: https://semgrep.dev/playground/s/spookylukey:expression-in-with-statement-contents

It seems that Semgrep only matches things when there is an `as` parameter, which is not needed in this case (and you wouldn't want to add, as it would  trigger other linter errors, like "local variable dummy is assigned to but never used").

See also https://github.com/returntocorp/semgrep/issues/5634

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Official binary of latest version, plus Playground

**Use case**
Any code using with statements that don't need an `as` parameter, which is quite a lot.
