### ISSUE TITLE
TS/JS - Issue with object deconstruction capturing incorrect values

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5638]
**Describe the bug**
The following pattern:
```
      - patterns:
          - pattern-either:
              - pattern-inside: |
                  { ..., $PROP,... } = this.props
          - focus-metavariable: $PROP
``` 
will match:
```
 const { copyright } = {};
```
**To Reproduce**
https://semgrep.dev/s/eEbb

**Expected behavior**
// ok Line should not match only items from this.props

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
Reduce false positives in taint mode rules.
