### ISSUE TITLE
Metavariable regex rule matching against YAML files fails to match after occurrence of unicode characters

### ISSUE THREAD

**Issue by aegarbutt-stripe** [semgrep/semgrep#5641]
**Describe the bug**
We've create a minimal test case that is supposed to match against all values that are set to "test":
```yaml
patterns:
  - pattern-either:
      - pattern: |
          $KEY: $VALUE
  - metavariable-regex:
      metavariable: $VALUE
      regex: test
```

It seems that after the first occurrence of a unicode character, the remaining matches are no longer flagged. One can move the unicode character from a value to a key, up or down in the target file, and can see that the boundary between where matches are correctly found and not found also shifts.

**To Reproduce**
A yaml file with unicode characters, but not using metavariable regex: https://semgrep.dev/playground/s/R4KO

A yaml file with unicode characters: https://semgrep.dev/playground/s/5e9A

A yaml file without unicode characters: https://semgrep.dev/playground/s/Gp4p

**Expected behavior**
All lines in the YAML file match, even after the unicode characters

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
We have a number of YAML files that contain unicode characters and this is diminishing our confidence in the accuracy of results using metavariable regex in those files.
