### ISSUE TITLE
Join rules ignore --no-git-ignore

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#5673]
**Describe the bug**
Join rules completely ignores the `--no-git-ignore` option

**To Reproduce**
- Copy the folder from https://github.com/returntocorp/semgrep/tree/develop/cli/tests/e2e/targets/join_rules
- Copy the join rule from https://github.com/returntocorp/semgrep/blob/develop/cli/tests/e2e/rules/join_rules/inline/inline-rules.yaml
- Run the rule against the folders:

```
% semgrep -c flask.yml join_rules 
Nothing to scan.

Scanning across multiple languages:
    <multilang> | 1 rule  × 14 files
         python | 2 rules ×  5 files

  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|19/19 tasks

Findings:

  join_rules/user-input-with-unescaped-extension/launch.htm.j2 
     flask-likely-xss
        Detected a XSS vulnerability: '$VAR' is rendered unsafely in '$TEMPLATE'.

          9┆ <li>person_name_full is <b>{{ person_name_full }}</b></li>


Ran 1 rule on 0 files: 1 finding.
```

- Now create a git repo from inside the `join_rules` folder, create a `.gitignore` with `user-input-with-unescaped-extension/` as content and scan again with the `--no-git-ignore`

```
% cd join_rules
% git init .
% echo 'user-input-with-unescaped-extension/' > .gitignore 
```

```
% semgrep -c flask.yml --no-git-ignore join_rules          
Nothing to scan.

Scanning across multiple languages:
    <multilang> | 1 rule  × 13 files
         python | 2 rules ×  4 files

  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|17/17 tasks


Ran 1 rule on 0 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
```

To double check that only join rules are affected, a search one can be created and ran against the folder as well:

```
rules:
- id: test
  message: test
  languages: [python]
  severity: INFO
  patterns:
    - pattern: return_error(...)

- id: flask-likely-xss
  mode: join
  join:
    rules:
      - id: user-input
        pattern: |
          $VAR = flask.request.$SOMETHING.get(...)
        languages: [python]
      - id: unescaped-extensions
        languages: [python]
        patterns:
        - pattern: |
            flask.render_template("$TEMPLATE", ..., $KWARG=$VAR, ...)
        - metavariable-regex:
            metavariable: '$TEMPLATE'
            regex: ".*(?<!html)$"
      - id: template-vars
        languages: [generic]
        pattern: |
          {{ $VAR }}
    on:
    - 'user-input.$VAR == unescaped-extensions.$VAR'
    - 'unescaped-extensions.$KWARG == template-vars.$VAR'
    - 'unescaped-extensions.$TEMPLATE < template-vars.path'
  message: |
    Detected a XSS vulnerability: '$VAR' is rendered
    unsafely in '$TEMPLATE'.
  severity: ERROR
```

```
% semgrep -c flask.yml --no-git-ignore join_rules
Scanning 5 files.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|5/5 tasks

Scanning across multiple languages:
    <multilang> | 1 rule  × 13 files
         python | 2 rules ×  4 files

  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|17/17 tasks

Findings:

  join_rules/user-input-with-unescaped-extension/views.py 
     test
        test

         28┆ return return_error('''Authentication error,
         29┆     please refresh and try again. If this error persists,
         30┆     please contact support.''')


Ran 2 rules on 5 files: 1 finding.
```

**Expected behavior**
The `--no-git-ignore` option should be considered when running join mode

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep 0.102.0 on MacOSX (Installed via Homebrew)
