### ISSUE TITLE
TS/JS Misleading behavior for object deconstruction pattern

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#5688]
**Describe the bug**

Describe the bug
The following pattern:

```
      - patterns:
          - pattern-either:
              - pattern-inside: |
                  { ..., $PROP,... } = this.props
          - focus-metavariable: $PROP
```

will match:

```
 const { copyright } = {};
```

**To Reproduce**
https://semgrep.dev/s/kPe7 Line 70

**Expected behavior**
In fact, the Javascript parser would fail to parse the pattern (even if the metavariable were replaced by a pattern) because it interprets `{...} = ...` as a block followed by an equality (which is a syntax error). Throwing an error here would thus be reasonable. Supporting the pattern would also be reasonable, since the meaning is ultimately unambiguous. Silently matching too much, as we do now, is not reasonable.

Internal: see https://linear.app/r2c/issue/PA-1574/tsjs-issue-with-object-deconstruction-capturing-incorrect-values for a discussion

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
