### ISSUE TITLE
Autofix should be aware of resolved names in matches

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#5756]
**Is your feature request related to a problem? Please describe.**
Autofix currently only seems to support Semgrep metavariables at the most basic level. If you want to do anything more complex, suddenly you need to write a complex regex, which almost negates the benefits of using Semgrep (so you don't have to worry about all that annoying regex syntax). You've created a tree when parsing the code to begin with, why can't we also use it when applying the fix? 

**Describe the solution you'd like**
The power of semgrep (patterns, ellipses, etc) available in "fix:" (then we might not need fix-regex)

**Describe alternatives you've considered**
keeping as is

**Use case**
Imagine the following, as one example:

```
- patterns:
      - pattern: load(...)
      - pattern-not: load(..., loader=SafeLoader, ...)
  - pattern: safe_load(..., loader=UnsafeLoader, ...)
```
So you want to write a fix that deals with load and safe_load. Maybe the fix would look like `safe_load(..., loader=SafeLoader, ...)`  just to cover all the cases. Now start thinking how complex the regex expression is to write that, dealing with whitespace around "loader=SafeLoader". It's bad.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1654/autofix-should-support-more-semgrep-patterns. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
You can use $...ARGS to name the ellipsis, so then they can be reused in the fix: part.
pattern: load($...ARGS)
fix: safe_load($...ARGS, loader=UnsafeLoader)

**Comment by efortuna** [comment]
@aryx I'm aware of `$...ARGS`. But as indicated in my first post, I don't want to autofix to suggest: `safe_load(..., loader=UnsafeLoader)` is a bad suggested fix. I want it to suggest: 

`safe_load(..., loader=SafeLoader)` <-- note what's passed in to `loader` there and how it's different

**Comment by emjin** [comment]
@efortuna I don't quite understand what's being matched in your example. Can you add a playground link?

**Comment by efortuna** [comment]
Yes, apologies for the delay. Okay, [here's a (completely different) example where I'd like autofix to have more Semgrep context than it actually does](https://semgrep.dev/playground/s/efortuna:unsafe_cerealizer_load-copy-2). Please ignore the original example I had, as that was not even a valid semgrep rule :-P 

So, in the rule in the playground link, Semgrep is smart enough to know that in the test code cerealizer=foo, so I can simply write my rules as `cerealizer.load(...)` and not have to worry about capturing the library name in a metavariable like `$CEREALIZER.load(...)`. HOWEVER, autofix seems to not know about these details. The autofix in that playground link is wrong. We want the autofix to contain whatever way the user imported the library -- be it `cerealizer.load` or `foo.load` or whatever! But unless we write the rule as:

```
patterns:
  - pattern-either:
      - pattern: $HALP_CANT_REPLACE.load($...ARGS)
      - pattern: $HALP_CANT_REPLACE.load($...ARGS, loader=...)
  - pattern-not: $HALP_CANT_REPLACE.$M(...,loader=cerealizer.SafeLoader)
```

Autofix won't know to the correct way to fix it. And that suggested rule ^ is less precise because now we can capture any `baz`.load() function rather than one in the cerealizer library.
It seems like semgrep has this information because it uses it in the original rule, is it no longer accessible when writing autofixes?
