### ISSUE TITLE
Cannot reference metavariables in rule message in join mode

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#5807]
**Describe the bug**

The rule's message cannot interpolate metavariables in join mode.
Messages are displayed verbatim, like `$VAR` rather than `foo`.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

Cannot save in playground due to schema validation errors.

```yaml
rules:
  - id: jsp-likely-xss
    mode: join
    severity: ERROR
    message: >-
      Detected a XSS vulnerability $VAR is rendered
      unsafely in $TEMPLATE.
    metadata:
      category: security
      technology:
        - html
        - javascript
    join:
      rules:
        - id: jsp-scriptlet-param
          languages: [generic]
          patterns:
            - pattern-inside: |
                <% ... %>
            - pattern: |
                $VAR = request.getParameter(...)
        - id: template-vars
          languages: [generic]
          patterns:
            - pattern-inside: |
                <%= ... %>
            - pattern: |
                $VAR
      on:
        - 'jsp-scriptlet-param.$VAR == template-vars.$VAR'
```

```html
<html>
<head>
<title>Tester</title>
<link rel='stylesheet' href='../../../style.css' type='text/css'>
</head>
<body>
<h1>View</h1>
<%
String foo = request.getParameter("bar");
%>
<a href="../../redirect.jsp?goto=<%=foo%>">Some Link</a>

<a href="../../redirect.jsp?goto=<%=2*fooo%>">Some Link</a>
<a href="../../redirect.jsp?goto=<%=bar*2%>">Some Link</a>

<a href="../../redirect.jsp?goto=<%=meow foo meow%>">Some Link</a>

<a href="../../redirect.jsp?goto=<%=notme%>">Some Link</a>
</body>
</html>
```

`semgrep -f jsp-likely-xss.yaml jsp-likely-xss.html`

**Expected behavior**

```
Nothing to scan.
Scanning 1 file with 2 <multilang> rules.

Findings:

  /jsp-likely-xss.html
     jsp-likely-xss
        Detected a XSS vulnerability foo is rendered unsafely in <%=foo%>.

         11┆ <a href="../../redirect.jsp?goto=<%=foo%>">Some Link</a>

        Detected a XSS vulnerability foo is rendered unsafely in <%=meow foo mewo %>.

         16┆ <a href="../../redirect.jsp?goto=<%=meow foo meow%>">Some Link</a>

Ran 1 rule on 0 files: 2 findings.
```

**Screenshots**

Actual undesired result.

```
Nothing to scan.
Scanning 1 file with 2 <multilang> rules.

Findings:

  /jsp-likely-xss.html
     jsp-likely-xss
        Detected a XSS vulnerability $VAR is rendered unsafely in $TEMPLATE.

         16┆ <a href="../../redirect.jsp?goto=<%=meow foo meow%>">Some Link</a>
          ⋮┆----------------------------------------
         11┆ <a href="../../redirect.jsp?goto=<%=foo%>">Some Link</a>


Ran 1 rule on 0 files: 2 findings.
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

local, semgrep 0.106.0
Join rules don't work in semgrep.dev playground.

**Use case**
What will fixing this bug enable for you?

Getting metavariable output in messages.
