### ISSUE TITLE
pattern-regex bug

### ISSUE THREAD

**Issue by zhengow** [semgrep/semgrep#5817]
**Describe the bug**
<img width="995" alt="image" src="https://user-images.githubusercontent.com/38389586/181205178-f7c170c7-eedb-47c3-8452-636fd55ffa02.png">

```
rules:
  - id: boto-client-ip
    patterns:
      - pattern-inside: boto3.client(host="...")
      - pattern-regex: \d{1,3}
    message: boto client using IP address
    languages:
      - python
    severity: ERROR
```

```
import boto3
# ruleid: boto-client-ip
client = boto3.client(host="12")
# ok: boto-client-ip
client = boto3.client(host="dev.internal.example.com")
```

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**
It shouldn't be matched in line5 `client = boto3.client(host="dev.internal.example.com")`
**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
