### ISSUE TITLE
PHP - @function() not matching while function() does

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#5823]
**Describe the bug**
When using taint with `not_conflicting`, or by simply having a sanitizer such as 

```
  - patterns:
    - pattern: $F(...)
    - pattern-not: something(...)
```

Will result in a code like `@something('a');` to not match while `something('a');` will

**To Reproduce**
https://semgrep.dev/s/LBgG

**Expected behavior**
Both the `something()` and `@something()` code should match

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

Current workaround is to have the below sanitizers

```
  - patterns:
    - pattern: $F(...)
    - pattern-not: something(...)
    - pattern-not: "@something(...)"
```
