### ISSUE TITLE
`pattern-not` can't declare metavariables?

### ISSUE THREAD

**Issue by zhengow** [semgrep/semgrep#5840]
**Describe the bug**
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/38389586/182140342-4c196443-0973-4191-851d-f73f0698335d.png">

```
id: untitled_rule
message: Semgrep found a match
languages: [python]
severity: WARNING
patterns: 
    - pattern: ...
    - pattern-not: $X = 1
    - metavariable-pattern:
        metavariable: $X
        pattern: ...
```

```
a = 1
b = 1
c = 1
```

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
