### ISSUE TITLE
Taint metavariable not reporting all the possible matches

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#5849]
**Describe the bug**
Rule:

```yaml
id: confusion-1
mode: taint
pattern-sinks:
  - pattern-either:
      - pattern-inside: exec(...)
pattern-sources:
  - patterns:
      - pattern: $STR
      - pattern-not: $FILE.read()
      - metavariable-pattern:
          metavariable: $STR
          patterns:
            - pattern-not-regex: (.*\/?[__]?version[__]?.py.*)
message: $STR
languages:
  - python
severity: WARNING
```

Target:

```python
exec("HERE")
exec(open('vapory_git/version.py').read())
```

The message for the first is `"HERE"` but for the second is `exec`. The first should also have `exec`.

**To Reproduce**

https://semgrep.dev/playground/s/enelli:confusion-1

**Expected behavior**

Message should be `open('vapory_git/version.py').read()`

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1718/taint-metavariable-capturing-wrong-string. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Are you sure this is a problem with taint-mode rather than a problem with the rule?

```yaml
- pattern: $STR
```

That `$STR` matches every subexpression, including `exec` itself. You can check https://semgrep.dev/s/vLQY that `exec` itself is tainted in line 2.

**Comment by emjin** [comment]
Why is the message correct for the first one? Is it just chance?

**Comment by emjin** [comment]
Looking at this again I'm confused about what the rule expresses. These were mostly examples to illustrate confusion, not real examples, so I'm just going to close this one.

**Comment by IagoAbal** [comment]
So in the first case `exec("HERE")` it may be by chance that we take `$STR = "HERE"` so that's not entirely great. I would need to check the deduplication code. It could be something to improve.

I would have written the sink like this:
```yaml
pattern-sinks:
  - patterns:
      - pattern: exec($...ARGS)
      - focus-metavariable: $...ARGS
```
