### ISSUE TITLE
for loops rules in solidity doesn't work as expected

### ISSUE THREAD

**Issue by shargon** [semgrep/semgrep#5889]
**Describe the bug**
for loop rules are not working as expected.

**To Reproduce**

rule:
```yaml
rules:
 -
    id: variable-default-value
    pattern: $X = 0
    languages: 
    - solidity
    severity: INFO
```

```javascript
pragma solidity >=0.8.4;

contract Test {
 
  function t(address[] calldata targets) external  {
    uint b = 0;
    for (uint256 i = 0; i < targets.length; i++) 
    { 

    }
  }
}
```

**Expected behavior**
`i` must be a match.

**Screenshots**
![image](https://user-images.githubusercontent.com/3167973/183293413-49404170-50da-4f33-8aba-6640e13fd8ef.png)

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
