### ISSUE TITLE
False positive matching in generic-mode with too many lines

### ISSUE THREAD

**Issue by fabian-zeindl-oebb** [semgrep/semgrep#5923]
**Describe the bug**
Pattern-inside using ... matches a context that is longer than 10 lines.

**To Reproduce**

**- Rule**:
````yaml
rules:
  - id: generic-ellipsis-test
    message: ""
    languages: ["generic"]
    severity: ERROR
    patterns:
      - pattern: <badValue>10</badValue>
      - pattern-inside: |
          <context>
            ...
          </context>
    paths:
      include:
        - "generic-ellipsis-test.xml"
````

**-Test**:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<xml>
    <!-- ok: generic-ellipsis-test -->
    <badValue>10</badValue>

    <context>
        <!-- ruleid: generic-ellipsis-test -->
        <badValue>10</badValue>
    </context>

    <context>
        <padding1/>
        <padding2/>
        <padding3/>
        <padding4/>
        <padding5/>
        <padding6/>
        <padding7/>
        <padding8/>
        <padding9/>
        <padding10/>
        <padding11/>
        <padding12/>
        <!-- ok: generic-ellipsis-test -->
        <badValue>10</badValue>
        <padding1/>
        <padding2/>
        <padding3/>
        <padding4/>
        <padding5/>
        <padding6/>
        <padding7/>
        <padding8/>
        <padding9/>
        <padding10/>
        <padding11/>
        <padding12/>
    </context>
</xml>
````

Steps to reproduce the behavior, ideally a link to https://semgrep.dev: **It works on semgrep.dev, but not locally!**

![grafik](https://user-images.githubusercontent.com/104771358/172320843-54891e78-f911-4419-abf3-09afc123642b.png)

**Environment**
Semgrep Version 0.96.0 installed via pip.
