### ISSUE TITLE
Semgrep crashes when using extract mode in YAML file

### ISSUE THREAD

**Issue by malexmave** [semgrep/semgrep#5950]
**Describe the bug**
When using the experimental extract mode, semgrep crashes with the following trace:

```
Scanning 1 file with 2 yaml rules.
[ERROR] Fatal error at line :1:
 Not_found
====[ BEGIN error trace ]====
Not_found
Raised at Stdlib__Hashtbl.find in file "hashtbl.ml", line 539, characters 13-28
Called from Run_semgrep.mk_rule_table.(fun) in file "src/runner/Run_semgrep.ml", line 436, characters 28-59
Called from Stdlib__List.mapi in file "list.ml", line 96, characters 20-25
Called from Stdlib__List.mapi in file "list.ml", line 96, characters 34-50
Called from Stdlib__List.mapi in file "list.ml" (inlined), line 98, characters 15-25
Called from Run_semgrep.mk_rule_table in file "src/runner/Run_semgrep.ml", line 435, characters 4-98
Called from Run_semgrep.semgrep_with_rules in file "src/runner/Run_semgrep.ml", line 594, characters 19-59
Called from Run_semgrep.semgrep_with_raw_results_and_exn_handler in file "src/runner/Run_semgrep.ml", line 682, characters 21-58
=====[ END error trace ]=====
```

**To Reproduce**
Use the following combination of rules:
```yaml
rules:
  - id: spring-actuator-fully-enabled-yaml
    patterns:
      - pattern-inside: |
          management:
            ...
            endpoints:
              ...
              web:
                ...
                exposure:
                  ...
      - pattern-either:
        - pattern: 'include: "*"'
    message: Spring Boot Actuator is fully enabled. This exposes sensitive endpoints
      such as /actuator/env, /actuator/logfile, /actuator/heapdump and others.
      Unless you have Spring Security enabled or another means to protect these
      endpoints, this functionality is available without authentication, causing a
      severe security risk.
    severity: ERROR
    languages:
      - yaml
    paths:
      include:
        - "*.yaml"
        - "*.yml"
    metadata:
      owasp: "A6: Security Misconfiguration"
      references:
        - https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-exposing-endpoints
        - https://medium.com/walmartglobaltech/perils-of-spring-boot-actuators-misconfiguration-185c43a0f785
      category: security
      technology:
        - spring
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  - id: extract-k8s-config-map-to-yaml
    mode: extract
    extract: $CONTENTS
    dest-language: yaml
    patterns:
      - pattern: | 
          data:
            $FILENAME: |-
              $CONTENTS
      - metavariable-regex:
          metavariable: $FILENAME
          regex: '.*.y(a?)ml'
    languages:
      - yaml
    paths:
      include:
        - "*.yaml"
        - "*.yml"
```

The example file to scan to trigger the crash is:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  repayment.yaml: |-
    spring:
      application:
         name: spring-stuff
         description: Just doing springy stuff
    
    management:
      endpoints:
         web:
           base-path: /internal
           exposure:
             include: "*"
      metrics:
        tags:
          application: ${spring.application.name}
```

**Expected behavior**
Either no findings (if I messed up the rule), or a finding (as the spring actuator rule should match).

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Binary from homebrew, v0.110.0

**Use case**
If this works, I would be able to write semgrep rules that search YAML files embedded in K8s config maps. As the files are not otherwise available on Git, being unable to do so means that I don't have any way to analyze them and discover misconfigurations like the one mentioned above (i.e., enabling all Spring actuators, which can be quite dangerous).
