### ISSUE TITLE
Taint mode does not interpret function parameters

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#6006]
https://semgrep.dev/playground/s/sjord:taint-in-func?editorMode=advanced

```
id: taint-in-func
message: Semgrep found a match
languages: [python]
severity: WARNING
mode: taint
pattern-sources:
  - pattern: source(...)
pattern-sinks:
  - pattern: sink(...)
```

```
def foo(a):
    sink(a)

foo(source())
```

I would expect this to match, as `source()` is passed to `foo()` as parameter, and ends up in `sink()` there.
