### ISSUE TITLE
Overly liberal matching for try-catch construct in Solidity

### ISSUE THREAD

**Issue by wuestholz** [semgrep/semgrep#6031]
**Describe the bug**

It seems like semgrep matches a try-catch construct in Solidity even if the external call does not match.

**To Reproduce**

I wrote the following rule to reproduce this in the semgrep playground (see https://semgrep.dev/s/0ApW):

```yml
id: test-try-catch
message: Found a try-catch.
languages:
  - solidity
severity: WARNING
patterns:
  - pattern: |
      try d.foo(42) {
        return 0;
      } catch {
        return 1;
      }
```

Semgrep emits a match for the following Solidity code:
```Solidity
pragma solidity 0.8.16;

interface D {
  function foo(uint256 x) external;
  function baz() external;
}

contract C {
  function bar(D d) external returns (uint256 r) {
    try d.baz() {
      return 0;
    } catch {
      return 1;
    }
  }
}
```

However, `d.baz()` should not match `d.foo(42)`.

**Expected behavior**
I expect the above rule not to result in a match for the above Solidity code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Building rules for detecting security-critical issues in Solidity code
