### ISSUE TITLE
Pattern parse error for Solidity modifiers and constructors

### ISSUE THREAD

**Issue by wuestholz** [semgrep/semgrep#6053]
**Describe the bug**

Semgrep seems to run into a pattern parse error when trying to use Solidity modifiers and constructors in rules.

**To Reproduce**

I am trying to match the following Solidity code:

```Solidity
pragma solidity 0.8.16;

contract C {
  modifier foo() { _; }
  constructor() { }
}
```

I wrote the following rule to match Solidity constructors in the semgrep playground (see https://semgrep.dev/s/BqLx):

```yml
id: test-constructor
message: Found a constructor.
languages:
  - solidity
severity: WARNING
patterns:
  - pattern: |
      constructor (...) {
        ...
      }
```

This results in a pattern parse error.

I wrote the following rule to match Solidity modifiers in the semgrep playground (see https://semgrep.dev/s/0Z5B):

```yml
id: test-modifier
message: Found a modifier.
languages:
  - solidity
severity: WARNING
patterns:
  - pattern: |
      modifier $M(...) {
        ...
      }
```

This also results in a pattern parse error.

**Expected behavior**
I expect the above rules to result in a match for the above Solidity code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Building rules for detecting security-critical issues in Solidity code
