### ISSUE TITLE
Too many matches for Solidity's unchecked-blocks

### ISSUE THREAD

**Issue by wuestholz** [semgrep/semgrep#6055]
**Describe the bug**

It seems like there is something off with how semgrep matches Solidity's unchecked-blocks. There seem to be more matches than expected.

**To Reproduce**

I wrote the following rule to reproduce this in the semgrep playground (see https://semgrep.dev/s/39re):

```yml
id: test-unchecked
message: Found a unchecked-block.
languages:
  - solidity
severity: WARNING
patterns:
  - pattern: |
      unchecked {
        ...
      }
```

Semgrep emits **two** matches for the following Solidity code:
```Solidity
pragma solidity 0.8.16;

contract C {
  function foo(uint256 x, uint256 y) external returns (uint256 z) {
    z = 0;
    unchecked {
      z = x + y;
    }
    z = x + y;
    return z;
  }
}
```

One of the matches is for the entire function body which does not seem right.

**Expected behavior**
I expect the above rule to result in a single match (from lines 6 to 8) for the above Solidity code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Building rules for detecting security-critical issues in Solidity code
