### ISSUE TITLE
semgrep `v0.112` Go regression - false positives reported

### ISSUE THREAD

**Issue by ewbankkit** [semgrep/semgrep#6059]
**Describe the bug**
After the release of semgrep **v0.112** we started getting false positives reported on one of our Go rules.

**To Reproduce**
Offending rule:

```yml
  - id: helper-schema-ResourceData-Resource-Set-tags
    languages: [go]
    message: (schema.ResourceData).Set() call with the tags key should be preceded by a call to IgnoreConfig or include IgnoreConfig in the value in the case of ASG
    paths:
      include:
        - internal/service/**/*.go
      exclude:
        - internal/service/**/*_data_source.go
    patterns:
      - pattern-inside: func $READMETHOD(...) $ERRORTYPE { ... }
      - pattern-either:
          - pattern: |
              tags := $TAGS
              ...
              if err := d.Set("tags", $TAGSMAP); err != nil { ... }
          - pattern: |
              tags = $TAGS
              ...
              if err := d.Set("tags", $TAGSMAP); err != nil { ... }
          - pattern: |
              $ASGTAGS := keyvaluetags.AutoscalingKeyValueTags(...)
              ...
              if err := d.Set("tags", $TAGSMAP); err != nil { ... }
      - pattern-not-regex: 'keyvaluetags.AutoscalingKeyValueTags\(.+\).IgnoreAws\(\).IgnoreConfig'
      - pattern-not: |
          tags = $KEYVALUETAGS.IgnoreAws().IgnoreConfig($CONFIG)
          ...
      - pattern-not: |
          tags = $KEYVALUETAGS.$IGNORESERVICE().IgnoreConfig($CONFIG)
          ...
      - pattern-not: |
          tags := keyvaluetags.$VALUETAGS($RESOURCETAGS).IgnoreAws().IgnoreConfig($CONFIG)
          ...
      - pattern-not: |
          tags = keyvaluetags.$VALUETAGS($RESOURCETAGS).IgnoreAws().IgnoreConfig($CONFIG)
          ...
      - pattern-not: |
          tags = $VALUETAGS($RESOURCETAGS).IgnoreAWS().IgnoreConfig($CONFIG).Ignore($IGNORE)
          ...
    severity: WARNING
```

**Expected behavior**

An example source file that passes the rule with **v0.111.1** (and below) but fails with **v0.112** is https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/accessanalyzer/analyzer.go.

Now getting:

```
Findings:

  internal/service/accessanalyzer/analyzer.go 
     ci.helper-schema-ResourceData-Resource-Set-tags
        (schema.ResourceData).Set() call with the tags key should be preceded by a call to
        IgnoreConfig or include IgnoreConfig in the value in the case of ASG

        [14](https://github.com/hashicorp/terraform-provider-aws/runs/8236235605?check_suite_focus=true#step:4:15)0┆ tags := KeyValueTags(output.Analyzer.Tags).IgnoreAWS().IgnoreConfig(ignoreTagsConfig)
        141┆ 
        142┆ //lintignore:AWSR002
        143┆ if err := d.Set("tags", tags.RemoveDefaultConfig(defaultTagsConfig).Map()); err != nil {
        144┆ 	return fmt.Errorf("error setting tags: %w", err)
        145┆ }
```

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker image in GitHub actions.
