### ISSUE TITLE
Ignore unrelated YAML files from rulesets

### ISSUE THREAD

**Issue by joelrebel** [semgrep/semgrep#6064]
**Describe the bug**

I'm trying to run semgrep in a GH Actions CI pipeline,
This error shows up only in the GH Actions environment, and not when I run the same command locally.

Is there any cli flags to ignore certain files as rulesets - I have tried adding the yamls to `--exclude` and `.semgrepignore`.

The GH action fails because semgrep attempts to load unrelated `yaml` files as a ruleset.
```
Run semgrep ci --config="p/golang" --config="p/trailofbits" --config="semgrep-go/" --exclude="*_test.go"
Running `semgrep ci` without API token but with configs ('p/golang', 'p/trailofbits', 'semgrep-go/')
Scan environment:
  versions    - semgrep 0.112.1 on python 3.10.7
  environment - running in environment github-actions, triggering event is push

Fetching configuration from semgrep.dev
Fetching rules from https://semgrep.dev/registry.
semgrep error: missing keys
  --> semgrep-go/docs/scripts/docker-compose.yml:2
2 | version: "2.1"
3 | services:
[4](https://github.com/metal-toolbox/alloy/runs/8249484959?check_suite_focus=true#step:5:5) |   jaeger:
[5](https://github.com/metal-toolbox/alloy/runs/8249484959?check_suite_focus=true#step:5:6) |     image: jaegertracing/all-in-one:1.37
[6](https://github.com/metal-toolbox/alloy/runs/8249484959?check_suite_focus=true#step:5:7) |     environment:
[7](https://github.com/metal-toolbox/alloy/runs/8249484959?check_suite_focus=true#step:5:8) |       COLLECTOR_OTLP_ENABLED: "true"

semgrep-go/docs/scripts/docker-compose.yml_2 is missing `rules` as top-level key
....
```

The GH action can be seen here https://github.com/metal-toolbox/alloy/runs/8249484959?check_suite_focus=true#step:5:13

The related GH action job configuration,

```yaml
  lint-sa:                                                                     
    name: run semgrep code analysis                                            
    runs-on: ubuntu-latest                                                     
    container:                                                                 
      image: returntocorp/semgrep                                              
    # Skip any PR created by dependabot to avoid permission issues             
    if: (github.actor != 'dependabot[bot]')                                    
    steps:                                                                     
      - name: Checkout Alloy code                                              
        uses: actions/checkout@v3                                              
        with:                                                                  
          path: alloy                                                          
      - name: clone dgryski semgrep rules                                      
        uses: actions/checkout@v3                                              
        with:                                                                  
          name: dgryski/semgrep-go                                             
          path: semgrep-go                                                     
      - run: semgrep ci --config="p/golang" --config="p/trailofbits" --config="semgrep-go/" --exclude="*_test.go"
```

**To Reproduce**

Create a GH actions on a repository with Go code, using the configuration described above,

**Expected behavior**

semgrep runs successfully in GH Actions or otherwise.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
GH Actions.

**Use case**
Run semgrep in GH actions.
