### ISSUE TITLE
Ignoring multiple rules with nosemgrep produces warnings

### ISSUE THREAD

**Issue by priyeshpatel** [semgrep/semgrep#6074]
**Describe the bug**
When ignoring multiple rules with a `nosemgrep` comment, semgrep produces incorrect warnings in strict mode or logs incorrect messages in non-strict mode.

1. The warning (strict mode) / log message (non-strict mode) is printed for ignored rules which have already been correctly skipped.
2. The "but no corresponding rule trying X" phrase in the warning (strict mode) / log message (non-strict mode) is confusing as X is the rule which matched.

```
found 'nosem' comment with id 'foo', skipping rule 'foo' on line 2
found 'nosem' comment with id 'bar', skipping rule 'bar' on line 2
[WARN] found 'nosem' comment with id 'bar', but no corresponding rule trying 'foo'
[WARN] found 'nosem' comment with id 'foo', but no corresponding rule trying 'bar'
```

**To Reproduce**

`rule.yml`
```
rules:
  - id: foo
    pattern: print("foo" + ...)
    message: foo
    languages: [python]
    severity: ERROR
  - id: bar
    pattern: print(... + "bar")
    message: bar
    languages: [python]
    severity: ERROR
```

`test.py`
```
# nosem: foo, bar
print("foo" + "bar")
```

**Expected behavior**
No warning is produced as both rules are being ignored correctly.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
```
$ semgrep --version
0.111.1
```

I believe the bug may originate from this code as we treat each rule match separately:

https://github.com/returntocorp/semgrep/blob/756408aafebb849d89993a067f9c6f8d834df8a4/cli/src/semgrep/nosemgrep.py#L126-L131 

**Use case**
It will allow us to use `nosemgrep` comments which specify multiple rule IDs.
