### ISSUE TITLE
[QUESTION] How to search array in rules

### ISSUE THREAD

**Issue by luisfontes19** [semgrep/semgrep#6108]
Hey guys,

Is there any native way of searching for arrays with a rule? 
I have a use case that if a method receives an array of hardcoded strings its not an issue. I know i can go with regex, but that will then have other issues. 

(I'm creating rules for python in case it matters)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1893/[question]-how-to-search-array-in-rules. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
@luisfontes19 could you please provide a concrete example and maybe also a draft rule as you envision it?

From your description ("an array of hardcoded strings") I think you may want to write something like:

```yaml
    patterns:
    - pattern: foo(...)
    - pattern-not:
      - pattern: foo([..., $X, ...])
      - metavariable-pattern:
          metavariable: $X
          patterns:
          - pattern-not: "..."
```

We don't currently support that but we could add support for it rather quickly nowadays thanks to a recent PR by @brandonspark.

**Comment by luisfontes19** [comment]
So just to give some context, i'm trying to re-write the usage of subprocess rule to improve on the results. 

The thing is that we can have for example:

```python
subprocess.run("ls")
subprocess.run(["ls", "-la"])
```

I'm trying to remove all results for hardcoded strings, as they contain no user input, and thats why I need to find all arrays with just hardcoded strings or the other way around.

Unfortunately the logic from the example you provided didn't work for this case 🥺

**Comment by luisfontes19** [comment]
Ok, so i got it working based on the suggestion @IagoAbal mentioned. 

I'm leaving the code here in case anybody else runs into a similar issue

```yaml
patterns:
  - pattern-either:
      # Check arrays without hardcoded values
      - patterns:
        - pattern-either:
          - pattern: $SUBPROCESS([...,$NOT_HARDCODED_STRING, ...])
          - pattern: $SUBPROCESS([...,$NOT_HARDCODED_STRING, ...], ...)

      # Check not hardcoded strings as param
      - patterns:
        - pattern: $SUBPROCESS($NOT_HARDCODED_STRING)
        - pattern-not: $SUBPROCESS([...])
  
  - metavariable-pattern:
      metavariable: $NOT_HARDCODED_STRING
      patterns:
        - pattern: ...
        - pattern-not: |
            "..."
  - metavariable-pattern:
      metavariable: $SUBPROCESS
      patterns:
        - pattern-either:
            - pattern: subprocess.call
            - pattern: subprocess.capture_output
            - pattern: subprocess.run
            - pattern: subprocess.Popen
```

If you think is still relevant to add a specific option to do this, we can keep this issue open, otherwise for me it can be closed as solved :)
