### ISSUE TITLE
Autofix rewrites CRLF line separators to LF line separators 

### ISSUE THREAD

**Issue by dmgping** [semgrep/semgrep#6163]
**Description**
Running a scan with the cli using a rule that has a fix definition and passing in the --autofix flag to implement the fix rewrites CRLF line separators to LF line separators. 

**To Reproduce**

**1** - Create an example.html file with the following contents 

```
<!DOCTYPE html>
#* Sample File *#
<html lang="$locale.getLanguage()" dir="ltr">
<body>
    <label class="class-name">
        <input type="type" name="$unescapedName" value="$unescapedValue"/>
    </label>
</body>
</html>
```

**2** - ensure it has CRLF line separator by running this command:
"find example.html | xargs file" 
This should output "example.html: HTML document text, ASCII text, with CRLF line terminators"

If not, run "unix2dos example.html" to convert it , run  "find example.html | xargs file" again to confirm.

**3** - Create a rule.yaml file with the following contents 
"
```
rules:
- id: HTML-XSS-Escape-all-html-input
  languages: [generic]
  paths:
    include:
      - "*html"
  patterns:
  - pattern-inside: <input ... />
  - pattern-not-inside: $escape.escape(...)
  - pattern-not: $escape...
  - pattern: $$OBJ
  fix: $escape.escape($$OBJ)
"
```
**4** - Run an autofix scan with the following rule:
semgrep --autofix --config rule.yaml example.html

**5** - Run "find example.html | xargs file"  again and observe the "with CRLF line terminators" has been dropped, indicating the file has been converted to LF line separators

**Expected behavior**
CRLF Line Separators are retained during autofixes
  
**Priority**
How important is this to you?
- [✓] P0: blocking me from making progress

**Desktop**
 - OS: macOS
 - Browser: N/A
 - Version: 12.6
