### ISSUE TITLE
Safe navigation operator support

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#6206]
The [safe navigation operator](https://en.wikipedia.org/wiki/Safe_navigation_operator#JavaScript) does null-safe dereferencing:

```
var name = articles?[0]?.Author?.Name;
```

This returns the first article author's name, but won't throw an exception if any of the values are null.

Currently, semgrep doesn't really support this. For example, the following rule wouldn't work, as it would also match on `article?.Author`:

```
rules:
  - id: null_safe_check
    pattern: article.Author
    message: Article may be null, use safe navigation operator
    languages:
      - csharp
    severity: WARNING
```

[AST_Generic](https://github.com/returntocorp/semgrep/blob/2428d17ee7cfe217f4a4ff62585a9884b9516cc7/semgrep-core/src/core/ast/AST_generic.ml#L508-L510) should have support for safe navigation operators. How?

One solution is to add `SafeDotAccess` and `SafeArrayAccess`, which would be similar to the current `DotAccess` and `ArrayAccess`. Another possibility is to add a boolean property to `DotAccess` and `ArrayAccess`, which would indicate whether the access is null-safe.

Currently, semgrep translates a null-safe access to a DotAccess. I wrapped this in a null-check in C#, but that caused [more problems](https://github.com/returntocorp/semgrep/issues/6018) and still makes matching on null-safe access impossible.
