### ISSUE TITLE
Missed findings when running on a folder

### ISSUE THREAD

**Issue by Techbrunch** [semgrep/semgrep#6209]
semgrep version 0.115.0

My rule:

```
rules:
  - id: my-pattern-name
    message: "Some message to display to the user"
    languages: [php]
    severity: ERROR
    mode: taint
    pattern-sources:
      - patterns:
          - pattern-either:
              - pattern: $_GET
              - pattern: $_POST
              - pattern: $_COOKIE
              - pattern: $_REQUEST
              - pattern: $_SERVER
    pattern-sinks:
      - patterns:
          - pattern: $SQL
          - pattern-either:
              - patterns:
                  - pattern: db_query($SQL, ...)
```

I have an empty `.semgrepignore`.

```
❯ semgrep sites/all --verbose
running 1 rules from 1 config .semgrep.yml
using path ignore rules from user provided .semgrepignore
Rules:
- my-pattern-name
Scanning 2435 files.
  100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|2435/2435 tasks

Blocking Findings:

  sites/all/modules/_shop_modules/shop_product_review/shop_product_review.admin.inc
     my-pattern-name
        Some message to display to the user

        431┆  ... "SELECT COUNT(*) AS `count`, FLOOR(SUM(pr.rating) / COUNT(*)) AS `rating` FROM {product_review} pr WHERE pr.pid = $pid")->fetch(); ...
          [shortened a long line from output, adjust with --max-chars-per-line]

Blocking Rules Fired:
   my-pattern-name

========================================
Files skipped:
========================================

  Always skipped by Semgrep:

   • <none>

  Skipped by .gitignore:
  (Disable by passing --no-git-ignore)

   • <all files not listed by `git ls-files` were skipped>

  Skipped by .semgrepignore:
  (See: https://semgrep.dev/docs/ignoring-files-folders-code/#understanding-semgrep-
  defaults)

   • <none>

  Skipped by --include patterns:

   • <none>

  Skipped by --exclude patterns:

   • <none>

  Skipped by limiting to files smaller than 1000000 bytes:
  (Adjust with the --max-target-bytes flag)

   • <none>

  Skipped by analysis failure due to parsing or internal Semgrep error

   • <none>


Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 1 rule on 2435 files: 1 finding.
Not sending pseudonymous metrics since metrics are configured to AUTO and registry usage is False
```

There is only one finding but I know that at least one of the file is not scanned since if I run semgrep only on this file then there are more findings.

I confirmed that the file in question is in `git ls-files`.

```
❯ semgrep sites/all/modules/_shop_modules/shop_action_pages/shop_action_pages.admin.inc
Scanning 1 file.

Blocking Findings:

  sites/all/modules/_shop_modules/shop_action_pages/shop_action_pages.admin.inc
     my-pattern-name
        Some message to display to the user

        265┆ $existed = db_query('
        266┆   SELECT apa.appid
        267┆   FROM {'.$table.'} apa
        268┆   WHERE apa.apid = :apid AND apa.cmmf=:cmmf',
          ⋮┆----------------------------------------
        402┆ $action_items = db_query('SELECT ap.*
        403┆                  FROM {'.$db_table.'} ap where apid=:apid ORDER BY ap.sort DESC',array(':apid'=>$_REQUEST['apid']))->fetchAll();
          ⋮┆----------------------------------------
        469┆ $existed = db_query('
        470┆ SELECT apa.appid
        471┆ FROM {'.$_REQUEST['table_name'].'} apa
        472┆ WHERE apa.apid = :apid AND apa.pid=:pid',
          ⋮┆----------------------------------------
        506┆ $existed = db_query('
        507┆     SELECT apa.appid
        508┆     FROM {'.$db_table.'} apa
        509┆     WHERE apa.apid = :apid AND apa.pid=:pid',
          ⋮┆----------------------------------------
        541┆ $existed = db_query('
        542┆       SELECT apa.appid,apa.apid
        543┆       FROM {'.$db_table.'} apa
        544┆       WHERE apa.appid = :appid',

Blocking Rules Fired:
   my-pattern-name


Ran 1 rule on 1 file: 5 findings.
```
