### ISSUE TITLE
add handle 'export' for function pattern

### ISSUE THREAD

**Issue by zakrush** [semgrep/semgrep#6218]
**Is your feature request related to a problem? Please describe.**
https://r2c-community.slack.com/archives/C018NJRRCJ0/p1664733162490709 was discus into Slack
Needed handle only export functions for JS and TS languages. 

```
export async function del(
  req: Sails.Request,
  res: Sails.Response,
): Promise<void> {
  if (!checkAccessToConfig(req)) {
    res.negotiate('Access is denied');
    return;
  }
```
I want handle only export type of functions and rule down/ now is not working

```
rules:
- id: authorization-rvn
  patterns:
    - pattern-inside: |
        export ... function $FUNC(..., res, ...){
          ...
        }
    - pattern: res.$ACTION($RES_STRING)
    - metavariable-regex:
        metavariable: '$RES_STRING'
        regex: '.*(denied|DENIED).*'
  message: No Check of authorization
  languages: [js, ts]
  severity: ERROR
```

**Describe the solution you'd like**
Add the ability to specify the type of function
`pattern-inside: export ... $FUNC(...){}`

**Use case**
I want is grepping functions that available for users and importing from other modules of app.

**Additional context**
See describe examples.
