### ISSUE TITLE
add `pattern-regex`

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#629]
to enable semgerp to completely replace any PCRE regex tool

**Comment by aryx** [comment]
I like this.

**Comment by ievans** [comment]
It is nice that our boolean composition work will work seamlessly with this. I wonder what this means for thefuture of the python parts of semgrep.

**Comment by aryx** [comment]
Honestly, it can be nice to have semgrep written half in OCaml half in Python so if people want to contribute, it's less scary if they think they can probably do stuff on the Python side. I feel the split with the set-based operators outside semgrep-core is still pretty good. I don't think we suffer much from it.

**Comment by DrewDennison** [comment]
basic feature: if `pattern-regex` is defined, read the file in python and return the range that the regex matches. Acceptance criteria is that `pattern-regex` should work with the boolean logic so I can match something like

```python

boto3.client(host="123.123.123.123")

```

with

```yaml

patterns:
  - pattern: boto3.client(host="...")
  - pattern-regex: "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"

```
