### ISSUE TITLE
Can't use Ellipsis Metavariables to capture JSX tag content

### ISSUE THREAD

**Issue by just-be-dev** [semgrep/semgrep#6323]
**Describe the bug**
In order to write a fix rule that removes some attributes of an JSX expression, you must be able to capture any other parameters in the JSX expression.

For example let's say you have a component that returns this SVG tag:

```jsx
<svg
    width={16}
    height={16}
    viewBox="0 0 16 16"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
  >
    <text>Hello</text>
  </svg>
```

If you want to remove width and height there, but otherwise keep the expression the same one would assume you could do..

```yaml
rules:
  - id: remove-responsive-icon-dimensions
    languages: 
      - ts
    severity: ERROR
    patterns:
      - pattern: <svg width={$W} height={$H} $...OTHER>$...BODY</svg>
    fix: <svg $...OTHER>$...BODY</svg>
```

In the above rule the `$...BODY` ellipsis metavariable functions as expected. The `$...OTHER` causes the program to error with 

```
Pattern error: Parse_info.Lexical_error (unrecognized symbol, in XHP tag:$, /tmp/tmp-9129-9ca9b3.js:1:28 "$")
```

**To Reproduce**
https://semgrep.dev/s/njrg

**Expected behavior**

```
<svg width={$W} height={$H} $...OTHER>$...BODY</svg>
```

`$...OTHER` should capture the other attributes in the JSX expression.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
I'm working through replacing our codemods with semgrep. Being able to strip out or modify attributes inside of JSX expressions is important.
