### ISSUE TITLE
`filename-not` not working?

### ISSUE THREAD

**Issue by amanagr** [semgrep/semgrep#636]
On rule:
```yml

  - id: dont-import-models-in-migrations
    patterns:
      - pattern-not: from zerver.lib.redis_utils import get_redis_client
      - pattern-not: from zerver.lib.utils import generate_random_token
      - pattern-either:
          - pattern: from zerver import $X
          - pattern: from analytics import $X
          - pattern: from confirmation import $X
    message: "Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md"
    languages: [python]
    severity: ERROR
    paths:
      - directory: "**/migrations"
      - filename-not: 'zerver/migrations/0032_verify_all_medium_avatar_images.py'
      - filename-not: 'zerver/migrations/0060_move_avatars_to_be_uid_based.py'
      - filename-not: 'zerver/migrations/0104_fix_unreads.py'
      - filename-not: 'zerver/migrations/0206_stream_rendered_description.py'
      - filename-not: 'zerver/migrations/0209_user_profile_no_empty_password.py'
      - filename-not: 'zerver/migrations/0260_missed_message_addresses_from_redis_to_db.py'
      - filename-not: 'pgroonga/migrations/0002_html_escape_subject.py'
```

The output is:
```bash
❯  ./tools/lint --only=semgrep-py
semgrep-py| pgroonga/migrations/0002_html_escape_subject.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 5:from zerver.lib.migrate import do_batch_update
semgrep-py|
semgrep-py| zerver/migrations/0001_initial.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 12:import zerver.models
semgrep-py|
semgrep-py| zerver/migrations/0032_verify_all_medium_avatar_images.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 10:from zerver.lib.upload import upload_backend
semgrep-py| 11:from zerver.lib.utils import make_safe_digest
semgrep-py| 12:from zerver.models import UserProfile
semgrep-py|
semgrep-py| zerver/migrations/0043_realm_filter_validators.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 4:import zerver.models
semgrep-py|
semgrep-py| zerver/migrations/0094_realm_filter_url_validator.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 5:import zerver.models
semgrep-py|
semgrep-py| zerver/migrations/0104_fix_unreads.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 6:from zerver.lib.fix_unreads import fix
semgrep-py|
semgrep-py| zerver/migrations/0206_stream_rendered_description.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 5:from zerver.lib.actions import render_stream_description
semgrep-py|
semgrep-py| zerver/migrations/0209_user_profile_no_empty_password.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 13:from zerver.lib.cache import cache_delete, user_profile_by_api_key_cache_key
semgrep-py| 13:from zerver.lib.cache import cache_delete, user_profile_by_api_key_cache_key
semgrep-py| 14:from zerver.lib.queue import queue_json_publish
semgrep-py| 15:from zerver.lib.utils import generate_api_key
semgrep-py|
semgrep-py| zerver/migrations/0212_make_stream_email_token_unique.py
semgrep-py| rule:tools.dont-import-models-in-migrations: Don't import models or other code in migrations; see docs/subsystems/schema-migrations.md
semgrep-py| 5:import zerver.models
```

Notice that most of the filenames here are excluded. Is there something wrong with my rule or is this a bug from your side?

Code: https://github.com/amanagr/zulip/tree/semgrep_port_non_gl_bl
Version: 0.5.0-dev.2
