### ISSUE TITLE
Use as pre-commit hook ignores includes/excludes

### ISSUE THREAD

**Issue by ikonst** [semgrep/semgrep#6494]
**Describe the bug**
When used as a pre-commit hook, semgrep appears to ignore `paths.includes` and `paths.excludes`, perhaps due to how pre-commit works by feeding the tool the exact targets that it should check.

Per [a comment in the semgrep code](https://github.com/returntocorp/semgrep/blob/89e9161243fdbe5e152acd556d21cd40d44d9789/cli/src/semgrep/target_manager.py#LL663C67-L663C67), command line targets bypass `includes` and `excludes`.

**To Reproduce**

Create a repo with `.pre-commit-config.yaml` containing:
```yaml
repos:
-   repo: https://github.com/returntocorp/semgrep
    rev: v0.121.0
    hooks:
    -   id: semgrep
        types: [python]
```
Then create a rule with an `includes` property:
```yaml
rules:
-   id: no-spam
    message: "don't spam"
    pattern: spam
    languages: [python]
    severity: ERROR
    paths:
        includes:
          - only_this_one.py
```
and finally add a file that's not included but matches the "pattern":
```python
echo spam > ham.py
```

Add to git:
```
git init
git add ham.py
git add .pre-commit-config.yaml
```

Run pre-commit on all files:
```python
pre-commit run semgrep -a
```

**Workaround**
Adding `pass_filenames: false` to the hook's configuration works around the problem by preventing targets from being passed to semgrep:
```diff
 -   repo: https://github.com/returntocorp/semgrep
     rev: v0.121.0
     hooks:
     -   id: semgrep
         types: [python]
+        pass_filenames: false
```

**Expected behavior**

- The `ham.py` file should be not matched. 
- Barring that, mentioning something in [the docs](https://semgrep.dev/docs/writing-rules/rule-syntax/#paths).

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed
