### ISSUE TITLE
Equivalences will sometimes supersede pattern logic

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#652]
**Describe the bug**
Using equivalences will sometimes result in findings that should not match the `pattern`.

**To Reproduce**
Eg., it should not fire on the last example.
https://semgrep.live/O67?version=develop

**Comment by brendongo** [comment]
Was able to reproduce this issue on semgrep-core

`semgrep-core -lang python -rules_file rules.yaml -equivalences equivalences.yaml target.py`

```
rules:
- id: 0.open-redirect
  pattern: django.shortcuts.redirect(..., request.$W.get(...), ...)
  severity: WARNING
  languages:
  - python
  message: <internalonly>
```

```
equivalences:
- id: open-redirect-0
  languages:
  - python
  pattern: django.shortcuts.redirect(...) <==> django.http.HttpResponseRedirect(...)
```

```
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

def arg(request):
    # ruleid: open-redirect
    return redirect(request.POST.get("url"))


def fine(request):
    # ok
    return redirect("index")

def argh(request):
    # ruleid: open-redirect
    return HttpResponseRedirect(request.POST.get("url"))

def arghhh(request):
    # ok
    return HttpResponseRedirect("index")
```
