### ISSUE TITLE
Extract mode ignoring destination language

### ISSUE THREAD

**Issue by Denis-Podgurskii** [semgrep/semgrep#6567]
**Describe the bug**
I have rules for javascript and vue  languages and when I use extract  rule I see that both rules report findings even I use dest-language: javascript

**To Reproduce**
https://semgrep.dev/s/denis-podgurskii:vanilla-dom-xss - first rule
https://semgrep.dev/s/denis-podgurskii:vue-dom-xss - second rule

extract rule:
```
rules:
  - id: extract-javascript
    mode: extract
    languages:
      - html
    patterns:
      - pattern: <script ...>$JS</script>
      - pattern-not: <script ...></script>
    extract: $JS
    dest-language: javascript
```

command I use
`semgrep --config ../html/extract/javascript --config ../html/extract/vue --config ../html/extract/extract-javascript.yaml ../html/extract/code`

html file in the /code folder
```
<!DOCTYPE html>
<html lang="en">
  <head> </head>

  <body>
    <script id="code">
      let msg = "Hash Value: <b>" + document.location.hash + "</b>";
      document.getElementById("output").innerHTML = msg;
    </script>
  </body>
</html>
```

**Expected behavior**
Only javascript rules should be applied, not vue

**Screenshots**

**What is the priority of the bug to you?**

- [P0 ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Local

**Use case**
Run a scan on html files to extract javascript and run JS rules on the extracted code
