### ISSUE TITLE
`...` is really slow on long files

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#664]
`pattern-not-inside` is really slow on long files. (I assume `pattern-inside` also suffers from this performance problem)

As part of my investigation of #520 I binary searched rules over files in https://github.com/sobolevn/python-code-disasters by far the biggest issue was with https://github.com/sobolevn/python-code-disasters/blob/master/python/my_first_calculator.py and `r2c.python.deadcode` and `r2c.python.smells` where really slow. I then further binary searched to get to https://semgrep.live/r/r2c.python.smells.open-never-closed being the really slow one in `r2c.python.smells`

When I delete the `pattern-not-inside` lines, it runs in under 2 seconds

To reproduce,

1. Clone `git clone https://github.com/sobolevn/python-code-disasters`
2. Delete `python/PhyRe.py` because it has parse errors reported in #663 
3. `curl https://semgrep.live/c/r/r2c.python.smells.open-never-closed > open-never-closed.yml`
4. run `time semgrep -f open-never-closed.yml python/my_first_calculator.py`
5. **Observe it hangs for several minutes**
6. Get sick of waiting and kill it
7. Delete all `pattern-not-inside` patterns in `open-never-closed.yml`
8. run `time semgrep -f open-never-closed.yml python/my_first_calculator.py`
9. Watch it complete in <2s

**Comment by DrewDennison** [comment]
for other discussion on this feeling like expontential backtracking https://r2c-community.slack.com/archives/CK8UH0A8Y/p1588445294017500?thread_ts=1588441876.015700&cid=CK8UH0A8Y

**Comment by DrewDennison** [comment]
@aryx it actually has nothing to do with `pattern-not-inside` when running over https://github.com/sobolevn/python-code-disasters/blob/master/python/my_first_calculator.py

```yaml
rules:
- id: performance-demonstrator-slow
  pattern: |
    $F = open(...)
    ...
    $F.close()
  message: super slow over 20k file
  languages: [python]
  severity: ERROR
```

takes `32s` on my mac


```yaml
rules:
- id: performance-demonstrator-fast
  pattern: $X == $X
  message: reasonably fast over 20k file
  languages: [python]
  severity: ERROR
```

takes `1.4s` on the same mac

The open-never-closed referenced above has 14 such patterns. No wonder it takes minutes to run.
