### ISSUE TITLE
need help with matching one OR other group of patterns

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#671]
**Describe the bug**
this is probably me not getting it right, but:

what if I want to match:
a function which has the last parameter not a string
OR a function which has the second-to-last parameter not a string

(same function in each case, number of parameters may vary)

I did it like this:
https://semgrep.live/p2d

```yaml
rules:
- id: check-check
  message: 'check'
  languages: [javascript]
  severity: ERROR
  pattern-either:
    - patterns:
        - pattern: foo(...,$F)
        - pattern-not: foo(...,"...")
    - patterns:
        - pattern: foo(...,$F,$P)
        - pattern-not: foo(...,"...",$P)
```

```javascript
// ruleid: check-check
foo(1,2,3,"yo")

// ruleid: check-check
foo(1,2,"hi",3)
```

but it wont work, while patterns work separately:

https://semgrep.live/2Oj

```yaml
rules:
- id: check-check
  message: 'check'
  languages: [javascript]
  severity: ERROR
  patterns:
    - pattern: foo(...,$F)
    - pattern-not: foo(...,"...")
```

```javascript
// ruleid: check-check
foo(1,2,"hi",3)
```

https://semgrep.live/XEq

```yaml
rules:
- id: check-check
  message: 'check'
  languages: [javascript]
  severity: ERROR
  patterns:
    - pattern: foo(...,$F,$P)
    - pattern-not: foo(...,"...",$P)
```

```javascript
// ruleid: check-check
foo(1,2,3,"yo")
```

whats the right way to sort it out?
