### ISSUE TITLE
JavaScript functions do not match inside objects

### ISSUE THREAD

**Issue by Vasco-jofra** [semgrep/semgrep#6748]
**Describe the bug**
A metavariable does not match a JavaScript function inside an object. For example, the pattern `var $X = {key: $A}` does not match the case `var y = { key: function (a) { return a - 1 }}` (https://semgrep.dev/s/Lk3J). In contrast, doing the same outside of the object works: the pattern `var $X = $A` matches `var y = function (a) { return a - 1 }` (https://semgrep.dev/s/xK4p).

**Expected behavior**
I expected JavaScript functions to match inside of objects as they do outside.

**What is the priority of the bug to you?**
- P1: important to fix or quite annoying

**Use case**
It will enable me to match everything that can be inside an object key except a few known good values. Example (https://semgrep.dev/s/7dnR):
 - pattern:
```yaml
    patterns:
      - metavariable-pattern:
          metavariable: $VALUE
          patterns:
            - pattern-not: |
                false
            - pattern-not: |
                []
      - pattern: |
          var $X = {..., key: $VALUE, ...}
```

 - Test cases:
```js
//ok:test
var x1 = {
    key: false
}

//ok:test
var x2 = {
    key: []
}

//ruleid:test
var x3 = {
    key: true
}

//ruleid:test
var x4 = {
    key: ["asd", "asd"]
}

//ruleid:test
var x5 = {
    key: 123
}

// This one fails to match
//ruleid:test
var x6 = {
    key: function (a) {
        return a - 1
    }
}
```
