### ISSUE TITLE
How to use metavariable-regex for variable in pattern-not-include to filter some cases ?

### ISSUE THREAD

**Issue by cokeBeer** [semgrep/semgrep#6768]
**Describe the bug**
How to use metavariable-regex for variable in pattern-not-include to filter some cases.
For example, useless sources from config file (which I would like to give it a regex pattern)
I tried the case below but it does not work and even outputs no result.

**To Reproduce**
A rule use metavariable-regex for variable in pattern-not-include to check bash injection in go
rule:
```yaml
rules:
- id: bash_injection
  languages: [go]
  severity: ERROR
  patterns:
  - pattern-either:
      - pattern: |
          exec.Command("$SHELL", "-c", fmt.Sprintf($F, $ARG, ...), ...)
  - pattern-inside: |
      import "os/exec"
      ...
  - pattern-not-inside: |
      $ARG = "$TEST"
      ...
  - metavariable-regex:
      metavariable: $SHELL
      regex: ^(sh|bash|zsh|dash|cmd|powershell|csh|ksh|vsh)$
  - metavariable-regex:
      metavariable: $TEST
      regex: .*
  message: $SHELL injection
```
A file, in ShouldMatch, the path is a variable. In ShouldNotMatch, the path is from some useless sources like constant.
file:
```go
package test

import (
	"fmt"
	"os/exec"
)

func ShouldMatch(path string) bool {
	cmd := "ls %s"
	out, err := exec.Command("sh", "-c", fmt.Sprintf(cmd, path)).Output()
	if err != nil {
		panic(err)
	}
	fmt.Println(out)
	return true
}

func ShouldNotMatch(path string) bool {
	path = "whatever"
	cmd := "ls %s"
	out, err := exec.Command("sh", "-c", fmt.Sprintf(cmd, path)).Output()
	if err != nil {
		panic(err)
	}
	fmt.Println(out)
	return true
}
```
**Expected behavior**
Command Injection in ShouldMatch is matched, ShouldNotMatch is not matched

**Screenshots**
not output
<img width="491" alt="image" src="https://user-images.githubusercontent.com/70683161/210188293-f94b7d85-3a19-4d2b-80a0-e8ec552598fd.png">

**Use case**
Seems using metavariable-regex for pattern-not-include leads to this problem
I want to know how to use  metavariable-regex for variable in pattern-not-include to filter some cases, not only constant value.

**Comment by LewisArdern** [comment]
There might be a bug with metavariable-regex and patter-not-inside, but I would personally rewrite the rule to do something like this https://semgrep.dev/s/ON5B

Does this help you?

**Comment by holdenmcg** [comment]
Hey @cokeBeer,

Right now, metavariable regex isn't compatible with pattern-not-inside. You can write the same rule via taint mode as a workaround, something like: 

```yaml
rules:
  - id: bash_injection
    languages:
      - go
    severity: ERROR
    mode: taint
    pattern-sources:
      - patterns:
          - pattern-inside: |
              func $FUNC($PATH string) {
                ...
              }
          - pattern: $PATH
          - pattern-not: |
              "..."
    pattern-sinks:
      - patterns:
          - pattern-either:
              - pattern: |
                  exec.Command("$SHELL", "-c", fmt.Sprintf($F, $ARG, ...), ...)
          - focus-metavariable: $ARG
          - pattern-inside: |
              import "os/exec"
              ...
          - metavariable-regex:
              metavariable: $SHELL
              regex: ^(sh|bash|zsh|dash|cmd|powershell|csh|ksh|vsh)$
    message: $SHELL injection
```

Let me know if this works for you.
