### ISSUE TITLE
issue with tutorial for http-responsewrite-write exercise

### ISSUE THREAD

**Issue by jrozner** [semgrep/semgrep#6805]
The following rule matches the correct parts and doesn't match the incorrect parts but the tutorial isn't showing it as correct.

```yaml
rules:
  - id: http-responsewriter-write
    patterns:
    - pattern-inside: |
        func $FUNC($WRITER http.ResponseWriter, $REQ *http.Request) {
          ...
        }
    - pattern: $WRITER.Write(...)
```
https://semgrep.dev/learn/composition/3
