### ISSUE TITLE
Include/exclude patterns matching on start/end

### ISSUE THREAD

**Issue by ikonst** [semgrep/semgrep#6835]
Since #3173 we're turning pattern `['foo/bar']` to `['**/foo/bar', '**/foo/bar/**']`:
https://github.com/returntocorp/semgrep/blob/4c3f8182dc9b820564c48156bf3e693071fc3b3a/cli/src/semgrep/target_manager.py#L524-L527

1. Sometimes it's desirable for a rule to apply to a specific directory of the project, without accidentally matching the same directory when it's found somewhere else in the project's hierarchy. For example:
   ```
   parsers/ <-- apply here
   database/parsers/ <-- but not here
   ```
   (without adding `database/parsers/` to excludes, since then you need to know ahead of time about any future "parsers" directory)

2. [The docs](https://semgrep.dev/docs/writing-rules/rule-syntax/#paths) don't call out that behavior. The docs state "any file inside project/tests or its subdirectories" omitting "... found anywhere within the project's hierarchy", or some other less cumbersome explanation. I guess what I'm trying to say is that I had to read semgrep sources to understand why it behaves this way.

**Comment by ievans** [comment]
@adamkvitek want to take a look here?

**Comment by adamkvitek** [comment]
Thanks, @ievans, I created an internal issue MKT-495.

**Comment by ikonst** [comment]
👋  @ievans @adamkvitek

Took me some time to figure it out, I really think we should document, or better yet, change it.

**Comment by ikonst** [comment]
@adamkvitek would the team be ok with reverting this behavior?

**Comment by ikonst** [comment]
@adamkvitek would the team be ok with reverting this behavior?

**Comment by ikonst** [comment]
Ping

**Comment by adamkvitek** [comment]
Hello @ikonst, I will have a look, sorry to keep you waiting for so long.

I was looking into https://semgrep.dev/docs/writing-rules/rule-syntax/#paths (there are a few things I need to edit) - would you like to start your PR to edit the docs first? I will test this behavior to understand your initial question better also.

**Comment by adamkvitek** [comment]
@ikonst just checking if I understand you correctly:

We should change:

```yaml
rules:
  - id: eqeq-is-bad
    pattern: $X == $X
    paths:
      exclude:
        - "*.jinja2"
        - "*_test.go"
        - "project/tests"
        - project/static/*.js
```

To:

```yaml
rules:
  - id: eqeq-is-bad
    pattern: $X == $X
    paths:
      exclude:
        - "*.jinja2"
        - "*_test.go"
        - "**/project/tests/**"
        - project/static/*.js
```

Also the text:

Original:
When invoked with `semgrep -f rule.yaml project/`, the above rule runes on files inside `project/`, but no results are returned for:

Suggestion:
When invoked with `semgrep -f rule.yaml project/`, the above rule runs on files inside `project/` directory hierarchy, but no results are returned for:
