### ISSUE TITLE
Autofixing annotated Python functions cumbersome

### ISSUE THREAD

**Issue by ikonst** [semgrep/semgrep#6847]
For example, this pattern:
```
def $NAME($...ARGS):
  $BODY
```
will match both
```python
def foo(a: int): return
def foo(a: int) -> None: return
```
but this fixer
```
def $NAME($...ARGS):
  $BODY
```
would fix both to
```python
def foo(a: int): return
def foo(a: int): return
```

**Describe the solution you'd like**
Since a pattern that specifies no return type captures both functions with and without a return type, it only follows that the autofix should carry over the return type (as it was not a "significant part" of the pattern).

I don't really know if the autofix mechanism works in a way that's conductive to what I'm describing, but IMO it fits the "delightful defaults" part of [the philosophy](https://semgrep.dev/docs/contributing/semgrep-philosophy/) :)

**Describe alternatives you've considered**
I suppose you can have 2 rules...

**Use case**
Any rewrite of a function where I don't want to omit the return type annotation.

**Comment by ikonst** [comment]
I tried to create a type-annotating autofixer which adds `-> None` to all `__init__`s:

```yaml
-  id: __init__-return-none
   message: type __init__ methods to return None
   languages: [ python ]
   severity: ERROR
   patterns:
      - pattern: |
            def __init__($...ARGS):
                $...BODY
      - pattern-not: |
            def __init__($...ARGS) -> None:
                $...BODY
   fix: |
       def __init__($...ARGS) -> None:
            $...BODY
```

This resulted in all the functions' bodies replaced by `$BODY`.

I also tried:
```yaml
   patterns:
      - pattern: |
            def __init__($...ARGS):
                $BODY
...
   fix: |
       def __init__($...ARGS) -> None:
            $BODY
```
but that captured just the first line of the function, and emitted it with indentation that didn't match the rest of the function, resulting in a Python syntax error.
