### ISSUE TITLE
GitLab 15.8.0-pre (fe974781392) Generates warning, sast report type version 14.1.2 is deprecated

### ISSUE THREAD

**Issue by marc-ostrow** [semgrep/semgrep#6871]
When we run `semgrep ci --verbose --gitlab-sast > gl-sast-report.json || true` and we view vulnerabilities introduced in the Security tab for a GitLab CI/CD Pipeline, we get the following warning:

> **Warning parsing security reports**
> Check the messages generated while parsing the following security reports, as they may prevent the results from being ingested by GitLab. Ensure the security report conforms to a supported JSON Schema.
> 
> - [Schema] version 14.1.2 for report type sast is deprecated. However, GitLab will still attempt to parse and ingest this report. Upgrade the security report to one of the following versions: 15.0.0, 15.0.1, 15.0.2, 15.0.4.

**To Reproduce**
We are including a company wide CI/CD configuration which is running `semgrep` in the `returntocorp/semgrep` container image as follows

```yaml
#include the required gitlab SAST base template
include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  #disable all non-semgrep analyzers
  SAST_EXCLUDED_ANALYZERS: "bandit,gosec,eslint,spotbugs,flawfinder,semgrep-sast"

semgrep:
  # A Docker image with Semgrep installed.
  image: returntocorp/semgrep
  # Run the "semgrep ci" command on the command line of the docker image.
  # Send the semgrep results to the gitlab security findings report
  # Allow pipeline to proceed despite blocking rules firing (using " || true")
  script: semgrep ci --verbose --gitlab-sast > gl-sast-report.json || true
  artifacts:
    reports:
      sast: gl-sast-report.json
  variables:
    # Use the semgrep pre-written ruleset for command injection
    SEMGREP_RULES: p/command-injection
    SEMGREP_GITLAB_JSON: "1"
```

Typically, projects will override this company wide `semgrep` CI Job to override the `SEMGREP_RULES` variable, possibly override the Job stage, and add/override CI Job rules.

 `https://gitlab.com/help` returns

> GitLab Enterprise Edition 15.8.0-pre [fe974781392](https://gitlab.com/gitlab-org/gitlab/-/commits/fe974781392)

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build? `an official binary/docker container image`
