### ISSUE TITLE
in Python , taint doesn't flow to **arg

### ISSUE THREAD

**Issue by yuval-piiano** [semgrep/semgrep#6920]
for this code:
```
def taint_test(param1):
    x = tainted
    #ruleid: test
    sink(x)
    #ruleid: test
    sink(**x)
```
a taint should flow from x = tainted to sink(**x) with this rule:

```
rules:
  - id: test
    languages:
      - python
    message: taint demo
    severity: WARNING
    mode: taint
    pattern-sources:
      - pattern: tainted
    pattern-sinks:
      - pattern: sink(...)
      
```

**To Reproduce**
https://semgrep.dev/playground/s/oWJ0

**Expected behavior**
sunk(**x) should be detected

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
using semgrep.dev 

**Use case**
More complete taint analysis of quite common python code
