### ISSUE TITLE
semgrep CLI command to generate rule starter

### ISSUE THREAD

**Issue by jcrumb-u21** [semgrep/semgrep#7000]
**Is your feature request related to a problem? Please describe.**
When creating a new custom rule on the CLI, it's easy to forget which fields are required and what a minimal rule file looks like. Often, I end up going to the semgrep playground, creating a new rule there, and then copying/pasting the contents into my editor.

**Describe the solution you'd like**
It would be great to have a CLI command like `semgrep scaffold` or `semgrep new` which takes a target language as an argument and writes to disk a file containing the minimum set of fields required to get started on my rule. As an example, given `semgrep scaffold my-rule.yaml --python` I'd expect the following output:
```yaml
rules:
  - id: my_rule
    pattern: print("...")
    message: Semgrep found a match
    languages: [python]
    severity: WARNING
```

This is similar to how the playground behaves today.

**Describe alternatives you've considered**
There is a 3rd party VS Code extension that provides similar functionality, but only works if you use VS Code: https://marketplace.visualstudio.com/items?itemName=lewisardern.semgrep-snippets

**Use case**
Less annoying custom rule creation.

**Additional context**
