### ISSUE TITLE
Semgrep does not match a "return" without a semicolon in Rust

### ISSUE THREAD

**Issue by Vasco-jofra** [semgrep/semgrep#7061]
**Describe the bug**
Semgrep does not match a "return" without a semicolon in Rust

**To Reproduce**
The example that reproduces the bug is shown below and in the following link: https://semgrep.dev/s/X36e
```yaml
rules:
  - id: rust-not-matching-inside-function
    message: Should match
    languages:
      - rust
    severity: WARNING
    patterns:
      - pattern: |
          3
```

```rust
fn return_3() -> i32 {
    // ruleid: rust-not-matching-return-with-semicolumn
    3
}

fn return_3() -> i32 {
    // ruleid: rust-not-matching-return-with-semicolumn
    3;
    // ruleid: rust-not-matching-return-with-semicolumn
    return 3;
}

// ruleid: rust-not-matching-return-with-semicolumn
3
```

**Expected behavior**
The 3 inside the `return_3` function should match
```rust
fn return_3() -> i32 {
    // ruleid: rust-not-matching-return-with-semicolumn
    3
}
```

**What is the priority of the bug to you?**
 P0: blocking your adoption of Semgrep or workflow (I cannot write the rule I want to, without this being fixed)
