### ISSUE TITLE
JavaScript: patterns not working for functions without return expression

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#720]
**Describe the bug**
not able to find patterns inside functions that do not return anything

not working:
https://semgrep.live/dd5
```yaml
rules:
- id: yo-yo
  message: yo
  severity: WARNING 
  languages: [javascript] 
  patterns:
  - pattern: |
      function $X(...) {
        ...
        foo(...);
        ...
      }
```

```javascript
function someFunc(val) {
    foo('123')
}
```

working:
https://semgrep.live/ZdL

```yaml
rules:
- id: yo-yo
  message: yo
  severity: WARNING 
  languages: [javascript] 
  patterns:
  - pattern: |
      function $X(...) {
        ...
        foo(...);
        ...
      }
```

```javascript
function someFunc(val) {
    foo('123')
    return true
}
```
