### ISSUE TITLE
Kotlin taint mode does not work with function call in sanitizer

### ISSUE THREAD

**Issue by Anni-eck** [semgrep/semgrep#7202]
**Describe the bug**
When writing a Kotlin rule using the taint mode, a sanitizer that contains a function call is not accurately detected.

More context: I'm trying to write a rule that detects path traversal vulnerabilities. A simplified version is that my source pattern is detecting an http request being received, the taint is a file being opened, and the sanitizer is some Apache Commons FilenameUtils function. However the rule is triggered even though the sanitizer is present. This only occurs when the sanitizer features a function being called (alternatives I tried reported below). A simplified version of my code and rule below for clarity .

**To Reproduce**
My code:
```
class FileManager{
    @Get("/retrievesafe")
    fun getsecurefile(request: HttpServletRequest): String {
       var filepath: String = request.getParameter("file")
       var filesanitized = FilenameUtils.getName(filepath)
// ok:kt-httpservlet-path-traversal
       var file: File = File(filesanitized)
       return "hello"
        }
    }
```

My rule:
```
rules:
  - id: kt-httpservlet-path-traversal
    metadata:
      category: security
    message: >-
      Redacted for brevity
    mode: taint
    pattern-sources:
    - pattern: |
        fun $FUNNAME($REQ: HttpServletRequest): $RET {...}
    pattern-sanitizers:
        - pattern: |
            FilenameUtils.getName(...)
    pattern-sinks:
        - pattern: |
            File($FILE)
    severity: ERROR
    languages:
      - kotlin
```

**Expected behavior**
The rule detects the sanitizer and reports that the file is ok.

**Actual behavior**
The rule triggers and reports the line "var file: File = File(filesanitized)" as the offending line.

**More observations**
When the pattern `FilenameUtils.getName(...)` is tested in isolation (as a separate rule, just to see if semgrep will find it) it is accurately detected

When the sanitizer pattern is changed to `var $VAR = $BLAH` the sanitizer is correctly detected and the rule reports the code as OK

When a different line with a function call is added to the code and added as a sanitizer, e.g.:
Code:
`Dostuff(filepath)`
Pattern for sanitizer:
`Dostuff(...)`
the sanitizer is NOT used correctly and the code is reported as bad even though the sanitizer is present in it.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep 1.12.1 on ubuntu running on WSL. Same behavior replicated in the playground.

**Use case**
Write functioning taint mode rules.
