### ISSUE TITLE
Pattern parse error for Solidity enum and events not found

### ISSUE THREAD

**Issue by josepchetrit12** [semgrep/semgrep#7230]
**Describe the bug**
Semgrep seems to run into a pattern parse error when trying to use Solidity enum in rules. And the events is not being found.

**To Reproduce**
I am trying to match the following Solidity code:
```solidity
contract MyContract {
    enum Status {
        BLOCKED,
        ACTIVATED
    }
    event UserUnblocked(address indexed userAddress_);
}
```
I wrote the following rule to match Solidity enums in the semgrep playground (see https://semgrep.dev/s/vwjW):
```yml
rules:
  - id: test-enum
    pattern: enum $ENUM {...}
    message: Found a enum.
    languages:
      - solidity
    severity: WARNING
```
This results in a pattern parse error.
I wrote the following rule to match Solidity events in the semgrep playground (see https://semgrep.dev/s/ERWE):
```yml
rules:
  - id: test-events
    pattern: event $EVENT(...);
    message: Found a event.
    languages:
      - solidity
    severity: WARNING

```
This results in the event not being found but does not result in a parse error.
**Expected behavior**
I expect the above rules to result in a match for the above Solidity code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Building rules for detecting security-critical issues in Solidity code
