### ISSUE TITLE
Add support of JavaServer Pages (JSP) scriptlets for Java rules

### ISSUE THREAD

**Issue by Kirill89** [semgrep/semgrep#7276]
**Is your feature request related to a problem? Please describe.**

It is possible to place Java code inside `.jsp` files ([scriptlets](https://www.baeldung.com/jsp#syntax)). I'd like to be able to scan `.jsp` files with the same rules as I use in Java.

**Describe alternatives you've considered**

One possible workaround I plan to use is replacing everything but Java code in scriptlets with spaces and then scanning files with Semgrep. Theoretically should work.

**Use case**

Improve rules coverage of Web Java projects.

**Additional context**

You can find many test cases here: https://github.com/sectooladdict/wavsep/blob/master/WebContent/active/SQL-Injection/SInjection-Detection-Evaluation-GET-200Error-Experimental/Case01-InjectionInInsertValues-String-BinaryDeliberateRuntimeError-With200Errors.jsp

**Comment by IagoAbal** [comment]
Extract-mode should help here, PR #7273 is doing some bug fixing so maybe you should try it once it's merged. See https://semgrep.dev/docs/writing-rules/experiments/extract-mode/.

**Comment by Kirill89** [comment]
@IagoAbal I'm actively experimenting with `extract` mode. I made a rule which looks like this:

```yaml
rules:
  - id: extract-jsp-to-java
    mode: extract
    pattern-regex: <%(?![=@!])([\S\s]+?)%>
# I also tried
#    patterns:
#      - pattern-regex: <%([\S\s]+?)%>
#      - pattern-not-regex: <%@
#      - pattern-not-regex: <%!
    reduce: concat
    extract: $1
    dest-language: java
    languages:
      - regex
    paths:
      include:
        - "*.jsp"
```

My test file is:

```jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@page import="java.sql.*" %>
<%@page import="com.sectooladdict.database.ConnectionPoolManager" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Case 1 - Injection into string values in a login page with erroneous responses</title>
</head>
<body>

<%
if (request.getParameter("username") == null
	&& request.getParameter("password") == null	) {
%>
	Login Page:<br><br>
	<form name="frmInput" id="frmInput" action="Case01-InjectionInLogin-String-LoginBypass-WithErrors.jsp" method="POST">
		<input type="text" name="username" id="username"><br>
		<input type="password" name="password" id="password"><br>
		<input type=submit value="submit">
	</form>
<%
}
else {
	Connection conn = null;
    try {
  	    String username = request.getParameter("username");
  	    String password = request.getParameter("password");

  	    conn = ConnectionPoolManager.getConnection();

        System.out.print("Connection Opened Successfully\n");

 	    String SqlString =
            "SELECT username, password " +
 	        "FROM users " +
 	        "WHERE username='" + username + "'" +
 	        " AND password='" + password + "'";
 		Statement stmt = conn.createStatement();
 		ResultSet rs = stmt.executeQuery(SqlString);

 		if(rs.next()) {
 			out.println("hello " + rs.getString(1));
 	    } else {
 	 		out.println("login failed");
 	 	}

	  	out.flush();

	  	if(conn != null) {
        	ConnectionPoolManager.closeConnection(conn);
        }

    } catch (Exception e) {
        response.sendError(500,"Exception details: " + e);

        if(!(e instanceof com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException)) {
  	        System.out.println("Exception details: " + e);
        }

		if(conn != null) {
        	ConnectionPoolManager.closeConnection(conn);
        }
    }
} //end of if/else block
%>

</body>
</html>
```

It doesn't work because of `<%@ page` scriptlets. If I remove the first four lines of the test file, it works. Otherwise I have `(Failure "not a program")` error.

**Comment by IagoAbal** [comment]
Have you tried with PR #7273? I just know it's fixing some bugs, and your rule seems like it should work. There should be a Docker image `returntocorp/semgrep:pr-7273` that you can use.

**Comment by Kirill89** [comment]
@IagoAbal, I verified my case with the PR you suggested. Unfortunately, the behavior is the same: `(Failure "not a program")` error. Maybe something is wrong with my `extract` rule?

**Comment by emjin** [comment]
Hey! I'm having trouble reproducing your error. This is the rule file I ran on your target:
```
rules:
  - id: extract-jsp-to-java
    mode: extract
    pattern-regex: <%(?![=@!])([\S\s]+?)%>
# I also tried
#    patterns:
#      - pattern-regex: <%([\S\s]+?)%>
#      - pattern-not-regex: <%@
#      - pattern-not-regex: <%!
    reduce: concat
    extract: $1
    dest-language: java
    languages:
      - regex
    paths:
      include:
        - "*.jsp"
  - id: some-java-rule
    pattern: $X == null
    languages:
       - java
    severity: ERROR
    message: none
```

On my branch, I get:
```
➜  semgrep git:(emma/pa-2591-fix-extract-mode) ✗ semgrep --config user.yaml user.jsp
Scanning 1 file.
           
           
┌─────────┐
│ Results │
└─────────┘
Findings:

  user.jsp 
     some-java-rule
        none

         14┆ if (request.getParameter("username") == null
          ⋮┆----------------------------------------
         15┆ && request.getParameter("password") == null	) {
```

Can you share more about how you're running this?

**Comment by Kirill89** [comment]
@emjin, thanks a lot for your answer. I think I found out why it worked for you and not for me:

I was running Semgrep with the `--scan-unknown-extensions` flag. Like `semgrep --config 1.yml --config 2.yml x.jsp --scan-unknown-extensions`.

Where `1.yml` is the extract rule and `2.yml` is the rule I'm trying to run.

If I remove `--scan-unknown-extensions`, the rule works as expected. I'll verify tomorrow if the rest of the rules work as expected.

**Comment by Kirill89** [comment]
I found another problem with `extract` mode – metavars position in the original file is broken.

```shell
semgrep --config semgrep_extract_jsp_to_java.yml SQLInjectionExample.jsp --json | jq .
```

__semgrep_extract_jsp_to_java.yml__

```yaml
rules:
  - id: semgrep_extract_jsp_to_java
    mode: extract
    patterns:
      - pattern-either:
          - patterns:
              - pattern-regex: <%([\S\s]+?)%>
              - pattern-not-regex: <%@([\S\s]+?)%>
              - pattern-not-regex: <%!([\S\s]+?)%>
              - pattern-not-regex: <%=([\S\s]+?)%>
              - pattern-not-regex: <%--([\S\s]+?)--%>
          - pattern-regex: <jsp:scriptlet>([\S\s]+?)</jsp:scriptlet>
    reduce: concat
    extract: $1
    dest-language: java
    languages:
      - regex
    paths:
      include:
        - "*.jsp"
  - id: __test
    pattern: DriverManager.$FN(...);
    languages:
      - java
    message: n
    severity: WARNING

```


__SQLInjectionExample.jsp__

```jsp
<%@ page import="java.sql.*" %>
<html>
<body>
<%
    String userInputA = request.getParameter("A");
%>
<div>
    <%
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root", "root");

        String query = "SELECT * FROM users WHERE username = '" + userInputA + "';";
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(query);
    %>
    <br/>
    <%
        while (rs.next()) {
            String username = rs.getString("username");
            String password = rs.getString("password");

            out.println("Username: " + username);
            out.println("Password: " + password);
        }
    %>
</div>
</body>
</html>
```

__output__

```json
{
  "errors": [],
  "paths": {
    "_comment": "<add --verbose for a list of skipped paths>",
    "scanned": [
      "SQLInjectionExample.jsp"
    ]
  },
  "results": [
    {
      "check_id": __test",
      "end": {
        "col": 103,
        "line": 9,
        "offset": 218
      },
      "extra": {
        "engine_kind": "OSS",
        "fingerprint": "8634fdead9862fe36eb700b2eb993b8b16f250308c51dda6228f885db57eb660c44da2e32fec179f7613a4a70d524e5139cf2f3d8055c552983954324a9e6484_0",
        "is_ignored": false,
        "lines": "        Connection con = DriverManager.getConnection(\"jdbc:mysql://localhost:3306/db\", \"root\", \"root\");",
        "message": "n",
        "metadata": {},
        "metavars": {
          "$FN": {
            "abstract_content": "getConnection",
            "end": {
              "col": 53,
              "line": 4,
              "offset": 132
            },
            "start": {
              "col": 40,
              "line": 4,
              "offset": 119
            }
          }
        },
        "severity": "WARNING"
      },
      "path": "SQLInjectionExample.jsp",
      "start": {
        "col": 9,
        "line": 9,
        "offset": 124
      }
    }
  ],
  "version": "1.15.0"
}
```

See `metavars.$FN.start.line` is `4` (should be `9`).
