### ISSUE TITLE
No emit of events found in Solidity when events have more than one parameter

### ISSUE THREAD

**Issue by josepchetrit12** [semgrep/semgrep#7281]
**Describe the bug**
Emits of events are not found if it has more than one parameter

**To Reproduce**
I am trying to match the following Solidity code:
```solidity
contract MyContract {
    
    event UserUnblocked1(address indexed userAddress_, uint256 amount);
    
    event UserUnblocked2(address indexed userAddress_);
    
    function test() public{
        // todoruleid: test-event-multiple-parameters
        emit UserUnblocked1(msg.sender, 10);
        // ruleid: test-event-multiple-parameters
        emit UserUnblocked2(msg.sender);
        
    }
}
```
I wrote the following rule to match Solidity events with multiple parameters in the semgrep playground (see https://semgrep.dev/s/7Oq4):
```yml
rules:
  - id: test-event-multiple-parameters
    pattern: emit $EVENT(...);
    message: Found a event with multiple parameters.
    languages:
      - solidity
    severity: WARNING
```
This results in one emit event not being found
**Expected behavior**
I expect the two emits be a match.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Building rules for detecting security-critical issues in Solidity code
