### ISSUE TITLE
Clojure: simple patterns rule not matching

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#7308]
Hi !
I'm trying to recreate an RCE/shell injection rule for Clojure, with a simple match on the import + usage of the shell
I'm suspecting it's not doing an AND with all the patterns.

```clj
(require '[clojure.java.shell :refer [sh]])
  (:require [clojure.java.io :as io]
            [clojure.java.shell :as shell])
  (:use [clojure.string :only [replace-first split upper-case trim-newline join]]
        [clojure.java.shell :only [sh]]
        [clojure.tools.cli :only (cli)])


(use '[clojure.java.shell :only [sh]])
(println (:out (sh "echo" "Printing a command-line output")))
```

and the rule, you can test and comment out the pattern-either, it will match the call to `sh`, and if you only use the pattern-either, it will match all the import statements, but I can't combine the two somehow.

```
rules:
- id: command-injection-formatted-runtime-call
  patterns:
  - pattern-either:
    - pattern: (require ... '[clojure.java.shell ...] ... )
    - pattern: (:require ... [clojure.java.shell ...] ... )
    - pattern: (:use ... [clojure.java.shell ...] ... )
  - pattern: (sh "..." "...")
  languages: [clojure]
  severity: WARNING
  message: An issue was found
```

I also tried changing the last pattern to `- pattern: (sh $X $R)` but it's also not working
