### ISSUE TITLE
Java: Find static method usage

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#733]
Not able to find static method usage in Java
https://semgrep.live/dxY

```yaml
rules:
- id: cipher-test
  message: |
  severity: WARNING
  languages: [java]
  pattern-either:
    - pattern: Cipher.getInstance("...");
```

```java
package testcode.crypto;

import javax.crypto.Cipher;

import java.security.Provider;

public class BlockCipherList {

    public static void main(String[] args) throws Exception {
        Cipher c = Cipher.getInstance("DES/ECB/PKCS5Padding");
        Cipher.getInstance("AES/CBC/NoPadding");
    }

}

```

**Comment by inkz** [comment]
one more example https://semgrep.live/ybO

```yaml
rules:
- id: posix-test
  message: |
    posix test
  severity: WARNING
  languages: [java]
  pattern-either:
  - pattern: Files.setPosixFilePermissions(...);
  - pattern: PosixFilePermissions.fromString(...);
  - pattern: Paths.get(...);
  - pattern: PosixFilePermission.OWNER_READ
```

```java
package testcode.file.permissions;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.HashSet;
import java.util.Set;

public class JavaNioPosixApi {

    public static void notOk() throws IOException {
        Files.setPosixFilePermissions(Paths.get("/var/opt/app/init_script.sh"), PosixFilePermissions.fromString("rw-rw-rw-"));
        Set<PosixFilePermission> perms = new HashSet<>();
        perms.add(PosixFilePermission.OWNER_READ);
        Files.setPosixFilePermissions(Paths.get("/var/opt/app/init_script.sh"),perms);
    }

}
```

none of the static methods and constants is found
