### ISSUE TITLE
Simple taint analysis failing in Rust

### ISSUE THREAD

**Issue by jgaleotti** [semgrep/semgrep#7331]
**Describe the bug**
The taint analysis seems to be not working properly in Rust

**To Reproduce**
Given the following yaml file
```
rules:
- id: rust_taint_analysis
  languages:
      - rust
  mode: taint
  pattern-sources:
      - pattern: source()
  pattern-sinks:
      - pattern: sink(...)
  message: Semgrep found a match
  severity: WARNING

```
Semgrep fails to find the taint on this sequential code:
```
fn source() -> i32 {
    15
}

fn sink(_: i32) {
    {}
}

fn main() {
    println!("Hello, world!");
    let val = source();
    sink(val);
}
```
However, it finds the rule on the code
```
fn main2() {
    println!("Hello, world!");
    sink(source());
}
```

**Expected behavior**
Semgrep should find the match of the taint_analysis_rule rule
```
Findings:

  src/main.rs 
     rust_taint_analysis
        Semgrep found a match

         12┆ let val = source();
         ....
         14┆ sink(val);
```

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
I am running semgrep on a Mac installed via bew
```
% semgrep --version                                 
1.14.0
```

**Use case**
What will fixing this bug enable for you?
It will allow us to use semgrep to study smart contracts written in Rust
