### ISSUE TITLE
typescript/javascript `async` arrow function not fixed/replaced properly

### ISSUE THREAD

**Issue by isthisnagee** [semgrep/semgrep#7353]
**Describe the bug**

An async argument doesn't get replaced properly. Below I have a demo of a pattern and a fix that are equivalent, so I would expect no changes in the "fix". However, they output is invalid code. 

**To Reproduce**
https://semgrep.dev/s/PZKq

```
rules:
  - id: demo
    pattern: fnTakingAsyncArg($X)
    fix: fnTakingAsyncArg($X)
    message: |
      Verifying that an async param is not matched.
    languages:
      - ts
    severity: WARNING
```

**Expected behavior**

I'd expect that nothing would actually change, and `fnTakingAsyncArg(async () => {})` would be replaced with `fnTakingAsyncArg(async () => {})`. However, the result is `fnTakingAsyncArg(=>{})`

**Screenshots**
<img width="1004" alt="CleanShot 2023-03-17 at 09 33 06@2x" src="https://user-images.githubusercontent.com/4813262/225964490-42b7e1e4-9001-4b09-929f-6463f4f5d40d.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

Binary
