### ISSUE TITLE
paths does not work on join mode rules

### ISSUE THREAD

**Issue by spaceraccoon** [semgrep/semgrep#7522]
**Describe the bug**
Join mode rules do not support the `paths` key, both at the top-level join mode rule as well as inline rules. At the top-level rule, Semgrep simply ignores it. For inline rules, it throws an error.

**To Reproduce**
Rule: 

Top-level:

```yaml
rules:
- id: aspx-likely-xss
  mode: join
  join:
    rules:
      - id: user-input
        languages:
          - c#
        patterns:
          - pattern-either:
            - pattern: $PARAM_VALUE = Request[$PARAM_NAME];
            - patterns:
                - pattern-inside: $PARAM_VALUE_PRE = Request[$PARAM_NAME];
                - pattern: $PARAM_VALUE = $PARAM_VALUE_PRE;
          - pattern-not-inside: |
              ...
              if ($PARAM_VALUE.$TRANSFORM() == "...") {
                ...
              }
          - pattern-not-inside: |
              ...
              if ($PARAM_VALUE == "...") {
                ...
              }
      - id: aspx-displaying-expression
        patterns:
          - pattern-not-inside: // ...
          - pattern: <%= $PARAM_VALUE %>
        languages:
          - generic
    on:
    - "user-input.$PARAM_VALUE == aspx-displaying-expression.$PARAM_VALUE"
    - "user-input.path > aspx-displaying-expression.path"
  paths:
    include:
      - "*.aspx"
  message: |
    Error found.
  severity: ERROR
```

```console
$ semgrep -f rule.yml .


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 123 files tracked by git with 1 Code rule:
  Nothing to scan.


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 152 files tracked by git with 2 Code rules:

  Language      Rules   Files          Origin    Rules
 ─────────────────────────────        ─────────────────
  <multilang>       1     123          Unknown       2
  csharp            1      22
```

Inline:

```yaml
rules:
- id: aspx-likely-xss
  mode: join
  join:
    rules:
      - id: user-input
        languages:
          - c#
        patterns:
          - pattern-either:
            - pattern: $PARAM_VALUE = Request[$PARAM_NAME];
            - patterns:
                - pattern-inside: $PARAM_VALUE_PRE = Request[$PARAM_NAME];
                - pattern: $PARAM_VALUE = $PARAM_VALUE_PRE;
          - pattern-not-inside: |
              ...
              if ($PARAM_VALUE.$TRANSFORM() == "...") {
                ...
              }
          - pattern-not-inside: |
              ...
              if ($PARAM_VALUE == "...") {
                ...
              }
      - id: aspx-displaying-expression
        patterns:
          - pattern-not-inside: // ...
          - pattern: <%= $PARAM_VALUE %>
        languages:
          - generic
        paths:
          include:
          - "*.aspx"
    on:
    - "user-input.$PARAM_VALUE == aspx-displaying-expression.$PARAM_VALUE"
    - "user-input.path > aspx-displaying-expression.path"
  message: |
    Error found.
  severity: ERROR
```
```console
$ semgrep -f rule.yml .
semgrep error: Invalid rule schema
  --> rule.yml:25
25 |       - id: aspx-displaying-expression
26 |         patterns:
27 |           - pattern-not-inside: // ...
28 |           - pattern: <%= $PARAM_VALUE %>
29 |         languages:
30 |           - generic
31 |         paths:
32 |           include:
33 |           - "*.aspx"
34 |     on:

Additional properties are not allowed ('paths' was unexpected)
```

**Expected behavior**
`paths` should be supported by join mode rules, including inline rules.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Official binary

**Use case**
What will fixing this bug enable for you?

It will allow less resource-intensive join mode rules
