### ISSUE TITLE
Typescript local vars shadow instance vars

### ISSUE THREAD

**Issue by sburf-rokt** [semgrep/semgrep#7555]
**Describe the bug**

Local variables with the same name as instance variables prevent metavariable type matching.

**To Reproduce**

This rule:
```yaml
rules:
  - id: rule-id
    patterns:
      - pattern: ($SVC: NrMessageService).$METHOD(...);
    message: Usage of $SVC.$METHOD(...)
    severity: INFO
    languages:
      - typescript 
```

Matches in `willMatch()` but not in `wontMatch()` for this code, even though both execute fine:
```javascript
mport { Injectable } from '@angular/core';
import { NrMessageService } from 'some/message';

export interface FSMsg {
  text: string;
}

@Injectable({ providedIn: 'root' })
export class FlashService {
  constructor(
    private ms: NrMessageService,
  ) {}

  private wontMatch(m: FSMsg) {
    const ms = m.text;
    // ruleid: rule-id
    this.ms.success(ms);
  }

  private willMatch(m: FSMsg) {
    const msg = m.text;
    // ruleid: rule-id
    this.ms.success(msg);
  }
}
```

**Expected behavior**

Local variables should not mask instance variables.  Both `willMatch()` and `wontMatch()` should have matched the above rule.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [2] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

This is reproduceable in semgrep.dev/playground

**Use case**

I noticed that some usages of NrMessageService were not found by Semgrep, preventing analysis of their usage.

This rule finds files that my analysis is missing (but not the usage of the service):
```yaml
rules:
  - id: missed-rule-id
    patterns:
      - pattern-inside: import { NrMessageService } from 'some/message';
      - pattern-not: ($SVC: NrMessageService).$METHOD(...);
    message: This file uses NrMessageService, but we cannot see where.
    severity: WARNING
    languages:
      - typescript 
```
