### ISSUE TITLE
Message field for Semgrep Join mode rule does not display metavariable output properly

### ISSUE THREAD

**Issue by fishp0rridg3** [semgrep/semgrep#7556]
**Describe the bug**
In Join mode, the `message` field under the `Rules` key does not output metavariables properly in the semgrep result.

**To Reproduce**

Rule:
```
rules:
- id: aspx-likely-xss
  mode: join
  join:
    rules:
      - id: user_input_and_source_checker
        patterns: 
          - pattern: $PARAM_VALUE = Request[$PARAM_NAME];
          - pattern-not-inside: |
              ...
              if ($PARAM_VALUE.$TRANSFORM() == "...")
                ...
              else if ($PARAM_VALUE.$TRANSFORM() == "...")
                ...
        languages:
          - c#
      - id: aspx_displaying_expression
        patterns:
          - pattern-not-inside: // ...
          - pattern: <%= $PARAM_VALUE %>
        languages:
          - generic
    on:
    - 'user_input_and_source_checker.$PARAM_VALUE == aspx_displaying_expression.$PARAM_VALUE'
    - 'user_input_and_source_checker.path > aspx_displaying_expression.path'
  message: |
    http parameter input from '$PARAM_VALUE' is reflected unsanitized in <>, leading to XSS.
  severity: ERROR
```

Command and Result:
```
$ semgrep -f rule.yml .

┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 149 files tracked by git with 1 Code rule:
  Nothing to scan.
               
               
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 149 files tracked by git with 2 Code rules:
                                                                                                                        
  Language      Rules   Files          Origin    Rules                                                                  
 ─────────────────────────────        ─────────────────                                                                 
  <multilang>       1     147          Unknown       2                                                                  
  csharp            1      29                                                                                           
                                                                                                                        
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:02                                                                                                                        
                  
                  
┌────────────────┐
│ 1 Code Finding │
└────────────────┘
                                                         
    Path/To/File 
       aspx-likely-xss                                                                  
          http parameter input from '$PARAM_VALUE' is reflected unsanitized in <>, leading to XSS.
                                                                                                  
          RESULT_REDACTED

                
                
┌──────────────┐
│ Scan Summary │
└──────────────┘

Ran 1 rule on 0 files: 1 finding.

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
```

**Expected behavior**
The output message should have been: `http parameter input from ACTUAL_VARIABLE_OUTPUT is reflected unsanitized in <>, leading to XSS.`

I also noticed that the Semgrep documentation also has this problem in its output, which confirmed the error to me. This is reflected in the screenshot below and the URL is as follows:

[https://semgrep.dev/docs/writing-rules/experiments/join-mode/overview/#on](url)

**Screenshots**

![Capture](https://user-images.githubusercontent.com/119428361/232733045-bcaf326f-326c-4056-81b4-630943820266.PNG)


**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Official binary.

**Use case**
What will fixing this bug enable for you?
Displaying correct metavariable output will help to identify faulty code more efficiently.
