### ISSUE TITLE
Handle poorly defined expressions gracefully in pattern-regex

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#758]
Using the following rule file:

```yaml
$ cat test.yaml 
rules:
  - id: test-regex
    patterns:
        - pattern-inside: boto3.client(host="...")
        - pattern-regex: '(abc'
    message: "test regex message"
    languages: [python]
    severity: ERROR
```

We get the following exception:

```
$ python -m semgrep -j 1 --config test.yaml test_dir/
multiprocessing.pool.RemoteTraceback: 
...
    for match in re.finditer(pattern["pattern"], contents)
...
re.error: missing ), unterminated subpattern at position 0
```

Let's gracefully handle `re.error` instead of throwing an exception.
