### ISSUE TITLE
pattern-regex does not have start and end line numbers

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#765]
pattern-regex does not fill `start` and `end` fields. Relatedly this causes semgrep.live to crash

 https://semgrep.live/O22?version=e4e89dcbe40830bfb8d5a8e5341e5587824e1770

```
rules:
  - id: boto-client-ip
    patterns:
      - pattern-regex: '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
    message: "boto client using IP address"
    languages: [python]
    severity: ERROR
```

on 

```
x = "1.1.1.1"
```
