### ISSUE TITLE
Or/And operators inside join "on" conditions

### ISSUE THREAD

**Issue by gand3lf** [semgrep/semgrep#7685]
**Describe the solution you'd like**
Hi guys!
I simply would like to do this:
```yaml
    on:
    - 'rule1.$VAR == rule2.$VAR || rule1.$VAR == rule2.$VAR2'
```
In other words: Is it possible to implement the OR operator within the ON conditions of the join mode?
Thank you!

**Comment by emjin** [comment]
Hello! I'm exploring different syntaxes for join mode. Could you share a more concrete example? Want to check whether the other options support this nicely!

**Comment by gand3lf** [comment]
Hi @emjin! Thank you for the answer.
Please consider the example of join mode described in the Semgrep documentation:
```yaml
rules:
- id: flask-likely-xss
  mode: join
  join:
    rules:
      - id: user-input
        pattern: |
          $VAR = flask.request.$SOMETHING.get(...)
        languages: [python]
      - id: unescaped-extensions
        languages: [python]
        patterns:
        - pattern: |
            flask.render_template("$TEMPLATE", ..., $KWARG=$VAR, ...)
        - metavariable-pattern:
            metavariable: $TEMPLATE
            language: generic
            patterns:
            - pattern-not-regex: .*\.html$
      - id: template-vars
        languages: [generic]
        pattern: |
          {{ $VAR }}
    on:
    - 'user-input.$VAR == unescaped-extensions.$VAR'
    - 'unescaped-extensions.$KWARG == template-vars.$VAR'
    - 'unescaped-extensions.$TEMPLATE < template-vars.path'
  message: |
    Detected a XSS vulnerability: '$VAR' is rendered
    unsafely in '$TEMPLATE'.
  severity: ERROR
```

Consider the situation where in the same row you obtain more than one input, for example:
```python
(x, y, z) = flask.request.cookies.get("test"), flask.request.form.get("test2"),flask.request.args.get("test3")
```
The rule to match the aforementioned Python row is:
```yaml
 - pattern: ($A, $B, $C)=flask.request.cookies.get("..."),flask.request.form.get("..."),flask.request.args.get("...")
```
In this case we have 3 metavariables with different names and could be useful to do:
```yaml
on:
    - 'user-input.$A == unescaped-extensions.$VAR || user-input.$B == unescaped-extensions.$VAR || user-input.$C == unescaped-extensions.$VAR'
```

I hope the scenario makes sense!
