### ISSUE TITLE
JavaScript template string pattern result has incorrect range

### ISSUE THREAD

**Issue by Kirill89** [semgrep/semgrep#7695]
**Describe the bug**

I use a pattern to detect template strings in JS code. Sometimes the match position of the detected template string is incorrect.

The pattern 

```yaml
pattern: "`...`"
```

in JS code

```javascript
const foo = '123';
const bar = `${foo}`;
```

detects

```
`${foo
```

**Expected behavior**

```
`${foo}`
```

**To Reproduce**

https://semgrep.dev/s/LlnX

**Screenshots**

<img width="823" alt="Screenshot 2023-05-01 at 16 47 38" src="https://user-images.githubusercontent.com/2003936/235460827-f44431ba-544a-4a36-a91c-1666170e923b.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by icholy** [comment]
This bug makes it impossible to write autofixes that deal with template strings:

**rule:**

``` yaml
rules:
  - id: bug
    patterns:
      - pattern: console.log($MSG)
    fix: console.log($MSG, "hello");
    message: Semgrep found a match
    languages: [javascript]
    severity: WARNING
```

**input:**
``` js
console.log(`this is a test ${id}`)
```

**output:**
``` js
console.log(`this is a test ${id, "hello");
```

**playground:** https://semgrep.dev/playground/s/A2KB
