### ISSUE TITLE
Document cross-pattern metavariable functionality

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#778]
#712 implemented cross-pattern metavariable usage, which can be useful as an additional filter to multi-pattern rules. E.g.

```yaml
    patterns:
      - pattern-inside: |
          $X = request.get("...")
          ...
      - pattern: open($X)
```

`$X` must be the same across the patterns. That is, we don't care if just anything is passed to `open`, we only care if request data is passed to `open`.

We should document this functionality because:

- We don't what this behavior to come as a surprise to users. I can imagine that different users both expect and don't expect this behavior, so we should definitely clear it up.
- User's will want to know when this functionality applies. Does it apply to all pattern operators? Are there exceptions?

My recommended approach would be to include cross-pattern information and an example for each pattern operator here: https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md
