### ISSUE TITLE
Ruby: taint not connecting source to sink when method call is done with omitted parenthesis

### ISSUE THREAD

**Issue by joaxcar** [semgrep/semgrep#7787]
**Describe the bug**
In Ruby you can omit the parenthesis on a method call, and in particular if the method does not take any arguments you can call it by just its name, like this
```ruby
def my_func
   "hello"
end

my_func
```
The `my_func` in the end is an expression and a function call and the program will return "hello". When writing a taint query in Semgrep for Ruby I can not get Semgrep to follow this data path from source to sink

<img width="359" alt="ruby" src="https://github.com/returntocorp/semgrep/assets/37298485/076c08b9-72b4-4d38-9116-62e7c3c4d408">

this is somewhat related to https://github.com/returntocorp/semgrep/issues/5222 but more serious. Also see https://ruby-for-beginners.rubymonstas.org/bonus/parentheses.html

**To Reproduce**
Test this in the playground (https://semgrep.dev/s/pJld)
Query
```yaml
rules:
  - id: untitled_rule
    languages:
      - ruby
    mode: taint
    message: $DATA
    pattern-sinks:
      - patterns:
          - pattern: $T
          - pattern-inside: print($T)
    pattern-sources:
      - patterns:
          - pattern: |
              def source
              $DATA
              end
```
and the ruby file
```ruby
# The source
def source
  data
end

# This one will fail to match, but is a valid call
def sink
    value = source
    print(value)
end

# The rest here will hit
def sink
    value = source()
    print(value)
end

def sink
    value = source ""
    print(value)
end

def sink
    value = source 1
    print(value)
end

def sink
    value = source ()
    print(value)
end

```

**Expected behavior**
All the sinks above should hit the query, allowing taint to follow though method calls without parenthesis. 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
What will fixing this bug enable for you?

Find bugs in Ruby code that are now being missed as this is a regular pattern

I am new to this so maybe I am doing something wrong, but this is a blocker for my workflow
