### ISSUE TITLE
Multiple rule IDs in the Playground

### ISSUE THREAD

**Issue by gand3lf** [semgrep/semgrep#7791]
Hi guys,
the Semgrep playground does not allow to specify multiple rules, for example:
```yaml
rules:
  - id: first
    pattern: print(1)
    message: Semgrep found a match
    languages: [python]
    severity: WARNING
  - id: second
    pattern: print(2)
    message: Semgrep found a match
    languages: [python]
    severity: WARNING
```

The rule is correct but I obtain the error message: `Rule must have only one rule ID()`.
Could you fix this issue?

Thank you!
