### ISSUE TITLE
Rule tests fail if rule uses a path include config

### ISSUE THREAD

**Issue by goodspark** [semgrep/semgrep#7804]
**Describe the bug**
Rule tests fail if rule uses a path include config.

**To Reproduce**
rule.yml
```yml
rules:
  - id: asd
    languages: [python]
    severity: WARNING
    message: asd
    pattern-regex: (logging|log|logger)\.(warn)\((.*)\)
    fix: $1.warning($3)
    paths:
      include:
        - asd.py
```
rule.py
```py
import logging
logger = logging.getLogger('asd')
# ruleid: asd
logger.warn('zxc')
```
rule.fixed.py
```py
import logging
logger = logging.getLogger('asd')
# ruleid: asd
logger.warning('zxc')
```

```sh
semgrep scan --test
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file with 1 Code rule:
  Nothing to scan.
               
               
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file with 1 Code rule:
  Nothing to scan.
no files modified.
No unit tests found. See https://semgrep.dev/docs/writing-rules/testing-rules
0/1: 1 fix tests did not pass: 
--------------------------------------------------------------------------------
        ✖ rule.fixed.py <> autofix applied to rule.py 

        ---
        +++
        @@ -3 +3 @@
        -logger.warning('zxc')
        +logger.warn('zxc')
```

If I remove the path config or change it to `'*.py'`, the rule tests work fine.

**Expected behavior**
Tests for rules should work regardless of whether a rule uses path include/exclude configs. Path configs are more for running the rules on the actual code. The tests are meant to just validate the rules themselves.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Official build, v1.21.0, Ubuntu 18.04

**Use case**
The intent of using the path include config is to control the rollout of a rule to a portion of a repo.
