### ISSUE TITLE
Semgrep not matching object properties

### ISSUE THREAD

**Issue by omerlh** [semgrep/semgrep#782]
**Describe the bug**
When trying to run semgroup on one of our codebases, I noticed it couldn't find anything although it should.

**To Reproduce**
Using this config file:

```yaml
rules:
  - id: open-never-closed
    pattern: downloadTime
    message: "file object opened without corresponding close"
    languages: [javascript]
    severity: ERROR
```

I expected the code to anything containing the word `downloadTime` - and when using with a search I can find it. 

**Expected behavior**
Find all the lines with this string, like regular find returns.

**Environment**
Version 0.7.0, installed with brew.
