### ISSUE TITLE
Top-level Pattern-Either Creates Warning

### ISSUE THREAD

**Issue by git-blame** [semgrep/semgrep#7952]
**Describe the bug**
`pattern-either` can be one of the required field at the top-level for a rule. However, when it is used, semgrep has a warning message: `skipping unknown field: pattern-either`. This doesn't seem to affect the rule when it comes to matching against files, but this warning may imply that the matching behavior is undefined or not fully specified as per the documentation.

**To Reproduce**
ok.yml:
```yml
rules:
    - id: test-rule
      message: Shows that pattern-either generates warning
      severity: INFO
      languages:
          - c
      patterns:
          - pattern-either:
              - pattern: foobar
              - pattern: deadbeef
```

warn.yml:
```yml
rules:
    - id: test-rule
      message: Shows that pattern-either generates warning
      severity: INFO
      languages:
          - c
      pattern-either:
          - pattern: foobar
          - pattern: deadbeef
```
```sh
semgrep-core -parse_rules *.yml -debug
[0.064  Info       Main.Core_CLI        ] Executed as: semgrep-core -parse_rules ok.yml warn.yml -debug
[0.064  Info       Main.Core_CLI        ] Version: semgrep-core version: 1.24.1
[0.064  Info       Main.Test_parsing    ] processing ok.yml
[0.064  Info       Main.Test_parsing    ] processing warn.yml
[0.064  Warning    Main.Parse_rule      ] skipping unknown field: pattern-either
[0.064  Info       Main.Test_parsing    ] done test_parse_rules
```

```sh
semgrep-core -rules warn.yml -debug -lang c testcase/
[0.040  Info       Main.Core_CLI        ] Executed as: semgrep-core -rules warn.yml -debug -lang c testcase/
[0.040  Info       Main.Core_CLI        ] Version: semgrep-core version: 1.24.1
[0.040  Info       Main.Run_semgrep     ] Parsing warn.yml:
rules:
    - id: test-rule
      message: Shows that pattern-either generates warning
      severity: INFO
      languages:
          - c
      pattern-either:
          - pattern: foobar
          - pattern: deadbeef

[0.040  Warning    Main.Parse_rule      ] skipping unknown field: pattern-either
[0.040  Info       Main.Run_semgrep     ] extracting nested content from 1 files
[0.040  Info       Main.Run_semgrep     ] processing 1 files, skipping 6 files
[0.040  Info       Main.Run_semgrep     ] Analyzing testcase/semgrep/files/hello.c
[0.060  Info       Main.Parse_target    ] Parse_target.parse_and_resolve_name done
testcase/semgrep/files/hello.c:5 with rule test-rule
   char *foobar = s;
[0.064  Info       Main.Run_semgrep     ] found 1 matches, 0 errors
[0.068  Info       Main.Run_semgrep     ] there were 6 skipped targets
```
**Expected behavior**
No warning when `pattern-either` is specified.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
an official binary

**Use case**
guarantee that rules are correctly parsed by engine without errors
