### ISSUE TITLE
In Java metavariable did not capture part of a function parameter if a parameter starts with "("

### ISSUE THREAD

**Issue by Kirill89** [semgrep/semgrep#7957]
**Describe the bug**

Metavariable did not capture part of a function parameter.

Java code:

```
public class A {
  public void a(HttpServletRequest b) {
      var catPicture = 
          new File(catPicturesDirectory, (id == null ? RandomUtils.nextInt(1, 11) : id) + ".jpg");
  }
}
```

Rule:

```
rules:
  - id: test
    patterns:
    - pattern: new $TYPE($ARG_PARENT, $ARG_CHILD);
    - metavariable-regex:
        metavariable: $TYPE
        regex: (File)
    message: "parent: $ARG_PARENT, child: $ARG_CHILD"
    severity: WARNING
    languages:
      - java
```

Expected message: `parent: catPicturesDirectory, child: (id == null ? RandomUtils.nextInt(1, 11) : id) + ".jpg"`
Actual message: `parent: catPicturesDirectory, child: id == null ? RandomUtils.nextInt(1, 11) : id) + ".jpg"`

**To Reproduce**

https://semgrep.dev/playground/s/nEqX

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**

I use Semgrep JSON output as part of my program analysis tool. Correct metavariables positions are important for me.
