### ISSUE TITLE
aliengrep: custom word character '=' breaks pattern matching

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#7988]
**Describe the bug**

Specifying `=` as a word character causes metavariables to not match.

**To Reproduce**

https://semgrep.dev/playground/s/0R5k

Rule:
```
rules:
- id: custom-word-chars
  severity: WARNING
  languages: [generic]
  options:
    generic_engine: aliengrep
    generic_extra_word_characters: ["="]
  message: "found something"
  pattern: "$X"
```

Target:
```
x
```

**Expected behavior**

The pattern `$X` should match the input `x`.

Matching seems to fail as soon as we add `=` to the word characters. For example, the following rule works:

```
rules:
- id: custom-word-chars
  severity: WARNING
  languages: [generic]
  options:
    generic_engine: aliengrep
    generic_extra_word_characters: ["/"]
  message: "found something"
  pattern: "$X"
```

See https://semgrep.dev/playground/s/2BRz

**Screenshots**

![image](https://github.com/returntocorp/semgrep/assets/343265/5931879c-f4f1-4c96-ba1a-e260119856a7)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

any

**Use case**

Capturing base64-encoded data, among other things.
