### ISSUE TITLE
Unable to process gb2312-encoded files

### ISSUE THREAD

**Issue by kayoch1n** [semgrep/semgrep#8015]
**Describe the bug**
The source code I wanted to analyze is encoded in gb2312, while semgrep-core seems to read file in utf8.

**To Reproduce**
Use the following python code to write gb2312-encoded contents to a source file named "gb2312.properties"

```python
with open('/tmp/src/gb2312.properties', mode='w', encoding='gb2312') as f:
    f.write('''#测试编码
test.password=admin
''')
```

And the rule is as follows

```yaml
rules:
- id: gb2312
  message: gb2312
  severity: ERROR
  languages:
    - generic
  patterns:
    - pattern-regex: .*password=.*
    - pattern-not-regex: .*#.*
  paths:
    include:
      - "*.properties"
```

Run semgrep on it `"/usr/local/python310/bin/semgrep" --debug --json --no-git-ignore  --config "/tmp/.rules.yaml" "/tmp/src/"`

```
[0.000  Error      Main.SPcre           ] [1364717] PCRE error: BadUTF8 on input "#\178\226\202\212\177\224\194\235\ntest.password=admin\n"
[0.045  Info       Main.Run_semgrep     ] found 0 matches, 0 errors
[0.045  Info       Main.Run_semgrep     ] there were 1 skipped targets
[0.045  Info       Main.Run_semgrep     ] size of returned JSON string: 745
```

Though I am not familiar with ocaml, semgrep-core seems to read file in utf8. Can I pass encoding-related information via some arguments or environment variables, in order for semgrep-core to read the file in gb2312?

**Expected behavior**
It is expected to report a match

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
