### ISSUE TITLE
Lack of exact version pinning of ruamel.yaml library

### ISSUE THREAD

**Issue by lbbooleans** [semgrep/semgrep#8029]
**Describe the bug**
The `ruamel.yaml` library contains a bug having to do with string values containing colons, ':'

https://sourceforge.net/p/ruamel-yaml/tickets/469/

This bug was introduced in a patch version of ruamel.yaml (0.17.29). However, due to semgrep not pinning the ruamel.yaml version on the patch version (`cli/setup.py` contains the range `ruamel.yaml>=0.16.0,<0.18`), semgrep's behavior in parsing YAML files changed _in the same version_, depending on the moment in time semgrep was installed.

This was probably also the root cause of:
https://github.com/returntocorp/semgrep/issues/7944
and
https://github.com/returntocorp/semgrep-rules/pull/2941
because both seem to be related to the same error, but are workarounds that do not address the actual issue.

**To Reproduce**
Install the current latest version of semgrep:
```
pip install semgrep==1.24.1
```

Take a "bad" rule from https://github.com/returntocorp/semgrep-rules/pull/2941 before it was modified:
```
rules:
- id: python.lang.security.audit.network.bind.avoid-bind-to-all-interfaces
  languages:
  - python
  message: Running `socket.bind` to 0.0.0.0, ::, or empty string could unexpectedly
    expose the server publicly as it binds to all available interfaces. Consider instead
    getting correct address from an environment variable or configuration file.
  metadata:
    category: security
    confidence: HIGH
    cwe:
    - 'CWE-200: Exposure of Sensitive Information to an Unauthorized Actor'
    cwe2021-top25: true
    impact: MEDIUM
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    likelihood: HIGH
    owasp:
    - A01:2021 - Broken Access Control
    references:
    - https://owasp.org/Top10/A01_2021-Broken_Access_Control
    semgrep.dev:
      rule:
        origin: community
        rule_id: OrU3og
        url: https://semgrep.dev/playground/r/5PTY5G/python.lang.security.audit.network.bind.avoid-bind-to-all-interfaces
        version_id: 5PTY5G
    shortlink: https://sg.run/rdln
    source: https://semgrep.dev/r/python.lang.security.audit.network.bind.avoid-bind-to-all-interfaces
    subcategory:
    - vuln
    technology:
    - python
  pattern-either:
  - pattern: '$S = socket.socket(...)

      ...

      $S.bind(("0.0.0.0", ...))

      '
  - pattern: '$S = socket.socket(...)

      ...

      $S.bind(("::", ...))

      '
  - pattern: '$S = socket.socket(...)

      ...

      $S.bind(("", ...))

      '
  severity: INFO
```

Validate with semgrep:
```
$ semgrep --config bad-rule.yml --validate
Configuration is invalid - found 1 configuration error(s), and 0 rule(s).
[ERROR] Invalid YAML file bad-rule.yml:
	while parsing a block mapping
	  in "<file>", line 2, column 3
	expected <block end>, but found '<scalar>'
	  in "<file>", line 5, column 47
```

This hits the ruamel.yaml bug. Now, when we force a downgrade of the patch version of ruamel.yaml _right_ before the bug was introduced:
```
pip install ruamel.yaml==0.17.28
```
.. and validate again, it works fine:
```
$ semgrep --config bad-rule.yml --validate
Configuration is valid - found 0 configuration error(s), and 1 rule(s).
```

In our situation, we experienced different behavior overnight due to the way pinning happens on ruamel.yaml's minor range inside semgrep, which caused some headaches trying to figure out what went wrong while using the exact same version of semgrep, only a new installation (we install semgrep during CI/CD runs), but fortunately we now have a good understanding of the issue.

**Expected behavior**
For important dependencies like these, it might make sense to pin them on the exact (patch) version, to avoid changing behavior between semgrep installs of the exact same version.

**Screenshots**
None, but can be made on request.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
pip install in virtualenv

**Use case**
No more sudden parsing errors with rules.
