### ISSUE TITLE
pattern-regex should work with pattern

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#805]
```yaml
rules:
  - id: boto-client-ip
    patterns:
      - pattern: boto3.client(host="...")
      - pattern-regex: '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
    message: "boto client using IP address"
    languages: [python]
    severity: ERROR
```

https://semgrep.live/0jj?version=develop
