### ISSUE TITLE
--emacs flag prints truncated rule IDs

### ISSUE THREAD

**Issue by gand3lf** [semgrep/semgrep#8050]
Hi guys!
In the case where the rule ID contains a dot, the `--emacs` flag prints a truncated rule ID.
Example:
```yaml
#rule.yaml
rules:
  - id: MYRULE-1.6
  ...
```
From terminal:
```
$ semgrep -c rule.yaml ./target --emacs
...
myfile.java:39:5:warning(6):    public static ... 
...
```
The expected output should be:
```
myfile.java:39:5:warning(MYRULE-1.6):    public static ... 
```

Thank you guys!
