### ISSUE TITLE
Metavariable Type Extension for Semgrep Rule Syntax

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#8119]
This issue proposes a dedicated field for annotating the type information of metavariables. By adopting this approach, instead of relying solely on language-specific casting syntax, we provide an additional way to enhance the overall usability by eliminating the need to write redundant type cast expressions for a single metavariable.

Moreover, the new syntax brings other benefits, including improved support for target languages that lack built-in casting syntax. It also promotes a unified approach to expressing type, pattern, and regex constraints for metavariables, resulting in improved consistency across rule definitions.

Current syntax:
```
rules:
  - id: no-string-eqeq
    severity: WARNING
    message: find errors
    languages:
      - java
    patterns:
      - pattern-not: null == (String $Y)
      - pattern: $X == (String $Y)
```

Proposed syntax:
```
rules:
  - id: no-string-eqeq
    severity: WARNING
    message: find errors
    languages:
      - java
    patterns:
      - pattern-not: null == $Y
      - pattern: $X == $Y
      - metavariable-type:
          metavariable: $Y
          type: String
```
