### ISSUE TITLE
Sub-expression is not matched

### ISSUE THREAD

**Issue by icholy** [semgrep/semgrep#8131]
**Describe the bug**

I'm unable to match certain sub-expressions in javascript.

**To Reproduce**

https://semgrep.dev/playground/s/dbBE

``` js
if (true && x.y && x.y.z) {

}
```

```yml
rules:
  - id: subexpression
    languages:
      - javascript
    message: Match found
    patterns:
      - pattern: $X.$Y && $X.$Y.$Z
    severity: WARNING
```

**Expected behavior**

Match `x.y && x.y.z`

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**

Finding places where optional chaining can be used.
