### ISSUE TITLE
Metavariable Type Extension for Semgrep Rule Syntax 2.0

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#8183]
We propose to extend the changes made in Semgrep rule syntax 1.0 to version 2.0 as well. This transition is crucial as we slowly move towards Semgrep rule syntax 2.0. Our goal is to ensure that both syntax versions, 1.0 and 2.0, have equivalent capabilities for metavariable typing. To achieve this, we will enhance the YAML syntax of version 2.0 by introducing a dedicated field for metavariable types.

Here is an example of the proposed syntax:
```
# rule syntax 2.0
rules:
  - id: no-string-eqeq
    message: find errors
    severity: WARNING
    languages:
      - java
    match:
      all:
        - not: null == (String $Y)
        - $X == (String $Y)
```
```
# rule syntax 2.0 after proposed change
rules:
  - id: no-string-eqeq
    message: find errors
    severity: WARNING
    languages:
      - java
    match:
      all:
        - not: null == $Y
        - $X == $Y
      where:
        - metavariable: $Y
          type: String
```

For rule syntax 1.0: #8119
