### ISSUE TITLE
[YAML] Excessive capture when matching sequences

### ISSUE THREAD

**Issue by d0nut-rh** [semgrep/semgrep#8226]
**Describe the bug**
We have a rule similar to the following:
```
rules:
    - id: foo
      languages: [yaml]
      pattern: |
        importantKey:
          ...
```

Which we intend to match blocks like this

```
arbitraryKey:
  importantKey:
    prop1: true
    prop2: true
    prop3: false
```

or

```
arbitraryKey:
  importantKey:
    - something: true
      somethingElse: false
```

However, we noticed that the start and end location for the match can include the whitespace before the next key if `importantKey` is a sequence. Additionally, it include comments even if they're not at the correct level of indentation.

**To Reproduce**
https://semgrep.dev/playground/s/p87d

**Expected behavior**
The newline + whitespace (+ and comments) should not be included.

**Screenshots**
See semgrep playground link

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Semgrep.dev and semgrep via pypi

**Use case**
We used `generic` language mode to address this issue, but has resulted in much slower scans with this rule and requiring us to play with the `generic_ellipsis_max_span` option to work for our use-cases.

This bug being fixed would allow us to revert the rule to a `yaml` rule which appears to perform much better.
