### ISSUE TITLE
Confusion when using multiple `pattern-either` inside `patterns`

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#828]
In my opinion: using `patterns` and `pattern-either` within one rule sometimes behave not as it would be predicted according to the docs (https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#patterns)

as I understand from the docs:
`patterns` performs a logical AND operation
`pattern-either` operator performs a logical OR operation

so by doing smth like this (sorry if its messy, tried hard to come up with descriptive example):
https://semgrep.live/9d8
```
  patterns:
    - pattern-either:
      - pattern: foo('bar',...)
      - pattern: foo('zzz',...)
    - pattern-either:
      - pattern: foo($X,1,...)
      - pattern: foo($X,2,...)
```
I would expect the logic like this:

(`foo('bar',...)` OR `foo('zzz',...)`) AND (`foo($X,1,...)` OR `foo($X,2,...)`)

so it means that I want to find usage of `foo` with either 'bar' or 'zzz' as the first argument and `1` or `2` as the second

but for now it seems like logically `semgrep` treats this rule as:

`foo('bar',...)` OR `foo('zzz',...)` OR `foo($X,1,...)` OR `foo($X,2,...)`

and highlights code if any of the `pattern` matches

example link: https://semgrep.live/9d8
