### ISSUE TITLE
A string template expression is only detected once, although it appears multiple times

### ISSUE THREAD

**Issue by PeterKogan** [semgrep/semgrep#8407]
**Describe the bug**
The `b` expression appears twice in the string template: ```myVar = `a${b}c${b}d` ```, but it's only returned once.

**To Reproduce**
Code: ```myVar = `a${b}c${b}d` ```

Rules:
```
rules:
  - id: semgrep_js_string_template_expressions
    patterns:
      - pattern: |
         `...${$EXP}...`
      - metavariable-regex:
         metavariable: $EXP
         regex: ^[^'"`]
    message: $EXP
    severity: ERROR
    languages:
      - javascript
      - typescript
```

**Expected behavior**
`b` should be returned twice.

**Screenshots**
![image](https://github.com/returntocorp/semgrep/assets/113822763/e0398517-c39f-4145-81c7-ca5efd97f972)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
