### ISSUE TITLE
unknown field when using r2c-internal-project-depends-on

### ISSUE THREAD

**Issue by yoshino-s** [semgrep/semgrep#8412]
**Describe the bug**
When using the follow rule, a warning will be report

**To Reproduce**
Using the following rule
```yaml
rules:
- id: check-outdated-sanitize-html
  message: "Versions of the library sanitize-html < 2.3.2 are vulnerable to sanitization bypass and/or RCE. Recommended to update to version 2.3.2 or later."
  languages: [javascript, typescript]
  severity: WARNING
  metadata:
    category: security
    references: |
      - https://semgrep.dev
    cwe:
      - "CWE-00: VALUE"
    owasp:
      - "A00:2021 - VALUE"
      - "A00:2017 - VALUE"
  patterns:
    - pattern-inside: |
        require('sanitize-html')
        ...
    - pattern: |
        sanitizeHtml(...)
  r2c-internal-project-depends-on:
    namespace: npm
    package: sanitize-html
    version: "< 2.3.2"
```

to scan the following code

```js
const sanitizeHtml = require('sanitize-html')

sanitizeHtml(html)
```

with the package.json as follow

```json
{
    "name": "test",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
      "sanitize-html": "1.4.2"
    }
  }
```

**Expected behavior**
It should work.

**Screenshots**
<img width="859" alt="image" src="https://github.com/returntocorp/semgrep/assets/28624661/88a9c082-24f7-440a-bf52-f5dd0ffaf76b">

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
using the `brew install semgrep`
