### ISSUE TITLE
metavariable-pattern failed, Gitlab 16.2 CI/CD

### ISSUE THREAD

**Issue by Evynglais** [semgrep/semgrep#8413]
**Describe the bug**
Lots of repeated error messages in the SAST stage of the Gitlab CI/CD pipeline:

`metavariable-pattern failed because $ADDR does not bind to a sub-program, please check your rule`

Still seems to be working and detecting vulnerabilities, but unsure if it's missing any.

**To Reproduce**
Run the pipeline against any of our internal Java applications in Gitlab CI/CD.

**Expected behavior**
No error logs are produced.

**Screenshots**

![image](https://github.com/returntocorp/semgrep/assets/71874625/fd231eb3-7032-4690-8caf-c572b5c7b119)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Running using the standard Gitlab CI/CD semgrep-sast stage using a Kubernetes executor. Gitlab 16.2.

**Use case**
Confidence using the tool with full vulnerability scanning.

**Comment by nmote** [comment]
Could you provide any more details about the rules you are using or the code that you are running?

**Comment by Evynglais** [comment]
Hi, 

I've not configured any custom rules - the Gitlab docs did not suggest that was required. I'm entirely new to semgrep-sast, so if I've missed an important configuration step, please could you link to some docs I can use to configure it properly?

The only configuration for the SAST stage in our pipeline is the following:

```
# Override pre-defined SAST stage:
sast:
  # No cache required:
  cache: []
  # Run on our Kubernetes executor:
  tags:
  - k8s
```

This results in the following 'active' pipeline stage:

```
semgrep-sast:
  stage: test
  artifacts:
    reports:
      sast:
      - gl-sast-report.json
  rules:
  - if: "$SAST_DISABLED == 'true' || $SAST_DISABLED == '1'"
    when: never
  - if: "$SAST_EXCLUDED_ANALYZERS =~ /semgrep/"
    when: never
  - if: "$CI_COMMIT_BRANCH"
    exists:
    - "**/*.py"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.c"
    - "**/*.go"
    - "**/*.java"
    - "**/*.cs"
    - "**/*.html"
    - "**/*.scala"
    - "**/*.sc"
  variables:
    SEARCH_MAX_DEPTH: 20
    SAST_ANALYZER_IMAGE_TAG: 4
    SAST_ANALYZER_IMAGE: "$SECURE_ANALYZERS_PREFIX/semgrep:$SAST_ANALYZER_IMAGE_TAG$SAST_IMAGE_SUFFIX"
  script:
  - "/analyzer run"
  cache: []
  tags:
  - k8s
  extends: ".sast-analyzer"
  allow_failure: true
  image:
    name: "$SAST_ANALYZER_IMAGE"
```

The application is written in Java (JDK17) with Maven.
