### ISSUE TITLE
Using pattern-inside with pattern-not not working as expected.

### ISSUE THREAD

**Issue by matejsp** [semgrep/semgrep#8428]
**Describe the bug**
I would like to match a line that does not have a string inside. It does not work using pattern-inside and pattern-not.

**To Reproduce**
```
rules:
- id: custom.missing_algoritm_instant
  patterns:
    - pattern-inside: ALTER ... ADD COLUMN ... ;
    - pattern-not-regex: ALGORITHM.*=.*INSTANT
    # - pattern-not: ALGORITHM = INSTANT
  message: |
      When adding with ADD COLUMN consider using ALGORITHM = INSTANT, because it will make upgrades faster.
  languages: [generic]
  severity: WARNING
```

```
ALTER TABLE `schedule` 
   ADD COLUMN `chain_currency` mediumint NULL
   ;

ALTER TABLE `schedule` ADD COLUMN `chain_currency` mediumint NULL,
   ALGORITHM =INSTANT;
````

With pattern-not-regex it matches only one (as expected) but when using pattern-not it matches both SQLs

**Expected behavior**
I would expect to be able to match a line that does not contain pattern-not.

**Screenshots**
Using pattern-not-regex:
<img width="1631" alt="image" src="https://github.com/returntocorp/semgrep/assets/3091122/8419777a-8734-4bfb-9357-7e81446bcf7c">

Using pattern-not:
<img width="1598" alt="image" src="https://github.com/returntocorp/semgrep/assets/3091122/ae0b090d-7bef-4212-a7f8-7fbfbc7b2bb9">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
It would enable to match lines that are not containing an expression.

**Comment by IagoAbal** [comment]
Hi @matejsp the `pattern-not` and `pattern-not-regex` operators work differently. Using `pattern-not`, this matches https://semgrep.dev/playground/s/Neg1, but this does not https://semgrep.dev/playground/s/kN9z. However with `pattern-not-regex` this does not match https://semgrep.dev/playground/s/wRXX. So `pattern-not` only filters out a match if it is _exactly the same_ match. That is, to filter our `x + y` with a `pattern-not`, the `pattern-not` must match _exactly_ `x + y`, no more and no less. Whereas `pattern-not-regex` filters out a match if it _intersects_ with it. I agree it's confusing.

**Comment by matejsp** [comment]
Thank you for the response. Yeah documentation update would be welcomed in this case.

You said exact match:

Then why does not work:
    - pattern-inside: ALTER ... ADD COLUMN ... ;
    - pattern-not: ... ALGORITHM = INSTANT... ;

However this works:
      - pattern-inside: ALTER ... ADD COLUMN ... ;
      - pattern-not: ALTER ... ADD COLUMN ... ALGORITHM = INSTANT;


Example from docs:
```
rules:
  - id: function-args-to-open
    patterns:
      - pattern-inside: |
          def $F($X):
              ...
      - pattern: open($X)
    message: "Function argument passed to open() builtin"
    languages: [python]
    severity: ERROR
```

I assumed when reading docs as pattern that is inside (function) vs pattern that is not inside (function).
And not pattern that is inside (function) vs pattern that is not as a whole (pattern-not: def $F($X)).
