### ISSUE TITLE
Error in metavariable binding from a string in PHP with metavariable pattern

### ISSUE THREAD

**Issue by mrnfrancesco** [semgrep/semgrep#8452]
**Describe the bug**
I wrote a rule for PHP which doesn't behave as expected. The rule is:

```yml
rules:
  - id: test
    severity: ERROR
    message: whatever
    languages: [php]
    patterns:
      - pattern: array_map('$SANITIZER', ...)
      - metavariable-pattern:
          metavariable: $SANITIZER
          pattern: int
```

I expect the rule to match code like:

```php
array_map('int', $categories);
```

but I got an error instead:

> Internal matching error when running wp-sec-sql-injection on target.php:
> An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at > https://github.com/returntocorp/semgrep
> 
> metavariable-pattern failed because $SANITIZER does not bind to a sub-program, please check your rule Engine()

You can check yourself on [playground](https://semgrep.dev/playground/s/XDR4).

In case of using taint-mode the error doesn't show up, but the pattern still doesn't match as you can see on this other [playground](https://semgrep.dev/playground/s/qvLe).

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
