### ISSUE TITLE
Java Metavariable Repeating Matched Text and Multiple Matches

### ISSUE THREAD

**Issue by git-blame** [semgrep/semgrep#8548]
**Describe the bug**
Using metavariables in semgrep rule to match a Java call so that its value in `metavars` can be processed. The metavars content is the matched text but repeated several times. If using `semgrep-core`, there are also multiple matches of the same line. Note: these are filtered out by main `semgrep` application.

**To Reproduce**
A rule as follows:
```yaml
rules:
  - id: cipher-java
    message: Java Ciphers
    severity: INFO
    patterns:
      - pattern: |
          $TYPE.getInstance("$ALG")
      - metavariable-regex:
          metavariable: $TYPE
          regex: (Cipher|KeyGenerator)
    languages:
      - java
      - kt
```

Test a file like the following:
```java
package test;

import java.io.IOException;
import javax.servlet.http.HttpServlet;
import javax.crypto.*;
import javax.crypto.Cipher;

public class Cls extends HttpServlet
{
    protected void test() throws IOException {
        Cipher c = Cipher.getInstance("AES");
        KeyGenerator k = KeyGenerator.getInstance("AES");
    }
}
```
The metavariable match against Cipher returns "Cipher Cipher Cipher"
```json
...
      "extra": {
        "message": "Java Ciphers",
        "metavars": {
          "$TYPE": {
            ...
            "abstract_content": "Cipher Cipher Cipher"
          },
          "$ALG": {
            ...
            "abstract_content": "AES"
          }
        },
```

The problem occurs when there is an **explicit** import statement such as `import javax.crypto.Cipher`. If we have only `import javax.crypto.*`, then there the bug does not occur. In the example, KeyGenerator is matched correctly because the file does not have `import javax.crypto.KeyGenerator`.

Note that if we are running `semgrep-core` directly, we also have duplicate matches. The main `semgrep` filters them out but it is not clear what logic is being used for filtering. In the example, `Cipher.getInstance()` will match twice with `semgrep-core`. For match 1, `$TYPE` metavar's content is "Cipher Cipher Cipher". For duplicate match, `$TYPE` metavar's content is "Cipher".

**Expected behavior**
The metavar content is the right value taken from the source file and there are no duplicate matches.

**What is the priority of the bug to you?**

P1: important to fix or quite annoying

**Environment**
semgrep docker version 1.24.1

**Use case**
* No duplicate matches
* Metavariable values are correct and can be used for further processing (tooling, UI, etc.)

**Comment by git-blame** [comment]
Trying to use `metavariable-pattern` with `pattern-not-regex` to filter out metavars that contain spaces does not work.

But a workaround that does work is to use `metavariable-pattern` with multiple pattern matches to filter instead of using `metavariable-regex`. So given the example rule in the description, this equivalent replacement will filter out duplicates:
```yaml
    patterns:
      - pattern: $TYPE.getInstance("$ALG", ...)
      - metavariable-pattern:
          metavariable: $TYPE
          patterns:
            - pattern-either:
              - pattern: Cipher
              - pattern: KeyGenerator
```
