### ISSUE TITLE
Java String Metavariable Does Not Return Full Value of Concat Strings

### ISSUE THREAD

**Issue by git-blame** [semgrep/semgrep#8555]
**Describe the bug**
A string metavar returns the content of a string (e.g., `s = "$V"`) whereas a non-string metavar returns the source code content of whatever it has matched. (e.g., `s = $V`).

In Java, to support longer strings, the `+` operator is often used. Semgrep recognizes that a single variable contains all the "concatenated" strings as content. This is in `$V` metavar content. But if the metavar is only of the string content, semgrep seems to return only the first line for the metavar content. Note: in both cases, the full matched region is correctly included in the lines block and/or the start and end regions.

**To Reproduce**
String metavar:
```yaml
rules:
  - id: pem-java
    message: Java PEM
    severity: INFO
    metadata:
      - bug:
    patterns:
      - pattern-either:
        - pattern: $F("$PEM",...)
        - pattern: $S = "$PEM"
      - metavariable-regex:
          metavariable: $PEM
          regex: \A(-----[ ]{0,5}BEGIN|M[0-9a-zA-Z+\/]{30,})
    languages:
      - java
```

Metavar:
```yaml
rules:
  - id: pem-java
    message: Java PEM
    severity: INFO
    metadata:
      - bug:
    patterns:
      - pattern-either:
        - pattern: $F($PEM,...)
        - pattern: $S = $PEM
      - metavariable-regex:
          metavariable: $PEM
          regex: \A(-----[ ]{0,5}BEGIN|M[0-9a-zA-Z+\/]{30,})
    languages:
      - java
```

String metavar content
```json
...
          "$PEM": {
            "start": {
...
            },
            "end": {
...
            },
            "abstract_content": "\"-----BEGIN X509 CERTIFICATE-----\\r\""
          }
```

Metavar content:
```json
...
          "$PEM": {
            "start": {
...
            },
            "end": {
...
            },
            "abstract_content": "\"-----BEGIN X509 CERTIFICATE-----\\r\"+\"MIIDXjCCAsegAwIBAgIBBzANBgkqhkiG9w0BAQQFADCBtzELMAkGA1UEBhMCQVUx\\r\"+<etc>"
          }
```

**Expected behavior**
For a String metavar, the full string data is returned. This is nicer than a regular metavar which preserves the quotation marks and the `+` operators. In the latter case, additional processing is needed to strip out these characters which are not part of the variable's data.

**What is the priority of the bug to you?**
P2: regular bug that should get fixed

**Environment**
semgrep docker 1.24.1

**Use case**
The content of a string variable can processed in a simple way instead of needing to first strip out non-data characters like quotation marks, concat `+` operators, etc.
