### ISSUE TITLE
Regexes anchored at the start of the string but not at the end

### ISSUE THREAD

**Issue by iuliadmtru** [semgrep/semgrep#8577]
**Describe the bug**
Regex expressions are start-of-string-anchored but not end-of-string-anchored. For example, searching for a string metavariable that contains only `string` like this:
```
patterns:
    - pattern: $FUN(..., "$STR", ...)
    - metavariable-regex:
        metavariable: $STR
        regex: string
```
with this source code
```julia
f("string")
f("--string--")
f("string--")
f("--string")
```
leads to two matches: `f("string")` (expected) and `f("string--")` (unexpected).

**To Reproduce**
https://semgrep.dev/playground/s/RJzq

**Expected behavior**
I would have expected anchoring on both sides.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Fixing this will allow writing simpler regexes that don't need to take into account end-of-string anchoring.
