### ISSUE TITLE
False positive with metavariable pattern

### ISSUE THREAD

**Issue by LuciaMartinezGavier** [semgrep/semgrep#8586]
**Describe the bug**
The following rule matches a pattern inside an if condition statement, which I think is a false positive: 
```yaml
rules:
- id: my_rule
  patterns:
    - pattern: |
        $RETURN_TYPE $FUNCTION_NAME(...) {
          ...
          $STATEMENT;
          ...
        }
    - metavariable-pattern:
        metavariable: $STATEMENT
        patterns:
          - pattern-either:
              - pattern: x == 1

  message: "my_rule triggered"
  languages: [c]
  severity: WARNING
```  

**To Reproduce**
The rule matches the code below 

 ```c
int function2(int x){
    if (x == 1){
        // do something
    }
}
 ```
 
 but this other which in my opinion should be equivalent, doesn't match:
 ```yaml
 rules:
- id: my_rule
  patterns:
    - pattern: |
        $RETURN_TYPE $FUNCTION_NAME(...) {
          ...
          x == 1
          ...
        }

  message: "my_rule triggered"
  languages: [c]
  severity: WARNING
 ```

**Expected behavior**
I expected no matches found. 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed
