### ISSUE TITLE
Surprising behavior with '...' ellipsis operator and Python decorators

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#859]
Consider the following example:

```yaml
rules:
- id: test-decorator
  pattern: |
      @foo
      def baz(...):
          ...
  message: "Decorator test"
  languages: [python]
  severity: ERROR
```

```
$ cat test.py 
@foo
@bar
def baz():
    pass
```

```
$ semgrep --config conf.yaml test.py 
test.py
ERROR rule:test-decorator: Decorator test
1:@foo
2:@bar
3:def baz():
4:    pass
```

It's surprising to me that the `pattern` matches the above code without a `...` after the `@foo` decorator. I was more surprised to see that a `...` after a decorator was a parse error:

```yaml
rules:
- id: test-decorator
  pattern: |
      @foo
      ...
      def baz(...):
          ...
  message: "Decorator test"
  languages: [python]
  severity: ERROR
```

```
$ semgrep --config conf.yaml test.py 
invalid pattern "@foo
...
def baz(...):
    ...
": Parsing.Parse_error
```

I'm not entirely sure what the expected behavior here is. Requiring a `...` after a decorator to consume additional decorators is more consistent with other `semgrep` behavior, but will likely break backwards compatibility. The existing behavior isn't obvious that a top-level decorator match will consume additional decorators without `...`.

Thoughts?
