### ISSUE TITLE
The docker container tagged 1.38.0 has permission error in github runners

### ISSUE THREAD

**Issue by khkyler** [semgrep/semgrep#8601]
**Describe the bug**
Github actions using the latest (1.38.0) version of the semgrep dockerfile is failing the checkout@v3 action while running on public github runners.

```
/usr/bin/docker exec  73e65bd80eabbd8f5f39eefd8d1210b4f6edf9b1fa4c58cc4319a3fc0f5d54a8 sh -c "cat /etc/*release | grep ^ID"
node:internal/fs/utils:347
    throw err;
    ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_29a0706e-e663-43be-a79a-d5b5d93752a1'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at Object.appendFileSync (node:fs:2264:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v3/dist/index.js:2950:8)
    at Object.saveState (/__w/_actions/actions/checkout/v3/dist/index.js:2867:31)
    at Object.8647 (/__w/_actions/actions/checkout/v3/dist/index.js:2326:10)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:[18](https://github.com/weekend-health/weekend-root/actions/runs/6043598229/job/16400873299?pr=3954#step:3:19)256:43)
    at Object.2565 (/__w/_actions/actions/checkout/v3/dist/index.js:146:34)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:18256:43)
    at Object.9[21](https://github.com/weekend-health/weekend-root/actions/runs/6043598229/job/16400873299?pr=3954#step:3:22)0 (/__w/_actions/actions/checkout/v3/dist/index.js:1141:36) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/__w/_temp/_runner_file_commands/save_state_[29](https://github.com/weekend-health/weekend-root/actions/runs/6043598229/job/16400873299?pr=3954#step:3:30)a0706e-e663-43be-a79a-d5b5d93752a1'
}
```

The semgrep action in our workflow is defined as follows:
```
name: Semgrep
on: [pull_request]
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: semgrep ci --config auto
 ```

**To Reproduce**
Running an action using `actions/checkout@v3` with the  `returntocorp/semgrep:1.38.0` will cause the action to fail.

**Expected behavior**
This Dockerfile works with github actions. Reverting and pinning the 1.37.0 version fixes this.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker build `returntocorp/semgrep` (the 1.38.0 version specifically has this bug)
