### ISSUE TITLE
Semgrep rewraps messages in findings and breaks up URLs

### ISSUE THREAD

**Issue by timmc-edx** [semgrep/semgrep#8608]
**Describe the bug**

When a rule has a message with lines that are more than 60-70 characters long, the text is hard-wrapped, making it hard to read—and even breaking URLs. It also removes existing newlines in messages, which is probably has the same cause.

**To Reproduce**

Here's a sample config file with a nontrivial message:

```yaml
rules:
  - id: celery-missing-code-owner
    message: |
      Celery tasks need to be decorated with `@set_code_owner_attribute`
      (from the `edx_django_utils.monitoring` module) in order for us
      to correctly track code-owners for errors and in other monitoring.

      For more information, see
      https://github.com/openedx/edx-django-utils/blob/master/edx_django_utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst#handling-celery-tasks
    languages:
      - python
    patterns:
      # Find functions with decorators containing the substring "task"
      # in their name. This might end up with false positives, but
      # there are a lot of variations on how we decorate Celery tasks.

      # This pattern should match all decorators, whether or not
      # they're called as a function (both `@foo(...)` and `@foo`)
      # and whether or not there are other decorators above or below.
      - pattern: |
          @$TASK
          def $F(...):
            ...
      # Restrict the decorators of interest to just ones with "task"
      # in the name.
      - metavariable-pattern:
          metavariable: $TASK
          patterns:
            - pattern-regex: >-
                [^\(]*task(\(|$)

      # Filter out all of the properly annotated functions, leaving
      # just the ones of interest.
      - pattern-not: |
          @set_code_owner_attribute
          def $F(...):
            ...
    severity: WARNING
```

Here's how it prints out in GitHub Actions, with strange wrapping and a broken URL:

```
    lms/djangoapps/discussion/rest_api/tasks.py 
       test_root.semgrep.celery-missing-code-owner                              
          Celery tasks need to be decorated with `@set_code_owner_attribute`    
  (from the                                                                     
          `edx_django_utils.monitoring` module) in order for us to correctly    
  track code-owners for                                                         
          errors and in other monitoring.                                       
                                                                                
          For more information, see                                             
  https://github.com/openedx/edx-django-utils/blob/master/edx_django            
          _utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_i
  da.rst#handling-                                                              
          celery-tasks       
```

Note that the hardwraps that were originally present in the message (for example, between "us" and "to") have been removed, and new ones added. (To reproduce, run `semgrep scan --config ./celery-code-owner.yml --error --quiet -- lms/djangoapps/discussion/` using semgrep 1.38.1 against commit 26d8c2166d5f of <https://github.com/openedx/edx-platform>.)

It seems to be sensitive to terminal size, because I still get the bad behavior in a terminal, but with wider breaks:

```
    lms/djangoapps/discussion/rest_api/tasks.py 
       test_root.semgrep.celery-missing-code-owner                                          
          Celery tasks need to be decorated with `@set_code_owner_attribute` (from the                
          `edx_django_utils.monitoring` module) in order for us to correctly track code-owners for    
          errors and in other monitoring.                                                             
                                                                                                      
          For more information, see https://github.com/openedx/edx-django-utils/blob/master/edx_django
          _utils/monitoring/docs/how_tos/add_code_owner_custom_attribute_to_an_ida.rst#handling-      
          celery-tasks                                                                                
```

**Expected behavior**

I would expect that the message is printed with no wrapping, other than whatever wrapping the terminal performs. (Added indentation is fine.)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

`pip install semgrep==1.38.1`

**Use case**

I'm running CI checks on PRs, and I'd like to be able to give people intelligible messages about the problems in their code, as well as URLs for more information.
