### ISSUE TITLE
Can't match $_POST with semgrep

### ISSUE THREAD

**Issue by CaledoniaProject** [semgrep/semgrep#8740]
I'm trying to do a simple matching on variable usages, e.g

```
$a = $_GET['a'];
$b = $_POST;
foreach ($_SERVER as $key => $value) {}
```

My requirements is simple enough, just output anywhere that access $_GET/$_POST etc. I wrote this and it won't match the code above:

```yml
rules:
- id: php-variable-usage
  patterns:
  - pattern: $VAR
  - metavariable-regex:
      metavariable: $VAR
      regex: ^\$_(REQUEST|GET|POST|SERVER|COOKIE)\b
  message: direct use of user inputs
  languages: [php]
  severity: ERROR
```

What's wrong?
