### ISSUE TITLE
Using a metavariable as the YAML key causes all parent keys to be matched

### ISSUE THREAD

**Issue by 0xn3va** [semgrep/semgrep#8751]
**Describe the bug**

Starting from Semgrep `1.10.0`, the patterns below will recursively identify all parent keys in a YAML file:

```yaml
patterns:
      - pattern: |
          $K: $V
      - metavariable-pattern:
          metavariable: $V
          language: generic
          pattern-either:
            - pattern: test_1
            - pattern: test_2
```

For example, for the YAML snippet below:

```yaml
first:
  second:
    third:
      key: test_1
```

The findings will be:

- `first: -> test_1`
- `second: -> test_1`
- `third: -> test_1`
- `key: -> test_1`

However, Semgrep of version `1.9.0` identifies only the last key-value pair: 

- `key: -> test_1`

**To Reproduce**

Please, see https://semgrep.dev/playground/s/w7zX

**Expected behavior**

Semgrep only identifies the last key-value pair or there is a flag that allows a user to explicitly specify that Semgrep should identify the last key-value pair.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

It is reproduced at semgrep.dev as well as in an official binary from pypi.

**Use case**
What will fixing this bug enable for you?

It will allow me to upgrade Semgrep from version `1.9.0` up to the latest one.
