### ISSUE TITLE
metavariable-type can't match non-primitive types in php

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#8781]
**To Reproduce**
rule:
```
rules:
  - id: test
    patterns:
      - pattern: $X->exec(...)
      - metavariable-type:
          metavariable: $X
          type: BAR
    message: foo bar
    languages:
      - php
    severity: ERROR
```
code:
```
<?php

$foo = new BAR($x, $y, $z);
$foo->exec($args);
```

**Expected behavior**
the last line of the sample code is matched with the provided rule.
