### ISSUE TITLE
Ability to support sanitize function 

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#883]
**Is your feature request related to a problem? Please describe.**
We have discussed this before and I know that a `pattern-santizer` is in the timeline. But I am opening this for tracking this at my end.

support for safe functions: ` res.send("Hello " + escape(obj.username));`

**Describe the solution you'd like**
If a particular safe function is called under `pattern-inside` section or invoked with the `<... $FOO ...>` in question as an object or function call argument, do not trigger a match.

This causes a lot of false positives when customer use framework exposed escape functions for example in case of XSS escape(), escapeHTML() are very common functions to santize user input.

**Comment by mschwager** [comment]
Hi @ajinabraham,

I believe we can achieve you're use-case by using a `pattern-not` operator and [deep expression matching](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#deep-expression-operator) functionality to whitelist cases that use `escape`. Consider the following example:

```yaml
rules:
    - id: test-sanitize
      message: "Sanitize test"
      patterns:
          - pattern-inside: $VAR.send(...)
          - pattern-not: $VAR.send(<... escape(...) ...>)
      languages: [javascript]
      severity: ERROR
```

```
$ cat test.js 
res.send("Hello " + escape(obj.username));
res.send("Hello " + obj.username);
```

```
$ semgrep --config test.yaml test.js 
test.js
ERROR rule:test-sanitize: Sanitize test
2:res.send("Hello " + obj.username);
```

This won't be perfect - for example the following case will be missed:

```
$ cat test.js 
res.send(obj.unescaped_data + escape(obj.username));
```

But this should get you most of the way there.
