### ISSUE TITLE
semgrep ci shows 0 vulnerabilities if there are greater than 20 commits on merge request

### ISSUE THREAD

**Issue by frozenSolid** [semgrep/semgrep#8882]
**Describe the bug**
Once there are more than 20 commits on a branch, semgrep ci doing diff based scanning will show 0 vulnerabilities found even if vulnerabilities are present. 

Tested with `1.41.0` using the`returntocorp/semgrep` Docker container
**To Reproduce**
1. configure diff based scanning. 
I was using a `.gitlab-ci.yml` config similar to: 

```
semgrep:
  # A Docker image with Semgrep installed.
  image: returntocorp/semgrep
  # Run the "semgrep ci" command on the command line of the docker image.
  script: semgrep ci --metrics off --config auto --gitlab-sast --output target/example.json

  rules:
  # Scan changed files in MRs, (diff-aware scanning):
  - if: $CI_MERGE_REQUEST_IID
```  
2. Create a new branch, push some changes to it with a new finding created. 
3. create a merge request (I am unsure if this is gitlab specific bug or not?). 
4. perform a semgrep ci scan. I was using `semgrep ci --metrics off --config auto --gitlab-sast --output target/example.json`
5. observe the `target/example.json` showing vulnerabilities found
6. add additional commits (19 more). 
7. observe the `target/example.json` showing vulnerabilities found
8. add 21st commit, `target/example.json` will show `0` vulnerabilities. 

**Expected behavior**
`semgrep ci` continuing to report findings after 20 commits or indicating that it was ignoring commits.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Screenshots**

**Desktop (please complete the following information):**
 - `semgrep 1.41.0`

**Smartphone (please complete the following information):**
N/A

**Additional context**
briefly mentioned in semgrep slack, was asked to raise an issue. https://semgrep.slack.com/archives/CK86BJ5DW/p1695744741234579
Working on larger features or testing CI integration I think more than 20 commits should be supported. additionally showing zero findings and not erroring in a security tool can give a false sense of security.
