### ISSUE TITLE
Distinguish between sync and async python functions

### ISSUE THREAD

**Issue by Redoubts** [semgrep/semgrep#8897]
**Describe the bug**
I wanted to write a semgrep rule that was specific to async functions, but I noticed it would apply to normal sync functions as well. I would expect semgrep to either recognize the async part, or error out and suggest `async` can't be part of the rule.

**To Reproduce**
https://semgrep.dev/playground/s/l7nB
```yaml
rules:
  - id: sleep-my-child
    languages: [python]
    message: Tenacity decorator to $FUNC should use an async sleep function
    patterns:
      - pattern: |
          @decorator(...)
          async def $FUNC(...):
            ...
      - pattern-not: |
          @decorator(..., sleep=..., ...)
          async def $FUNC(...):
            ...
      # - pattern-not: |
      #     @decorator(...)
      #     def $FUNC(...):
      #       ...
    severity: ERROR
```
```py3
def decorator(sleep=None):
    def inner_decorator(func):
        def inner():
            print(sleep)
            return func()
        return inner
    return inner_decorator


def x():
    pass

@decorator()
def y():
    pass

@decorator(sleep="wao")
def z():
    pass

@decorator()
async def a_y():
    pass

@decorator(sleep="wao")
async def a_z():
    pass


x()
y()
z()
```

**Expected behavior**
Only `a_y` should be tagged by the rule, to the exclusion of `y`. The commented out pattern-not causes the rule to match nothing.

**Screenshots**

**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
python & semgrep-1.43.0, but also repro in playground

**Use case**
I specifically care about linting `tenacity` decorator usage, that may accidentally use sync sleeps in async code when used with default arguments. But async code is sufficiently different in general, so I would like semgrep support for giving them special rules.
