### ISSUE TITLE
JavaScript: Deep statement matching for code inside `try catch`

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#891]
**Describe the bug**
usually deep statement matching works perfect for code inside `try {} catch () {}` 
but I found one case when it does not work (it may be incorrect pattern from me but still need some clarification) 

https://semgrep.live/d86P

```yaml
rules:
- id: express-xml2json-xxe-event
  message: Xml Parser is used inside Request Event.
  severity: WARNING
  languages: [javascript]
  patterns:
  - pattern: |
      $REQ.on('...', function(...) {
        ...
        $EXPAT.toJson($INPUT,...);
        ...
      });
```

```javascript
// not working
req.on('event1', function () {
    try {
        req.body = expat.toJson(buf, {coerce: true, object: true});
        next();
    } catch (err) {

    }
});

// working
req.on('event2', function () {
    req.body = expat.toJson(buf, {coerce: true, object: true});
    next();
});
```
