### ISSUE TITLE
Allowing multiple type fields in metavariable-type rule syntax

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#8913]
Not only:
```
metavariable-type:
  metavariable: $X
  type: typeA
```
but we would also like to allow:
```
metavariable-type:
  metavariable: $X
  types:
    - typeA
    - typeB
```
This implies typeA or typeB.
