### ISSUE TITLE
... Can't represent contract in solidity

### ISSUE THREAD

**Issue by w3-9** [semgrep/semgrep#8934]
**Is your feature request related to a problem? Please describe.**
currently in solidity, we can use ... to represent functions, expressions, but we can't use them to represent contracts. This makes it hard to deal-with cross-contract vulnerals.

**Describe the solution you'd like**
Add support of using ... to represent contract

**Describe alternatives you've considered**
None

**Use case**
find cross-contract vulnerabilities.

**Additional context**
None

**Comment by aryx** [comment]
Can you add an example of rule/pattern you would like to write?

**Comment by w3-9** [comment]
Sometimes, we have multiple contracts in a file.
```
rules:
  - id: untitled_rule
    patterns:
      - pattern: contract A {...}
      - pattern-inside: |
          ...
          contract B {...}
    message: Semgrep found a match
    languages:
      - solidity
    severity: WARNING
```
I want this to work for 
```
pragma solidity 0.8.20;
contract A{
    function test()
}

contract B {
    function x() {
        revert();
    }
}
```
