### ISSUE TITLE
Unable to enforce use of `os.getenv` for sensitive values in Python

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#918]
I'd like to ensure that all `aws_secret_key` values are read from environment variables in my code, rather than being hard coded or coming from potentially checked-in config. I haven't been able to articulate a rule that reliably does this.

Full pattern and test cases: https://semgrep.live/qNxR

My current pattern fails to exclude the "good" case.

Pattern:
```yaml
rules:
  - id: boto3-secret
    patterns: 
      - pattern: boto3.client(..., aws_secret_access_key=$SECRET, ...)
      - pattern-not: |
          $SECRET = os.getenv(...)
          ...
          boto3.client(..., aws_secret_access_key=$SECRET ,...)
    severity: ERROR
```

**Comment by dlukeomalley** [comment]
In this case ideally I'd be able to specify the following:

```yaml
rules:
  - id: boto3-secret
    patterns: 
      - pattern: boto3.client(..., aws_secret_access_key=$X, ...)
      - pattern-not: boto3.client(..., aws_secret_access_key=os.getenv(...),...)
    severity: ERROR
```

Rather than having to remember that people may not directly use `os.getenv` in the method call, Semgrep would ideally understand that the following code is equivalent:

```py
AWS_SECRET = os.getenv(...)

s3 = boto3.client(
    's3',
    aws_access_key_id = "foobar",
    aws_secret_access_key = AWS_SECRET)
```

**Comment by dlukeomalley** [comment]
A seperate user ask is the following `set_cookie` example: https://semgrep.live/YGvD

Pattern
```yaml
rules:
- id: flask-secure-set-cookie
  patterns:
    - pattern-not: flask.response.set_cookie(..., httponly=True, secure=True,...)
    - pattern: flask.response.set_cookie(...)
```

Code
```py
SECURE_FLAG = True
response.set_cookie("hello", "world", secure=SECURE_FLAG, httponly=True, samesite="Lax")
```
