### ISSUE TITLE
Osemgrep: javascript file is erroneously ignored

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#9281]
I ran using this rule:
```
rules:
  - id: test
    message: "foo"
    languages: [javascript]
    severity: WARNING
    patterns:
    - pattern: "$F(...)"
  - id: assert-eqeq-is-ok
    pattern: |
      def __eq__():
          ...
          $X == $X
    message: "possibly useless comparison but in eq function"
    languages: [python]
    severity: ERROR
```

with

```
osemgrep  --config my_rule.yaml targets/nosem_invalid_id --experimental  
```

That folder contains one Javascript file. When I run that file explicitly, it gets scanned correctly. However, when the
folder is passed, the file doesn't get scanned. With `--debug` we can see that the file gets skipped by `.semgrepignore`.

With `semgrep`, this file is scanned as I expected.
