### ISSUE TITLE
Lower memory usage when outputting no lines and using metavariables just for message-context

### ISSUE THREAD

**Issue by fabian-zeindl-oebb** [semgrep/semgrep#9346]
**Is your feature request related to a problem? Please describe.**
I have a very large json file (> 1MB) that I am scanning for combinations. 

I use one metavariable that is matched and three metavariables that are just used in the message for output, something like this:

```
{
    "$CONTEXT_FOR_MESSAGE_1": {
        "$CONTEXT_FOR_MESSAGE_2": {
            "$CONTEXT_FOR_MESSAGE_3:" {
                "key": "$ACTUAL_VARIABLE_USED_FOR_MATCHING",
                ...
            },
            ...
        },
        ...
    },
    ...
}
```

I noticed that scanning takes extremely long (> 20 minutes) and uses many gigabytes of memory.

I also noticed that scanning get's much faster if 
* a) I don't use the metavariables that are just used for outputting the message or 
* b) I change my test-file so that there's only one match instead of 100 or so.

**Describe the solution you'd like**
I don't see a reason why memory needs to explode like this when using metavariables just for logging, even when I disable output of lines.

Semgrep seems to hold on to some structures in memory that aren't needed in my output.

**Describe alternatives you've considered**
There are no alternatives.

**Use case**
Scanning my system in 5 seconds instead of 20 minutes.

**Comment by fabian-zeindl-oebb** [comment]
@aryx Could you have a look at this and at least close it?

**Comment by aryx** [comment]
Could you attach or link to this big JSON file and send the exact command you run so we can try to reproduce?

**Comment by fabian-zeindl-oebb** [comment]
Thank you for your answer.

I have constructed a redacted file for you: [api.json](https://github.com/semgrep/semgrep/files/13658198/api.json)

This is not as complex as the original, so it is faster, but you can still see my point:

* If I run the rule below against this it takes 17 seconds for me.
* If I remove the `$COMPONENT` variable in the rule, which is just used in the message, runtime goes down to 1 second on my system.

```yaml
rules:
  - id: api-reserved-returncode
    message: API $PATH in component $COMPONENT has returncode $CODE that is reserved by the HTTP-standard
    severity: INFO
    patterns:
      - pattern: |
          {
            "apis": {
              "$COMPONENT": {
                "paths": {
                  "$PATH": {
                    "...": {
                      "responses": {
                        "$CODE": ...,
                        ...
                      },
                      ...
                    },
                    ...
                  },
                  ...
                },
                ...
              },
              ...
            }
          }
      - metavariable-pattern:
          metavariable: $CODE
          language: "generic"
          pattern-either:
            - pattern: "900"
            - pattern: "901"
      - focus-metavariable: $CODE
    languages: [json]
```
