### ISSUE TITLE
Constant propagation of class field in C++

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#9352]
Example rule:
```yaml
rules:
  - id: cpp-const-field
    languages:
      - cpp
    message: testing
    severity: INFO
    pattern: std::cout<<1
```
Example target:
```cpp
#include<iostream>

namespace B {
class Bar {
    public:
        static const int one = 1;
};
}

int main() {
    // ruleid: cpp-const-field
    std::cout<<1<<std::endl;
    // ruleid: cpp-const-field
    std::cout<<B::Bar::one<<std::endl;
}
```
