### ISSUE TITLE
Handling IdQualified in constant propagation

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#9354]
Handing IdQualified in constant propagation, which enables the following matches:
```yaml
rules:
  - id: cpp-const-field
    languages:
      - cpp
    message: testing
    severity: INFO
    pattern: std::cout<<1
```
```cpp
#include<iostream>
#include "a.h"

namespace B {
class Bar {
    public:
        static const int one = 1;
};
}

int main() {
    // ruleid: cpp-const-field
    std::cout<<1<<std::endl;

    // ruleid: cpp-const-field
    std::cout<<A::Foo::one<<std::endl;

    // ruleid: cpp-const-field
    std::cout<<B::Bar::one<<std::endl;
}
```
