### ISSUE TITLE
invalid SARIF - instance.runs[0].tool.driver.rules contains duplicate item

### ISSUE THREAD

**Issue by ben-manes** [semgrep/semgrep#9633]
**Describe the bug**
The `github/codeql-action/upload-sarif` action does not accept the sarif file due to a validation error.

[semgrep.sarif.zip](https://github.com/semgrep/semgrep/files/13999793/semgrep.sarif.zip)

**To Reproduce**
I use the container image `returntocorp/semgrep` which was working until today, so maybe it was updated with this bug.

**Expected behavior**
Valid sarif is produced and reported on.

**Screenshots**
<img width="1840" alt="Screenshot 2024-01-20 at 6 10 12 PM" src="https://github.com/semgrep/semgrep/assets/378614/b2908047-a382-4ea0-8a47-56efae4a1709">

**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
`returntocorp/semgrep` on github actions ([logs](https://github.com/ben-manes/caffeine/actions/runs/7597967896/job/20693447263), [workflow](https://github.com/ben-manes/caffeine/actions/runs/7597967896/workflow))

**Use case**
I worked around this by preprocessing the sarif to remove duplicates and upload successfully.
```yaml
- name: Remove duplicate rules
  if: steps.check_files.outputs.files_exists == 'true'
  run: jq -c '.runs[0].tool.driver.rules |= unique_by(.id)' < results.sarif > semgrep.sarif
```
