### ISSUE TITLE
Using metavariable pattern matches more of the line than a simple pattern without metavariable

### ISSUE THREAD

**Issue by clavedeluna** [semgrep/semgrep#9756]
**Describe the bug**

I'd like to match calls to Python `request.get/post/etc` which do not contain the timeout pattern.
```
import requests
# should match
req = requests.get("https://example.com")
req = requests.get("https://example.com").json()
# should not match
req = requests.get("https://example.com", timeout=29).json()
```
So I wrote a very simple semgrep rule:

```
rules:
  - id: requests
    patterns:
      - pattern: requests.get(...)
      - pattern-not: requests.get(..., timeout=$TIMEOUT, ...)
      - pattern-inside: |
          import requests
          ...
```

That rule is great, but I'd like to generalize so either `get`, `post`, etc methods are matched. So I make this rule with metavariable-pattern
```
    patterns:
      - pattern-inside: |
          import requests
          ...
      - pattern: $CALL(...)
      - pattern-not: $CALL(..., timeout=$TIMEOUT, ...)
      - metavariable-pattern:
          metavariable: $CALL
          patterns:
            - pattern-either:
                - pattern: requests.get
                - pattern: requests.post
                - pattern: requests.put
                - pattern: requests.delete
                - pattern: requests.head
                - pattern: requests.options
                - pattern: requests.patch
                - pattern: requests.request
```

However, I immediately notice that the change to use metavariable-pattern matches more of the code string. With the original simple pattern, `req = requests.get("https://example.com").json()` only `req = requests.get("https://example.com")` is matched. With the more complex pattern, the entire `req = requests.get("https://example.com").json()` including `.json()` is matched. This isn't what I expect.

**EDIT:** I noticed that by changing the rule to
```
    patterns:
      - pattern-inside: |
          import requests
          ...
      - pattern: requests.$CALL(...)
      - pattern-not: requests.$CALL(..., timeout=$TIMEOUT, ...)
      - metavariable-pattern:
          metavariable: $CALL
          patterns:
            - pattern-either:
                - pattern: get
                 - pattern: post
                 - pattern: put
                 - pattern: delete
                 - pattern: head
                 - pattern: options
                 - pattern: patch
                 - pattern: request
```

This works as expected.

**To Reproduce**
[Steps to reproduce the behavior, ideally a link to https://semgrep.dev:](https://semgrep.dev/playground/s/X5gEl)

**Expected behavior**
I expect matching the same characters between a simple rule and a more complex rule that uses metavariable-pattern. I also expect the two rule versions with metavariable-pattern to work identically.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
Use metavariable pattern instead of duplicating the pattern for each case
