### ISSUE TITLE
Fully qualified calls before their import missed but valid in Python Frameworks such as Django and Flask

### ISSUE THREAD

**Issue by jdsalaro** [semgrep/semgrep#9839]
**Describe the bug**

Semgrep fails to detect fully qualified Python calls whenever they happen before the respective, necessary import. Under normal circumstances, such code would be invalid, yet in scenarios where code is pre-processed as with Flask and Django, cases as the one portrayed below can in fact arise. 

```
rules:
  - id: semgrep-python-use-before-import-confusion
    mode: taint
    pattern-sources:
      - pattern: $VAR
    pattern-sinks:
      - patterns:
          - pattern: $CMD
          - pattern-inside: os.system(...)
    message: Semgrep found a match
    languages:
      - python
    severity: WARNING
```

```
01  from datetime import datetime
02
03  def foo(request):
04    query=f"{request.headers.get('query')}"
05      #ruleid: semgrep-python-use-before-import-confusion
06      system(f"{query}") #missed
07      return render (request, "foo.html")
08  
09  from os import system
10
11  def foo(request):
12    query=f"{request.headers.get('query')}"
13    #ruleid: semgrep-python-use-before-import-confusion
14    system(f"{query}")
15    return render (request, "bar.html")
```

**To Reproduce**

https://semgrep.dev/playground/r/WAUWqL2/jdsalaro.semgrep-python-import-confusion?editorMode=advanced

**Expected behavior**

As denoted by both Semgrep test annotations in the code snippet above, line six and fourteen should be identified as matches.

**Screenshots**

![image](https://github.com/semgrep/semgrep/assets/9462892/3cc39b4c-d7d3-4849-902a-dcbb5a7405ee)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

The behavior described holds both for semgrep.dev as well as locally ran instances.

**Use case**

Preemptive detection of scenarios where widely adopted best practices (e.g. https://peps.python.org/pep-0008/#imports ) are not followed yet the resulting code is valid.
